/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_pll_out : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, true], [false, true]]
  falT := [false, true]
  atomsT := [[], ["p"]]

theorem cm_pll_out_ok : (cm_pll_out).okB = true := by decide
theorem cm_pll_out_root : (cm_pll_out).root < (cm_pll_out).n := by decide

def K_pll_out : Kripke := (cm_pll_out).toKripke cm_pll_out_ok cm_pll_out_root

set_option maxRecDepth 1000000 in
theorem pll_out_force :
    ¬ (K_pll_out).force (K_pll_out).root (ofPLL (((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "p"))) := by decide

/-- **⊬ (◯p ⊃ p)** — refuted by the finite rooted poset model above. -/
theorem pll_out : ¬ Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "p"))) :=
  not_derivable_of_countermodel K_pll_out pll_out_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_pll_out_control :
    (K_pll_out).force (K_pll_out).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms pll_out
