/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯(◯p ∧ p) ⊃ ◯p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell046_term : PLLND.Tm [] (((((PLLFormula.prop "p").somehow).and (PLLFormula.prop "p")).somehow).ifThen ((PLLFormula.prop "p").somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := (((PLLFormula.prop "p").somehow).and (PLLFormula.prop "p"))) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.lam (PLLND.Tm.app (φ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.fst (ψ := (PLLFormula.prop "p")) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.snd (φ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.var PLLND.Var.here)))))

theorem cell046 : Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").somehow).and (PLLFormula.prop "p")).somehow).ifThen ((PLLFormula.prop "p").somehow))) :=
  ⟨(cell046_term).toND⟩

#print axioms cell046
