/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((p ⊃ (p ⊃ ◯p)) ⊃ (p ⊃ ◯p))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell055_term : PLLND.Tm [] (((PLLFormula.prop "p").ifThen ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "p").somehow))).ifThen ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "p").somehow))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here))))

theorem cell055 : Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").ifThen ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "p").somehow))).ifThen ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "p").somehow)))) :=
  ⟨(cell055_term).toND⟩

#print axioms cell055
