/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell053 : FRJ.Search.Tab where
  n := 3
  root := 0
  leT := [[true, true, true], [false, true, true], [false, false, true]]
  rmT := [[true, false, false], [false, true, true], [false, false, true]]
  falT := [false, false, true]
  atomsT := [[], [], ["p"]]

theorem cm_cell053_ok : (cm_cell053).okB = true := by decide
theorem cm_cell053_root : (cm_cell053).root < (cm_cell053).n := by decide

def K_cell053 : Kripke := (cm_cell053).toKripke cm_cell053_ok cm_cell053_root

set_option maxRecDepth 1000000 in
theorem cell053_force :
    ¬ (K_cell053).force (K_cell053).root (ofPLL (((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "p")).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) := by decide

/-- **⊬ (((◯p ⊃ p) ⊃ ◯p) ⊃ ◯p)** — refuted by the finite rooted poset model above. -/
theorem cell053 : ¬ Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "p")).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) :=
  not_derivable_of_countermodel K_cell053 cell053_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell053_control :
    (K_cell053).force (K_cell053).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell053
