/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell051 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell051_ok : (cm_cell051).okB = true := by decide
theorem cm_cell051_root : (cm_cell051).root < (cm_cell051).n := by decide

def K_cell051 : Kripke := (cm_cell051).toKripke cm_cell051_ok cm_cell051_root

set_option maxRecDepth 1000000 in
theorem cell051_force :
    ¬ (K_cell051).force (K_cell051).root (ofPLL (((((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) := by decide

/-- **⊬ ((¬◯p ⊃ ◯p) ⊃ ◯p)** — refuted by the finite rooted poset model above. -/
theorem cell051 : ¬ Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) :=
  not_derivable_of_countermodel K_cell051 cell051_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell051_control :
    (K_cell051).force (K_cell051).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell051
