/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell108 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["q"]]

theorem cm_cell108_ok : (cm_cell108).okB = true := by decide
theorem cm_cell108_root : (cm_cell108).root < (cm_cell108).n := by decide

def K_cell108 : Kripke := (cm_cell108).toKripke cm_cell108_ok cm_cell108_root

set_option maxRecDepth 1000000 in
theorem cell108_force :
    ¬ (K_cell108).force (K_cell108).root (ofPLL (((((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "p")).ifThen (PLLFormula.prop "p")).ifThen ((((PLLFormula.prop "q").ifThen (PLLFormula.prop "p")).ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")))) := by decide

/-- **⊬ ((((p ⊃ q) ⊃ p) ⊃ p) ⊃ (((q ⊃ p) ⊃ q) ⊃ q))** — refuted by the finite rooted poset model above. -/
theorem cell108 : ¬ Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "p")).ifThen (PLLFormula.prop "p")).ifThen ((((PLLFormula.prop "q").ifThen (PLLFormula.prop "p")).ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")))) :=
  not_derivable_of_countermodel K_cell108 cell108_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell108_control :
    (K_cell108).force (K_cell108).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell108
