/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(p ⊃ ¬¬p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell026_term : PLLND.Tm [] ((PLLFormula.prop "p").ifThen (((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL)) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.app (φ := PLLFormula.falsePLL) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))))

theorem cell026 : Nonempty (PLLND.LaxND [] ((PLLFormula.prop "p").ifThen (((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL))) :=
  ⟨(cell026_term).toND⟩

#print axioms cell026
