/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell010 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell010_ok : (cm_cell010).okB = true := by decide
theorem cm_cell010_root : (cm_cell010).root < (cm_cell010).n := by decide

def K_cell010 : Kripke := (cm_cell010).toKripke cm_cell010_ok cm_cell010_root

set_option maxRecDepth 1000000 in
theorem cell010_force :
    ¬ (K_cell010).force (K_cell010).root (ofPLL ((PLLFormula.falsePLL.somehow).and (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL))) := by decide

/-- **⊬ (◯⊥ ∧ ⊤)** — refuted by the finite rooted poset model above. -/
theorem cell010 : ¬ Nonempty (PLLND.LaxND [] ((PLLFormula.falsePLL.somehow).and (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL))) :=
  not_derivable_of_countermodel K_cell010 cell010_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell010_control :
    (K_cell010).force (K_cell010).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell010
