/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell004 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell004_ok : (cm_cell004).okB = true := by decide
theorem cm_cell004_root : (cm_cell004).root < (cm_cell004).n := by decide

def K_cell004 : Kripke := (cm_cell004).toKripke cm_cell004_ok cm_cell004_root

set_option maxRecDepth 1000000 in
theorem cell004_force :
    ¬ (K_cell004).force (K_cell004).root (ofPLL (PLLFormula.falsePLL.and (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL))) := by decide

/-- **⊬ (⊥ ∧ ⊤)** — refuted by the finite rooted poset model above. -/
theorem cell004 : ¬ Nonempty (PLLND.LaxND [] (PLLFormula.falsePLL.and (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL))) :=
  not_derivable_of_countermodel K_cell004 cell004_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell004_control :
    (K_cell004).force (K_cell004).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell004
