/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell025 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell025_ok : (cm_cell025).okB = true := by decide
theorem cm_cell025_root : (cm_cell025).root < (cm_cell025).n := by decide

def K_cell025 : Kripke := (cm_cell025).toKripke cm_cell025_ok cm_cell025_root

set_option maxRecDepth 1000000 in
theorem cell025_force :
    ¬ (K_cell025).force (K_cell025).root (ofPLL ((((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.prop "p"))) := by decide

/-- **⊬ (¬¬p ⊃ p)** — refuted by the finite rooted poset model above. -/
theorem cell025 : ¬ Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.prop "p"))) :=
  not_derivable_of_countermodel K_cell025 cell025_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell025_control :
    (K_cell025).force (K_cell025).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell025
