/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell090 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell090_ok : (cm_cell090).okB = true := by decide
theorem cm_cell090_root : (cm_cell090).root < (cm_cell090).n := by decide

def K_cell090 : Kripke := (cm_cell090).toKripke cm_cell090_ok cm_cell090_root

set_option maxRecDepth 1000000 in
theorem cell090_force :
    ¬ (K_cell090).force (K_cell090).root (ofPLL (((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "q").or ((PLLFormula.prop "p").somehow)))) := by decide

/-- **⊬ (((◯p ⊃ q) ⊃ q) ⊃ (q ∨ ◯p))** — refuted by the finite rooted poset model above. -/
theorem cell090 : ¬ Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "q").or ((PLLFormula.prop "p").somehow)))) :=
  not_derivable_of_countermodel K_cell090 cell090_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell090_control :
    (K_cell090).force (K_cell090).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell090
