/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((p ∧ ◯p) ⊃ p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell033_term : PLLND.Tm [] (((PLLFormula.prop "p").and ((PLLFormula.prop "p").somehow)).ifThen (PLLFormula.prop "p")) :=
  (PLLND.Tm.lam (PLLND.Tm.app (φ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.fst (ψ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.snd (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here))))

theorem cell033 : Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").and ((PLLFormula.prop "p").somehow)).ifThen (PLLFormula.prop "p"))) :=
  ⟨(cell033_term).toND⟩

#print axioms cell033
