/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯◯⊥ ⊃ ◯⊥)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell014_term : PLLND.Tm [] (((PLLFormula.falsePLL.somehow).somehow).ifThen (PLLFormula.falsePLL.somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := (PLLFormula.falsePLL.somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var PLLND.Var.here)))

theorem cell014 : Nonempty (PLLND.LaxND [] (((PLLFormula.falsePLL.somehow).somehow).ifThen (PLLFormula.falsePLL.somehow))) :=
  ⟨(cell014_term).toND⟩

#print axioms cell014
