/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell009 : FRJ.Search.Tab where
  n := 3
  root := 0
  leT := [[true, true, true], [false, true, true], [false, false, true]]
  rmT := [[true, false, false], [false, true, true], [false, false, true]]
  falT := [false, false, true]
  atomsT := [[], [], []]

theorem cm_cell009_ok : (cm_cell009).okB = true := by decide
theorem cm_cell009_root : (cm_cell009).root < (cm_cell009).n := by decide

def K_cell009 : Kripke := (cm_cell009).toKripke cm_cell009_ok cm_cell009_root

set_option maxRecDepth 1000000 in
theorem cell009_force :
    ¬ (K_cell009).force (K_cell009).root (ofPLL ((PLLFormula.falsePLL.somehow).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL))) := by decide

/-- **⊬ (◯⊥ ∨ ¬◯⊥)** — refuted by the finite rooted poset model above. -/
theorem cell009 : ¬ Nonempty (PLLND.LaxND [] ((PLLFormula.falsePLL.somehow).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL))) :=
  not_derivable_of_countermodel K_cell009 cell009_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell009_control :
    (K_cell009).force (K_cell009).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell009
