/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell006 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, true], [false, true]]
  falT := [false, true]
  atomsT := [[], []]

theorem cm_cell006_ok : (cm_cell006).okB = true := by decide
theorem cm_cell006_root : (cm_cell006).root < (cm_cell006).n := by decide

def K_cell006 : Kripke := (cm_cell006).toKripke cm_cell006_ok cm_cell006_root

set_option maxRecDepth 1000000 in
theorem cell006_force :
    ¬ (K_cell006).force (K_cell006).root (ofPLL ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)) := by decide

/-- **⊬ ¬◯⊥** — refuted by the finite rooted poset model above. -/
theorem cell006 : ¬ Nonempty (PLLND.LaxND [] ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)) :=
  not_derivable_of_countermodel K_cell006 cell006_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell006_control :
    (K_cell006).force (K_cell006).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell006
