/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell023 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell023_ok : (cm_cell023).okB = true := by decide
theorem cm_cell023_root : (cm_cell023).root < (cm_cell023).n := by decide

def K_cell023 : Kripke := (cm_cell023).toKripke cm_cell023_ok cm_cell023_root

set_option maxRecDepth 1000000 in
theorem cell023_force :
    ¬ (K_cell023).force (K_cell023).root (ofPLL ((PLLFormula.prop "p").or ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL))) := by decide

/-- **⊬ (p ∨ ¬p)** — refuted by the finite rooted poset model above. -/
theorem cell023 : ¬ Nonempty (PLLND.LaxND [] ((PLLFormula.prop "p").or ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL))) :=
  not_derivable_of_countermodel K_cell023 cell023_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell023_control :
    (K_cell023).force (K_cell023).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell023
