/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯◯◯(p ∧ q) ⊃ ◯(p ∧ q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell100_term : PLLND.Tm [] ((((((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow).somehow).somehow).ifThen (((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow).somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.bind (φ := (((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var PLLND.Var.here))))

theorem cell100 : Nonempty (PLLND.LaxND [] ((((((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow).somehow).somehow).ifThen (((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow))) :=
  ⟨(cell100_term).toND⟩

#print axioms cell100
