/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯(p ∧ q) ⊃ ◯◯◯(p ∧ q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell101_term : PLLND.Tm [] ((((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow).ifThen (((((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow).somehow).somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((PLLFormula.prop "p").and (PLLFormula.prop "q"))) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.app (φ := (PLLFormula.prop "q")) (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.lam (PLLND.Tm.val (PLLND.Tm.val (PLLND.Tm.val (PLLND.Tm.pair (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))))) (PLLND.Tm.fst (ψ := (PLLFormula.prop "q")) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.snd (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here)))))

theorem cell101 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow).ifThen (((((PLLFormula.prop "p").and (PLLFormula.prop "q")).somehow).somehow).somehow))) :=
  ⟨(cell101_term).toND⟩

#print axioms cell101
