/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell022 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell022_ok : (cm_cell022).okB = true := by decide
theorem cm_cell022_root : (cm_cell022).root < (cm_cell022).n := by decide

def K_cell022 : Kripke := (cm_cell022).toKripke cm_cell022_ok cm_cell022_root

set_option maxRecDepth 1000000 in
theorem cell022_force :
    ¬ (K_cell022).force (K_cell022).root (ofPLL (PLLFormula.prop "p")) := by decide

/-- **⊬ p** — refuted by the finite rooted poset model above. -/
theorem cell022 : ¬ Nonempty (PLLND.LaxND [] (PLLFormula.prop "p")) :=
  not_derivable_of_countermodel K_cell022 cell022_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell022_control :
    (K_cell022).force (K_cell022).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell022
