/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell059 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell059_ok : (cm_cell059).okB = true := by decide
theorem cm_cell059_root : (cm_cell059).root < (cm_cell059).n := by decide

def K_cell059 : Kripke := (cm_cell059).toKripke cm_cell059_ok cm_cell059_root

set_option maxRecDepth 1000000 in
theorem cell059_force :
    ¬ (K_cell059).force (K_cell059).root (ofPLL ((((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "p")).somehow).ifThen (PLLFormula.prop "p")).somehow)) := by decide

/-- **⊬ ◯(◯(◯p ⊃ p) ⊃ p)** — refuted by the finite rooted poset model above. -/
theorem cell059 : ¬ Nonempty (PLLND.LaxND [] ((((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "p")).somehow).ifThen (PLLFormula.prop "p")).somehow)) :=
  not_derivable_of_countermodel K_cell059 cell059_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell059_control :
    (K_cell059).force (K_cell059).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell059
