/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell076 : FRJ.Search.Tab where
  n := 3
  root := 0
  leT := [[true, true, true], [false, true, true], [false, false, true]]
  rmT := [[true, false, false], [false, true, true], [false, false, true]]
  falT := [false, false, true]
  atomsT := [[], ["p"], ["p", "q"]]

theorem cm_cell076_ok : (cm_cell076).okB = true := by decide
theorem cm_cell076_root : (cm_cell076).root < (cm_cell076).n := by decide

def K_cell076 : Kripke := (cm_cell076).toKripke cm_cell076_ok cm_cell076_root

set_option maxRecDepth 1000000 in
theorem cell076_force :
    ¬ (K_cell076).force (K_cell076).root (ofPLL ((((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)).ifThen (((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).somehow))) := by decide

/-- **⊬ ((◯p ⊃ ◯q) ⊃ ◯(p ⊃ q))** — refuted by the finite rooted poset model above. -/
theorem cell076 : ¬ Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)).ifThen (((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).somehow))) :=
  not_derivable_of_countermodel K_cell076 cell076_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell076_control :
    (K_cell076).force (K_cell076).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell076
