/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(((p ⊃ q) ⊃ (q ⊃ p)) ⊃ (q ⊃ p))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell092_term : PLLND.Tm [] ((((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p"))).ifThen ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p"))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.app (φ := ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p"))) (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := (PLLFormula.prop "q")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").ifThen (PLLFormula.prop "q"))) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.lam (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)))))))

theorem cell092 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p"))).ifThen ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p")))) :=
  ⟨(cell092_term).toND⟩

#print axioms cell092
