/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell109 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell109_ok : (cm_cell109).okB = true := by decide
theorem cm_cell109_root : (cm_cell109).root < (cm_cell109).n := by decide

def K_cell109 : Kripke := (cm_cell109).toKripke cm_cell109_ok cm_cell109_root

set_option maxRecDepth 1000000 in
theorem cell109_force :
    ¬ (K_cell109).force (K_cell109).root (ofPLL (((((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "p")).ifThen (PLLFormula.prop "p"))) := by decide

/-- **⊬ ((((p ⊃ q) ⊃ q) ⊃ p) ⊃ p)** — refuted by the finite rooted poset model above. -/
theorem cell109 : ¬ Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "p")).ifThen (PLLFormula.prop "p"))) :=
  not_derivable_of_countermodel K_cell109 cell109_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell109_control :
    (K_cell109).force (K_cell109).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell109
