/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((◯p ⊃ ◯q) ⊃ ◯(◯p ⊃ ◯q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell127_term : PLLND.Tm [] ((((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)).ifThen ((((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)).somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here)))

theorem cell127 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)).ifThen ((((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)).somehow))) :=
  ⟨(cell127_term).toND⟩

#print axioms cell127
