/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell097 : FRJ.Search.Tab where
  n := 3
  root := 0
  leT := [[true, true, true], [false, true, false], [false, false, true]]
  rmT := [[true, false, false], [false, true, false], [false, false, true]]
  falT := [false, false, false]
  atomsT := [[], ["p"], ["q"]]

theorem cm_cell097_ok : (cm_cell097).okB = true := by decide
theorem cm_cell097_root : (cm_cell097).root < (cm_cell097).n := by decide

def K_cell097 : Kripke := (cm_cell097).toKripke cm_cell097_ok cm_cell097_root

set_option maxRecDepth 1000000 in
theorem cell097_force :
    ¬ (K_cell097).force (K_cell097).root (ofPLL ((((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).or ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p"))).somehow)) := by decide

/-- **⊬ ◯((p ⊃ q) ∨ (q ⊃ p))** — refuted by the finite rooted poset model above. -/
theorem cell097 : ¬ Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).or ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p"))).somehow)) :=
  not_derivable_of_countermodel K_cell097 cell097_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell097_control :
    (K_cell097).force (K_cell097).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell097
