/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell027 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell027_ok : (cm_cell027).okB = true := by decide
theorem cm_cell027_root : (cm_cell027).root < (cm_cell027).n := by decide

def K_cell027 : Kripke := (cm_cell027).toKripke cm_cell027_ok cm_cell027_root

set_option maxRecDepth 1000000 in
theorem cell027_force :
    ¬ (K_cell027).force (K_cell027).root (ofPLL (((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).or (PLLFormula.prop "p"))) := by decide

/-- **⊬ (¬p ∨ p)** — refuted by the finite rooted poset model above. -/
theorem cell027 : ¬ Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).or (PLLFormula.prop "p"))) :=
  not_derivable_of_countermodel K_cell027 cell027_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell027_control :
    (K_cell027).force (K_cell027).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell027
