/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell028 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell028_ok : (cm_cell028).okB = true := by decide
theorem cm_cell028_root : (cm_cell028).root < (cm_cell028).n := by decide

def K_cell028 : Kripke := (cm_cell028).toKripke cm_cell028_ok cm_cell028_root

set_option maxRecDepth 1000000 in
theorem cell028_force :
    ¬ (K_cell028).force (K_cell028).root (ofPLL (((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).or (PLLFormula.prop "p"))) := by decide

/-- **⊬ (¬p ∨ p)** — refuted by the finite rooted poset model above. -/
theorem cell028 : ¬ Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).or (PLLFormula.prop "p"))) :=
  not_derivable_of_countermodel K_cell028 cell028_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell028_control :
    (K_cell028).force (K_cell028).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell028
