/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(((p ∧ q) ⊃ r) ⊃ (p ⊃ (q ⊃ r)))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell122_term : PLLND.Tm [] ((((PLLFormula.prop "p").and (PLLFormula.prop "q")).ifThen (PLLFormula.prop "r")).ifThen ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").ifThen (PLLFormula.prop "r")))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "r")) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").and (PLLFormula.prop "q"))) (PLLND.Tm.var (PLLND.Var.there (PLLND.Var.there PLLND.Var.here))) (PLLND.Tm.pair (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.var PLLND.Var.here)))))))

theorem cell122 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").and (PLLFormula.prop "q")).ifThen (PLLFormula.prop "r")).ifThen ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").ifThen (PLLFormula.prop "r"))))) :=
  ⟨(cell122_term).toND⟩

#print axioms cell122
