/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell072 : FRJ.Search.Tab where
  n := 3
  root := 0
  leT := [[true, true, true], [false, true, false], [false, false, true]]
  rmT := [[true, false, true], [false, true, false], [false, false, true]]
  falT := [false, false, false]
  atomsT := [[], ["q"], ["p"]]

theorem cm_cell072_ok : (cm_cell072).okB = true := by decide
theorem cm_cell072_root : (cm_cell072).root < (cm_cell072).n := by decide

def K_cell072 : Kripke := (cm_cell072).toKripke cm_cell072_ok cm_cell072_root

set_option maxRecDepth 1000000 in
theorem cell072_force :
    ¬ (K_cell072).force (K_cell072).root (ofPLL ((((PLLFormula.prop "p").or (PLLFormula.prop "q")).somehow).ifThen (((PLLFormula.prop "p").somehow).or ((PLLFormula.prop "q").somehow)))) := by decide

/-- **⊬ (◯(p ∨ q) ⊃ (◯p ∨ ◯q))** — refuted by the finite rooted poset model above. -/
theorem cell072 : ¬ Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").or (PLLFormula.prop "q")).somehow).ifThen (((PLLFormula.prop "p").somehow).or ((PLLFormula.prop "q").somehow)))) :=
  not_derivable_of_countermodel K_cell072 cell072_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell072_control :
    (K_cell072).force (K_cell072).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell072
