/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯(p ⊃ ◯q) ⊃ (p ⊃ ◯q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell086_term : PLLND.Tm [] ((((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").somehow)).somehow).ifThen ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").somehow))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").somehow))) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.app (φ := ((PLLFormula.prop "q").somehow)) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)))))))

theorem cell086 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").somehow)).somehow).ifThen ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").somehow)))) :=
  ⟨(cell086_term).toND⟩

#print axioms cell086
