/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯(p ∧ ¬p) ⊃ ◯q)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell099_term : PLLND.Tm [] ((((PLLFormula.prop "p").and ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL)).somehow).ifThen ((PLLFormula.prop "q").somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((PLLFormula.prop "p").and ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL))) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL)) (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.lam (PLLND.Tm.app (φ := PLLFormula.falsePLL) (PLLND.Tm.lam (PLLND.Tm.abort ((PLLFormula.prop "q").somehow) (PLLND.Tm.var PLLND.Var.here))) (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.var PLLND.Var.here)))) (PLLND.Tm.fst (ψ := ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL)) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.snd (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here)))))

theorem cell099 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").and ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL)).somehow).ifThen ((PLLFormula.prop "q").somehow))) :=
  ⟨(cell099_term).toND⟩

#print axioms cell099
