/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell005 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell005_ok : (cm_cell005).okB = true := by decide
theorem cm_cell005_root : (cm_cell005).root < (cm_cell005).n := by decide

def K_cell005 : Kripke := (cm_cell005).toKripke cm_cell005_ok cm_cell005_root

set_option maxRecDepth 1000000 in
theorem cell005_force :
    ¬ (K_cell005).force (K_cell005).root (ofPLL (PLLFormula.falsePLL.somehow)) := by decide

/-- **⊬ ◯⊥** — refuted by the finite rooted poset model above. -/
theorem cell005 : ¬ Nonempty (PLLND.LaxND [] (PLLFormula.falsePLL.somehow)) :=
  not_derivable_of_countermodel K_cell005 cell005_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell005_control :
    (K_cell005).force (K_cell005).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell005
