/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((p ∨ q) ⊃ ((p ⊃ q) ⊃ q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell089_term : PLLND.Tm [] (((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen (((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q"))) :=
  (PLLND.Tm.lam (PLLND.Tm.case (φ := (PLLFormula.prop "p")) (ψ := (PLLFormula.prop "q")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "q")) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.lam (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)))))

theorem cell089 : Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen (((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")))) :=
  ⟨(cell089_term).toND⟩

#print axioms cell089
