/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((◯p ⊃ ◯◯q) ⊃ (◯p ⊃ ◯q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell084_term : PLLND.Tm [] ((((PLLFormula.prop "p").somehow).ifThen (((PLLFormula.prop "q").somehow).somehow)).ifThen (((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.bind (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.app (φ := (((PLLFormula.prop "q").somehow).somehow)) (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((PLLFormula.prop "q").somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var PLLND.Var.here))) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.var (PLLND.Var.there (PLLND.Var.there PLLND.Var.here))) (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here)))))))

theorem cell084 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").somehow).ifThen (((PLLFormula.prop "q").somehow).somehow)).ifThen (((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)))) :=
  ⟨(cell084_term).toND⟩

#print axioms cell084
