/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell087 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell087_ok : (cm_cell087).okB = true := by decide
theorem cm_cell087_root : (cm_cell087).root < (cm_cell087).n := by decide

def K_cell087 : Kripke := (cm_cell087).toKripke cm_cell087_ok cm_cell087_root

set_option maxRecDepth 1000000 in
theorem cell087_force :
    ¬ (K_cell087).force (K_cell087).root (ofPLL (((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) := by decide

/-- **⊬ (((◯p ⊃ q) ⊃ ◯p) ⊃ ◯p)** — refuted by the finite rooted poset model above. -/
theorem cell087 : ¬ Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) :=
  not_derivable_of_countermodel K_cell087 cell087_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell087_control :
    (K_cell087).force (K_cell087).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell087
