/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(p ⊃ p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell021_term : PLLND.Tm [] ((PLLFormula.prop "p").ifThen (PLLFormula.prop "p")) :=
  (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here))

theorem cell021 : Nonempty (PLLND.LaxND [] ((PLLFormula.prop "p").ifThen (PLLFormula.prop "p"))) :=
  ⟨(cell021_term).toND⟩

#print axioms cell021
