/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((p ∨ q) ⊃ (q ∨ p))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell064_term : PLLND.Tm [] (((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "q").or (PLLFormula.prop "p"))) :=
  (PLLND.Tm.lam (PLLND.Tm.case (φ := (PLLFormula.prop "p")) (ψ := (PLLFormula.prop "q")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.inr (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.inl (PLLND.Tm.var PLLND.Var.here))))

theorem cell064 : Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "q").or (PLLFormula.prop "p")))) :=
  ⟨(cell064_term).toND⟩

#print axioms cell064
