/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell066 : FRJ.Search.Tab where
  n := 3
  root := 0
  leT := [[true, true, true], [false, true, false], [false, false, true]]
  rmT := [[true, false, false], [false, true, false], [false, false, true]]
  falT := [false, false, false]
  atomsT := [[], ["p"], ["q"]]

theorem cm_cell066_ok : (cm_cell066).okB = true := by decide
theorem cm_cell066_root : (cm_cell066).root < (cm_cell066).n := by decide

def K_cell066 : Kripke := (cm_cell066).toKripke cm_cell066_ok cm_cell066_root

set_option maxRecDepth 1000000 in
theorem cell066_force :
    ¬ (K_cell066).force (K_cell066).root (ofPLL (((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).or ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p")))) := by decide

/-- **⊬ ((p ⊃ q) ∨ (q ⊃ p))** — refuted by the finite rooted poset model above. -/
theorem cell066 : ¬ Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").ifThen (PLLFormula.prop "q")).or ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p")))) :=
  not_derivable_of_countermodel K_cell066 cell066_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell066_control :
    (K_cell066).force (K_cell066).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell066
