/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((¬◯p ∧ ◯(p ∨ q)) ⊃ ◯q)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell096_term : PLLND.Tm [] (((((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL).and (((PLLFormula.prop "p").or (PLLFormula.prop "q")).somehow)).ifThen ((PLLFormula.prop "q").somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.app (φ := (((PLLFormula.prop "p").or (PLLFormula.prop "q")).somehow)) (PLLND.Tm.lam (PLLND.Tm.app (φ := (((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL)) (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((PLLFormula.prop "p").or (PLLFormula.prop "q"))) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.case (φ := (PLLFormula.prop "p")) (ψ := (PLLFormula.prop "q")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.app (φ := PLLFormula.falsePLL) (PLLND.Tm.lam (PLLND.Tm.abort ((PLLFormula.prop "q").somehow) (PLLND.Tm.var PLLND.Var.here))) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.var (PLLND.Var.there (PLLND.Var.there PLLND.Var.here))) (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here)))) (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here))))) (PLLND.Tm.fst (ψ := (((PLLFormula.prop "p").or (PLLFormula.prop "q")).somehow)) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.snd (φ := (((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL)) (PLLND.Tm.var PLLND.Var.here))))

theorem cell096 : Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL).and (((PLLFormula.prop "p").or (PLLFormula.prop "q")).somehow)).ifThen ((PLLFormula.prop "q").somehow))) :=
  ⟨(cell096_term).toND⟩

#print axioms cell096
