/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯◯◯◯p ⊃ ◯◯p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell106_term : PLLND.Tm [] ((((((PLLFormula.prop "p").somehow).somehow).somehow).somehow).ifThen (((PLLFormula.prop "p").somehow).somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((((PLLFormula.prop "p").somehow).somehow).somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.bind (φ := (((PLLFormula.prop "p").somehow).somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var PLLND.Var.here))))

theorem cell106 : Nonempty (PLLND.LaxND [] ((((((PLLFormula.prop "p").somehow).somehow).somehow).somehow).ifThen (((PLLFormula.prop "p").somehow).somehow))) :=
  ⟨(cell106_term).toND⟩

#print axioms cell106
