/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(p ⊃ (q ⊃ p))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell060_term : PLLND.Tm [] ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p"))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))

theorem cell060 : Nonempty (PLLND.LaxND [] ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").ifThen (PLLFormula.prop "p")))) :=
  ⟨(cell060_term).toND⟩

#print axioms cell060
