/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell050 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell050_ok : (cm_cell050).okB = true := by decide
theorem cm_cell050_root : (cm_cell050).root < (cm_cell050).n := by decide

def K_cell050 : Kripke := (cm_cell050).toKripke cm_cell050_ok cm_cell050_root

set_option maxRecDepth 1000000 in
theorem cell050_force :
    ¬ (K_cell050).force (K_cell050).root (ofPLL ((((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).ifThen (PLLFormula.prop "p")).ifThen (PLLFormula.prop "p"))) := by decide

/-- **⊬ ((¬p ⊃ p) ⊃ p)** — refuted by the finite rooted poset model above. -/
theorem cell050 : ¬ Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).ifThen (PLLFormula.prop "p")).ifThen (PLLFormula.prop "p"))) :=
  not_derivable_of_countermodel K_cell050 cell050_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell050_control :
    (K_cell050).force (K_cell050).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell050
