/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(((p ⊃ r) ∧ (q ⊃ r)) ⊃ ((p ∨ q) ⊃ r))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell116_term : PLLND.Tm [] ((((PLLFormula.prop "p").ifThen (PLLFormula.prop "r")).and ((PLLFormula.prop "q").ifThen (PLLFormula.prop "r"))).ifThen (((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen (PLLFormula.prop "r"))) :=
  (PLLND.Tm.lam (PLLND.Tm.app (φ := ((PLLFormula.prop "q").ifThen (PLLFormula.prop "r"))) (PLLND.Tm.lam (PLLND.Tm.app (φ := ((PLLFormula.prop "p").ifThen (PLLFormula.prop "r"))) (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.case (φ := (PLLFormula.prop "p")) (ψ := (PLLFormula.prop "q")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.app (φ := (PLLFormula.prop "r")) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.var (PLLND.Var.there (PLLND.Var.there PLLND.Var.here))) (PLLND.Tm.var PLLND.Var.here))) (PLLND.Tm.app (φ := (PLLFormula.prop "r")) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := (PLLFormula.prop "q")) (PLLND.Tm.var (PLLND.Var.there (PLLND.Var.there (PLLND.Var.there PLLND.Var.here)))) (PLLND.Tm.var PLLND.Var.here)))))) (PLLND.Tm.fst (ψ := ((PLLFormula.prop "q").ifThen (PLLFormula.prop "r"))) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.snd (φ := ((PLLFormula.prop "p").ifThen (PLLFormula.prop "r"))) (PLLND.Tm.var PLLND.Var.here))))

theorem cell116 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").ifThen (PLLFormula.prop "r")).and ((PLLFormula.prop "q").ifThen (PLLFormula.prop "r"))).ifThen (((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen (PLLFormula.prop "r")))) :=
  ⟨(cell116_term).toND⟩

#print axioms cell116
