/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((p ∧ q) ⊃ (q ∧ p))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell065_term : PLLND.Tm [] (((PLLFormula.prop "p").and (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "q").and (PLLFormula.prop "p"))) :=
  (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "q")) (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.lam (PLLND.Tm.pair (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.var PLLND.Var.here))) (PLLND.Tm.fst (ψ := (PLLFormula.prop "q")) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.snd (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here))))

theorem cell065 : Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").and (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "q").and (PLLFormula.prop "p")))) :=
  ⟨(cell065_term).toND⟩

#print axioms cell065
