/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(p ⊃ ◯p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell029_term : PLLND.Tm [] ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "p").somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here)))

theorem cell029 : Nonempty (PLLND.LaxND [] ((PLLFormula.prop "p").ifThen ((PLLFormula.prop "p").somehow))) :=
  ⟨(cell029_term).toND⟩

#print axioms cell029
