/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯p ⊃ ◯◯◯p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell057_term : PLLND.Tm [] (((PLLFormula.prop "p").somehow).ifThen ((((PLLFormula.prop "p").somehow).somehow).somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.val (PLLND.Tm.val (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here))))))

theorem cell057 : Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").somehow).ifThen ((((PLLFormula.prop "p").somehow).somehow).somehow))) :=
  ⟨(cell057_term).toND⟩

#print axioms cell057
