/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯◯◯⊥ ⊃ ◯⊥)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell020_term : PLLND.Tm [] ((((PLLFormula.falsePLL.somehow).somehow).somehow).ifThen (PLLFormula.falsePLL.somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((PLLFormula.falsePLL.somehow).somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.bind (φ := (PLLFormula.falsePLL.somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var PLLND.Var.here))))

theorem cell020 : Nonempty (PLLND.LaxND [] ((((PLLFormula.falsePLL.somehow).somehow).somehow).ifThen (PLLFormula.falsePLL.somehow))) :=
  ⟨(cell020_term).toND⟩

#print axioms cell020
