/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯⊥ ⊃ ◯◯⊥)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell015_term : PLLND.Tm [] ((PLLFormula.falsePLL.somehow).ifThen ((PLLFormula.falsePLL.somehow).somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := PLLFormula.falsePLL) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.abort ((PLLFormula.falsePLL.somehow).somehow) (PLLND.Tm.var PLLND.Var.here))))

theorem cell015 : Nonempty (PLLND.LaxND [] ((PLLFormula.falsePLL.somehow).ifThen ((PLLFormula.falsePLL.somehow).somehow))) :=
  ⟨(cell015_term).toND⟩

#print axioms cell015
