/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((◯p ∨ ◯q) ⊃ ◯(p ∨ q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell073_term : PLLND.Tm [] ((((PLLFormula.prop "p").somehow).or ((PLLFormula.prop "q").somehow)).ifThen (((PLLFormula.prop "p").or (PLLFormula.prop "q")).somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.case (φ := ((PLLFormula.prop "p").somehow)) (ψ := ((PLLFormula.prop "q").somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.bind (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.val (PLLND.Tm.inl (PLLND.Tm.var PLLND.Var.here)))) (PLLND.Tm.bind (φ := (PLLFormula.prop "q")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.val (PLLND.Tm.inr (PLLND.Tm.var PLLND.Var.here))))))

theorem cell073 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").somehow).or ((PLLFormula.prop "q").somehow)).ifThen (((PLLFormula.prop "p").or (PLLFormula.prop "q")).somehow))) :=
  ⟨(cell073_term).toND⟩

#print axioms cell073
