/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell045 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell045_ok : (cm_cell045).okB = true := by decide
theorem cm_cell045_root : (cm_cell045).root < (cm_cell045).n := by decide

def K_cell045 : Kripke := (cm_cell045).toKripke cm_cell045_ok cm_cell045_root

set_option maxRecDepth 1000000 in
theorem cell045_force :
    ¬ (K_cell045).force (K_cell045).root (ofPLL (((PLLFormula.prop "p").or ((PLLFormula.prop "p").somehow)).somehow)) := by decide

/-- **⊬ ◯(p ∨ ◯p)** — refuted by the finite rooted poset model above. -/
theorem cell045 : ¬ Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").or ((PLLFormula.prop "p").somehow)).somehow)) :=
  not_derivable_of_countermodel K_cell045 cell045_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell045_control :
    (K_cell045).force (K_cell045).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell045
