/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell069 : FRJ.Search.Tab where
  n := 3
  root := 0
  leT := [[true, true, true], [false, true, false], [false, false, true]]
  rmT := [[true, false, false], [false, true, false], [false, false, true]]
  falT := [false, false, false]
  atomsT := [[], ["p"], ["q"]]

theorem cm_cell069_ok : (cm_cell069).okB = true := by decide
theorem cm_cell069_root : (cm_cell069).root < (cm_cell069).n := by decide

def K_cell069 : Kripke := (cm_cell069).toKripke cm_cell069_ok cm_cell069_root

set_option maxRecDepth 1000000 in
theorem cell069_force :
    ¬ (K_cell069).force (K_cell069).root (ofPLL ((((PLLFormula.prop "p").and (PLLFormula.prop "q")).ifThen PLLFormula.falsePLL).ifThen (((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).or ((PLLFormula.prop "q").ifThen PLLFormula.falsePLL)))) := by decide

/-- **⊬ (¬(p ∧ q) ⊃ (¬p ∨ ¬q))** — refuted by the finite rooted poset model above. -/
theorem cell069 : ¬ Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").and (PLLFormula.prop "q")).ifThen PLLFormula.falsePLL).ifThen (((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).or ((PLLFormula.prop "q").ifThen PLLFormula.falsePLL)))) :=
  not_derivable_of_countermodel K_cell069 cell069_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell069_control :
    (K_cell069).force (K_cell069).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell069
