/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯(⊥ ∨ ⊤) ⊃ (◯⊥ ∨ ◯⊤))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell018_term : PLLND.Tm [] (((PLLFormula.falsePLL.or (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)).somehow).ifThen ((PLLFormula.falsePLL.somehow).or ((PLLFormula.falsePLL.ifThen PLLFormula.falsePLL).somehow))) :=
  (PLLND.Tm.lam (PLLND.Tm.inr (PLLND.Tm.bind (φ := (PLLFormula.falsePLL.or (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL))) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.case (φ := PLLFormula.falsePLL) (ψ := (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.abort ((PLLFormula.falsePLL.ifThen PLLFormula.falsePLL).somehow) (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here))))))

theorem cell018 : Nonempty (PLLND.LaxND [] (((PLLFormula.falsePLL.or (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)).somehow).ifThen ((PLLFormula.falsePLL.somehow).or ((PLLFormula.falsePLL.ifThen PLLFormula.falsePLL).somehow)))) :=
  ⟨(cell018_term).toND⟩

#print axioms cell018
