/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell094 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell094_ok : (cm_cell094).okB = true := by decide
theorem cm_cell094_root : (cm_cell094).root < (cm_cell094).n := by decide

def K_cell094 : Kripke := (cm_cell094).toKripke cm_cell094_ok cm_cell094_root

set_option maxRecDepth 1000000 in
theorem cell094_force :
    ¬ (K_cell094).force (K_cell094).root (ofPLL (((((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) := by decide

/-- **⊬ (((◯p ⊃ ◯q) ⊃ ◯p) ⊃ ◯p)** — refuted by the finite rooted poset model above. -/
theorem cell094 : ¬ Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) :=
  not_derivable_of_countermodel K_cell094 cell094_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell094_control :
    (K_cell094).force (K_cell094).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell094
