/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `◯(⊥ ∨ ⊤)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell012_term : PLLND.Tm [] ((PLLFormula.falsePLL.or (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)).somehow) :=
  (PLLND.Tm.val (PLLND.Tm.inr (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here))))

theorem cell012 : Nonempty (PLLND.LaxND [] ((PLLFormula.falsePLL.or (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)).somehow)) :=
  ⟨(cell012_term).toND⟩

#print axioms cell012
