/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯p ⊃ (q ⊃ ◯p))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell077_term : PLLND.Tm [] (((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").ifThen ((PLLFormula.prop "p").somehow))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))

theorem cell077 : Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").ifThen ((PLLFormula.prop "p").somehow)))) :=
  ⟨(cell077_term).toND⟩

#print axioms cell077
