/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell031 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell031_ok : (cm_cell031).okB = true := by decide
theorem cm_cell031_root : (cm_cell031).root < (cm_cell031).n := by decide

def K_cell031 : Kripke := (cm_cell031).toKripke cm_cell031_ok cm_cell031_root

set_option maxRecDepth 1000000 in
theorem cell031_force :
    ¬ (K_cell031).force (K_cell031).root (ofPLL ((PLLFormula.prop "p").somehow)) := by decide

/-- **⊬ ◯p** — refuted by the finite rooted poset model above. -/
theorem cell031 : ¬ Nonempty (PLLND.LaxND [] ((PLLFormula.prop "p").somehow)) :=
  not_derivable_of_countermodel K_cell031 cell031_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell031_control :
    (K_cell031).force (K_cell031).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell031
