/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(⊥ ⊃ ◯⊥)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell011_term : PLLND.Tm [] (PLLFormula.falsePLL.ifThen (PLLFormula.falsePLL.somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.abort (PLLFormula.falsePLL.somehow) (PLLND.Tm.var PLLND.Var.here)))

theorem cell011 : Nonempty (PLLND.LaxND [] (PLLFormula.falsePLL.ifThen (PLLFormula.falsePLL.somehow))) :=
  ⟨(cell011_term).toND⟩

#print axioms cell011
