/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯◯(◯p ∨ q) ⊃ ◯(◯p ∨ q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell102_term : PLLND.Tm [] ((((((PLLFormula.prop "p").somehow).or (PLLFormula.prop "q")).somehow).somehow).ifThen ((((PLLFormula.prop "p").somehow).or (PLLFormula.prop "q")).somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((((PLLFormula.prop "p").somehow).or (PLLFormula.prop "q")).somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var PLLND.Var.here)))

theorem cell102 : Nonempty (PLLND.LaxND [] ((((((PLLFormula.prop "p").somehow).or (PLLFormula.prop "q")).somehow).somehow).ifThen ((((PLLFormula.prop "p").somehow).or (PLLFormula.prop "q")).somehow))) :=
  ⟨(cell102_term).toND⟩

#print axioms cell102
