/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `((p ⊃ (q ⊃ ◯p)) ⊃ ((p ∧ q) ⊃ ◯p))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell095_term : PLLND.Tm [] (((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").ifThen ((PLLFormula.prop "p").somehow))).ifThen (((PLLFormula.prop "p").and (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "p").somehow))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "q")) (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "p")) (PLLND.Tm.lam (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here))) (PLLND.Tm.fst (ψ := (PLLFormula.prop "q")) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here))))) (PLLND.Tm.snd (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here)))))

theorem cell095 : Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").ifThen ((PLLFormula.prop "q").ifThen ((PLLFormula.prop "p").somehow))).ifThen (((PLLFormula.prop "p").and (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "p").somehow)))) :=
  ⟨(cell095_term).toND⟩

#print axioms cell095
