/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell044 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell044_ok : (cm_cell044).okB = true := by decide
theorem cm_cell044_root : (cm_cell044).root < (cm_cell044).n := by decide

def K_cell044 : Kripke := (cm_cell044).toKripke cm_cell044_ok cm_cell044_root

set_option maxRecDepth 1000000 in
theorem cell044_force :
    ¬ (K_cell044).force (K_cell044).root (ofPLL ((PLLFormula.prop "p").somehow)) := by decide

/-- **⊬ ◯p** — refuted by the finite rooted poset model above. -/
theorem cell044 : ¬ Nonempty (PLLND.LaxND [] ((PLLFormula.prop "p").somehow)) :=
  not_derivable_of_countermodel K_cell044 cell044_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell044_control :
    (K_cell044).force (K_cell044).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell044
