/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell030 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, true], [false, true]]
  falT := [false, true]
  atomsT := [[], ["p"]]

theorem cm_cell030_ok : (cm_cell030).okB = true := by decide
theorem cm_cell030_root : (cm_cell030).root < (cm_cell030).n := by decide

def K_cell030 : Kripke := (cm_cell030).toKripke cm_cell030_ok cm_cell030_root

set_option maxRecDepth 1000000 in
theorem cell030_force :
    ¬ (K_cell030).force (K_cell030).root (ofPLL (((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "p"))) := by decide

/-- **⊬ (◯p ⊃ p)** — refuted by the finite rooted poset model above. -/
theorem cell030 : ¬ Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "p"))) :=
  not_derivable_of_countermodel K_cell030 cell030_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell030_control :
    (K_cell030).force (K_cell030).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell030
