/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell110 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell110_ok : (cm_cell110).okB = true := by decide
theorem cm_cell110_root : (cm_cell110).root < (cm_cell110).n := by decide

def K_cell110 : Kripke := (cm_cell110).toKripke cm_cell110_ok cm_cell110_root

set_option maxRecDepth 1000000 in
theorem cell110_force :
    ¬ (K_cell110).force (K_cell110).root (ofPLL ((((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) := by decide

/-- **⊬ ((((◯p ⊃ q) ⊃ q) ⊃ ◯p) ⊃ ◯p)** — refuted by the finite rooted poset model above. -/
theorem cell110 : ¬ Nonempty (PLLND.LaxND [] ((((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q")).ifThen (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "p").somehow)).ifThen ((PLLFormula.prop "p").somehow))) :=
  not_derivable_of_countermodel K_cell110 cell110_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell110_control :
    (K_cell110).force (K_cell110).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell110
