/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell032 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell032_ok : (cm_cell032).okB = true := by decide
theorem cm_cell032_root : (cm_cell032).root < (cm_cell032).n := by decide

def K_cell032 : Kripke := (cm_cell032).toKripke cm_cell032_ok cm_cell032_root

set_option maxRecDepth 1000000 in
theorem cell032_force :
    ¬ (K_cell032).force (K_cell032).root (ofPLL ((((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL).or ((PLLFormula.prop "p").somehow))) := by decide

/-- **⊬ (¬◯p ∨ ◯p)** — refuted by the finite rooted poset model above. -/
theorem cell032 : ¬ Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL).or ((PLLFormula.prop "p").somehow))) :=
  not_derivable_of_countermodel K_cell032 cell032_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell032_control :
    (K_cell032).force (K_cell032).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell032
