/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(((p ∨ q) ⊃ r) ⊃ ((p ⊃ r) ∧ (q ⊃ r)))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell115_term : PLLND.Tm [] ((((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen (PLLFormula.prop "r")).ifThen (((PLLFormula.prop "p").ifThen (PLLFormula.prop "r")).and ((PLLFormula.prop "q").ifThen (PLLFormula.prop "r")))) :=
  (PLLND.Tm.lam (PLLND.Tm.pair (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "r")) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").or (PLLFormula.prop "q"))) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.inl (PLLND.Tm.var PLLND.Var.here))))) (PLLND.Tm.lam (PLLND.Tm.app (φ := (PLLFormula.prop "r")) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").or (PLLFormula.prop "q"))) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.inr (PLLND.Tm.var PLLND.Var.here)))))))

theorem cell115 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen (PLLFormula.prop "r")).ifThen (((PLLFormula.prop "p").ifThen (PLLFormula.prop "r")).and ((PLLFormula.prop "q").ifThen (PLLFormula.prop "r"))))) :=
  ⟨(cell115_term).toND⟩

#print axioms cell115
