/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯(◯p ⊃ q) ⊃ (◯p ⊃ ◯q))`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell081_term : PLLND.Tm [] (((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q")).somehow).ifThen (((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow))) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.bind (φ := (PLLFormula.prop "p")) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.bind (φ := (((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q"))) (PLLND.Tm.var (PLLND.Var.there (PLLND.Var.there PLLND.Var.here))) (PLLND.Tm.app (φ := (PLLFormula.prop "q")) (PLLND.Tm.lam (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here))) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.val (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)))))))))

theorem cell081 : Nonempty (PLLND.LaxND [] (((((PLLFormula.prop "p").somehow).ifThen (PLLFormula.prop "q")).somehow).ifThen (((PLLFormula.prop "p").somehow).ifThen ((PLLFormula.prop "q").somehow)))) :=
  ⟨(cell081_term).toND⟩

#print axioms cell081
