/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(¬◯p ⊃ ¬p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell039_term : PLLND.Tm [] ((((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL).ifThen ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL)) :=
  (PLLND.Tm.lam (PLLND.Tm.lam (PLLND.Tm.app (φ := PLLFormula.falsePLL) (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here)) (PLLND.Tm.app (φ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.var (PLLND.Var.there PLLND.Var.here)) (PLLND.Tm.val (PLLND.Tm.var PLLND.Var.here))))))

theorem cell039 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").somehow).ifThen PLLFormula.falsePLL).ifThen ((PLLFormula.prop "p").ifThen PLLFormula.falsePLL))) :=
  ⟨(cell039_term).toND⟩

#print axioms cell039
