/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell019 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [[]]

theorem cm_cell019_ok : (cm_cell019).okB = true := by decide
theorem cm_cell019_root : (cm_cell019).root < (cm_cell019).n := by decide

def K_cell019 : Kripke := (cm_cell019).toKripke cm_cell019_ok cm_cell019_root

set_option maxRecDepth 1000000 in
theorem cell019_force :
    ¬ (K_cell019).force (K_cell019).root (ofPLL (((PLLFormula.falsePLL.somehow).somehow).somehow)) := by decide

/-- **⊬ ◯◯◯⊥** — refuted by the finite rooted poset model above. -/
theorem cell019 : ¬ Nonempty (PLLND.LaxND [] (((PLLFormula.falsePLL.somehow).somehow).somehow)) :=
  not_derivable_of_countermodel K_cell019 cell019_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell019_control :
    (K_cell019).force (K_cell019).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell019
