/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell068 : FRJ.Search.Tab where
  n := 1
  root := 0
  leT := [[true]]
  rmT := [[true]]
  falT := [false]
  atomsT := [["q"]]

theorem cm_cell068_ok : (cm_cell068).okB = true := by decide
theorem cm_cell068_root : (cm_cell068).root < (cm_cell068).n := by decide

def K_cell068 : Kripke := (cm_cell068).toKripke cm_cell068_ok cm_cell068_root

set_option maxRecDepth 1000000 in
theorem cell068_force :
    ¬ (K_cell068).force (K_cell068).root (ofPLL (((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "p").and (PLLFormula.prop "q")))) := by decide

/-- **⊬ ((p ∨ q) ⊃ (p ∧ q))** — refuted by the finite rooted poset model above. -/
theorem cell068 : ¬ Nonempty (PLLND.LaxND [] (((PLLFormula.prop "p").or (PLLFormula.prop "q")).ifThen ((PLLFormula.prop "p").and (PLLFormula.prop "q")))) :=
  not_derivable_of_countermodel K_cell068 cell068_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell068_control :
    (K_cell068).force (K_cell068).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell068
