/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell052 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, false], [false, true]]
  falT := [false, false]
  atomsT := [[], ["p"]]

theorem cm_cell052_ok : (cm_cell052).okB = true := by decide
theorem cm_cell052_root : (cm_cell052).root < (cm_cell052).n := by decide

def K_cell052 : Kripke := (cm_cell052).toKripke cm_cell052_ok cm_cell052_root

set_option maxRecDepth 1000000 in
theorem cell052_force :
    ¬ (K_cell052).force (K_cell052).root (ofPLL ((((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.prop "p"))) := by decide

/-- **⊬ (¬¬p ⊃ p)** — refuted by the finite rooted poset model above. -/
theorem cell052 : ¬ Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.prop "p"))) :=
  not_derivable_of_countermodel K_cell052 cell052_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell052_control :
    (K_cell052).force (K_cell052).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell052
