/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `(◯◯p ⊃ ◯p)`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell041_term : PLLND.Tm [] ((((PLLFormula.prop "p").somehow).somehow).ifThen ((PLLFormula.prop "p").somehow)) :=
  (PLLND.Tm.lam (PLLND.Tm.bind (φ := ((PLLFormula.prop "p").somehow)) (PLLND.Tm.var PLLND.Var.here) (PLLND.Tm.var PLLND.Var.here)))

theorem cell041 : Nonempty (PLLND.LaxND [] ((((PLLFormula.prop "p").somehow).somehow).ifThen ((PLLFormula.prop "p").somehow))) :=
  ⟨(cell041_term).toND⟩

#print axioms cell041
