/- GENERATED by `lake exe pll`.  Do not edit. -/
import LaxLogic.PLLTerms

/-- The proof term the Gbu◯ decider found for `⊤`;
    its Lax type is its index — the elaborator checks the agreement. -/
def cell064_term : PLLND.Tm [] (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL) :=
  (PLLND.Tm.lam (PLLND.Tm.var PLLND.Var.here))

theorem cell064 : Nonempty (PLLND.LaxND [] (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) :=
  ⟨(cell064_term).toND⟩

#print axioms cell064
