/- GENERATED by `lake exe pll`.  Do not edit. -/
import FRJ.Search.Pin

open FRJ

def cm_cell008 : FRJ.Search.Tab where
  n := 2
  root := 0
  leT := [[true, true], [false, true]]
  rmT := [[true, true], [false, true]]
  falT := [false, true]
  atomsT := [[], []]

theorem cm_cell008_ok : (cm_cell008).okB = true := by decide
theorem cm_cell008_root : (cm_cell008).root < (cm_cell008).n := by decide

def K_cell008 : Kripke := (cm_cell008).toKripke cm_cell008_ok cm_cell008_root

set_option maxRecDepth 1000000 in
theorem cell008_force :
    ¬ (K_cell008).force (K_cell008).root (ofPLL ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)) := by decide

/-- **⊬ ¬◯⊥** — refuted by the finite rooted poset model above. -/
theorem cell008 : ¬ Nonempty (PLLND.LaxND [] ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)) :=
  not_derivable_of_countermodel K_cell008 cell008_force

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_cell008_control :
    (K_cell008).force (K_cell008).root (ofPLL (PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)) := by decide

#print axioms cell008
