/-
# Completeness of FRJ(G) — Section 6

The direct route (Lemma `minMod`, Theorem `minMod`), which the paper
records in a footnote as the completeness proof of the TABLEAUX 2017
version.  We prove the EXISTENCE half of Lemma 6.4: the rank bounds (i)
and (iii) serve minimality, which is out of scope, and dropping them
costs nothing in the construction.

Setting: `K` a countermodel for `G`, `α` a world, and

* `α ⊩* H` iff `α ⊩ H` and either `H ∈ PV`, or `H = A ⊃ B` and `α ⊮ A`;
* `Λ_α  = {A ∈ Sf^L(G) | α ⊩ A}`;
* `Λ*_α = {A ∈ Sf^L(G) | α ⊩* A}`;
* `Ω_α  = {C ∈ Sf^R(G) | α ⊮ C}`.

Note that `Λ*_α ⊆ Ĝ` by construction — its members are variables or
implications — which is what lets it appear on the left of a sequent.

**Constructive metatheory.**  The paper is classical, and forms `Λ*_α`
by classical comprehension.  We do not need to: `Kripke` carries a world
enumeration together with decidable order and valuation, so forcing is
DECIDABLE (`decForce`), `Λ*_α` is an ordinary `List.filter`, and the
height of a world is a `List.countP`.  Nothing here depends on
`Classical.choice`, and the construction computes.
-/
import FRJ.Sound

namespace FRJ

open Form

namespace Kripke

variable (K : Kripke)

/-- `α ⊩* H`: "`α ⊩ H` and either `H ∈ PV` or `H = A ⊃ B` and `α ⊮ A`".
For every other shape of `H` this is false, so the formulas satisfying it
are variables and implications only. -/
def forceStar (a : K.W) : Form → Prop
  | .atom p => K.V a p
  | .imp A B => K.force a (.imp A B) ∧ ¬ K.force a A
  | _ => False

theorem forceStar_force {a : K.W} : ∀ {H : Form}, K.forceStar a H → K.force a H := by
  intro H h
  cases H with
  | atom p => exact h
  | bot => exact h.elim
  | and A B => exact h.elim
  | or A B => exact h.elim
  | imp A B => exact h.1

/-- A formula satisfying `⊩*` is a variable or an implication. -/
theorem forceStar_shape {a : K.W} : ∀ {H : Form},
    K.forceStar a H → H.isPV ∨ H.isImp := by
  intro H h
  cases H with
  | atom p => exact Or.inl rfl
  | bot => exact h.elim
  | and A B => exact h.elim
  | or A B => exact h.elim
  | imp A B => exact Or.inr rfl

/-- `⊩*` is decidable, because `⊩` is. -/
instance decForceStar (K : Kripke) (a : K.W) :
    ∀ H : Form, Decidable (K.forceStar a H)
  | .atom p => K.decV a p
  | .bot => inferInstanceAs (Decidable False)
  | .and _ _ => inferInstanceAs (Decidable False)
  | .or _ _ => inferInstanceAs (Decidable False)
  | .imp A B =>
      inferInstanceAs (Decidable (K.force a (.imp A B) ∧ ¬ K.force a A))

end Kripke

/-- `Λ*_α`.  A filter, not a classical comprehension. -/
def lamStar (K : Kripke) (a : K.W) (G : Form) : List Form :=
  (sfL G).filter (fun H => decide (K.forceStar a H))

theorem mem_lamStar {K : Kripke} {a : K.W} {G H : Form} :
    H ∈ lamStar K a G ↔ (H ∈ sfL G ∧ K.forceStar a H) := by
  simp [lamStar, List.mem_filter]

/-- `Λ*_α ⊆ Ĝ`: this is what lets it stand on the left of a sequent. -/
theorem lamStar_subset_gHat {K : Kripke} {a : K.W} {G : Form} :
    lamStar K a G ⊆ gHat G := by
  intro H hH
  obtain ⟨hsf, hst⟩ := mem_lamStar.mp hH
  rcases K.forceStar_shape hst with h | h
  · exact List.mem_append_left _ (List.mem_filter.mpr ⟨hsf, h⟩)
  · exact List.mem_append_right _ (List.mem_filter.mpr ⟨hsf, h⟩)

/-- Everything in `Λ*_α` is forced at `α`. -/
theorem forces_lamStar {K : Kripke} {a : K.W} {G : Form} :
    K.forces a (lamStar K a G) :=
  fun _ hH => K.forceStar_force (mem_lamStar.mp hH).2

/-- Hence everything in `Cl(Λ*_α)` is forced at `α` — one half of the
paper's Lemma 6.5, and the half that holds for arbitrary formulas. -/
theorem forces_clo_lamStar {K : Kripke} {a : K.W} {G X : Form}
    (h : Clo (lamStar K a G) X) : K.force a X :=
  clo_forces forces_lamStar h

/-- **Lemma 6.5, the direction the construction uses**: a left subformula
forced at `α` lies in `Cl(Λ*_α)`.

DIVERGENCE (recorded in `docs/frj-fidelity.md`): the paper states this as
the set equality `Λ_α = Cl(Λ_α) = Cl(Λ*_α)`.  Taken literally the first
equality is false — `Cl` is generated by a grammar in which `A` ranges
over ALL formulas, so `Cl(Λ_α)` contains `Z ⊃ C` for arbitrary `Z`,
which need not lie in `Sf^L(G)` and so not in `Λ_α`.  Its proof also has
a step ("`α ⊩ A ∧ B`, hence `A ∧ B ∈ Λ_α`") that silently needs
`A ∧ B ∈ Sf^L(G)`.  What the rest of the paper actually uses are the two
directions proved here and in `forces_clo_lamStar`, and both are true. -/
theorem mem_clo_lamStar {K : Kripke} {a : K.W} {G : Form} :
    ∀ {A : Form}, A ∈ sfL G → K.force a A → Clo (lamStar K a G) A := by
  intro A
  induction A with
  | atom p =>
      intro hsf hf
      exact .base (mem_lamStar.mpr ⟨hsf, hf⟩)
  | bot => intro _ hf; exact hf.elim
  | and A B ihA ihB =>
      intro hsf hf
      obtain ⟨hA, hB⟩ := sfL_and hsf
      exact .and (ihA hA hf.1) (ihB hB hf.2)
  | or A B ihA ihB =>
      intro hsf hf
      obtain ⟨hA, hB⟩ := sfL_or hsf
      rcases hf with hf | hf
      · exact .orL (ihA hA hf)
      · exact .orR (ihB hB hf)
  | imp A B ihA ihB =>
      intro hsf hf
      obtain ⟨hA, hB⟩ := sfL_imp hsf
      by_cases hfa : K.force a A
      · exact .imp (ihB hB (hf a (K.le_refl a) hfa))
      · exact .base (mem_lamStar.mpr ⟨hsf, ⟨hf, hfa⟩⟩)

/-- `Λ*` grows along `≤`, modulo closure: if `α ≤ β` then everything in
`Λ*_α` lies in `Cl(Λ*_β)`.  (Used where the construction moves to a
world above.) -/
theorem lamStar_mono {K : Kripke} {a b : K.W} {G : Form} (hab : K.le a b) :
    ∀ X ∈ lamStar K a G, Clo (lamStar K b G) X := by
  intro X hX
  obtain ⟨hsf, hst⟩ := mem_lamStar.mp hX
  exact mem_clo_lamStar hsf (K.force_mono hab (K.forceStar_force hst))

/-! ## The height of a world

The paper's main induction is on `h(α)`, the length of the longest chain
above `α`, which decreases as one moves up.  On a finite poset the
cardinality of the strict up-set does the same job and is easier to
handle. -/

/-- `h(α)`, realised as the number of worlds strictly above `α`, counted
over the model's own enumeration.  (`Finset.card` would need `Fintype`,
and `Fintype.ofFinite` costs `Classical.choice`.) -/
def ht (K : Kripke) (a : K.W) : Nat :=
  K.elems.countP (fun b => decide (K.le a b ∧ b ≠ a))

/-- Moving strictly up strictly decreases the height. -/
theorem ht_lt {K : Kripke} {a b : K.W} (hab : K.le a b) (hne : b ≠ a) :
    ht K b < ht K a := by
  refine countP_lt_countP ?_ (K.complete b) ?_ ?_
  · intro c _ hc
    simp only [decide_eq_true_eq] at hc ⊢
    refine ⟨K.le_trans hab hc.1, ?_⟩
    intro hca
    exact hne (K.le_antisymm (hca ▸ hc.1) hab)
  · simp only [decide_eq_true_eq]
    exact ⟨hab, hne⟩
  · simp

/-! ## The minimal `η`

The paper's "without loss of generality" choice of a world `η ≥ α` with
`η ⊩ A`, `η ⊮ B` and no world strictly between forcing `A`.  This has to
be DATA: the derivation the completeness construction builds from it must
compute, and extracting a witness from an existence proof is choice. -/

/-- The candidate worlds. -/
def etaCand (K : Kripke) (a : K.W) (A B : Form) : List K.W :=
  K.elems.filter (fun x => decide (K.le a x ∧ K.force x A ∧ ¬ K.force x B))

theorem mem_etaCand {K : Kripke} {a : K.W} {A B : Form} {e : K.W} :
    e ∈ etaCand K a A B ↔ (K.le a e ∧ K.force e A ∧ ¬ K.force e B) := by
  simp [etaCand, List.mem_filter, K.complete e]

/-- `α ⊮ A ⊃ B` means there is a candidate.  Constructive, because
forcing is decidable. -/
theorem etaCand_ne_nil {K : Kripke} {a : K.W} {A B : Form}
    (h : ¬ K.force a (.imp A B)) : etaCand K a A B ≠ [] := by
  intro hn
  refine h ?_
  rw [Kripke.force_imp]
  intro b hab hbA
  by_cases hbB : K.force b B
  · exact hbB
  · exact absurd (mem_etaCand.mpr ⟨hab, hbA, hbB⟩) (by rw [hn]; exact List.not_mem_nil)

/-- The paper's minimal `η`, as data. -/
structure MinEta (K : Kripke) (a : K.W) (A B : Form) : Type where
  e : K.W
  le : K.le a e
  fA : K.force e A
  nfB : ¬ K.force e B
  min : ∀ d : K.W, K.le a d → K.le d e → d ≠ e → ¬ K.force d A

/-- Take a candidate of maximal height: no candidate lies strictly below
it, which is the minimality the paper asks for. -/
def minEta {K : Kripke} {a : K.W} {A B : Form}
    (h : ¬ K.force a (.imp A B)) : MinEta K a A B :=
  match hopt : (etaCand K a A B).argmax (fun x => ht K x) with
  | none => absurd (List.argmax_eq_none.mp hopt) (etaCand_ne_nil h)
  | some e =>
      { e := e
        le := (mem_etaCand.mp (List.argmax_mem (Option.mem_def.mpr hopt))).1
        fA := (mem_etaCand.mp (List.argmax_mem (Option.mem_def.mpr hopt))).2.1
        nfB := (mem_etaCand.mp (List.argmax_mem (Option.mem_def.mpr hopt))).2.2
        min := by
          intro d had hde hdne hdA
          have heB := (mem_etaCand.mp (List.argmax_mem (Option.mem_def.mpr hopt))).2.2
          have hdB : ¬ K.force d B := fun hc => heB (K.force_mono hde hc)
          have hle : ht K d ≤ ht K e :=
            List.le_of_mem_argmax (mem_etaCand.mpr ⟨had, hdA, hdB⟩)
              (Option.mem_def.mpr hopt)
          exact absurd hle (Nat.not_le.mpr (ht_lt hde hdne.symm)) }


end FRJ
