/-
# Completeness of FRJ(G) — Section 6

The direct route (Lemma `minMod`, Theorem `minMod`), which the paper
records in a footnote as the completeness proof of the TABLEAUX 2017
version.  We prove the EXISTENCE half of Lemma 6.4: the rank bounds (i)
and (iii) serve minimality, which is out of scope, and dropping them
costs nothing in the construction.

Setting: `K` a countermodel for `G`, `α` a world, and

* `α ⊩* H` iff `α ⊩ H` and either `H ∈ PV`, or `H = A ⊃ B` and `α ⊮ A`;
* `Λ_α  = {A ∈ Sf^L(G) | α ⊩ A}`;
* `Λ*_α = {A ∈ Sf^L(G) | α ⊩* A}`;
* `Ω_α  = {C ∈ Sf^R(G) | α ⊮ C}`.

Note that `Λ*_α ⊆ Ĝ` by construction — its members are variables or
implications — which is what lets it appear on the left of a sequent.

**Classical metatheory.**  The paper is classical throughout, and `Λ*_α`
is a *finite set* carved out of `Sf^L(G)` by a forcing condition, which
is not decidable for an abstract Kripke model.  We therefore use
classical decidability to form these `Finset`s.  This is the paper's own
setting, not a divergence from it.
-/
import FRJ.Sound

namespace FRJ

open Form

namespace Kripke

variable (K : Kripke)

/-- `α ⊩* H`: "`α ⊩ H` and either `H ∈ PV` or `H = A ⊃ B` and `α ⊮ A`".
For every other shape of `H` this is false, so the formulas satisfying it
are variables and implications only. -/
def forceStar (a : K.W) : Form → Prop
  | .atom p => K.V a p
  | .imp A B => K.force a (.imp A B) ∧ ¬ K.force a A
  | _ => False

theorem forceStar_force {a : K.W} : ∀ {H : Form}, K.forceStar a H → K.force a H := by
  intro H h
  cases H with
  | atom p => exact h
  | bot => exact h.elim
  | and A B => exact h.elim
  | or A B => exact h.elim
  | imp A B => exact h.1

/-- A formula satisfying `⊩*` is a variable or an implication. -/
theorem forceStar_shape {a : K.W} : ∀ {H : Form},
    K.forceStar a H → H.isPV ∨ H.isImp := by
  intro H h
  cases H with
  | atom p => exact Or.inl trivial
  | bot => exact h.elim
  | and A B => exact h.elim
  | or A B => exact h.elim
  | imp A B => exact Or.inr trivial

end Kripke

open Classical in
/-- `Λ*_α`, as a finite set. -/
noncomputable def lamStar (K : Kripke) (a : K.W) (G : Form) : Finset Form :=
  (sfL G).filter (fun H => K.forceStar a H)

theorem mem_lamStar {K : Kripke} {a : K.W} {G H : Form} :
    H ∈ lamStar K a G ↔ (H ∈ sfL G ∧ K.forceStar a H) := by
  classical
  simp [lamStar]

/-- `Λ*_α ⊆ Ĝ`: this is what lets it stand on the left of a sequent. -/
theorem lamStar_subset_gHat {K : Kripke} {a : K.W} {G : Form} :
    lamStar K a G ⊆ gHat G := by
  intro H hH
  obtain ⟨hsf, hst⟩ := mem_lamStar.mp hH
  rcases K.forceStar_shape hst with h | h
  · exact Finset.mem_union_left _ (Finset.mem_filter.mpr ⟨hsf, h⟩)
  · exact Finset.mem_union_right _ (Finset.mem_filter.mpr ⟨hsf, h⟩)

/-- Everything in `Λ*_α` is forced at `α`. -/
theorem forces_lamStar {K : Kripke} {a : K.W} {G : Form} :
    K.forces a (lamStar K a G) :=
  fun _ hH => K.forceStar_force (mem_lamStar.mp hH).2

/-- Hence everything in `Cl(Λ*_α)` is forced at `α` — one half of the
paper's Lemma 6.5, and the half that holds for arbitrary formulas. -/
theorem forces_clo_lamStar {K : Kripke} {a : K.W} {G X : Form}
    (h : Clo (lamStar K a G) X) : K.force a X :=
  clo_forces forces_lamStar h

/-- **Lemma 6.5, the direction the construction uses**: a left subformula
forced at `α` lies in `Cl(Λ*_α)`.

DIVERGENCE (recorded in `docs/frj-fidelity.md`): the paper states this as
the set equality `Λ_α = Cl(Λ_α) = Cl(Λ*_α)`.  Taken literally the first
equality is false — `Cl` is generated by a grammar in which `A` ranges
over ALL formulas, so `Cl(Λ_α)` contains `Z ⊃ C` for arbitrary `Z`,
which need not lie in `Sf^L(G)` and so not in `Λ_α`.  Its proof also has
a step ("`α ⊩ A ∧ B`, hence `A ∧ B ∈ Λ_α`") that silently needs
`A ∧ B ∈ Sf^L(G)`.  What the rest of the paper actually uses are the two
directions proved here and in `forces_clo_lamStar`, and both are true. -/
theorem mem_clo_lamStar {K : Kripke} {a : K.W} {G : Form} :
    ∀ {A : Form}, A ∈ sfL G → K.force a A → Clo (lamStar K a G) A := by
  intro A
  induction A with
  | atom p =>
      intro hsf hf
      exact .base (mem_lamStar.mpr ⟨hsf, hf⟩)
  | bot => intro _ hf; exact hf.elim
  | and A B ihA ihB =>
      intro hsf hf
      obtain ⟨hA, hB⟩ := sfL_and hsf
      exact .and (ihA hA hf.1) (ihB hB hf.2)
  | or A B ihA ihB =>
      intro hsf hf
      obtain ⟨hA, hB⟩ := sfL_or hsf
      rcases hf with hf | hf
      · exact .orL (ihA hA hf)
      · exact .orR (ihB hB hf)
  | imp A B ihA ihB =>
      intro hsf hf
      obtain ⟨hA, hB⟩ := sfL_imp hsf
      by_cases hfa : K.force a A
      · exact .imp (ihB hB (hf a (K.le_refl a) hfa))
      · exact .base (mem_lamStar.mpr ⟨hsf, ⟨hf, hfa⟩⟩)

/-- `Λ*` grows along `≤`, modulo closure: if `α ≤ β` then everything in
`Λ*_α` lies in `Cl(Λ*_β)`.  (Used where the construction moves to a
world above.) -/
theorem lamStar_mono {K : Kripke} {a b : K.W} {G : Form} (hab : K.le a b) :
    ∀ X ∈ lamStar K a G, Clo (lamStar K b G) X := by
  intro X hX
  obtain ⟨hsf, hst⟩ := mem_lamStar.mp hX
  exact mem_clo_lamStar hsf (K.force_mono hab (K.forceStar_force hst))

/-! ## The height of a world

The paper's main induction is on `h(α)`, the length of the longest chain
above `α`, which decreases as one moves up.  On a finite poset the
cardinality of the strict up-set does the same job and is easier to
handle. -/

open Classical in
/-- `h(α)`, realised as the number of worlds strictly above `α`. -/
noncomputable def ht (K : Kripke) (a : K.W) : Nat :=
  letI : Fintype K.W := Fintype.ofFinite K.W
  (Finset.univ.filter (fun b => K.le a b ∧ b ≠ a)).card

open Classical in
/-- Moving strictly up strictly decreases the height. -/
theorem ht_lt {K : Kripke} {a b : K.W} (hab : K.le a b) (hne : b ≠ a) :
    ht K b < ht K a := by
  letI : Fintype K.W := Fintype.ofFinite K.W
  refine Finset.card_lt_card ⟨?_, ?_⟩
  · intro c hc
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hc ⊢
    refine ⟨K.le_trans hab hc.1, ?_⟩
    intro hca
    subst hca
    exact hne (K.le_antisymm hc.1 hab)
  · intro hsub
    have hb : b ∈ Finset.univ.filter (fun c => K.le a c ∧ c ≠ a) := by
      simp only [Finset.mem_filter, Finset.mem_univ, true_and]
      exact ⟨hab, hne⟩
    have := hsub hb
    simp only [Finset.mem_filter, Finset.mem_univ, true_and] at this
    exact this.2 rfl

/-- A minimal world above `α` at which `A` is forced and `B` is not.
This is the paper's "without loss of generality" choice of `η`: no world
strictly between `α` and `η` forces `A`. -/
theorem exists_min_eta {K : Kripke} {a : K.W} {A B : Form}
    (h : ¬ K.force a (.imp A B)) :
    ∃ e : K.W, K.le a e ∧ K.force e A ∧ ¬ K.force e B ∧
      ∀ d : K.W, K.le a d → K.le d e → d ≠ e → ¬ K.force d A := by
  classical
  letI : Fintype K.W := Fintype.ofFinite K.W
  have hne : (Finset.univ.filter
      (fun e => K.le a e ∧ K.force e A ∧ ¬ K.force e B)).Nonempty := by
    simp only [Kripke.force_imp, not_forall] at h
    obtain ⟨e, he⟩ := h
    refine ⟨e, ?_⟩
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    obtain ⟨h1, h3, h4⟩ := he
    exact ⟨h1, h3, h4⟩
  -- take an element minimal for `≤` among those
  obtain ⟨e, hemem, hmax⟩ := Finset.exists_max_image _ (fun x => ht K x) hne
  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hemem
  refine ⟨e, hemem.1, hemem.2.1, hemem.2.2, ?_⟩
  intro d had hde hdne hdA
  have hdB : ¬ K.force d B := fun hc => hemem.2.2 (K.force_mono hde hc)
  have hdmem : d ∈ Finset.univ.filter
      (fun x => K.le a x ∧ K.force x A ∧ ¬ K.force x B) := by
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨had, hdA, hdB⟩
  exact absurd (hmax d hdmem) (Nat.not_le.mpr (ht_lt hde hdne.symm))


end FRJ
