/-
# The relation `↦` and the sequents occurring in a derivation (Lemma 3.4)

Section 3 of Fiorentini–Ferrari, from "Now, we begin to study the
properties of FRJ(G)-derivations":

* `σ₁ ↦_R σ₂` iff `R` is a rule of `FRJ(G)` such that `σ₂` is the
  conclusion of `R` and `σ₁` is one of its premises;
* `σ₁ ↦₀ σ₂` iff there exists a rule `R` such that `σ₁ ↦_R σ₂`;
* `↦` is the transitive closure of `↦₀`;
* `↦*` is the reflexive closure of `↦`.

and then **Lemma 3.4** (`lemma:lhs`):

* (i)   `σ₁ ↦_R σ₂` and `R ≠ ⊃∉` imply `Lhs(σ₂) ⊆ Lhs(σ₁)`;
* (ii)  `σ₁ ↦₀ σ₂` implies `Lhs(σ₂) ⊆ Cl(Lhs(σ₁))`;
* (iii) `σ₁ ↦* σ₂` implies `Lhs(σ₂) ⊆ Cl(Lhs(σ₁))`.

`↦` is a relation on SEQUENTS generated by the rule instances, exactly
as the paper defines it, so it is reified here independently of any
derivation.  Occurrence in a derivation is separate, and the two are
tied together by `occR_steps`/`occI_steps`: every sequent occurring in
`D` reaches `D`'s root sequent by `↦*`.  That is the form in which the
soundness proof consumes Lemma 3.4(iii).
-/
import FRJ.Calculus

namespace FRJ

open Form

/-! ## Sequents as data -/

/-- An `FRJ(G)`-sequent: regular `Γ ⇒ C` or irregular `Σ ; Θ → C`. -/
inductive Sequent where
  | reg (Γ : List Form) (C : Form)
  | irr (St Th : List Form) (C : Form)
  deriving DecidableEq

namespace Sequent

/-- "`Lhs(σ) = Γ` if `σ` is regular, `Σ ++ Θ` if `σ` is irregular." -/
def lhs : Sequent → List Form
  | .reg Γ _ => Γ
  | .irr St Th _ => St ++ Th

/-- "`Rhs(σ) = C`." -/
def rhs : Sequent → Form
  | .reg _ C => C
  | .irr _ _ C => C

@[simp] theorem lhs_reg (Γ : List Form) (C : Form) : (reg Γ C).lhs = Γ := rfl
@[simp] theorem lhs_irr (St Th : List Form) (C : Form) :
    (irr St Th C).lhs = St ++ Th := rfl

end Sequent

/-- The names of the rules that have premises.  `Ax^R` and `Ax^I` have
none, so they generate no instance of `↦`. -/
inductive RuleName where
  | andR1 | andR2 | impIn | circIn | joinAt | joinAtP | joinAtF | joinOr
  | joinOrP | joinOrF | joinCirc | joinCircP | promAt | promOr | promCirc
  | andI1 | andI2 | orI | impInI | impNotIn | circNotIn
  deriving DecidableEq

/-! ## `↦_R`, `↦₀`, `↦`, `↦*` -/

/-- `σ₁ ↦_R σ₂`: `σ₂` is the conclusion of an instance of rule `R` and
`σ₁` is one of its premises.  Only the side conditions that Lemma 3.4
consumes are carried. -/
inductive Step (G : Form) : RuleName → Sequent → Sequent → Prop
  | andR1 {Γ : List Form} {A₁ A₂ : Form} :
      Step G .andR1 (.reg Γ A₁) (.reg Γ (.and A₁ A₂))
  | andR2 {Γ : List Form} {A₁ A₂ : Form} :
      Step G .andR2 (.reg Γ A₂) (.reg Γ (.and A₁ A₂))
  | impIn {Γ : List Form} {A B : Form} :
      Step G .impIn (.reg Γ B) (.reg Γ (.imp A B))
  | circIn {Γ : List Form} {Z : Form} :
      Step G .circIn (.reg Γ Z) (.reg Γ (.circ Z))
  | andI1 {St Th : List Form} {A₁ A₂ : Form} :
      Step G .andI1 (.irr St Th A₁) (.irr St Th (.and A₁ A₂))
  | andI2 {St Th : List Form} {A₁ A₂ : Form} :
      Step G .andI2 (.irr St Th A₂) (.irr St Th (.and A₁ A₂))
  | orI₁ {St₁ Th₁ St₂ Th₂ St' Th' : List Form} {C₁ C₂ : Form}
      (h₁ : St₁ ⊆ St₂ ++ Th₂) (h₂ : St₂ ⊆ St₁ ++ Th₁)
      (hSt : St' ≐ St₁ ++ St₂) (hTh : Th' ≐ cap Th₁ Th₂) :
      Step G .orI (.irr St₁ Th₁ C₁) (.irr St' Th' (.or C₁ C₂))
  | orI₂ {St₁ Th₁ St₂ Th₂ St' Th' : List Form} {C₁ C₂ : Form}
      (h₁ : St₁ ⊆ St₂ ++ Th₂) (h₂ : St₂ ⊆ St₁ ++ Th₁)
      (hSt : St' ≐ St₁ ++ St₂) (hTh : Th' ≐ cap Th₁ Th₂) :
      Step G .orI (.irr St₂ Th₂ C₂) (.irr St' Th' (.or C₁ C₂))
  | impInI {St Th Lam ThLam St' Th' : List Form} {A B : Form}
      (hdisj : cap Th Lam = []) (hpre : ThLam ≐ Th ++ Lam)
      (hSt : St' ≐ St ++ Lam) (hTh : Th' ≐ Th) :
      Step G .impInI (.irr St ThLam B) (.irr St' Th' (.imp A B))
  | impNotIn {Γ Th : List Form} {A B : Form}
      (hTh : ∀ X ∈ Th, Clo Γ X ∧ X ∈ gHat G) :
      Step G .impNotIn (.reg Γ B) (.irr [] Th (.imp A B))
  | circNotIn {Γ Th : List Form} {Z : Form}
      (hTh : ∀ X ∈ Th, Clo Γ X ∧ X ∈ gHat G) :
      Step G .circNotIn (.reg Γ Z) (.irr [] Th (.circ Z))
  | joinAt {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form} (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinAt (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxAt stab th rhs F) F)
  | joinOr {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form} (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinOr (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxOr stab th rhs) (.or C₁ C₂))
  | joinAtP {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form} {Δs : Fin (k + 1) → List Form}
      (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinAtP (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxAtP stab th rhs F Δs) F)
  /-- the promise edge of `⋈^At,p`: condition (J7) is what Lemma 3.5
  consumes, exactly as `⊃∉` supplies its `Θ ⊆ Cl(Γ)` condition. -/
  | promAt {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form} (i : Fin (k + 1))
      (hJ7 : ∀ X ∈ joinCtxAtP stab th rhs F Δs, Clo (Δs i) X) :
      Step G .promAt (.reg (Δs i) (Ds i))
        (.reg (joinCtxAtP stab th rhs F Δs) F)
  | joinAtF {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form} (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinAtF (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxAtF stab th rhs F) F)
  | joinOrP {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form} {Δs : Fin (k + 1) → List Form}
      (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinOrP (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxOrP stab th rhs Δs) (.or C₁ C₂))
  | promOr {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form} (i : Fin (k + 1))
      (hJ7 : ∀ X ∈ joinCtxOrP stab th rhs Δs, Clo (Δs i) X) :
      Step G .promOr (.reg (Δs i) (Ds i))
        (.reg (joinCtxOrP stab th rhs Δs) (.or C₁ C₂))
  | joinOrF {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form} (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinOrF (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxOrF stab th rhs) (.or C₁ C₂))
  | joinCirc {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {Z : Form} (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinCirc (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxOr stab th rhs) (.circ Z))
  | joinCircP {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {Z : Form} {Δs : Fin (k + 1) → List Form}
      (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinCircP (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxOrP stab th rhs Δs) (.circ Z))
  | promCirc {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {Z : Form} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form} (i : Fin (k + 1))
      (hJ7 : ∀ X ∈ joinCtxOrP stab th rhs Δs, Clo (Δs i) X) :
      Step G .promCirc (.reg (Δs i) (Ds i))
        (.reg (joinCtxOrP stab th rhs Δs) (.circ Z))

/-- `σ₁ ↦₀ σ₂`: "there exists a rule `R` such that `σ₁ ↦_R σ₂`." -/
def Step₀ (G : Form) (s₁ s₂ : Sequent) : Prop := ∃ R, Step G R s₁ s₂

/-- `↦*`, the reflexive-transitive closure. -/
abbrev StepsRfl (G : Form) : Sequent → Sequent → Prop :=
  Relation.ReflTransGen (Step₀ G)

/-! ## Auxiliary facts about the join contexts -/

theorem interAll_subset {n : Nat} {f : Fin (n + 1) → List Form}
    (j : Fin (n + 1)) : interAll f ⊆ f j :=
  fun _ hx => (mem_interAll.mp hx) j

theorem atPart_subset {Γ : List Form} : atPart Γ ⊆ Γ := (fun _ h => (List.mem_filter.mp h).1)

theorem impPart_subset {Γ : List Form} : impPart Γ ⊆ Γ := (fun _ h => (List.mem_filter.mp h).1)

theorem circPart_subset {Γ : List Form} : circPart Γ ⊆ Γ := (fun _ h => (List.mem_filter.mp h).1)

/-- `Σ^at` and `Σ^imp` land inside every premise's left formulas, by (J1). -/
theorem unionAll_part_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1))
    (part : List Form → List Form) (hpart : ∀ Γ, part Γ ⊆ Γ) :
    unionAll (fun i => part (stab i)) ⊆ stab j ++ th j := by
  intro x hx
  obtain ⟨i, hi⟩ := mem_unionAll.mp hx
  have hx' : x ∈ stab i := hpart _ hi
  by_cases hij : i = j
  · subst hij; exact List.mem_append_left _ hx'
  · exact hJ1 i j hij hx'

theorem joinCtxAt_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form} {F : Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxAt stab th rhs F ⊆ stab j ++ th j := by
  intro x hx
  simp only [joinCtxAt, List.mem_append] at hx
  rcases hx with ((hx | hx) | hx) | hx
  · exact unionAll_part_subset hJ1 j atPart (fun _ => atPart_subset) hx
  · exact List.mem_append_right _
      (atPart_subset (interAll_subset j (rm_subset hx)))
  · exact unionAll_part_subset hJ1 j impPart (fun _ => impPart_subset) hx
  · exact List.mem_append_right _
      (impPart_subset (interAll_subset j (restrict_subset hx)))

theorem joinCtxOr_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxOr stab th rhs ⊆ stab j ++ th j := by
  intro x hx
  simp only [joinCtxOr, List.mem_append] at hx
  rcases hx with ((hx | hx) | hx) | hx
  · exact unionAll_part_subset hJ1 j atPart (fun _ => atPart_subset) hx
  · exact List.mem_append_right _ (atPart_subset (interAll_subset j hx))
  · exact unionAll_part_subset hJ1 j impPart (fun _ => impPart_subset) hx
  · exact List.mem_append_right _
      (impPart_subset (interAll_subset j (restrict_subset hx)))

/-- The modal part of a promise/fallible join context also lands in every
premise's left formulas, by (J1) for the stable half and by the
intersections for the second-zone half. -/
theorem joinCtxCircP_subset {n k : Nat} {stab th : Fin (n + 1) → List Form}
    {Δs : Fin (k + 1) → List Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxCircP stab th Δs ⊆ stab j ++ th j := by
  intro x hx
  simp only [joinCtxCircP, List.mem_append] at hx
  rcases hx with hx | hx
  · exact unionAll_part_subset hJ1 j circPart (fun _ => circPart_subset) hx
  · exact List.mem_append_right _
      (circPart_subset (interAll_subset j (restrictC_subset hx)))

theorem joinCtxCircF_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxCircF stab th ⊆ stab j ++ th j := by
  intro x hx
  simp only [joinCtxCircF, List.mem_append] at hx
  rcases hx with hx | hx
  · exact unionAll_part_subset hJ1 j circPart (fun _ => circPart_subset) hx
  · exact List.mem_append_right _ (circPart_subset (interAll_subset j hx))

theorem joinCtxAtP_subset {n k : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form} {F : Form} {Δs : Fin (k + 1) → List Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxAtP stab th rhs F Δs ⊆ stab j ++ th j := by
  intro x hx
  rcases List.mem_append.mp (restrictP_subset hx) with hx | hx
  · exact joinCtxAt_subset hJ1 j hx
  · exact joinCtxCircP_subset hJ1 j hx

theorem joinCtxAtF_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form} {F : Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxAtF stab th rhs F ⊆ stab j ++ th j := by
  intro x hx
  rcases List.mem_append.mp hx with hx | hx
  · exact joinCtxAt_subset hJ1 j hx
  · exact joinCtxCircF_subset hJ1 j hx

theorem joinCtxOrP_subset {n k : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form} {Δs : Fin (k + 1) → List Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxOrP stab th rhs Δs ⊆ stab j ++ th j := by
  intro x hx
  rcases List.mem_append.mp (restrictP_subset hx) with hx | hx
  · exact joinCtxOr_subset hJ1 j hx
  · exact joinCtxCircP_subset hJ1 j hx

theorem joinCtxOrF_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxOrF stab th rhs ⊆ stab j ++ th j := by
  intro x hx
  rcases List.mem_append.mp hx with hx | hx
  · exact joinCtxOr_subset hJ1 j hx
  · exact joinCtxCircF_subset hJ1 j hx

/-- (J7), now a THEOREM of the restricted promise contexts: everything a
promise join keeps lies in every `Cl(Δᵢ)`. -/
theorem joinCtxAtP_clo {n k : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form} {F : Form} {Δs : Fin (k + 1) → List Form}
    (i : Fin (k + 1)) : ∀ X ∈ joinCtxAtP stab th rhs F Δs, Clo (Δs i) X :=
  fun _ hX => (mem_restrictP.mp hX).2 i

theorem joinCtxOrP_clo {n k : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form} {Δs : Fin (k + 1) → List Form}
    (i : Fin (k + 1)) : ∀ X ∈ joinCtxOrP stab th rhs Δs, Clo (Δs i) X :=
  fun _ hX => (mem_restrictP.mp hX).2 i

/-! ## Lemma 3.4 -/

/-- **Lemma 3.4(i).**  "`σ₁ ↦_R σ₂` and `R ≠ ⊃∉` imply
`Lhs(σ₂) ⊆ Lhs(σ₁)`."  `◯∉` joins `⊃∉` on the exception list: both
change world, so their conclusion's zone is contained in the premise's
only modulo `Cl`. -/
theorem lhs_subset_of_step {G : Form} {R : RuleName} {s₁ s₂ : Sequent}
    (h : Step G R s₁ s₂)
    (hR : R ≠ .impNotIn) (hRc : R ≠ .circNotIn)
    (hRp : R ≠ .promAt) (hRq : R ≠ .promOr) (hRr : R ≠ .promCirc) :
    s₂.lhs ⊆ s₁.lhs := by
  cases h with
  | andR1 => exact List.Subset.refl _
  | andR2 => exact List.Subset.refl _
  | impIn => exact List.Subset.refl _
  | circIn => exact List.Subset.refl _
  | andI1 => exact List.Subset.refl _
  | andI2 => exact List.Subset.refl _
  | orI₁ h₁ h₂ hSt hTh =>
      intro x hx
      simp only [Sequent.lhs_irr, List.mem_append] at hx ⊢
      rcases hx with hx | hx
      · rcases List.mem_append.mp ((hSt x).mp hx) with hx' | hx'
        · exact Or.inl hx'
        · exact List.mem_append.mp (h₂ hx')
      · exact Or.inr (mem_cap.mp ((hTh x).mp hx)).1
  | orI₂ h₁ h₂ hSt hTh =>
      intro x hx
      simp only [Sequent.lhs_irr, List.mem_append] at hx ⊢
      rcases hx with hx | hx
      · rcases List.mem_append.mp ((hSt x).mp hx) with hx' | hx'
        · exact List.mem_append.mp (h₁ hx')
        · exact Or.inl hx'
      · exact Or.inr (mem_cap.mp ((hTh x).mp hx)).2
  | impInI hdisj hpre hSt hTh =>
      intro x hx
      simp only [Sequent.lhs_irr, List.mem_append] at hx ⊢
      rcases hx with hx | hx
      · rcases List.mem_append.mp ((hSt x).mp hx) with hx' | hx'
        · exact Or.inl hx'
        · exact Or.inr ((hpre x).mpr (List.mem_append_right _ hx'))
      · exact Or.inr ((hpre x).mpr (List.mem_append_left _ ((hTh x).mp hx)))
  | impNotIn => exact absurd rfl hR
  | circNotIn => exact absurd rfl hRc
  | promAt i hJ7 => exact absurd rfl hRp
  | promOr i hJ7 => exact absurd rfl hRq
  | promCirc i hJ7 => exact absurd rfl hRr
  | joinCirc j hJ1 =>
      intro x hx
      exact joinCtxOr_subset hJ1 j hx
  | joinCircP j hJ1 =>
      intro x hx
      exact joinCtxOrP_subset hJ1 j hx
  | joinAt j hJ1 =>
      intro x hx
      exact joinCtxAt_subset hJ1 j hx
  | joinOr j hJ1 =>
      intro x hx
      exact joinCtxOr_subset hJ1 j hx
  | joinAtP j hJ1 =>
      intro x hx
      exact joinCtxAtP_subset hJ1 j hx
  | joinAtF j hJ1 =>
      intro x hx
      exact joinCtxAtF_subset hJ1 j hx
  | joinOrP j hJ1 =>
      intro x hx
      exact joinCtxOrP_subset hJ1 j hx
  | joinOrF j hJ1 =>
      intro x hx
      exact joinCtxOrF_subset hJ1 j hx

/-- **Lemma 3.4(ii).**  "`σ₁ ↦₀ σ₂` implies `Lhs(σ₂) ⊆ Cl(Lhs(σ₁))`."
For every rule but `⊃∉` this is (i) together with (Cl3); for `⊃∉` it is
that rule's own side condition `Θ ⊆ Cl(Γ) ∩ Ĝ`. -/
theorem lhs_clo_of_step₀ {G : Form} {s₁ s₂ : Sequent} (h : Step₀ G s₁ s₂) :
    ∀ X ∈ s₂.lhs, Clo s₁.lhs X := by
  obtain ⟨R, hR⟩ := h
  intro X hX
  by_cases hname : R = .impNotIn
  · subst hname
    cases hR with
    | impNotIn hTh =>
        refine (hTh X ?_).1
        simpa using hX
  by_cases hnameC : R = .circNotIn
  · subst hnameC
    cases hR with
    | circNotIn hTh =>
        refine (hTh X ?_).1
        simpa using hX
  by_cases hnameP : R = .promAt
  · subst hnameP
    cases hR with
    | promAt i hJ7 => exact hJ7 X hX
  by_cases hnameQ : R = .promOr
  · subst hnameQ
    cases hR with
    | promOr i hJ7 => exact hJ7 X hX
  by_cases hnameR : R = .promCirc
  · subst hnameR
    cases hR with
    | promCirc i hJ7 => exact hJ7 X hX
  exact .base (lhs_subset_of_step hR hname hnameC hnameP hnameQ hnameR hX)

/-- **Lemma 3.4(iii).**  "`σ₁ ↦* σ₂` implies `Lhs(σ₂) ⊆ Cl(Lhs(σ₁))`."
By (ii) along the chain, glued with (Cl6). -/
theorem lhs_clo_of_steps {G : Form} {s₁ s₂ : Sequent} (h : StepsRfl G s₁ s₂) :
    ∀ X ∈ s₂.lhs, Clo s₁.lhs X := by
  induction h with
  | refl => exact fun X hX => .base hX
  | tail _ hbc ih => exact fun X hX => clo_trans ih (lhs_clo_of_step₀ hbc X hX)

/-! ## The sequents occurring in a derivation

"σ occurs in D": the root sequent of `D`, or a sequent occurring in one
of its sub-derivations.  An inductive relation, one constructor per
premise slot.
-/

mutual

/-- `σ` occurs in the regular derivation `d`.

The variable-packing below quantifies whole side-condition bundles as
implicit records rather than naming each; what matters is only which
PREMISE SLOT each constructor descends into. -/
inductive OccR {G : Form} : {t : Tag} → {Γ : List Form} → {C : Form} →
    FRJr G t Γ C → Sequent → Prop
  | root {t : Tag} {Γ : List Form} {C : Form} (d : FRJr G t Γ C) : OccR d (.reg Γ C)
  | andR1 {t : Tag} {Γ : List Form} {A₁ A₂ : Form} {d : FRJr G t Γ A₁}
      {hg : Form.and A₁ A₂ ∈ sfR G} {s : Sequent} :
      OccR d s → OccR (FRJr.andR1 d hg) s
  | andR2 {t : Tag} {Γ : List Form} {A₁ A₂ : Form} {d : FRJr G t Γ A₂}
      {hg : Form.and A₁ A₂ ∈ sfR G} {s : Sequent} :
      OccR d s → OccR (FRJr.andR2 d hg) s
  | impIn {t : Tag} {Γ : List Form} {A B : Form} {d : FRJr G t Γ B} {hA : Clo Γ A}
      {hg : Form.imp A B ∈ sfR G} {s : Sequent} :
      OccR d s → OccR (FRJr.impIn d hA hg) s
  | circIn {t : Tag} {Γ : List Form} {Z : Form} {d : FRJr G t Γ Z}
      {htag : t = .barren ∨ ∃ W, t = .chain W ∧ Covers Γ W Z}
      {hg : Form.circ Z ∈ sfR G} {s : Sequent} :
      OccR d s → OccR (FRJr.circIn d htag hg) s
  | joinAt {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hcirc : unionAll (fun j => circPart (stab j)) = []}
      {hF : F.isPrime} {hFnot : F ∉ unionAll (fun j => atPart (stab j))}
      {hg : F ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxAt stab th rhs F} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s → OccR (FRJr.joinAt prem hJ1 hJ2 hcirc hF hFnot hg hΓ) s
  | joinAtP {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form} {t' : Tag}
      {tps : Fin (k + 1) → Tag} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {dps : ∀ i, FRJr G (tps i) (Δs i) (Ds i)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hJ5 : ∀ Y : Form, Form.circ Y ∈ unionAll (fun j => circPart (stab j)) →
        ∃ i, Clo (Δs i) Y}
      {hJ7s : ∀ i j, ∀ X ∈ stab j, Clo (Δs i) X}
      {htag : t' = .blocked ∨ (t' = .chain (Ds 0) ∧ ∀ i, Ds i = Ds 0 ∧
        (tps i = .barren ∨ ∃ W, tps i = .chain W ∧ Covers (Δs i) W (Ds 0)))}
      {hF : F.isPrime} {hFnot : F ∉ unionAll (fun j => atPart (stab j))}
      {hg : F ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxAtP stab th rhs F Δs} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s →
      OccR (FRJr.joinAtP prem dps hJ1 hJ2 hJ5 hJ7s htag hF hFnot hg hΓ) s
  | joinAtPprom {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form} {t' : Tag}
      {tps : Fin (k + 1) → Tag} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {dps : ∀ i, FRJr G (tps i) (Δs i) (Ds i)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hJ5 : ∀ Y : Form, Form.circ Y ∈ unionAll (fun j => circPart (stab j)) →
        ∃ i, Clo (Δs i) Y}
      {hJ7s : ∀ i j, ∀ X ∈ stab j, Clo (Δs i) X}
      {htag : t' = .blocked ∨ (t' = .chain (Ds 0) ∧ ∀ i, Ds i = Ds 0 ∧
        (tps i = .barren ∨ ∃ W, tps i = .chain W ∧ Covers (Δs i) W (Ds 0)))}
      {hF : F.isPrime} {hFnot : F ∉ unionAll (fun j => atPart (stab j))}
      {hg : F ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxAtP stab th rhs F Δs} {s : Sequent} (i : Fin (k + 1)) :
      OccR (dps i) s →
      OccR (FRJr.joinAtP prem dps hJ1 hJ2 hJ5 hJ7s htag hF hFnot hg hΓ) s
  | joinAtF {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hF : F.isPrime} {hFnot : F ∉ unionAll (fun j => atPart (stab j))}
      {hg : F ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxAtF stab th rhs F} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s → OccR (FRJr.joinAtF prem hJ1 hJ2 hF hFnot hg hΓ) s
  | joinOr {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hcirc : unionAll (fun j => circPart (stab j)) = []}
      {hC : C₁ ∈ upsilon rhs ∧ C₂ ∈ upsilon rhs}
      {hg : Form.or C₁ C₂ ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxOr stab th rhs} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s → OccR (FRJr.joinOr prem hJ1 hJ2 hcirc hC hg hΓ) s
  | joinOrP {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form} {t' : Tag}
      {tps : Fin (k + 1) → Tag} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {dps : ∀ i, FRJr G (tps i) (Δs i) (Ds i)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hJ5 : ∀ Y : Form, Form.circ Y ∈ unionAll (fun j => circPart (stab j)) →
        ∃ i, Clo (Δs i) Y}
      {hJ7s : ∀ i j, ∀ X ∈ stab j, Clo (Δs i) X}
      {htag : t' = .blocked ∨ (t' = .chain (Ds 0) ∧ ∀ i, Ds i = Ds 0 ∧
        (tps i = .barren ∨ ∃ W, tps i = .chain W ∧ Covers (Δs i) W (Ds 0)))}
      {hC : C₁ ∈ upsilon rhs ∧ C₂ ∈ upsilon rhs}
      {hg : Form.or C₁ C₂ ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxOrP stab th rhs Δs} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s →
      OccR (FRJr.joinOrP prem dps hJ1 hJ2 hJ5 hJ7s htag hC hg hΓ) s
  | joinOrPprom {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form} {t' : Tag}
      {tps : Fin (k + 1) → Tag} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {dps : ∀ i, FRJr G (tps i) (Δs i) (Ds i)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hJ5 : ∀ Y : Form, Form.circ Y ∈ unionAll (fun j => circPart (stab j)) →
        ∃ i, Clo (Δs i) Y}
      {hJ7s : ∀ i j, ∀ X ∈ stab j, Clo (Δs i) X}
      {htag : t' = .blocked ∨ (t' = .chain (Ds 0) ∧ ∀ i, Ds i = Ds 0 ∧
        (tps i = .barren ∨ ∃ W, tps i = .chain W ∧ Covers (Δs i) W (Ds 0)))}
      {hC : C₁ ∈ upsilon rhs ∧ C₂ ∈ upsilon rhs}
      {hg : Form.or C₁ C₂ ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxOrP stab th rhs Δs} {s : Sequent} (i : Fin (k + 1)) :
      OccR (dps i) s →
      OccR (FRJr.joinOrP prem dps hJ1 hJ2 hJ5 hJ7s htag hC hg hΓ) s
  | joinOrF {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hC : C₁ ∈ upsilon rhs ∧ C₂ ∈ upsilon rhs}
      {hg : Form.or C₁ C₂ ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxOrF stab th rhs} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s → OccR (FRJr.joinOrF prem hJ1 hJ2 hC hg hΓ) s
  | joinCirc {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {Z : Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hcirc : unionAll (fun j => circPart (stab j)) = []}
      {hZ : Z ∈ upsilon rhs}
      {hg : Form.circ Z ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxOr stab th rhs} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s → OccR (FRJr.joinCirc prem hJ1 hJ2 hcirc hZ hg hΓ) s
  | joinCircP {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {Z : Form}
      {tps : Fin (k + 1) → Tag} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {dps : ∀ i, FRJr G (tps i) (Δs i) (Ds i)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hJ5 : ∀ Y : Form, Form.circ Y ∈ unionAll (fun j => circPart (stab j)) →
        ∃ i, Clo (Δs i) Y}
      {hJ7s : ∀ i j, ∀ X ∈ stab j, Clo (Δs i) X}
      {hDs : ∀ i, Ds i = Z ∧
        (tps i = .barren ∨ ∃ W, tps i = .chain W ∧ Covers (Δs i) W Z)}
      {hZ : Z ∈ upsilon rhs}
      {hg : Form.circ Z ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxOrP stab th rhs Δs} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s →
      OccR (FRJr.joinCircP prem dps hJ1 hJ2 hJ5 hJ7s hDs hZ hg hΓ) s
  | joinCircPprom {n k : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {Z : Form}
      {tps : Fin (k + 1) → Tag} {Δs : Fin (k + 1) → List Form}
      {Ds : Fin (k + 1) → Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {dps : ∀ i, FRJr G (tps i) (Δs i) (Ds i)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hJ5 : ∀ Y : Form, Form.circ Y ∈ unionAll (fun j => circPart (stab j)) →
        ∃ i, Clo (Δs i) Y}
      {hJ7s : ∀ i j, ∀ X ∈ stab j, Clo (Δs i) X}
      {hDs : ∀ i, Ds i = Z ∧
        (tps i = .barren ∨ ∃ W, tps i = .chain W ∧ Covers (Δs i) W Z)}
      {hZ : Z ∈ upsilon rhs}
      {hg : Form.circ Z ∈ sfR G} {Γ' : List Form} {hΓ : Γ' = joinCtxOrP stab th rhs Δs} {s : Sequent} (i : Fin (k + 1)) :
      OccR (dps i) s →
      OccR (FRJr.joinCircP prem dps hJ1 hJ2 hJ5 hJ7s hDs hZ hg hΓ) s

/-- `σ` occurs in the irregular derivation `d`. -/
inductive OccI {G : Form} :
    {St Th : List Form} → {C : Form} → FRJi G St Th C → Sequent → Prop
  | root {St Th : List Form} {C : Form} (d : FRJi G St Th C) : OccI d (.irr St Th C)
  | andI1 {St Th : List Form} {A₁ A₂ : Form} {d : FRJi G St Th A₁}
      {hg : Form.and A₁ A₂ ∈ sfR G} {s : Sequent} :
      OccI d s → OccI (FRJi.andI1 d hg) s
  | andI2 {St Th : List Form} {A₁ A₂ : Form} {d : FRJi G St Th A₂}
      {hg : Form.and A₁ A₂ ∈ sfR G} {s : Sequent} :
      OccI d s → OccI (FRJi.andI2 d hg) s
  | orI₁ {St₁ Th₁ St₂ Th₂ : List Form} {C₁ C₂ : Form}
      {d₁ : FRJi G St₁ Th₁ C₁} {d₂ : FRJi G St₂ Th₂ C₂}
      {h₁ : St₁ ⊆ St₂ ++ Th₂} {h₂ : St₂ ⊆ St₁ ++ Th₁}
      {hg : Form.or C₁ C₂ ∈ sfR G} {St' Th' : List Form} {hSt : St' ≐ St₁ ++ St₂} {hTh : Th' ≐ cap Th₁ Th₂} {s : Sequent} :
      OccI d₁ s → OccI (FRJi.orI d₁ d₂ h₁ h₂ hg hSt hTh) s
  | orI₂ {St₁ Th₁ St₂ Th₂ : List Form} {C₁ C₂ : Form}
      {d₁ : FRJi G St₁ Th₁ C₁} {d₂ : FRJi G St₂ Th₂ C₂}
      {h₁ : St₁ ⊆ St₂ ++ Th₂} {h₂ : St₂ ⊆ St₁ ++ Th₁}
      {hg : Form.or C₁ C₂ ∈ sfR G} {St' Th' : List Form} {hSt : St' ≐ St₁ ++ St₂} {hTh : Th' ≐ cap Th₁ Th₂} {s : Sequent} :
      OccI d₂ s → OccI (FRJi.orI d₁ d₂ h₁ h₂ hg hSt hTh) s
  | impInI {St Th Lam ThLam : List Form} {A B : Form}
      {d : FRJi G St ThLam B} {hpre : ThLam ≐ Th ++ Lam}
      {hdisj : cap Th Lam = []} {hA : Clo (St ++ Lam) A}
      {hg : Form.imp A B ∈ sfR G} {St' Th' : List Form} {hSt : St' ≐ St ++ Lam} {hTh : Th' ≐ Th} {s : Sequent} :
      OccI d s → OccI (FRJi.impInI d hpre hdisj hA hg hSt hTh) s
  | impNotIn {t : Tag} {Γ Th : List Form} {A B : Form} {d : FRJr G t Γ B}
      {hTh : ∀ X ∈ Th, Clo Γ X ∧ X ∈ gHat G} {hA : Clo Γ A} {hAnot : ¬ Clo Th A}
      {hg : Form.imp A B ∈ sfR G} {s : Sequent} :
      OccR d s → OccI (FRJi.impNotIn d hTh hA hAnot hg) s
  | circNotIn {t : Tag} {Γ Th : List Form} {Z : Form} {d : FRJr G t Γ Z}
      {htag : t = .barren ∨ ∃ W, t = .chain W ∧ Covers Γ W Z}
      {hTh : ∀ X ∈ Th, Clo Γ X ∧ X ∈ gHat G}
      {hg : Form.circ Z ∈ sfR G} {s : Sequent} :
      OccR d s → OccI (FRJi.circNotIn d htag hTh hg) s

end

/-! ## Occurrence reaches the root by `↦*`

This is the bridge that lets the soundness proof apply Lemma 3.4(iii) to
an arbitrary sequent of `D`.  Each step up the derivation is an instance
of `↦` supplied by the rule that was applied, with its side conditions
taken from the derivation itself. -/

mutual

theorem occR_steps {G : Form} {t : Tag} {Γ : List Form} {C : Form}
    {d : FRJr G t Γ C}
    {s : Sequent} : OccR d s → StepsRfl G s (.reg Γ C)
  | .root _ => .refl
  | .andR1 h' => (occR_steps h').tail ⟨_, .andR1⟩
  | .andR2 h' => (occR_steps h').tail ⟨_, .andR2⟩
  | .impIn h' => (occR_steps h').tail ⟨_, .impIn⟩
  | .circIn h' => (occR_steps h').tail ⟨_, .circIn⟩
  | .joinAt (hΓ := rfl) (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinAt j hJ1⟩
  | .joinAtP (hΓ := rfl) (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinAtP j hJ1⟩
  | .joinAtPprom (hΓ := rfl) i h' => (occR_steps h').tail ⟨_, .promAt i (joinCtxAtP_clo i)⟩
  | .joinAtF (hΓ := rfl) (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinAtF j hJ1⟩
  | .joinOr (hΓ := rfl) (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinOr j hJ1⟩
  | .joinOrP (hΓ := rfl) (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinOrP j hJ1⟩
  | .joinOrPprom (hΓ := rfl) i h' => (occR_steps h').tail ⟨_, .promOr i (joinCtxOrP_clo i)⟩
  | .joinOrF (hΓ := rfl) (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinOrF j hJ1⟩
  | .joinCirc (hΓ := rfl) (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinCirc j hJ1⟩
  | .joinCircP (hΓ := rfl) (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinCircP j hJ1⟩
  | .joinCircPprom (hΓ := rfl) i h' => (occR_steps h').tail ⟨_, .promCirc i (joinCtxOrP_clo i)⟩

theorem occI_steps {G : Form} {St Th : List Form} {C : Form}
    {d : FRJi G St Th C} {s : Sequent} : OccI d s → StepsRfl G s (.irr St Th C)
  | .root _ => .refl
  | .andI1 h' => (occI_steps h').tail ⟨_, .andI1⟩
  | .andI2 h' => (occI_steps h').tail ⟨_, .andI2⟩
  | .orI₁ (hSt := hSt) (hTh := hTh) (h₁ := h₁) (h₂ := h₂) h' =>
      (occI_steps h').tail ⟨_, .orI₁ h₁ h₂ hSt hTh⟩
  | .orI₂ (hSt := hSt) (hTh := hTh) (h₁ := h₁) (h₂ := h₂) h' =>
      (occI_steps h').tail ⟨_, .orI₂ h₁ h₂ hSt hTh⟩
  | .impInI (hpre := hpre) (hSt := hSt) (hTh := hTh) (hdisj := hd) h' =>
      (occI_steps h').tail ⟨_, .impInI hd hpre hSt hTh⟩
  | .impNotIn (hTh := hTh) h' => (occR_steps h').tail ⟨_, .impNotIn hTh⟩
  | .circNotIn (hTh := hTh) h' => (occR_steps h').tail ⟨_, .circNotIn hTh⟩

end

/-- **Lemma 3.4(iii), in the form the soundness proof uses it.**  For any
sequent `σ` occurring in a derivation `D` of `Γ ⇒ C`, the left formulas
of `D`'s root sequent lie in `Cl(Lhs(σ))`. -/
theorem lhs_clo_of_occR {G : Form} {t : Tag} {Γ : List Form} {C : Form}
    {d : FRJr G t Γ C} {s : Sequent} (h : OccR d s) :
    ∀ X ∈ Γ, Clo s.lhs X :=
  lhs_clo_of_steps (occR_steps h)

/-! ## Well-formedness of derivable sequents

The paper builds the constraints `Γ ⊆ Ĝ` and `Σ ++ Θ ⊆ Ĝ` into the
definition of the sequent set.  We carry them as a lemma instead
(divergence 4 of `docs/frj-fidelity.md`), and this is that lemma.  It is
what makes the `atPart`/`impPart` split in the join rules faithful: a
context can only contain variables and `⊃`-formulas, so the split loses
nothing. -/

mutual

/-- Every context of a derivable regular sequent lies inside `Ĝ`. -/
theorem wfR {G : Form} : ∀ {t : Tag} {Γ : List Form} {C : Form},
    FRJr G t Γ C → Γ ⊆ gHat G
  | _, _, _, .axR _ _ _ rfl => fun _ hx =>
      List.mem_append_left _ (List.mem_append_left _ (rm_subset hx))
  | _, _, _, .andR1 d _ => wfR d
  | _, _, _, .andR2 d _ => wfR d
  | _, _, _, .impIn d _ _ => wfR d
  | _, _, _, .circIn d _ _ => wfR d
  | _, _, _, .joinAt prem hJ1 _ _ _ _ _ rfl => fun _ hx =>
      wfI (prem 0) (joinCtxAt_subset hJ1 0 hx)
  | _, _, _, .joinAtP prem _ hJ1 _ _ _ _ _ _ _ rfl => fun _ hx =>
      wfI (prem 0) (joinCtxAtP_subset hJ1 0 hx)
  | _, _, _, .joinAtF prem hJ1 _ _ _ _ rfl => fun _ hx =>
      wfI (prem 0) (joinCtxAtF_subset hJ1 0 hx)
  | _, _, _, .joinOr prem hJ1 _ _ _ _ rfl => fun _ hx =>
      wfI (prem 0) (joinCtxOr_subset hJ1 0 hx)
  | _, _, _, .joinOrP prem _ hJ1 _ _ _ _ _ _ rfl => fun _ hx =>
      wfI (prem 0) (joinCtxOrP_subset hJ1 0 hx)
  | _, _, _, .joinOrF prem hJ1 _ _ _ rfl => fun _ hx =>
      wfI (prem 0) (joinCtxOrF_subset hJ1 0 hx)
  | _, _, _, .joinCirc prem hJ1 _ _ _ _ rfl => fun _ hx =>
      wfI (prem 0) (joinCtxOr_subset hJ1 0 hx)
  | _, _, _, .joinCircP prem _ hJ1 _ _ _ _ _ _ rfl => fun _ hx =>
      wfI (prem 0) (joinCtxOrP_subset hJ1 0 hx)

/-- Every zone of a derivable irregular sequent lies inside `Ĝ`. -/
theorem wfI {G : Form} : ∀ {St Th : List Form} {C : Form},
    FRJi G St Th C → St ++ Th ⊆ gHat G
  | _, _, _, .axI _ _ _ hTh => by
      intro x hx
      simp only [List.nil_append] at hx
      rcases List.mem_append.mp ((hTh x).mp hx) with hx' | hx'
      · rcases List.mem_append.mp hx' with hx'' | hx''
        · exact List.mem_append_left _ (List.mem_append_left _ (rm_subset hx''))
        · exact List.mem_append_left _ (List.mem_append_right _ hx'')
      · exact List.mem_append_right _ hx'
  | _, _, _, .andI1 d _ => wfI d
  | _, _, _, .andI2 d _ => wfI d
  | _, _, _, .orI d₁ _ _ h₂ _ hSt hTh => by
      intro x hx
      rcases List.mem_append.mp hx with hx | hx
      · rcases List.mem_append.mp ((hSt x).mp hx) with hx | hx
        · exact wfI d₁ (List.mem_append_left _ hx)
        · exact wfI d₁ (h₂ hx)
      · exact wfI d₁ (List.mem_append_right _ (mem_cap.mp ((hTh x).mp hx)).1)
  | _, _, _, .impInI d hpre _ _ _ hSt hTh => by
      intro x hx
      rcases List.mem_append.mp hx with hx | hx
      · rcases List.mem_append.mp ((hSt x).mp hx) with hx' | hx'
        · exact wfI d (List.mem_append_left _ hx')
        · exact wfI d (List.mem_append_right _ ((hpre x).mpr (List.mem_append_right _ hx')))
      · exact wfI d (List.mem_append_right _
          ((hpre x).mpr (List.mem_append_left _ ((hTh x).mp hx))))
  | _, _, _, .impNotIn _ hTh _ _ _ => by
      intro x hx
      simp only [List.nil_append] at hx
      exact (hTh x hx).2
  | _, _, _, .circNotIn _ _ hTh _ => by
      intro x hx
      simp only [List.nil_append] at hx
      exact (hTh x hx).2
  | _, _, _, .axIC _ _ _ _ _ hTh => by
      intro x hx
      simp only [List.nil_append] at hx
      exact (List.mem_filter.mp ((hTh x).mp hx)).1

end

/-- The three parts of a derivable context exhaust it:
`Γ = Γ^at ++ Γ^⊃ ++ Γ^◯`.  This is what the join rules' split silently
relies on — the invariant the third zone would have broken had it been
added without the modal rules, and keeps now that it is added with
them. -/
theorem atPart_union_impPart {G : Form} {t : Tag} {Γ : List Form} {C : Form}
    (d : FRJr G t Γ C) : Γ ⊆ atPart Γ ++ impPart Γ ++ circPart Γ := by
  intro x hx
  have hG := wfR d hx
  simp only [gHat, List.mem_append] at hG
  rcases hG with (hG | hG) | hG
  · exact List.mem_append_left _ (List.mem_append_left _
      (List.mem_filter.mpr ⟨hx, (List.mem_filter.mp hG).2⟩))
  · exact List.mem_append_left _ (List.mem_append_right _
      (List.mem_filter.mpr ⟨hx, (List.mem_filter.mp hG).2⟩))
  · exact List.mem_append_right _
      (List.mem_filter.mpr ⟨hx, (List.mem_filter.mp hG).2⟩)

/-! ## The `Ax^I` case of Lemma 3.9(ii), in label form

"We have `σ = ∅ ; Ĝ_at \ {C}, Ĝ_imp → C`, with `C ∈ Prime`.  Let
`Γ^at = V(σ_p)`.  Since `σ ↦ σ_p`, by Lemma 3.4(iii) and (Cl5) we get
`Γ^at ⊆ Ĝ_at \ {C}`.  This implies `C ∉ Γ^at`, hence `σ_p ⊮ C`."

The argument is entirely about labels, so it is available already: it
needs Lemma 3.4(iii) and (Cl5) and nothing about the model.  Once
`Mod(D)` is in place, `V(σ_p) = Lhs(σ_p) ∩ PV` turns this into
`σ_p ⊮ C` directly. -/

/-- For a variable `p`, no sequent reachable from the `Ax^I` conclusion
for `p` has `p` among its left formulas. -/
theorem axI_not_mem_lhs {G : Form} {p : String} {s : Sequent}
    (h : StepsRfl G
      (.irr [] (rm (gAt G) (.atom p) ++ gImp G ++ gCirc G) (.atom p)) s) :
    Form.atom p ∉ s.lhs := by
  intro hmem
  have hclo := lhs_clo_of_steps h _ hmem
  have hin := clo_pv hclo
  simp only [Sequent.lhs_irr, List.nil_append, List.mem_append] at hin
  rcases hin with (hin | hin) | hin
  · exact (mem_rm.mp hin).1 rfl
  · rw [gImp] at hin
    exact Bool.noConfusion ((List.mem_filter.mp hin).2)
  · rw [gCirc] at hin
    exact Bool.noConfusion ((List.mem_filter.mp hin).2)


end FRJ
