/-
# The relation `↦` and the sequents occurring in a derivation (Lemma 3.5)

Section 3 of Fiorentini–Ferrari, from "Now, we begin to study the
properties of FRJ(G)-derivations":

* `σ₁ ↦_R σ₂` iff `R` is a rule of `FRJ(G)` such that `σ₂` is the
  conclusion of `R` and `σ₁` is one of its premises;
* `σ₁ ↦₀ σ₂` iff there exists a rule `R` such that `σ₁ ↦_R σ₂`;
* `↦` is the transitive closure of `↦₀`;
* `↦*` is the reflexive closure of `↦`.

and then **Lemma 3.5** (`lemma:lhs`):

* (i)   `σ₁ ↦_R σ₂` and `R ≠ ⊃∉` imply `Lhs(σ₂) ⊆ Lhs(σ₁)`;
* (ii)  `σ₁ ↦₀ σ₂` implies `Lhs(σ₂) ⊆ Cl(Lhs(σ₁))`;
* (iii) `σ₁ ↦* σ₂` implies `Lhs(σ₂) ⊆ Cl(Lhs(σ₁))`.

`↦` is a relation on SEQUENTS generated by the rule instances, exactly
as the paper defines it, so it is reified here independently of any
derivation.  Occurrence in a derivation is separate, and the two are
tied together by `occR_steps`/`occI_steps`: every sequent occurring in
`D` reaches `D`'s root sequent by `↦*`.  That is the form in which the
soundness proof consumes Lemma 3.5(iii).
-/
import FRJ.Calculus

namespace FRJ

open Form

/-! ## Sequents as data -/

/-- An `FRJ(G)`-sequent: regular `Γ ⇒ C` or irregular `Σ ; Θ → C`. -/
inductive Sequent where
  | reg (Γ : List Form) (C : Form)
  | irr (St Th : List Form) (C : Form)
  deriving DecidableEq

namespace Sequent

/-- "`Lhs(σ) = Γ` if `σ` is regular, `Σ ++ Θ` if `σ` is irregular." -/
def lhs : Sequent → List Form
  | .reg Γ _ => Γ
  | .irr St Th _ => St ++ Th

/-- "`Rhs(σ) = C`." -/
def rhs : Sequent → Form
  | .reg _ C => C
  | .irr _ _ C => C

@[simp] theorem lhs_reg (Γ : List Form) (C : Form) : (reg Γ C).lhs = Γ := rfl
@[simp] theorem lhs_irr (St Th : List Form) (C : Form) :
    (irr St Th C).lhs = St ++ Th := rfl

end Sequent

/-- The names of the rules that have premises.  `Ax^R` and `Ax^I` have
none, so they generate no instance of `↦`. -/
inductive RuleName where
  | andR1 | andR2 | impIn | joinAt | joinOr
  | andI1 | andI2 | orI | impInI | impNotIn
  deriving DecidableEq

/-! ## `↦_R`, `↦₀`, `↦`, `↦*` -/

/-- `σ₁ ↦_R σ₂`: `σ₂` is the conclusion of an instance of rule `R` and
`σ₁` is one of its premises.  Only the side conditions that Lemma 3.5
consumes are carried. -/
inductive Step (G : Form) : RuleName → Sequent → Sequent → Prop
  | andR1 {Γ : List Form} {A₁ A₂ : Form} :
      Step G .andR1 (.reg Γ A₁) (.reg Γ (.and A₁ A₂))
  | andR2 {Γ : List Form} {A₁ A₂ : Form} :
      Step G .andR2 (.reg Γ A₂) (.reg Γ (.and A₁ A₂))
  | impIn {Γ : List Form} {A B : Form} :
      Step G .impIn (.reg Γ B) (.reg Γ (.imp A B))
  | andI1 {St Th : List Form} {A₁ A₂ : Form} :
      Step G .andI1 (.irr St Th A₁) (.irr St Th (.and A₁ A₂))
  | andI2 {St Th : List Form} {A₁ A₂ : Form} :
      Step G .andI2 (.irr St Th A₂) (.irr St Th (.and A₁ A₂))
  | orI₁ {St₁ Th₁ St₂ Th₂ : List Form} {C₁ C₂ : Form}
      (h₁ : St₁ ⊆ St₂ ++ Th₂) (h₂ : St₂ ⊆ St₁ ++ Th₁) :
      Step G .orI (.irr St₁ Th₁ C₁)
        (.irr (St₁ ++ St₂) (nf G (cap Th₁ Th₂)) (.or C₁ C₂))
  | orI₂ {St₁ Th₁ St₂ Th₂ : List Form} {C₁ C₂ : Form}
      (h₁ : St₁ ⊆ St₂ ++ Th₂) (h₂ : St₂ ⊆ St₁ ++ Th₁) :
      Step G .orI (.irr St₂ Th₂ C₂)
        (.irr (St₁ ++ St₂) (nf G (cap Th₁ Th₂)) (.or C₁ C₂))
  | impInI {St Th Lam : List Form} {A B : Form} (hdisj : cap Th Lam = []) :
      Step G .impInI (.irr St (nf G (Th ++ Lam)) B)
        (.irr (nf G (St ++ Lam)) (nf G Th) (.imp A B))
  | impNotIn {Γ Th : List Form} {A B : Form}
      (hTh : ∀ X ∈ Th, Clo Γ X ∧ X ∈ gHat G) :
      Step G .impNotIn (.reg Γ B) (.irr [] Th (.imp A B))
  | joinAt {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form} (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinAt (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxAt stab th rhs F) F)
  | joinOr {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form} (j : Fin (n + 1))
      (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) :
      Step G .joinOr (.irr (stab j) (th j) (rhs j))
        (.reg (joinCtxOr stab th rhs) (.or C₁ C₂))

/-- `σ₁ ↦₀ σ₂`: "there exists a rule `R` such that `σ₁ ↦_R σ₂`." -/
def Step₀ (G : Form) (s₁ s₂ : Sequent) : Prop := ∃ R, Step G R s₁ s₂

/-- `↦*`, the reflexive-transitive closure. -/
abbrev StepsRfl (G : Form) : Sequent → Sequent → Prop :=
  Relation.ReflTransGen (Step₀ G)

/-! ## Auxiliary facts about the join contexts -/

theorem interAll_subset {n : Nat} {f : Fin (n + 1) → List Form}
    (j : Fin (n + 1)) : interAll f ⊆ f j :=
  fun _ hx => (mem_interAll.mp hx) j

theorem atPart_subset {Γ : List Form} : atPart Γ ⊆ Γ := (fun _ h => (List.mem_filter.mp h).1)

theorem impPart_subset {Γ : List Form} : impPart Γ ⊆ Γ := (fun _ h => (List.mem_filter.mp h).1)

/-- `Σ^at` and `Σ^imp` land inside every premise's left formulas, by (J1). -/
theorem unionAll_part_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1))
    (part : List Form → List Form) (hpart : ∀ Γ, part Γ ⊆ Γ) :
    unionAll (fun i => part (stab i)) ⊆ stab j ++ th j := by
  intro x hx
  obtain ⟨i, hi⟩ := mem_unionAll.mp hx
  have hx' : x ∈ stab i := hpart _ hi
  by_cases hij : i = j
  · subst hij; exact List.mem_append_left _ hx'
  · exact hJ1 i j hij hx'

theorem joinCtxAt_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form} {F : Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxAt stab th rhs F ⊆ stab j ++ th j := by
  intro x hx
  simp only [joinCtxAt, List.mem_append] at hx
  rcases hx with ((hx | hx) | hx) | hx
  · exact unionAll_part_subset hJ1 j atPart (fun _ => atPart_subset) hx
  · exact List.mem_append_right _
      (atPart_subset (interAll_subset j (rm_subset hx)))
  · exact unionAll_part_subset hJ1 j impPart (fun _ => impPart_subset) hx
  · exact List.mem_append_right _
      (impPart_subset (interAll_subset j (restrict_subset hx)))

theorem joinCtxOr_subset {n : Nat} {stab th : Fin (n + 1) → List Form}
    {rhs : Fin (n + 1) → Form}
    (hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j) (j : Fin (n + 1)) :
    joinCtxOr stab th rhs ⊆ stab j ++ th j := by
  intro x hx
  simp only [joinCtxOr, List.mem_append] at hx
  rcases hx with ((hx | hx) | hx) | hx
  · exact unionAll_part_subset hJ1 j atPart (fun _ => atPart_subset) hx
  · exact List.mem_append_right _ (atPart_subset (interAll_subset j hx))
  · exact unionAll_part_subset hJ1 j impPart (fun _ => impPart_subset) hx
  · exact List.mem_append_right _
      (impPart_subset (interAll_subset j (restrict_subset hx)))

/-! ## Lemma 3.5 -/

/-- **Lemma 3.5(i).**  "`σ₁ ↦_R σ₂` and `R ≠ ⊃∉` imply
`Lhs(σ₂) ⊆ Lhs(σ₁)`." -/
theorem lhs_subset_of_step {G : Form} {R : RuleName} {s₁ s₂ : Sequent}
    (h : Step G R s₁ s₂) (hR : R ≠ .impNotIn) : s₂.lhs ⊆ s₁.lhs := by
  cases h with
  | andR1 => exact List.Subset.refl _
  | andR2 => exact List.Subset.refl _
  | impIn => exact List.Subset.refl _
  | andI1 => exact List.Subset.refl _
  | andI2 => exact List.Subset.refl _
  | orI₁ h₁ h₂ =>
      intro x hx
      simp only [Sequent.lhs_irr, List.mem_append, mem_nf, mem_cap] at hx ⊢
      rcases hx with (hx | hx) | ⟨-, hx⟩
      · exact Or.inl hx
      · exact List.mem_append.mp (h₂ hx)
      · exact Or.inr hx.1
  | orI₂ h₁ h₂ =>
      intro x hx
      simp only [Sequent.lhs_irr, List.mem_append, mem_nf, mem_cap] at hx ⊢
      rcases hx with (hx | hx) | ⟨-, hx⟩
      · exact List.mem_append.mp (h₁ hx)
      · exact Or.inl hx
      · exact Or.inr hx.2
  | impInI hdisj =>
      intro x hx
      simp only [Sequent.lhs_irr, List.mem_append, mem_nf] at hx ⊢
      rcases hx with ⟨hg, hx | hx⟩ | ⟨hg, hx⟩
      · exact Or.inl hx
      · exact Or.inr ⟨hg, Or.inr hx⟩
      · exact Or.inr ⟨hg, Or.inl hx⟩
  | impNotIn => exact absurd rfl hR
  | joinAt j hJ1 =>
      intro x hx
      exact joinCtxAt_subset hJ1 j hx
  | joinOr j hJ1 =>
      intro x hx
      exact joinCtxOr_subset hJ1 j hx

/-- **Lemma 3.5(ii).**  "`σ₁ ↦₀ σ₂` implies `Lhs(σ₂) ⊆ Cl(Lhs(σ₁))`."
For every rule but `⊃∉` this is (i) together with (Cl3); for `⊃∉` it is
that rule's own side condition `Θ ⊆ Cl(Γ) ∩ Ĝ`. -/
theorem lhs_clo_of_step₀ {G : Form} {s₁ s₂ : Sequent} (h : Step₀ G s₁ s₂) :
    ∀ X ∈ s₂.lhs, Clo s₁.lhs X := by
  obtain ⟨R, hR⟩ := h
  intro X hX
  by_cases hname : R = .impNotIn
  · subst hname
    cases hR with
    | impNotIn hTh =>
        refine (hTh X ?_).1
        simpa using hX
  · exact .base (lhs_subset_of_step hR hname hX)

/-- **Lemma 3.5(iii).**  "`σ₁ ↦* σ₂` implies `Lhs(σ₂) ⊆ Cl(Lhs(σ₁))`."
By (ii) along the chain, glued with (Cl6). -/
theorem lhs_clo_of_steps {G : Form} {s₁ s₂ : Sequent} (h : StepsRfl G s₁ s₂) :
    ∀ X ∈ s₂.lhs, Clo s₁.lhs X := by
  induction h with
  | refl => exact fun X hX => .base hX
  | tail _ hbc ih => exact fun X hX => clo_trans ih (lhs_clo_of_step₀ hbc X hX)

/-! ## The sequents occurring in a derivation

"σ occurs in D": the root sequent of `D`, or a sequent occurring in one
of its sub-derivations.  An inductive relation, one constructor per
premise slot.
-/

mutual

/-- `σ` occurs in the regular derivation `d`. -/
inductive OccR {G : Form} : {Γ : List Form} → {C : Form} → FRJr G Γ C → Sequent → Prop
  | root {Γ : List Form} {C : Form} (d : FRJr G Γ C) : OccR d (.reg Γ C)
  | andR1 {Γ : List Form} {A₁ A₂ : Form} {d : FRJr G Γ A₁}
      {hg : Form.and A₁ A₂ ∈ sfR G} {s : Sequent} :
      OccR d s → OccR (FRJr.andR1 d hg) s
  | andR2 {Γ : List Form} {A₁ A₂ : Form} {d : FRJr G Γ A₂}
      {hg : Form.and A₁ A₂ ∈ sfR G} {s : Sequent} :
      OccR d s → OccR (FRJr.andR2 d hg) s
  | impIn {Γ : List Form} {A B : Form} {d : FRJr G Γ B} {hA : Clo Γ A}
      {hg : Form.imp A B ∈ sfR G} {s : Sequent} :
      OccR d s → OccR (FRJr.impIn d hA hg) s
  | joinAt {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {F : Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hF : F.isPrime} {hFnot : F ∉ unionAll (fun j => atPart (stab j))}
      {hg : F ∈ sfR G} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s → OccR (FRJr.joinAt prem hJ1 hJ2 hF hFnot hg) s
  | joinOr {n : Nat} {stab th : Fin (n + 1) → List Form}
      {rhs : Fin (n + 1) → Form} {C₁ C₂ : Form}
      {prem : ∀ j, FRJi G (stab j) (th j) (rhs j)}
      {hJ1 : ∀ i j, i ≠ j → stab i ⊆ stab j ++ th j}
      {hJ2 : ∀ A B : Form, Form.imp A B ∈ unionAll (fun j => impPart (stab j)) →
        A ∈ upsilon rhs}
      {hC : C₁ ∈ upsilon rhs ∧ C₂ ∈ upsilon rhs}
      {hg : Form.or C₁ C₂ ∈ sfR G} {s : Sequent} (j : Fin (n + 1)) :
      OccI (prem j) s → OccR (FRJr.joinOr prem hJ1 hJ2 hC hg) s

/-- `σ` occurs in the irregular derivation `d`. -/
inductive OccI {G : Form} :
    {St Th : List Form} → {C : Form} → FRJi G St Th C → Sequent → Prop
  | root {St Th : List Form} {C : Form} (d : FRJi G St Th C) : OccI d (.irr St Th C)
  | andI1 {St Th : List Form} {A₁ A₂ : Form} {d : FRJi G St Th A₁}
      {hg : Form.and A₁ A₂ ∈ sfR G} {s : Sequent} :
      OccI d s → OccI (FRJi.andI1 d hg) s
  | andI2 {St Th : List Form} {A₁ A₂ : Form} {d : FRJi G St Th A₂}
      {hg : Form.and A₁ A₂ ∈ sfR G} {s : Sequent} :
      OccI d s → OccI (FRJi.andI2 d hg) s
  | orI₁ {St₁ Th₁ St₂ Th₂ : List Form} {C₁ C₂ : Form}
      {d₁ : FRJi G St₁ Th₁ C₁} {d₂ : FRJi G St₂ Th₂ C₂}
      {h₁ : St₁ ⊆ St₂ ++ Th₂} {h₂ : St₂ ⊆ St₁ ++ Th₁}
      {hg : Form.or C₁ C₂ ∈ sfR G} {s : Sequent} :
      OccI d₁ s → OccI (FRJi.orI d₁ d₂ h₁ h₂ hg) s
  | orI₂ {St₁ Th₁ St₂ Th₂ : List Form} {C₁ C₂ : Form}
      {d₁ : FRJi G St₁ Th₁ C₁} {d₂ : FRJi G St₂ Th₂ C₂}
      {h₁ : St₁ ⊆ St₂ ++ Th₂} {h₂ : St₂ ⊆ St₁ ++ Th₁}
      {hg : Form.or C₁ C₂ ∈ sfR G} {s : Sequent} :
      OccI d₂ s → OccI (FRJi.orI d₁ d₂ h₁ h₂ hg) s
  | impInI {St Th Lam : List Form} {A B : Form}
      {d : FRJi G St (nf G (Th ++ Lam)) B}
      {hdisj : cap Th Lam = []} {hA : Clo (nf G (St ++ Lam)) A}
      {hg : Form.imp A B ∈ sfR G} {s : Sequent} :
      OccI d s → OccI (FRJi.impInI d hdisj hA hg) s
  | impNotIn {Γ Th : List Form} {A B : Form} {d : FRJr G Γ B}
      {hTh : ∀ X ∈ Th, Clo Γ X ∧ X ∈ gHat G} {hA : Clo Γ A} {hAnot : ¬ Clo Th A}
      {hg : Form.imp A B ∈ sfR G} {s : Sequent} :
      OccR d s → OccI (FRJi.impNotIn d hTh hA hAnot hg) s

end

/-! ## Occurrence reaches the root by `↦*`

This is the bridge that lets the soundness proof apply Lemma 3.5(iii) to
an arbitrary sequent of `D`.  Each step up the derivation is an instance
of `↦` supplied by the rule that was applied, with its side conditions
taken from the derivation itself. -/

mutual

theorem occR_steps {G : Form} {Γ : List Form} {C : Form} {d : FRJr G Γ C}
    {s : Sequent} : OccR d s → StepsRfl G s (.reg Γ C)
  | .root _ => .refl
  | .andR1 h' => (occR_steps h').tail ⟨_, .andR1⟩
  | .andR2 h' => (occR_steps h').tail ⟨_, .andR2⟩
  | .impIn h' => (occR_steps h').tail ⟨_, .impIn⟩
  | .joinAt (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinAt j hJ1⟩
  | .joinOr (hJ1 := hJ1) j h' => (occI_steps h').tail ⟨_, .joinOr j hJ1⟩

theorem occI_steps {G : Form} {St Th : List Form} {C : Form}
    {d : FRJi G St Th C} {s : Sequent} : OccI d s → StepsRfl G s (.irr St Th C)
  | .root _ => .refl
  | .andI1 h' => (occI_steps h').tail ⟨_, .andI1⟩
  | .andI2 h' => (occI_steps h').tail ⟨_, .andI2⟩
  | .orI₁ (h₁ := h₁) (h₂ := h₂) h' => (occI_steps h').tail ⟨_, .orI₁ h₁ h₂⟩
  | .orI₂ (h₁ := h₁) (h₂ := h₂) h' => (occI_steps h').tail ⟨_, .orI₂ h₁ h₂⟩
  | .impInI (hdisj := hd) h' => (occI_steps h').tail ⟨_, .impInI hd⟩
  | .impNotIn (hTh := hTh) h' => (occR_steps h').tail ⟨_, .impNotIn hTh⟩

end

/-- **Lemma 3.5(iii), in the form the soundness proof uses it.**  For any
sequent `σ` occurring in a derivation `D` of `Γ ⇒ C`, the left formulas
of `D`'s root sequent lie in `Cl(Lhs(σ))`. -/
theorem lhs_clo_of_occR {G : Form} {Γ : List Form} {C : Form}
    {d : FRJr G Γ C} {s : Sequent} (h : OccR d s) :
    ∀ X ∈ Γ, Clo s.lhs X :=
  lhs_clo_of_steps (occR_steps h)

/-! ## Well-formedness of derivable sequents

The paper builds the constraints `Γ ⊆ Ĝ` and `Σ ++ Θ ⊆ Ĝ` into the
definition of the sequent set.  We carry them as a lemma instead
(divergence 4 of `docs/frj-fidelity.md`), and this is that lemma.  It is
what makes the `atPart`/`impPart` split in the join rules faithful: a
context can only contain variables and `⊃`-formulas, so the split loses
nothing. -/

mutual

/-- Every context of a derivable regular sequent lies inside `Ĝ`. -/
theorem wfR {G : Form} : ∀ {Γ : List Form} {C : Form}, FRJr G Γ C → Γ ⊆ gHat G
  | _, _, .axR _ _ _ => fun _ hx =>
      List.mem_append_left _ (rm_subset hx)
  | _, _, .andR1 d _ => wfR d
  | _, _, .andR2 d _ => wfR d
  | _, _, .impIn d _ _ => wfR d
  | _, _, .joinAt prem hJ1 _ _ _ _ => fun _ hx =>
      wfI (prem 0) (joinCtxAt_subset hJ1 0 hx)
  | _, _, .joinOr prem hJ1 _ _ _ => fun _ hx =>
      wfI (prem 0) (joinCtxOr_subset hJ1 0 hx)

/-- Every zone of a derivable irregular sequent lies inside `Ĝ`. -/
theorem wfI {G : Form} : ∀ {St Th : List Form} {C : Form},
    FRJi G St Th C → St ++ Th ⊆ gHat G
  | _, _, _, .axI _ _ _ => by
      intro x hx
      simp only [List.nil_append] at hx
      exact nf_subset hx
  | _, _, _, .andI1 d _ => wfI d
  | _, _, _, .andI2 d _ => wfI d
  | _, _, _, .orI d₁ _ _ h₂ _ => by
      intro x hx
      simp only [List.mem_append, mem_nf] at hx
      rcases hx with (hx | hx) | ⟨hg, -⟩
      · exact wfI d₁ (List.mem_append_left _ hx)
      · exact wfI d₁ (h₂ hx)
      · exact hg
  | _, _, _, .impInI _ _ _ _ => by
      intro x hx
      simp only [List.mem_append, mem_nf] at hx
      rcases hx with ⟨hg, -⟩ | ⟨hg, -⟩ <;> exact hg
  | _, _, _, .impNotIn _ hTh _ _ _ => by
      intro x hx
      simp only [List.nil_append] at hx
      exact (hTh x hx).2

end

/-- The atomic and implicational parts of a derivable context exhaust it:
`Γ = Γ^at ++ Γ^⊃`.  This is what the join rules' use of `atPart`/`impPart`
silently relies on. -/
theorem atPart_union_impPart {G : Form} {Γ : List Form} {C : Form}
    (d : FRJr G Γ C) : Γ ⊆ atPart Γ ++ impPart Γ := by
  intro x hx
  have hG := wfR d hx
  simp only [gHat, List.mem_append] at hG
  rcases hG with hG | hG
  · exact List.mem_append_left _
      (List.mem_filter.mpr ⟨hx, (List.mem_filter.mp hG).2⟩)
  · exact List.mem_append_right _
      (List.mem_filter.mpr ⟨hx, (List.mem_filter.mp hG).2⟩)

/-! ## The `Ax^I` case of Lemma 3.9(ii), in label form

"We have `σ = ∅ ; Ĝ_at \ {C}, Ĝ_imp → C`, with `C ∈ Prime`.  Let
`Γ^at = V(σ_p)`.  Since `σ ↦ σ_p`, by Lemma 3.5(iii) and (Cl5) we get
`Γ^at ⊆ Ĝ_at \ {C}`.  This implies `C ∉ Γ^at`, hence `σ_p ⊮ C`."

The argument is entirely about labels, so it is available already: it
needs Lemma 3.5(iii) and (Cl5) and nothing about the model.  Once
`Mod(D)` is in place, `V(σ_p) = Lhs(σ_p) ∩ PV` turns this into
`σ_p ⊮ C` directly. -/

/-- For a variable `p`, no sequent reachable from the `Ax^I` conclusion
for `p` has `p` among its left formulas. -/
theorem axI_not_mem_lhs {G : Form} {p : String} {s : Sequent}
    (h : StepsRfl G (.irr [] (rm (gAt G) (.atom p) ++ gImp G) (.atom p)) s) :
    Form.atom p ∉ s.lhs := by
  intro hmem
  have hclo := lhs_clo_of_steps h _ hmem
  have hin := clo_pv hclo
  simp only [Sequent.lhs_irr, List.nil_append, List.mem_append] at hin
  rcases hin with hin | hin
  · exact (mem_rm.mp hin).1 rfl
  · rw [gImp] at hin
    exact Bool.noConfusion ((List.mem_filter.mp hin).2)


end FRJ
