/-
# The battery separations the database lacked: 95 kernel certificates

GENERATED by `lake exe rhocover emit` (2026-08-25) — the ⊬ cells of the
22-class ρ-order that are battery-separable but had no banked entry
(the other 208 ⊬ cells were already covered by the FRJ bank, the
dictionary entries, or the ord-* pair).  Each cell: a mutually
confluent ≤5-world frame refuting `DerivU` (`not_derivU_of_checkConf`,
kernel `decide`), transferred to PLL by `nle_of_nleU`.  With these,
EVERY ⊬ cell of the 462-cell matrix is kernel-pinned: no edge between
two nodes of `docs/rho-hasse-pll.svg` means both non-derivabilities
are kernel theorems (single exception: the open half `ρ12 ⊢? ρ15`).

Regenerate after catalogue changes: `lake exe rhocover emit`.
-/
import LaxLogic.PLLSearchConf
import LaxLogic.Deriv
import LaxLogic.RN.Rho

namespace RhoSeps

/-- `Deriv ⊆ DerivU` (`DerivU.of_nd`), contraposed: a PCLL refutation
is a PLL refutation. -/
theorem nle_of_nleU {a b : PLLFormula}
    (h : ¬ PLLND.ConfluentU.DerivU [a] b) : ¬ PLLND.SemUI.Deriv [a] b :=
  fun ⟨t⟩ => h (PLLND.ConfluentU.DerivU.of_nd t)

/-- `ρ1 ⊬ᵤ ρ9` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_1_9 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 1] (RhoOrder.rhoF 9) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_1_nle_9 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 1] (RhoOrder.rhoF 9) :=
  nle_of_nleU sepU_1_9

/-- `ρ1 ⊬ᵤ ρ15` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_1_15 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 1] (RhoOrder.rhoF 15) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_1_nle_15 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 1] (RhoOrder.rhoF 15) :=
  nle_of_nleU sepU_1_15

/-- `ρ1 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_1_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 1] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_1_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 1] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_1_16

/-- `ρ1 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_1_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 1] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_1_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 1] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_1_18

/-- `ρ5 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_5_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 5] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_5_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 5] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_5_16

/-- `ρ5 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_5_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 5] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_5_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 5] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_5_19

/-- `ρ6 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_6_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 6] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_6_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 6] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_6_16

/-- `ρ6 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_6_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 6] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_6_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 6] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_6_19

/-- `ρ8 ⊬ᵤ ρ9` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_8_9 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 8] (RhoOrder.rhoF 9) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_8_nle_9 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 8] (RhoOrder.rhoF 9) :=
  nle_of_nleU sepU_8_9

/-- `ρ8 ⊬ᵤ ρ15` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_8_15 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 8] (RhoOrder.rhoF 15) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_8_nle_15 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 8] (RhoOrder.rhoF 15) :=
  nle_of_nleU sepU_8_15

/-- `ρ8 ⊬ᵤ ρ16` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_8_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 8] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_8_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 8] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_8_16

/-- `ρ8 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_8_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 8] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_8_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 8] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_8_18

/-- `ρ8 ⊬ᵤ ρ20` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_8_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 8] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_8_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 8] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_8_20

/-- `ρ8 ⊬ᵤ ρ21` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_8_21 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 8] (RhoOrder.rhoF 21) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_8_nle_21 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 8] (RhoOrder.rhoF 21) :=
  nle_of_nleU sepU_8_21

/-- `ρ9 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_9_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 9] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_9_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 9] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_9_16

/-- `ρ9 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_9_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 9] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_9_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 9] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_9_19

/-- `ρ10 ⊬ᵤ ρ9` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_10_9 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 10] (RhoOrder.rhoF 9) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_10_nle_9 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 10] (RhoOrder.rhoF 9) :=
  nle_of_nleU sepU_10_9

/-- `ρ10 ⊬ᵤ ρ15` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_10_15 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 10] (RhoOrder.rhoF 15) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_10_nle_15 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 10] (RhoOrder.rhoF 15) :=
  nle_of_nleU sepU_10_15

/-- `ρ10 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_10_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 10] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_10_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 10] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_10_16

/-- `ρ10 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_10_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 10] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_10_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 10] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_10_18

/-- `ρ10 ⊬ᵤ ρ20` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_10_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 10] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_10_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 10] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_10_20

/-- `ρ10 ⊬ᵤ ρ21` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_10_21 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 10] (RhoOrder.rhoF 21) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_10_nle_21 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 10] (RhoOrder.rhoF 21) :=
  nle_of_nleU sepU_10_21

/-- `ρ11 ⊬ᵤ ρ4` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_11_4 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 4) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_11_nle_4 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 4) :=
  nle_of_nleU sepU_11_4

/-- `ρ11 ⊬ᵤ ρ6` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_11_6 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 6) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_11_nle_6 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 6) :=
  nle_of_nleU sepU_11_6

/-- `ρ11 ⊬ᵤ ρ7` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_11_7 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 7) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_11_nle_7 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 7) :=
  nle_of_nleU sepU_11_7

/-- `ρ11 ⊬ᵤ ρ8` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_11_8 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 8) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_11_nle_8 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 8) :=
  nle_of_nleU sepU_11_8

/-- `ρ11 ⊬ᵤ ρ9` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_11_9 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 9) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_11_nle_9 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 9) :=
  nle_of_nleU sepU_11_9

/-- `ρ11 ⊬ᵤ ρ10` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_11_10 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 10) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_11_nle_10 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 10) :=
  nle_of_nleU sepU_11_10

/-- `ρ11 ⊬ᵤ ρ12` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_11_12 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 12) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_11_nle_12 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 12) :=
  nle_of_nleU sepU_11_12

/-- `ρ11 ⊬ᵤ ρ14` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_11_14 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 14) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_11_nle_14 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 14) :=
  nle_of_nleU sepU_11_14

/-- `ρ11 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_11_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_11_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_11_16

/-- `ρ11 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_11_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_11_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_11_18

/-- `ρ11 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_11_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_11_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_11_19

/-- `ρ11 ⊬ᵤ ρ20` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_11_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_11_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_11_20

/-- `ρ11 ⊬ᵤ ρ21` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_11_21 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 11] (RhoOrder.rhoF 21) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_11_nle_21 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 11] (RhoOrder.rhoF 21) :=
  nle_of_nleU sepU_11_21

/-- `ρ12 ⊬ᵤ ρ7` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_12_7 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 12] (RhoOrder.rhoF 7) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_12_nle_7 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 12] (RhoOrder.rhoF 7) :=
  nle_of_nleU sepU_12_7

/-- `ρ12 ⊬ᵤ ρ8` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_12_8 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 12] (RhoOrder.rhoF 8) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_12_nle_8 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 12] (RhoOrder.rhoF 8) :=
  nle_of_nleU sepU_12_8

/-- `ρ12 ⊬ᵤ ρ10` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_12_10 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 12] (RhoOrder.rhoF 10) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_12_nle_10 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 12] (RhoOrder.rhoF 10) :=
  nle_of_nleU sepU_12_10

/-- `ρ12 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_12_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 12] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_12_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 12] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_12_16

/-- `ρ12 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_12_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 12] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_12_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 12] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_12_18

/-- `ρ12 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_12_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 12] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_12_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 12] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_12_19

/-- `ρ12 ⊬ᵤ ρ20` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_12_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 12] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_12_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 12] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_12_20

/-- `ρ13 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_13_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 13] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_13_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 13] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_13_16

/-- `ρ13 ⊬ᵤ ρ17` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_13_17 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 13] (RhoOrder.rhoF 17) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_13_nle_17 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 13] (RhoOrder.rhoF 17) :=
  nle_of_nleU sepU_13_17

/-- `ρ13 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_13_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 13] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_13_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 13] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_13_18

/-- `ρ13 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_13_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 13] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_13_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 13] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_13_19

/-- `ρ13 ⊬ᵤ ρ20` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_13_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 13] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_13_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 13] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_13_20

/-- `ρ14 ⊬ᵤ ρ4` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_4 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 4) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_4 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 4) :=
  nle_of_nleU sepU_14_4

/-- `ρ14 ⊬ᵤ ρ6` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_6 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 6) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_6 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 6) :=
  nle_of_nleU sepU_14_6

/-- `ρ14 ⊬ᵤ ρ7` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_7 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 7) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_7 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 7) :=
  nle_of_nleU sepU_14_7

/-- `ρ14 ⊬ᵤ ρ9` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_9 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 9) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_9 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 9) :=
  nle_of_nleU sepU_14_9

/-- `ρ14 ⊬ᵤ ρ12` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_12 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 12) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_12 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 12) :=
  nle_of_nleU sepU_14_12

/-- `ρ14 ⊬ᵤ ρ13` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_13 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 13) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_13 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 13) :=
  nle_of_nleU sepU_14_13

/-- `ρ14 ⊬ᵤ ρ19` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_14_19

/-- `ρ14 ⊬ᵤ ρ20` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_14_20

/-- `ρ14 ⊬ᵤ ρ21` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_14_21 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 14] (RhoOrder.rhoF 21) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_14_nle_21 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 14] (RhoOrder.rhoF 21) :=
  nle_of_nleU sepU_14_21

/-- `ρ15 ⊬ᵤ ρ7` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_15_7 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 7) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_15_nle_7 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 7) :=
  nle_of_nleU sepU_15_7

/-- `ρ15 ⊬ᵤ ρ8` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_15_8 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 8) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_15_nle_8 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 8) :=
  nle_of_nleU sepU_15_8

/-- `ρ15 ⊬ᵤ ρ9` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_15_9 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 9) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_15_nle_9 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 9) :=
  nle_of_nleU sepU_15_9

/-- `ρ15 ⊬ᵤ ρ10` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_15_10 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 10) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_15_nle_10 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 10) :=
  nle_of_nleU sepU_15_10

/-- `ρ15 ⊬ᵤ ρ12` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_15_12 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 12) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_15_nle_12 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 12) :=
  nle_of_nleU sepU_15_12

/-- `ρ15 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_15_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_15_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_15_16

/-- `ρ15 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_15_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_15_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_15_18

/-- `ρ15 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_15_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_15_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_15_19

/-- `ρ15 ⊬ᵤ ρ20` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_15_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_15_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_15_20

/-- `ρ15 ⊬ᵤ ρ21` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_15_21 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 15] (RhoOrder.rhoF 21) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_15_nle_21 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 15] (RhoOrder.rhoF 21) :=
  nle_of_nleU sepU_15_21

/-- `ρ16 ⊬ᵤ ρ7` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_16_7 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 16] (RhoOrder.rhoF 7) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_16_nle_7 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 16] (RhoOrder.rhoF 7) :=
  nle_of_nleU sepU_16_7

/-- `ρ16 ⊬ᵤ ρ9` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_16_9 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 16] (RhoOrder.rhoF 9) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_16_nle_9 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 16] (RhoOrder.rhoF 9) :=
  nle_of_nleU sepU_16_9

/-- `ρ16 ⊬ᵤ ρ12` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_16_12 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 16] (RhoOrder.rhoF 12) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_16_nle_12 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 16] (RhoOrder.rhoF 12) :=
  nle_of_nleU sepU_16_12

/-- `ρ16 ⊬ᵤ ρ19` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_16_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 16] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_16_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 16] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_16_19

/-- `ρ16 ⊬ᵤ ρ20` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_16_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 16] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_16_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 16] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_16_20

/-- `ρ16 ⊬ᵤ ρ21` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_16_21 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 16] (RhoOrder.rhoF 21) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_16_nle_21 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 16] (RhoOrder.rhoF 21) :=
  nle_of_nleU sepU_16_21

/-- `ρ17 ⊬ᵤ ρ13` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_17_13 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 17] (RhoOrder.rhoF 13) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_17_nle_13 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 17] (RhoOrder.rhoF 13) :=
  nle_of_nleU sepU_17_13

/-- `ρ17 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_17_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 17] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_17_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 17] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_17_16

/-- `ρ17 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_17_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 17] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_17_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 17] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_17_19

/-- `ρ17 ⊬ᵤ ρ20` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_17_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 17] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_17_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 17] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_17_20

/-- `ρ17 ⊬ᵤ ρ21` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_17_21 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 17] (RhoOrder.rhoF 21) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_17_nle_21 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 17] (RhoOrder.rhoF 21) :=
  nle_of_nleU sepU_17_21

/-- `ρ18 ⊬ᵤ ρ9` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_18_9 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 18] (RhoOrder.rhoF 9) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_18_nle_9 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 18] (RhoOrder.rhoF 9) :=
  nle_of_nleU sepU_18_9

/-- `ρ18 ⊬ᵤ ρ12` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_18_12 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 18] (RhoOrder.rhoF 12) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_18_nle_12 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 18] (RhoOrder.rhoF 12) :=
  nle_of_nleU sepU_18_12

/-- `ρ18 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_18_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 18] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_18_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 18] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_18_16

/-- `ρ18 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_18_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 18] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_18_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 18] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_18_19

/-- `ρ18 ⊬ᵤ ρ20` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_18_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 18] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_18_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 18] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_18_20

/-- `ρ18 ⊬ᵤ ρ21` (PCLL): battery separation, frame 608, world 3. -/
theorem sepU_18_21 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 18] (RhoOrder.rhoF 21) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

theorem rho_18_nle_21 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 18] (RhoOrder.rhoF 21) :=
  nle_of_nleU sepU_18_21

/-- `ρ19 ⊬ᵤ ρ15` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_19_15 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 19] (RhoOrder.rhoF 15) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_19_nle_15 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 19] (RhoOrder.rhoF 15) :=
  nle_of_nleU sepU_19_15

/-- `ρ19 ⊬ᵤ ρ16` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_19_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 19] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_19_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 19] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_19_16

/-- `ρ19 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_19_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 19] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_19_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 19] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_19_18

/-- `ρ20 ⊬ᵤ ρ15` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_20_15 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 20] (RhoOrder.rhoF 15) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_20_nle_15 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 20] (RhoOrder.rhoF 15) :=
  nle_of_nleU sepU_20_15

/-- `ρ20 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_20_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 20] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_20_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 20] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_20_16

/-- `ρ20 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_20_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 20] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_20_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 20] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_20_18

/-- `ρ20 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_20_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 20] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_20_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 20] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_20_19

/-- `ρ21 ⊬ᵤ ρ15` (PCLL): battery separation, frame 9900, world 0. -/
theorem sepU_21_15 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 21] (RhoOrder.rhoF 15) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_21_nle_15 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 21] (RhoOrder.rhoF 15) :=
  nle_of_nleU sepU_21_15

/-- `ρ21 ⊬ᵤ ρ16` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_21_16 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 21] (RhoOrder.rhoF 16) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_21_nle_16 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 21] (RhoOrder.rhoF 16) :=
  nle_of_nleU sepU_21_16

/-- `ρ21 ⊬ᵤ ρ18` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_21_18 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 21] (RhoOrder.rhoF 18) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_21_nle_18 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 21] (RhoOrder.rhoF 18) :=
  nle_of_nleU sepU_21_18

/-- `ρ21 ⊬ᵤ ρ19` (PCLL): battery separation, frame 108, world 2. -/
theorem sepU_21_19 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 21] (RhoOrder.rhoF 19) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

theorem rho_21_nle_19 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 21] (RhoOrder.rhoF 19) :=
  nle_of_nleU sepU_21_19

/-- `ρ21 ⊬ᵤ ρ20` (PCLL): battery separation, frame 9328, world 0. -/
theorem sepU_21_20 : ¬ PLLND.ConfluentU.DerivU [RhoOrder.rhoF 21] (RhoOrder.rhoF 20) :=
  PLLND.RNC.not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

theorem rho_21_nle_20 : ¬ PLLND.SemUI.Deriv [RhoOrder.rhoF 21] (RhoOrder.rhoF 20) :=
  nle_of_nleU sepU_21_20

/-! ## Pins — UNGUARDED as emitted; guard via tools/pin-backfill.py -/

/-- info: 'RhoSeps.rho_1_nle_9' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_1_nle_9
/-- info: 'RhoSeps.rho_1_nle_15' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_1_nle_15
/-- info: 'RhoSeps.rho_1_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_1_nle_16
/-- info: 'RhoSeps.rho_1_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_1_nle_18
/-- info: 'RhoSeps.rho_5_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_5_nle_16
/-- info: 'RhoSeps.rho_5_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_5_nle_19
/-- info: 'RhoSeps.rho_6_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_6_nle_16
/-- info: 'RhoSeps.rho_6_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_6_nle_19
/-- info: 'RhoSeps.rho_8_nle_9' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_8_nle_9
/-- info: 'RhoSeps.rho_8_nle_15' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_8_nle_15
/-- info: 'RhoSeps.rho_8_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_8_nle_16
/-- info: 'RhoSeps.rho_8_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_8_nle_18
/-- info: 'RhoSeps.rho_8_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_8_nle_20
/-- info: 'RhoSeps.rho_8_nle_21' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_8_nle_21
/-- info: 'RhoSeps.rho_9_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_9_nle_16
/-- info: 'RhoSeps.rho_9_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_9_nle_19
/-- info: 'RhoSeps.rho_10_nle_9' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_10_nle_9
/-- info: 'RhoSeps.rho_10_nle_15' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_10_nle_15
/-- info: 'RhoSeps.rho_10_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_10_nle_16
/-- info: 'RhoSeps.rho_10_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_10_nle_18
/-- info: 'RhoSeps.rho_10_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_10_nle_20
/-- info: 'RhoSeps.rho_10_nle_21' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_10_nle_21
/-- info: 'RhoSeps.rho_11_nle_4' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_4
/-- info: 'RhoSeps.rho_11_nle_6' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_6
/-- info: 'RhoSeps.rho_11_nle_7' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_7
/-- info: 'RhoSeps.rho_11_nle_8' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_8
/-- info: 'RhoSeps.rho_11_nle_9' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_9
/-- info: 'RhoSeps.rho_11_nle_10' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_10
/-- info: 'RhoSeps.rho_11_nle_12' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_12
/-- info: 'RhoSeps.rho_11_nle_14' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_14
/-- info: 'RhoSeps.rho_11_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_16
/-- info: 'RhoSeps.rho_11_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_18
/-- info: 'RhoSeps.rho_11_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_19
/-- info: 'RhoSeps.rho_11_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_20
/-- info: 'RhoSeps.rho_11_nle_21' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_11_nle_21
/-- info: 'RhoSeps.rho_12_nle_7' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_12_nle_7
/-- info: 'RhoSeps.rho_12_nle_8' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_12_nle_8
/-- info: 'RhoSeps.rho_12_nle_10' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_12_nle_10
/-- info: 'RhoSeps.rho_12_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_12_nle_16
/-- info: 'RhoSeps.rho_12_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_12_nle_18
/-- info: 'RhoSeps.rho_12_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_12_nle_19
/-- info: 'RhoSeps.rho_12_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_12_nle_20
/-- info: 'RhoSeps.rho_13_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_13_nle_16
/-- info: 'RhoSeps.rho_13_nle_17' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_13_nle_17
/-- info: 'RhoSeps.rho_13_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_13_nle_18
/-- info: 'RhoSeps.rho_13_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_13_nle_19
/-- info: 'RhoSeps.rho_13_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_13_nle_20
/-- info: 'RhoSeps.rho_14_nle_4' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_4
/-- info: 'RhoSeps.rho_14_nle_6' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_6
/-- info: 'RhoSeps.rho_14_nle_7' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_7
/-- info: 'RhoSeps.rho_14_nle_9' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_9
/-- info: 'RhoSeps.rho_14_nle_12' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_12
/-- info: 'RhoSeps.rho_14_nle_13' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_13
/-- info: 'RhoSeps.rho_14_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_19
/-- info: 'RhoSeps.rho_14_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_20
/-- info: 'RhoSeps.rho_14_nle_21' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_14_nle_21
/-- info: 'RhoSeps.rho_15_nle_7' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_7
/-- info: 'RhoSeps.rho_15_nle_8' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_8
/-- info: 'RhoSeps.rho_15_nle_9' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_9
/-- info: 'RhoSeps.rho_15_nle_10' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_10
/-- info: 'RhoSeps.rho_15_nle_12' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_12
/-- info: 'RhoSeps.rho_15_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_16
/-- info: 'RhoSeps.rho_15_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_18
/-- info: 'RhoSeps.rho_15_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_19
/-- info: 'RhoSeps.rho_15_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_20
/-- info: 'RhoSeps.rho_15_nle_21' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_15_nle_21
/-- info: 'RhoSeps.rho_16_nle_7' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_16_nle_7
/-- info: 'RhoSeps.rho_16_nle_9' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_16_nle_9
/-- info: 'RhoSeps.rho_16_nle_12' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_16_nle_12
/-- info: 'RhoSeps.rho_16_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_16_nle_19
/-- info: 'RhoSeps.rho_16_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_16_nle_20
/-- info: 'RhoSeps.rho_16_nle_21' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_16_nle_21
/-- info: 'RhoSeps.rho_17_nle_13' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_17_nle_13
/-- info: 'RhoSeps.rho_17_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_17_nle_16
/-- info: 'RhoSeps.rho_17_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_17_nle_19
/-- info: 'RhoSeps.rho_17_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_17_nle_20
/-- info: 'RhoSeps.rho_17_nle_21' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_17_nle_21
/-- info: 'RhoSeps.rho_18_nle_9' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_18_nle_9
/-- info: 'RhoSeps.rho_18_nle_12' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_18_nle_12
/-- info: 'RhoSeps.rho_18_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_18_nle_16
/-- info: 'RhoSeps.rho_18_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_18_nle_19
/-- info: 'RhoSeps.rho_18_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_18_nle_20
/-- info: 'RhoSeps.rho_18_nle_21' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_18_nle_21
/-- info: 'RhoSeps.rho_19_nle_15' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_19_nle_15
/-- info: 'RhoSeps.rho_19_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_19_nle_16
/-- info: 'RhoSeps.rho_19_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_19_nle_18
/-- info: 'RhoSeps.rho_20_nle_15' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_20_nle_15
/-- info: 'RhoSeps.rho_20_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_20_nle_16
/-- info: 'RhoSeps.rho_20_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_20_nle_18
/-- info: 'RhoSeps.rho_20_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_20_nle_19
/-- info: 'RhoSeps.rho_21_nle_15' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_21_nle_15
/-- info: 'RhoSeps.rho_21_nle_16' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_21_nle_16
/-- info: 'RhoSeps.rho_21_nle_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_21_nle_18
/-- info: 'RhoSeps.rho_21_nle_19' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_21_nle_19
/-- info: 'RhoSeps.rho_21_nle_20' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms rho_21_nle_20

end RhoSeps
