#!/usr/bin/env python3
"""Build a challenge set that is not a walkthrough ending at the answer.

The first challenge set was generated by bare prefix truncation, which has a
property no instruction-not-to-peek can remove: *everything the ground-truth
proof used is, by construction, above the cut*.  Measured on those four files,
one had its answer in a sibling challenge file and two more had every
ingredient in the prefix; only one needed anything its own file did not
contain.  See `docs/toolkit-test-design.md`.

This adds the acceptance filters of that proposal (§4, "cheaper variant") on
top of `extract.py`, and emits blinded files:

  EXTERNAL CITATION   the ground-truth proof must cite at least one global
                      name that is NOT declared in the prefix, so the proof
                      genuinely needs something the challenge file lacks.
  NO VISIBLE TWIN     reject a target whose proof is near-identical to a
                      sibling's already visible in the prefix.  This is the
                      `conservativity` / `conservativity_prop` trap: the
                      second was proved 60 lines above the first.
  COMPILES            the emitted file must elaborate with exactly one
                      `sorry` and no errors.
  BLIND               the header names the group and nothing else: no line
                      count, no source file, no source line.

Usage:
    python3 challenge.py report                 # what the filters say, no output files
    python3 challenge.py build -o <dir> [-n N]  # emit and validate a set
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import extract  # noqa: E402
from toolkit_config import find_config  # noqa: E402

# ---------------------------------------------------------------- identifiers

# A global reference: dotted (`List.mem_cons_self`, `PLLND.erase`) or a bare
# name.  The negative lookbehind rejects Lean's anonymous-constructor dot
# (`.iden`, `.impIntro`), which resolves against the expected type's namespace
# and is therefore never evidence of an outside dependency.
IDENT_RE = re.compile(r"(?<![.\w'])([A-Za-z_][A-Za-z0-9_']*(?:\.[A-Za-z_][A-Za-z0-9_']*)*)")

DECL_NAME_RE = re.compile(
    r"^(?:@\[[^\]]*\]\s*)?"
    r"(?:private\s+|protected\s+|noncomputable\s+|partial\s+|unsafe\s+|scoped\s+)*"
    r"(?:theorem|lemma|def|abbrev|instance|structure|inductive|class|opaque|axiom)\s+"
    r"([A-Za-z_][A-Za-z0-9_'!?]*)",
    re.M,
)

# Tactics, keywords and term-level syntax.  A citation of one of these says
# nothing about what the proof depends on.
NOISE = frozenset("""
by exact refine apply intro intros rintro rcases obtain cases casesm induction
match with fun let have show from at in do then else if this simp simpa dsimp
omega decide native_decide rfl trivial constructor exists use left right
first try repeat all_goals any_goals focus rotate_left skip sorry admit
assumption contradiction absurd exfalso subst substs rw rewrite erw conv
unfold delta change calc gcongr positivity linarith nlinarith ring ring_nf
field_simp norm_num push_neg by_cases by_contra specialize revert clear
rename_i next case set generalize injection ext funext congr aesop tauto
convert cc solve_by_elim assumption' split splits stop guard_hyp guard_target
where deriving open section end namespace variable universe attribute
Type Prop Sort True False And Or Not Iff Eq Exists forall fun
nil cons some none inl inr mk fst snd val property
""".split())


def strip_comments(text: str) -> str:
    return extract.strip_comments_for_scan(text)


def declared_names(source: str) -> set[str]:
    """Every name declared at top level in `source`, plus its last component."""
    out: set[str] = set()
    for m in DECL_NAME_RE.finditer(source):
        n = m.group(1)
        out.add(n)
        out.add(n.rsplit(".", 1)[-1])
    # `inductive`/`structure` constructor names, one per indented `| Name`
    for m in re.finditer(r"^\s*\|\s*([A-Za-z_][A-Za-z0-9_']*)", source, re.M):
        out.add(m.group(1))
    return out


def cited(proof: str) -> set[str]:
    """Global names a proof appears to reference."""
    scan = strip_comments(proof)
    out = set()
    for m in IDENT_RE.finditer(scan):
        tok = m.group(1)
        if tok in NOISE:
            continue
        if "." not in tok and len(tok) <= 2:
            continue                      # h, ih, p — binders, not citations
        out.add(tok)
    return out


# Namespace roots from Lean core / Mathlib that the corpus index does not cover.
STDLIB_ROOTS = frozenset("""
List Nat Int Option Prod Sum Sigma Subtype Finset Set Multiset Array String
Bool Char Function Classical Decidable Quot Quotient And Or Iff Not Exists Eq
Ne Membership Std Lean Fin Vector Sublist Perm
""".split())


def is_global(tok: str, prefix_names: set[str], index_names: set[str]) -> bool:
    """Does `tok` reference a declaration, rather than project off a binder?

    `C.Ri`, `hw.elim` and `d.toSC` are dotted but are field access on local
    hypotheses, not dependencies on anything importable.  A dotted token only
    counts when its HEAD is a namespace we can actually name.
    """
    if "." in tok:
        head = tok.split(".", 1)[0]
        return (head in STDLIB_ROOTS or head in prefix_names
                or head in index_names)
    return tok in prefix_names or tok in index_names


def external_citations(item, prefix_names: set[str], index_names: set[str]) -> set[str]:
    """Globals the target needs that are NOT declared in the prefix.

    Both the proof AND the statement count.  The statement matters because a
    definitional dependency need never be named in the proof: `pfree_trans`
    cites nothing external, yet cannot be proved without knowing what
    `LJF.PFreeP` and `LJF.PFreeN` unfold to, and those live in another file.
    It was the one target of the original four that genuinely tested
    retrieval, and a proof-only filter drops it — which is how this was
    found.
    """
    self_names = {item.name, item.name.rsplit(".", 1)[-1]}
    out = set()
    for tok in cited(item.ground_truth) | cited(item.statement):
        if not is_global(tok, prefix_names, index_names):
            continue
        head = tok.rsplit(".", 1)[-1]
        if tok in self_names or head in self_names:
            continue                       # the target naming itself
        if tok in prefix_names or head in prefix_names:
            continue
        out.add(tok)
    return out


def proof_external(item, prefix_names: set[str], index_names: set[str]) -> set[str]:
    """External citations made by the PROOF — the strongest form of the signal.

    A statement-only dependency (`pfree_trans`) is real but weaker: you must
    know what the name unfolds to, yet the proof never writes it.  Targets are
    ranked on this count first, so a set built with `-n` takes the ones whose
    proofs reach outside before the ones whose statements merely mention it.
    """
    return {t for t in external_citations(item, prefix_names, index_names)
            if t in cited(item.ground_truth)}


# ------------------------------------------------------------ visible twins

def proof_shape(proof: str) -> list[str]:
    """Token bag of a proof, comments and binder noise removed."""
    scan = strip_comments(proof)
    return [t for t in IDENT_RE.findall(scan)
            if t not in NOISE and not ("." not in t and len(t) <= 2)]


MIN_SHAPE = 5


def overlap(a: list[str], b: list[str]) -> float:
    """Containment of the smaller token-set in the larger. 1.0 = identical set.

    Below `MIN_SHAPE` distinct tokens containment is degenerate — `by omega`
    is a subset of almost everything — so short proofs fall back to Jaccard,
    which does not reward being small.
    """
    sa, sb = set(a), set(b)
    if not sa or not sb:
        return 0.0
    if min(len(sa), len(sb)) < MIN_SHAPE:
        return len(sa & sb) / len(sa | sb)
    return len(sa & sb) / min(len(sa), len(sb))


def visible_twin(item, siblings: list, threshold: float) -> tuple[str | None, float]:
    """The most similar proof already visible in this item's prefix."""
    shape = proof_shape(item.ground_truth)
    best, score = None, 0.0
    for sib in siblings:
        if sib.name == item.name or sib.file != item.file:
            continue
        if sib.line >= item.line:          # not visible: it comes after the cut
            continue
        s = overlap(shape, proof_shape(sib.ground_truth))
        if s > score:
            best, score = sib.name, s
    return (best if score >= threshold else None), score


# ------------------------------------------------------------------- emission

BLIND_HEADER = """/- Challenge: `{name}`.  Group: {group}.
   Replace the `sorry`.  Do not look for the original proof.

   Deliberately not stated here: where this comes from, how long the known
   proof is, or how hard it is.  Those were hints. -/
"""


def render(item) -> str:
    return BLIND_HEADER.format(name=item.name, group=item.group) + \
        item.prefix.rstrip("\n") + "\n\n" + item.statement + " := by\n  sorry\n"


def compiles_with_one_sorry(text: str, repo: Path) -> tuple[bool, str]:
    """Elaborate `text`; require zero errors and exactly one sorry warning."""
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=repo,
                                     delete=False, encoding="utf-8") as fh:
        fh.write(text)
        tmp = Path(fh.name)
    try:
        r = subprocess.run(["lake", "env", "lean", str(tmp)], cwd=repo,
                           capture_output=True, text=True, timeout=900)
        out = (r.stdout or "") + (r.stderr or "")
        errors = [l for l in out.splitlines() if ": error:" in l]
        # Lean spells this with BACKTICKS -- "declaration uses `sorry`".  An
        # earlier version matched straight quotes and so counted zero on every
        # file, rejecting the whole set.  Match the quoting loosely.
        sorries = [l for l in out.splitlines()
                   if re.search(r"declaration uses .?sorry", l)]
        if errors:
            return False, f"{len(errors)} error(s): {errors[0][:160]}"
        if len(sorries) != 1:
            return False, f"expected 1 sorry warning, got {len(sorries)}"
        return True, "ok"
    except subprocess.TimeoutExpired:
        return False, "timeout"
    finally:
        tmp.unlink(missing_ok=True)


# ----------------------------------------------------------------------- main

def load_items(cfg_path: Path, max_proof_lines: int):
    srcs = json.loads(cfg_path.read_text())
    items = []
    for s in srcs:
        got, _ = extract.extract_file(Path(s["repo"]), s["file"], s["group"],
                                      max_proof_lines)
        items.extend(got)
    return items


def index_declaration_names(index_path: Path) -> set[str]:
    if not index_path.is_file():
        return set()
    names = set()
    for line in index_path.read_text().splitlines():
        if not line.strip():
            continue
        d = json.loads(line)
        names.add(d["name"])
        names.add(d.get("short") or d["name"].rsplit(".", 1)[-1])
    return names


# Targets excluded by hand, with the reason.  A deny-list is a confession that
# a filter is missing; keep it short and say why each entry is here.
DENY = {
    "conservativity_prop":
        "its ground truth is written out inside the retired Challenge/ set "
        "(Challenge/conservativity.lean proves it in full), so it is already "
        "spent — proposal step 2",
}


def screen(items, index_names, threshold):
    """Annotate each item with the filter verdicts. Returns list of dicts."""
    rows = []
    for it in items:
        prefix_names = declared_names(strip_comments(it.prefix))
        ext = external_citations(it, prefix_names, index_names)
        pext = proof_external(it, prefix_names, index_names)
        twin, twin_score = visible_twin(it, items, threshold)
        reasons = []
        if it.name in DENY:
            reasons.append(f"deny-list: {DENY[it.name]}")
        if not ext:
            reasons.append("no external citation")
        if twin:
            reasons.append(f"visible twin {twin} ({twin_score:.2f})")
        rows.append({
            "item": it,
            "external": sorted(ext),
            "proof_external": sorted(pext),
            "twin": twin,
            "twin_score": round(twin_score, 3),
            "reject": reasons,
        })
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("report", "build"):
        p = sub.add_parser(name)
        p.add_argument("--config", type=Path,
                       default=Path(__file__).parent / "corpora/laxlogic.json")
        p.add_argument("--max-proof-lines", type=int, default=15)
        p.add_argument("--twin-threshold", type=float, default=0.55)
        if name == "build":
            p.add_argument("-o", "--out", type=Path, required=True)
            p.add_argument("-n", "--limit", type=int, default=6)
            p.add_argument("--manifest", type=Path, default=None)
    args = ap.parse_args()

    cfg = find_config()
    index_names = index_declaration_names(
        Path(__file__).parent / "leansearch/index.jsonl")
    items = load_items(args.config, args.max_proof_lines)
    rows = screen(items, index_names, args.twin_threshold)

    if args.cmd == "report":
        kept = [r for r in rows if not r["reject"]]
        print(f"{len(items)} candidates -> {len(kept)} pass the filters\n")
        by_file: dict[str, list] = {}
        for r in rows:
            by_file.setdefault(r["item"].file, []).append(r)
        for f, rs in sorted(by_file.items()):
            k = sum(1 for r in rs if not r["reject"])
            print(f"{f}: {k}/{len(rs)} pass")
            for r in sorted(rs, key=lambda r: r["item"].line):
                it = r["item"]
                mark = "PASS" if not r["reject"] else "drop"
                why = "" if not r["reject"] else "  <- " + "; ".join(r["reject"])
                print(f"   {mark} {it.name:<34} ext={len(r['external']):<2} "
                      f"pext={len(r['proof_external']):<2} "
                      f"twin={r['twin_score']:.2f}{why}")
        return 0

    # build
    repo = cfg.repo
    args.out.mkdir(parents=True, exist_ok=True)
    manifest, emitted, tried = [], 0, 0
    # AT MOST ONE TARGET PER SOURCE FILE.  Two prefix-truncated targets from the
    # same file always leak: the later one's prefix contains the earlier one's
    # proof.  That is exactly what happened to `conservativity` /
    # `conservativity_prop`.  Lifting this restriction is what hole-punching
    # (proposal §4) buys.
    used_files: set[str] = set()
    for r in sorted((r for r in rows if not r["reject"]),
                    key=lambda r: (-len(r["proof_external"]), -len(r["external"]),
                                   r["item"].proof_lines)):
        if emitted >= args.limit:
            break
        it = r["item"]
        if it.file in used_files:
            continue
        tried += 1
        text = render(it)
        ok, why = compiles_with_one_sorry(text, repo)
        if not ok:
            print(f"  reject {it.name}: {why}", file=sys.stderr)
            continue
        dest = args.out / f"{it.name}.lean"
        dest.write_text(text, encoding="utf-8")
        manifest.append({
            "name": it.name, "file": str(dest.relative_to(repo)),
            "group": it.group, "source_file": it.file, "source_line": it.line,
            "proof_lines": it.proof_lines,
            "external_citations": r["external"],
            "proof_external_citations": r["proof_external"],
            "max_visible_twin": r["twin_score"],
        })
        emitted += 1
        used_files.add(it.file)
        print(f"  emit   {it.name}  ({len(r['external'])} external citations)",
              file=sys.stderr)

    mpath = args.manifest or (args.out.parent / "challenge-manifest.json")
    mpath.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\n{emitted} emitted (of {tried} tried) -> {args.out}", file=sys.stderr)
    print(f"manifest -> {mpath}  (provenance only; no ground-truth proofs)",
          file=sys.stderr)
    return 0 if emitted else 1


if __name__ == "__main__":
    raise SystemExit(main())
