#!/usr/bin/env python3
"""Build a challenge set that is not a walkthrough ending at the answer.

The first challenge set was generated by bare prefix truncation, which has a
property no instruction-not-to-peek can remove: *everything the ground-truth
proof used is, by construction, above the cut*.  Measured on those four files,
one had its answer in a sibling challenge file and two more had every
ingredient in the prefix; only one needed anything its own file did not
contain.  See `docs/toolkit-test-design.md`.

This adds the acceptance filters of that proposal (§4, "cheaper variant") on
top of `extract.py`, and emits blinded files:

  EXTERNAL CITATION   the ground-truth proof must cite at least one global
                      name that is NOT declared in the prefix, so the proof
                      genuinely needs something the challenge file lacks.
  NO VISIBLE TWIN     reject a target whose proof is near-identical to a
                      sibling's already visible in the prefix.  This is the
                      `conservativity` / `conservativity_prop` trap: the
                      second was proved 60 lines above the first.
  COMPILES            the emitted file must elaborate with exactly one
                      `sorry` and no errors.
  BLIND               the header names the group and nothing else: no line
                      count, no source file, no source line.

Usage:
    python3 challenge.py report                 # what the filters say, no output files
    python3 challenge.py build -o <dir> [-n N]  # emit and validate a set
"""

from __future__ import annotations

import argparse
import json
import re
import os
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import extract  # noqa: E402
from toolkit_config import find_config  # noqa: E402

# ---------------------------------------------------------------- identifiers

# A global reference: dotted (`List.mem_cons_self`, `PLLND.erase`) or a bare
# name.  The negative lookbehind rejects Lean's anonymous-constructor dot
# (`.iden`, `.impIntro`), which resolves against the expected type's namespace
# and is therefore never evidence of an outside dependency.
IDENT_RE = re.compile(r"(?<![.\w'])([A-Za-z_][A-Za-z0-9_']*(?:\.[A-Za-z_][A-Za-z0-9_']*)*)")

DECL_NAME_RE = re.compile(
    r"^(?:@\[[^\]]*\]\s*)?"
    r"(?:private\s+|protected\s+|noncomputable\s+|partial\s+|unsafe\s+|scoped\s+)*"
    r"(?:theorem|lemma|def|abbrev|instance|structure|inductive|class|opaque|axiom)\s+"
    r"([A-Za-z_][A-Za-z0-9_'!?]*)",
    re.M,
)

# Tactics, keywords and term-level syntax.  A citation of one of these says
# nothing about what the proof depends on.
NOISE = frozenset("""
by exact refine apply intro intros rintro rcases obtain cases casesm induction
match with fun let have show from at in do then else if this simp simpa dsimp
omega decide native_decide rfl trivial constructor exists use left right
first try repeat all_goals any_goals focus rotate_left skip sorry admit
assumption contradiction absurd exfalso subst substs rw rewrite erw conv
unfold delta change calc gcongr positivity linarith nlinarith ring ring_nf
field_simp norm_num push_neg by_cases by_contra specialize revert clear
rename_i next case set generalize injection ext funext congr aesop tauto
convert cc solve_by_elim assumption' split splits stop guard_hyp guard_target
where deriving open section end namespace variable universe attribute
Type Prop Sort True False And Or Not Iff Eq Exists forall fun
nil cons some none inl inr mk fst snd val property
""".split())


def strip_comments(text: str) -> str:
    return extract.strip_comments_for_scan(text)


def declared_names(source: str) -> set[str]:
    """Every name declared at top level in `source`, plus its last component."""
    out: set[str] = set()
    for m in DECL_NAME_RE.finditer(source):
        n = m.group(1)
        out.add(n)
        out.add(n.rsplit(".", 1)[-1])
    # `inductive`/`structure` constructor names, one per indented `| Name`
    for m in re.finditer(r"^\s*\|\s*([A-Za-z_][A-Za-z0-9_']*)", source, re.M):
        out.add(m.group(1))
    return out


def cited(proof: str) -> set[str]:
    """Global names a proof appears to reference."""
    scan = strip_comments(proof)
    out = set()
    for m in IDENT_RE.finditer(scan):
        tok = m.group(1)
        if tok in NOISE:
            continue
        if "." not in tok and len(tok) <= 2:
            continue                      # h, ih, p — binders, not citations
        out.add(tok)
    return out


# Namespace roots from Lean core / Mathlib that the corpus index does not cover.
STDLIB_ROOTS = frozenset("""
List Nat Int Option Prod Sum Sigma Subtype Finset Set Multiset Array String
Bool Char Function Classical Decidable Quot Quotient And Or Iff Not Exists Eq
Ne Membership Std Lean Fin Vector Sublist Perm
""".split())


def is_global(tok: str, prefix_names: set[str], index_names: set[str]) -> bool:
    """Does `tok` reference a declaration, rather than project off a binder?

    `C.Ri`, `hw.elim` and `d.toSC` are dotted but are field access on local
    hypotheses, not dependencies on anything importable.  A dotted token only
    counts when its HEAD is a namespace we can actually name.
    """
    if "." in tok:
        head = tok.split(".", 1)[0]
        return (head in STDLIB_ROOTS or head in prefix_names
                or head in index_names)
    return tok in prefix_names or tok in index_names


def external_citations(item, prefix_names: set[str], index_names: set[str]) -> set[str]:
    """Globals the target needs that are NOT declared in the prefix.

    Both the proof AND the statement count.  The statement matters because a
    definitional dependency need never be named in the proof: `pfree_trans`
    cites nothing external, yet cannot be proved without knowing what
    `LJF.PFreeP` and `LJF.PFreeN` unfold to, and those live in another file.
    It was the one target of the original four that genuinely tested
    retrieval, and a proof-only filter drops it — which is how this was
    found.
    """
    self_names = {item.name, item.name.rsplit(".", 1)[-1]}
    out = set()
    for tok in cited(item.ground_truth) | cited(item.statement):
        if not is_global(tok, prefix_names, index_names):
            continue
        head = tok.rsplit(".", 1)[-1]
        if tok in self_names or head in self_names:
            continue                       # the target naming itself
        if tok in prefix_names or head in prefix_names:
            continue
        out.add(tok)
    return out


def proof_external(item, prefix_names: set[str], index_names: set[str]) -> set[str]:
    """External citations made by the PROOF — the strongest form of the signal.

    A statement-only dependency (`pfree_trans`) is real but weaker: you must
    know what the name unfolds to, yet the proof never writes it.  Targets are
    ranked on this count first, so a set built with `-n` takes the ones whose
    proofs reach outside before the ones whose statements merely mention it.
    """
    return {t for t in external_citations(item, prefix_names, index_names)
            if t in cited(item.ground_truth)}


# ------------------------------------------------------------ visible twins

def proof_shape(proof: str) -> list[str]:
    """Token bag of a proof, comments and binder noise removed."""
    scan = strip_comments(proof)
    return [t for t in IDENT_RE.findall(scan)
            if t not in NOISE and not ("." not in t and len(t) <= 2)]


MIN_SHAPE = 5


def overlap(a: list[str], b: list[str]) -> float:
    """Containment of the smaller token-set in the larger. 1.0 = identical set.

    Below `MIN_SHAPE` distinct tokens containment is degenerate — `by omega`
    is a subset of almost everything — so short proofs fall back to Jaccard,
    which does not reward being small.
    """
    sa, sb = set(a), set(b)
    if not sa or not sb:
        return 0.0
    if min(len(sa), len(sb)) < MIN_SHAPE:
        return len(sa & sb) / len(sa | sb)
    return len(sa & sb) / min(len(sa), len(sb))


def visible_twin(item, siblings: list, threshold: float) -> tuple[str | None, float]:
    """The most similar proof already visible in this item's prefix."""
    shape = proof_shape(item.ground_truth)
    best, score = None, 0.0
    for sib in siblings:
        if sib.name == item.name or sib.file != item.file:
            continue
        if sib.line >= item.line:          # not visible: it comes after the cut
            continue
        s = overlap(shape, proof_shape(sib.ground_truth))
        if s > score:
            best, score = sib.name, s
    return (best if score >= threshold else None), score


# ------------------------------------------------------------------- emission

BLIND_HEADER = """/- Challenge: `{name}`.  Group: {group}.
   Replace the `sorry`.  Do not look for the original proof.

   Deliberately not stated here: where this comes from, how long the known
   proof is, or how hard it is.  Those were hints. -/
"""


def render(item) -> str:
    return BLIND_HEADER.format(name=item.name, group=item.group) + \
        item.prefix.rstrip("\n") + "\n\n" + item.statement + " := by\n  sorry\n"


def compiles_with_one_sorry(text: str, repo: Path) -> tuple[bool, str]:
    """Elaborate `text`; require zero errors and exactly one sorry warning."""
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=repo,
                                     delete=False, encoding="utf-8") as fh:
        fh.write(text)
        tmp = Path(fh.name)
    try:
        r = subprocess.run(["lake", "env", "lean", str(tmp)], cwd=repo,
                           capture_output=True, text=True, timeout=900)
        out = (r.stdout or "") + (r.stderr or "")
        errors = [l for l in out.splitlines() if ": error:" in l]
        # Lean spells this with BACKTICKS -- "declaration uses `sorry`".  An
        # earlier version matched straight quotes and so counted zero on every
        # file, rejecting the whole set.  Match the quoting loosely.
        sorries = [l for l in out.splitlines()
                   if re.search(r"declaration uses .?sorry", l)]
        if errors:
            return False, f"{len(errors)} error(s): {errors[0][:160]}"
        if len(sorries) != 1:
            return False, f"expected 1 sorry warning, got {len(sorries)}"
        return True, "ok"
    except subprocess.TimeoutExpired:
        return False, "timeout"
    finally:
        tmp.unlink(missing_ok=True)


# ------------------------------------------------------------- hole-punching

PUNCH_ROOT = "LaxLogic/ToolkitTest/Punched"
PUNCH_NS = "LaxLogic.ToolkitTest.Punched"

PUNCHED_HEADER = """/- Generated by prover-toolkit/challenge.py -- DO NOT EDIT.

   `{module}` with {n} declaration(s) removed: {names}.
   Their statements are posed as challenges; this module supplies everything
   else the original file had in scope, so a challenge file can be four lines
   long and give nothing away by being read. -/
"""

PUNCHED_CHALLENGE = """/- Challenge: `{name}`.  Group: {group}.
   Replace the `sorry`.  Do not look for the original proof.

   Deliberately not stated here: where this comes from, how long the known
   proof is, or how hard it is.  Those were hints. -/
import {punched}

{opens}
{statement} := by
  sorry
"""


def context_at(lines: list[str], upto: int) -> tuple[list[str], list[str]]:
    """The `namespace` stack and the `open`s in force at 1-indexed line `upto`.

    `end` is not a namespace closer on its own: `mutual` and `section` are also
    closed by `end`, and a BARE `end` never closes a namespace (Lean requires
    `end Foo`).  Getting this wrong silently reported `LJFComplete`'s targets
    as being at top level, because that file's `mutual ... end` blocks popped
    the stack.
    """
    stack: list[tuple[str, str | None]] = []      # (kind, name)
    opens: list[str] = []
    for raw in lines[: upto - 1]:
        m = re.match(r"^namespace\s+([A-Za-z_][\w.'!?]*)", raw)
        if m:
            stack.append(("ns", m.group(1)))
            continue
        m = re.match(r"^section(?:\s+([A-Za-z_][\w.'!?]*))?", raw)
        if m:
            stack.append(("sec", m.group(1)))
            continue
        if re.match(r"^mutual\b", raw):
            stack.append(("mut", None))
            continue
        m = re.match(r"^end(?:\s+([A-Za-z_][\w.'!?]*))?\s*$", raw)
        if m:
            name = m.group(1)
            if name is None:
                for i in range(len(stack) - 1, -1, -1):
                    if stack[i][0] in ("sec", "mut"):
                        stack.pop(i)
                        break
            else:
                for i in range(len(stack) - 1, -1, -1):
                    if stack[i][1] == name:
                        del stack[i:]
                        break
            continue
        m = re.match(r"^open\s+(.+?)\s*$", raw)
        if m and " in" not in m.group(1):
            opens.append(m.group(1).strip())
    return [n for k, n in stack if k == "ns"], opens


def all_declarations(lines: list[str]) -> list[tuple[str, int, int]]:
    """Every top-level declaration as (name, start, end) 0-indexed line span.

    Attribute and doc-comment chunks immediately above a declaration are
    absorbed into it, exactly as `extract.extract_file` does, so deleting a
    span never strands a `@[simp]` or a `/-- ... -/`.
    """
    spans = extract.split_top_level(lines)
    out: list[tuple[str, int, int]] = []
    for si, (st, en) in enumerate(spans):
        m = DECL_NAME_RE.match("".join(lines[st:en]))
        if not m:
            continue
        start = st
        j = si - 1
        while j >= 0:
            ps, pe = spans[j]
            if pe == start and extract.ATTACH_RE.match(lines[ps]):
                start = ps
                j -= 1
            else:
                break
        out.append((m.group(1), start, en))
    return out


def drop_empty_mutual(lines: list[str]) -> list[str]:
    """Remove `mutual ... end` blocks the cascade emptied.

    Deleting every member of a mutual block leaves `mutual` immediately
    followed by `end`, which Lean reports as `unexpected end` -- LJF.lean's
    first failure after the cascade landed.
    """
    out, i, n = [], 0, len(lines)
    while i < n:
        if re.match(r"^mutual\b", lines[i]):
            j = i + 1
            while j < n and not lines[j].strip():
                j += 1
            if j < n and re.match(r"^end\b", lines[j]):
                i = j + 1
                continue
        out.append(lines[i])
        i += 1
    return out


def punch_module(repo: Path, rel: str, targets: list) -> tuple[str, str, list[str]]:
    """`rel` with every target deleted, AND everything that then dangles.

    Deleting a target alone does not work: a theorem in a mature development
    is normally USED further down its own module, so the punched copy fails to
    elaborate.  All six modules failed this way on the first attempt --
    `isIPL_erase` at line 273, `map_unNeg_negOf` at 443, `force_hered` at 102.
    The proposal's "everything else in M survives" is simply false here.

    So the cut is closed under reverse dependency: remove a target, then
    remove anything whose text names something already removed, to fixpoint.
    What survives is everything the original module had that does not depend
    on any target -- strictly more than a prefix truncation, which also drops
    every later declaration that was independent of the target.

    Returns (module name, text, names removed).
    """
    src = (repo / rel).read_text(encoding="utf-8")
    lines = src.splitlines(keepends=True)
    decls = all_declarations(lines)

    # The cascade runs over EVERY top-level chunk, not just declarations.
    # `#guard_msgs in / #print axioms X` audit blocks are commands, so a
    # declaration-only cascade leaves them behind referring to a name it has
    # just deleted -- which is how LJFComplete and PLLG4ipComplete failed.
    spans = extract.split_top_level(lines)
    # Key on the END line, which is unique per chunk.  Keying on (start, end)
    # was a bug: `all_declarations` reports the ATTRIBUTE-ABSORBED start, so
    # every declaration carrying a doc-comment failed the lookup, was cut
    # WITHOUT its name being recorded, and the cascade stopped propagating
    # there.  `exI_sound` went that way and left `uniform_interpolation_IPC`
    # referring to it.
    named = {en: nm for nm, st, en in decls}

    def group_start(si: int) -> int:
        """Walk back over the doc-comments and `#guard_msgs in` above a chunk."""
        st = spans[si][0]
        j = si - 1
        while j >= 0:
            ps, pe = spans[j]
            head = lines[ps]
            if pe == st and (extract.ATTACH_RE.match(head)
                             or re.match(r"^#\w+.*\bin\s*$", head)):
                st = ps
                j -= 1
            else:
                break
        return st

    removed = {t.name for t in targets}
    cut_spans = {(t.decl_start - 1, t.decl_end - 1) for t in targets}
    changed = True
    while changed:
        changed = False
        for si, (st, en) in enumerate(spans):
            gs = group_start(si)
            if (gs, en) in cut_spans or (st, en) in cut_spans:
                continue
            body = strip_comments("".join(lines[st:en]))
            toks = {m.group(1) for m in IDENT_RE.finditer(body)}
            toks |= {t.rsplit(".", 1)[-1] for t in toks if "." in t}
            if toks & removed:
                nm = named.get(en)
                if nm:
                    removed.add(nm)
                cut_spans.add((gs, en))
                changed = True

    cut = set()
    for st, en in cut_spans:
        cut.update(range(st, en))
    kept = [l for i, l in enumerate(lines) if i not in cut]
    kept = drop_empty_mutual(kept)
    stem = Path(rel).stem
    header = PUNCHED_HEADER.format(
        module=rel, n=len(removed),
        names=", ".join(f"`{n}`" for n in sorted(removed)))
    return f"{PUNCH_NS}.{stem}", header + "".join(kept), sorted(removed)


def render_punched_challenge(item, punched_module: str, opens: list[str]) -> str:
    return PUNCHED_CHALLENGE.format(
        name=item.name, group=item.group, punched=punched_module,
        opens="\n".join(f"open {o}" for o in opens) + ("\n" if opens else ""),
        statement=item.statement)


# ----------------------------------------------------------------------- main

def load_items(cfg_path: Path, max_proof_lines: int):
    srcs = json.loads(cfg_path.read_text())
    items = []
    for s in srcs:
        got, _ = extract.extract_file(Path(s["repo"]), s["file"], s["group"],
                                      max_proof_lines)
        items.extend(got)
    return items


def index_declaration_names(index_path: Path) -> set[str]:
    if not index_path.is_file():
        return set()
    names = set()
    for line in index_path.read_text().splitlines():
        if not line.strip():
            continue
        d = json.loads(line)
        names.add(d["name"])
        names.add(d.get("short") or d["name"].rsplit(".", 1)[-1])
    return names


# Targets excluded by hand, with the reason.  A deny-list is a confession that
# a filter is missing; keep it short and say why each entry is here.
DENY = {
    "conservativity_prop":
        "its ground truth is written out inside the retired Challenge/ set "
        "(Challenge/conservativity.lean proves it in full), so it is already "
        "spent — proposal step 2",
}


def screen(items, index_names, threshold):
    """Annotate each item with the filter verdicts. Returns list of dicts."""
    rows = []
    for it in items:
        prefix_names = declared_names(strip_comments(it.prefix))
        ext = external_citations(it, prefix_names, index_names)
        pext = proof_external(it, prefix_names, index_names)
        twin, twin_score = visible_twin(it, items, threshold)
        reasons = []
        if it.name in DENY:
            reasons.append(f"deny-list: {DENY[it.name]}")
        if not ext:
            reasons.append("no external citation")
        if twin:
            reasons.append(f"visible twin {twin} ({twin_score:.2f})")
        rows.append({
            "item": it,
            "external": sorted(ext),
            "proof_external": sorted(pext),
            "twin": twin,
            "twin_score": round(twin_score, 3),
            "reject": reasons,
        })
    return rows


# ------------------------------------------------------- scoring & ablation

def axioms_of(repo: Path, lean_file: Path, fq_name: str) -> list[str] | None:
    """`#print axioms` on a finished challenge file. None if it will not run."""
    src = lean_file.read_text(encoding="utf-8")
    ns = re.findall(r"^namespace\s+([\w.']+)", src, re.M)
    probe = src.rstrip("\n")
    if ns and not re.search(r"^end\s", src, re.M):
        probe += "\n\nend " + ns[-1]
    probe += f"\n\n#print axioms {fq_name}\n"
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=repo,
                                     delete=False, encoding="utf-8") as fh:
        fh.write(probe)
        tmp = Path(fh.name)
    try:
        r = subprocess.run(["lake", "env", "lean", str(tmp)], cwd=repo,
                           capture_output=True, text=True, timeout=1800)
        out = (r.stdout or "") + (r.stderr or "")
        m = re.search(r"depends on axioms: \[([^\]]*)\]", out)
        if m:
            return [a.strip() for a in m.group(1).split(",") if a.strip()]
        if "does not depend on any axioms" in out:
            return []
        return None
    finally:
        tmp.unlink(missing_ok=True)


def score(repo: Path, manifest_path: Path, name: str) -> dict:
    """Did this target get closed, and on what does it now rest?"""
    entries = json.loads(manifest_path.read_text())
    e = next((x for x in entries if x["name"] == name), None)
    if e is None:
        return {"name": name, "error": "not in manifest"}
    f = repo / e["file"]
    text = f.read_text(encoding="utf-8")
    ns = re.findall(r"^namespace\s+([\w.']+)", text, re.M)
    fq = (".".join(ns) + "." + name) if ns else name
    ok, why = compiles_clean(text, repo)
    return {
        "name": name, "closed": ok, "detail": why,
        "axioms": axioms_of(repo, f, fq) if ok else None,
        "source_file": e["source_file"],
        "external_citations": e["external_citations"],
    }


def query_index(port: int, q: str, k: int) -> list[str]:
    import urllib.request
    body = json.dumps({"query": [q], "num_results": k}).encode()
    req = urllib.request.Request(f"http://127.0.0.1:{port}/search", data=body,
                                 headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=20) as fh:
        res = json.load(fh)
    return [r["result"]["name"] for r in (res[0] if res else [])]


def retrieval_check(repo: Path, manifest_path: Path, port: int, k: int) -> int:
    """Can the index deliver what each target actually needs?

    This is the half of the §5 ablation that needs no agent: for each target,
    query with its statement and ask whether its external citations come back
    in the top k.  A target whose dependencies retrieval cannot surface is one
    where the with/without-index comparison has nothing to measure.
    """
    entries = json.loads(manifest_path.read_text())
    index_names = index_declaration_names(
        Path(__file__).parent / "leansearch/index.jsonl")
    print("in-corpus = the citation exists in the index at all.  A citation "
          "that does not\nis unreachable by construction: the index covers "
          "this development, NOT Mathlib.\n")
    print(f"{'target':<24} {'in-corpus':>9} {'found':>5} {'off-corpus':>10}  missed")
    tot_need = tot_found = tot_off = 0
    for e in entries:
        # Prefer the statement recorded in the manifest; fall back to the
        # emitted file.  Never fail because a set was rebuilt elsewhere.
        stmt = e.get("statement")
        if stmt is None:
            f = repo / e["file"]
            if not f.is_file():
                print(f"{e['name']:<24}    ?     ?  (file missing: {e['file']})")
                continue
            stmt = f.read_text(encoding="utf-8").split(":= by")[0]
        q = " ".join(stmt.splitlines()[-6:])
        hits = set(query_index(port, q, k))
        heads = {h.rsplit(".", 1)[-1] for h in hits}
        cites = [c for c in e.get("needed", e["external_citations"])
                 if "." in c or len(c) > 2]
        need = [c for c in cites
                if c in index_names or c.rsplit(".", 1)[-1] in index_names]
        off = [c for c in cites if c not in need]
        found = [c for c in need
                 if c in hits or c.rsplit(".", 1)[-1] in heads]
        missed = [c for c in need if c not in found]
        tot_need += len(need); tot_found += len(found); tot_off += len(off)
        print(f"{e['name']:<24} {len(need):>9} {len(found):>5} {len(off):>10}  "
              f"{', '.join(missed[:3]) if missed else '-'}")
    pct = 100 * tot_found / tot_need if tot_need else 0.0
    print(f"\nrecall@{k} on in-corpus citations: {tot_found}/{tot_need} = "
          f"{pct:.0f}%")
    print(f"off-corpus citations: {tot_off} — mostly Lean core and Mathlib "
          f"(`List.*`), which\nthis index does not cover at all. For those "
          f"targets the corpus index cannot help,\nwhatever its ranking: the "
          f"answer is not in it.")
    return 0


def build_punched(args, rows, repo: Path, idx_names: set[str]) -> int:
    """Emit Punched/<Module>.lean per source file, and a 4-line challenge each.

    Every selected target of a module is removed from the SAME punched copy, so
    no challenge file can contain another challenge's proof.  That is what
    lifts the one-target-per-file rule of the truncation build.
    """
    punch_dir = repo / PUNCH_ROOT
    punch_dir.mkdir(parents=True, exist_ok=True)
    args.out = args.out if args.out.is_absolute() else (repo / args.out)
    args.out.mkdir(parents=True, exist_ok=True)

    by_file: dict[str, list] = {}
    for r in sorted((r for r in rows if not r["reject"]),
                    key=lambda r: (-len(r["proof_external"]), -len(r["external"]),
                                   r["item"].proof_lines)):
        by_file.setdefault(r["item"].file, []).append(r)

    # PASS 1 -- write the punched modules and check each compiles on its own.
    plan: list[tuple[str, str, list]] = []
    lp = lean_path(repo)
    budget = args.limit
    for rel, rs in by_file.items():
        if budget <= 0:
            break
        chosen = rs[: args.per_file]
        items = [r["item"] for r in chosen]
        # Read the ORIGINAL from the item's own repo, not from `repo`: the
        # corpus may point at a different checkout, and this worktree has no
        # FRJ/ at all.  Write the punched copy here, where it will be built.
        module, text, removed = punch_module(Path(items[0].repo), rel, items)
        orig = len((Path(items[0].repo) / rel).read_text().splitlines())
        frac = 1 - len(text.splitlines()) / orig
        if frac > args.max_cascade:
            print(f"  reject module {rel}: cascade removes {frac:.0%} of the "
                  f"module ({len(removed)} declarations) -- the target is too "
                  f"load-bearing to punch out", file=sys.stderr)
            continue
        src_rel = f"{PUNCH_ROOT}/{Path(rel).stem}.lean"
        (repo / src_rel).write_text(text, encoding="utf-8")
        ok, why = build_olean(repo, src_rel, module, lp)
        if not ok:
            print(f"  reject module {rel}: punched copy does not compile ({why})",
                  file=sys.stderr)
            (repo / src_rel).unlink(missing_ok=True)
            continue
        plan.append((rel, module, chosen))
        budget -= len(chosen)
        print(f"  punched {rel} -- {len(removed)} declaration(s) removed "
              f"for {len(chosen)} target(s): {', '.join(removed[:8])}"
              f"{' ...' if len(removed) > 8 else ''}", file=sys.stderr)

    if not plan:
        print("no punched module compiled; nothing to emit", file=sys.stderr)
        return 1

    # PASS 2 -- emit and validate the challenge files.
    manifest, emitted = [], 0
    for rel, module, chosen in plan:
        mpath = punch_dir / (Path(rel).stem + ".lean")  # noqa: F841
        src_lines = (Path(chosen[0]["item"].repo) / rel).read_text(
            encoding="utf-8").splitlines(keepends=True)
        for r in chosen:
            it = r["item"]
            ns, opens = context_at(src_lines, it.decl_start)
            prefix_names = declared_names(strip_comments(it.prefix))
            needed = {t for t in cited(it.ground_truth) | cited(it.statement)
                      if is_global(t, prefix_names, idx_names)
                      and t.rsplit(".", 1)[-1] not in
                          {it.name, it.name.rsplit(".", 1)[-1]}}
            body = render_punched_challenge(it, module, opens)
            if ns:
                body = body.replace(f"import {module}\n",
                                    f"import {module}\n\nnamespace {'.'.join(ns)}\n")
                body = body.rstrip("\n") + f"\n\nend {'.'.join(ns)}\n"
            good, why2 = compiles_with_one_sorry(body, repo)
            if not good:
                print(f"  reject {it.name}: {why2}", file=sys.stderr)
                continue
            (args.out / f"{it.name}.lean").write_text(body, encoding="utf-8")
            manifest.append({
                "name": it.name,
                "file": str((args.out / f"{it.name}.lean").relative_to(repo)),
                "punched_module": module,
                "punched_file": str(mpath.relative_to(repo)),
                "group": it.group, "source_file": it.file, "source_line": it.line,
                "proof_lines": it.proof_lines,
                "challenge_lines": len(body.splitlines()),
                "statement": it.statement,
                # In punch mode there is NO prefix, so "external to the prefix"
                # measures nothing: the challenge file contains none of the
                # target's dependencies.  Record every global the target cites;
                # those are exactly what a proposer must find, and their
                # originals are in the index even though the punched copy is not.
                "needed": sorted(needed),
                "external_citations": r["external"],
                "proof_external_citations": r["proof_external"],
                "max_visible_twin": r["twin_score"],
            })
            emitted += 1
            print(f"  emit   {it.name:<22} {len(body.splitlines()):>3} lines "
                  f"(was {len(src_lines)}-line prefix)", file=sys.stderr)

    mpath2 = args.manifest or (args.out.parent / "challenge-manifest.json")
    mpath2.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\n{emitted} emitted -> {args.out}\nmanifest -> {mpath2}",
          file=sys.stderr)
    return 0 if emitted else 1


def lean_path(repo: Path) -> str:
    r = subprocess.run(["lake", "env", "printenv", "LEAN_PATH"], cwd=repo,
                       capture_output=True, text=True, timeout=300)
    return r.stdout.strip()


def build_olean(repo: Path, src_rel: str, module: str, lp: str) -> tuple[bool, str]:
    """Compile a punched module into Lake's own build root.

    Writing the `.olean` where Lake already looks means a challenge file can
    `import` it under plain `lake env lean` -- so `toolkit_cli.py check` works
    unchanged, and `lakefile.toml` is not touched.  Adding a `lean_lib` was
    tried first and reverted: `frj-dev` inserts its own libraries at exactly
    the point a new one would go, so the hunk conflicts on every merge, and
    the branch convention says tooling does not touch the lakefile.
    """
    out = repo / ".lake/build/lib/lean" / (module.replace(".", "/") + ".olean")
    out.parent.mkdir(parents=True, exist_ok=True)
    env = dict(os.environ, LEAN_PATH=lp)
    r = subprocess.run(["lean", "-o", str(out), src_rel], cwd=repo, env=env,
                       capture_output=True, text=True, timeout=3600)
    if r.returncode != 0 or not out.is_file():
        msg = ((r.stdout or "") + (r.stderr or "")).strip().splitlines()
        return False, (msg[0][:160] if msg else f"exit {r.returncode}")
    return True, "ok"


def compiles_clean(text: str, repo: Path) -> tuple[bool, str]:
    """Elaborate `text`; require zero errors and zero sorries."""
    with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=repo,
                                     delete=False, encoding="utf-8") as fh:
        fh.write(text)
        tmp = Path(fh.name)
    try:
        r = subprocess.run(["lake", "env", "lean", str(tmp)], cwd=repo,
                           capture_output=True, text=True, timeout=1800)
        out = (r.stdout or "") + (r.stderr or "")
        errs = [l for l in out.splitlines() if ": error:" in l]
        sry = [l for l in out.splitlines() if re.search(r"declaration uses .?sorry", l)]
        if errs:
            return False, errs[0][:160]
        if sry:
            return False, f"{len(sry)} sorry warning(s)"
        return True, "ok"
    except subprocess.TimeoutExpired:
        return False, "timeout"
    finally:
        tmp.unlink(missing_ok=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    ps = sub.add_parser("score", help="did a challenge get closed, and on what "
                                      "does it rest?")
    ps.add_argument("name")
    ps.add_argument("--manifest", type=Path, default=None)

    pr = sub.add_parser("retrieval-check",
                        help="can the index surface each target's external "
                             "citations? the agent-free half of the ablation")
    pr.add_argument("--manifest", type=Path, default=None)
    pr.add_argument("-k", type=int, default=10)

    for name in ("report", "build"):
        p = sub.add_parser(name)
        p.add_argument("--config", type=Path,
                       default=Path(__file__).parent / "corpora/laxlogic.json")
        p.add_argument("--max-proof-lines", type=int, default=15)
        p.add_argument("--twin-threshold", type=float, default=0.55)
        if name == "build":
            p.add_argument("-o", "--out", type=Path, required=True)
            p.add_argument("-n", "--limit", type=int, default=6)
            p.add_argument("--manifest", type=Path, default=None)
            p.add_argument("--punch", action="store_true",
                           help="hole-punch: emit a per-module Punched/ copy "
                                "with the targets removed, and a four-line "
                                "challenge that imports it. Lifts the "
                                "one-target-per-file restriction.")
            p.add_argument("--max-cascade", type=float, default=0.35,
                           help="reject a module if punching removes more than "
                                "this fraction of it")
            p.add_argument("--per-file", type=int, default=2,
                           help="max targets per source module in --punch mode")
    args = ap.parse_args()

    cfg = find_config()
    default_manifest = cfg.repo / "LaxLogic/ToolkitTest/challenge-manifest.json"
    if args.cmd == "score":
        print(json.dumps(score(cfg.repo, args.manifest or default_manifest,
                               args.name), indent=2))
        return 0
    if args.cmd == "retrieval-check":
        return retrieval_check(cfg.repo, args.manifest or default_manifest,
                               cfg.index_port, args.k)

    index_names = index_declaration_names(
        Path(__file__).parent / "leansearch/index.jsonl")
    items = load_items(args.config, args.max_proof_lines)
    rows = screen(items, index_names, args.twin_threshold)

    if args.cmd == "report":
        kept = [r for r in rows if not r["reject"]]
        print(f"{len(items)} candidates -> {len(kept)} pass the filters\n")
        by_file: dict[str, list] = {}
        for r in rows:
            by_file.setdefault(r["item"].file, []).append(r)
        for f, rs in sorted(by_file.items()):
            k = sum(1 for r in rs if not r["reject"])
            print(f"{f}: {k}/{len(rs)} pass")
            for r in sorted(rs, key=lambda r: r["item"].line):
                it = r["item"]
                mark = "PASS" if not r["reject"] else "drop"
                why = "" if not r["reject"] else "  <- " + "; ".join(r["reject"])
                print(f"   {mark} {it.name:<34} ext={len(r['external']):<2} "
                      f"pext={len(r['proof_external']):<2} "
                      f"twin={r['twin_score']:.2f}{why}")
        return 0

    # build
    repo = cfg.repo
    if getattr(args, "punch", False):
        return build_punched(args, rows, repo, index_names)
    repo = cfg.repo
    args.out.mkdir(parents=True, exist_ok=True)
    manifest, emitted, tried = [], 0, 0
    # AT MOST ONE TARGET PER SOURCE FILE.  Two prefix-truncated targets from the
    # same file always leak: the later one's prefix contains the earlier one's
    # proof.  That is exactly what happened to `conservativity` /
    # `conservativity_prop`.  Lifting this restriction is what hole-punching
    # (proposal §4) buys.
    used_files: set[str] = set()
    for r in sorted((r for r in rows if not r["reject"]),
                    key=lambda r: (-len(r["proof_external"]), -len(r["external"]),
                                   r["item"].proof_lines)):
        if emitted >= args.limit:
            break
        it = r["item"]
        if it.file in used_files:
            continue
        tried += 1
        text = render(it)
        ok, why = compiles_with_one_sorry(text, repo)
        if not ok:
            print(f"  reject {it.name}: {why}", file=sys.stderr)
            continue
        dest = args.out / f"{it.name}.lean"
        dest.write_text(text, encoding="utf-8")
        manifest.append({
            "name": it.name, "file": str(dest.relative_to(repo)),
            "group": it.group, "source_file": it.file, "source_line": it.line,
            "proof_lines": it.proof_lines,
            "statement": it.statement,
            "external_citations": r["external"],
            "proof_external_citations": r["proof_external"],
            "max_visible_twin": r["twin_score"],
        })
        emitted += 1
        used_files.add(it.file)
        print(f"  emit   {it.name}  ({len(r['external'])} external citations)",
              file=sys.stderr)

    mpath = args.manifest or (args.out.parent / "challenge-manifest.json")
    mpath.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\n{emitted} emitted (of {tried} tried) -> {args.out}", file=sys.stderr)
    print(f"manifest -> {mpath}  (provenance only; no ground-truth proofs)",
          file=sys.stderr)
    return 0 if emitted else 1


if __name__ == "__main__":
    raise SystemExit(main())
