/-
THE CATALOGUE SIMPSET — 323 certified rules, harvested.

Source: `wip/rnDict.lean`, the certified operation table of the
variable-free dictionary (the explorer's "Operation tables" tab).
Every entry is a theorem `Interd (qi ⊙ qj) qk`: a binary combination
of dictionary classes collapsing to a class REPRESENTATIVE.  That is
exactly a rewrite rule, already oriented compound → representative,
and already kernel-checked.  Nothing here is conjectured; nothing is
re-derived.

This is the answer to "each painfully gathered equation is also a
simplifier": 323 of them were sitting in the tree unused by
search.

Composition:
  ∧-table 78   ∨-table 74   ⊃-table 164   ◯-table 7

Orientation is screened by `lean_exe rwscreen`, not asserted: by
`norm_interd` the correctness of `norm` does not depend on it.
-/
import Rewrite.Core
import Rewrite.Set
import wip.rnDict

namespace Rewrite

open PLLND PLLND.SemUI

/-- The dictionary operation table as rewrite rules. -/
def rndSet : List RwRule :=
  [ ⟨_, _, RND.cAnd_2_3⟩,
  ⟨_, _, RND.cAnd_2_4⟩,
  ⟨_, _, RND.cAnd_2_5⟩,
  ⟨_, _, RND.cAnd_2_6⟩,
  ⟨_, _, RND.cAnd_2_7⟩,
  ⟨_, _, RND.cAnd_2_8⟩,
  ⟨_, _, RND.cAnd_2_9⟩,
  ⟨_, _, RND.cAnd_2_10⟩,
  ⟨_, _, RND.cAnd_2_11⟩,
  ⟨_, _, RND.cAnd_2_12⟩,
  ⟨_, _, RND.cAnd_2_13⟩,
  ⟨_, _, RND.cAnd_2_14⟩,
  ⟨_, _, RND.cAnd_3_4⟩,
  ⟨_, _, RND.cAnd_3_5⟩,
  ⟨_, _, RND.cAnd_3_6⟩,
  ⟨_, _, RND.cAnd_3_7⟩,
  ⟨_, _, RND.cAnd_3_8⟩,
  ⟨_, _, RND.cAnd_3_9⟩,
  ⟨_, _, RND.cAnd_3_10⟩,
  ⟨_, _, RND.cAnd_3_11⟩,
  ⟨_, _, RND.cAnd_3_12⟩,
  ⟨_, _, RND.cAnd_3_13⟩,
  ⟨_, _, RND.cAnd_3_14⟩,
  ⟨_, _, RND.cAnd_4_5⟩,
  ⟨_, _, RND.cAnd_4_6⟩,
  ⟨_, _, RND.cAnd_4_7⟩,
  ⟨_, _, RND.cAnd_4_8⟩,
  ⟨_, _, RND.cAnd_4_9⟩,
  ⟨_, _, RND.cAnd_4_10⟩,
  ⟨_, _, RND.cAnd_4_11⟩,
  ⟨_, _, RND.cAnd_4_12⟩,
  ⟨_, _, RND.cAnd_4_13⟩,
  ⟨_, _, RND.cAnd_4_14⟩,
  ⟨_, _, RND.cAnd_5_6⟩,
  ⟨_, _, RND.cAnd_5_7⟩,
  ⟨_, _, RND.cAnd_5_8⟩,
  ⟨_, _, RND.cAnd_5_9⟩,
  ⟨_, _, RND.cAnd_5_10⟩,
  ⟨_, _, RND.cAnd_5_11⟩,
  ⟨_, _, RND.cAnd_5_12⟩,
  ⟨_, _, RND.cAnd_5_13⟩,
  ⟨_, _, RND.cAnd_5_14⟩,
  ⟨_, _, RND.cAnd_6_7⟩,
  ⟨_, _, RND.cAnd_6_8⟩,
  ⟨_, _, RND.cAnd_6_9⟩,
  ⟨_, _, RND.cAnd_6_10⟩,
  ⟨_, _, RND.cAnd_6_11⟩,
  ⟨_, _, RND.cAnd_6_12⟩,
  ⟨_, _, RND.cAnd_6_13⟩,
  ⟨_, _, RND.cAnd_6_14⟩,
  ⟨_, _, RND.cAnd_7_8⟩,
  ⟨_, _, RND.cAnd_7_9⟩,
  ⟨_, _, RND.cAnd_7_10⟩,
  ⟨_, _, RND.cAnd_7_11⟩,
  ⟨_, _, RND.cAnd_7_12⟩,
  ⟨_, _, RND.cAnd_7_13⟩,
  ⟨_, _, RND.cAnd_7_14⟩,
  ⟨_, _, RND.cAnd_8_9⟩,
  ⟨_, _, RND.cAnd_8_10⟩,
  ⟨_, _, RND.cAnd_8_11⟩,
  ⟨_, _, RND.cAnd_8_12⟩,
  ⟨_, _, RND.cAnd_8_13⟩,
  ⟨_, _, RND.cAnd_8_14⟩,
  ⟨_, _, RND.cAnd_9_10⟩,
  ⟨_, _, RND.cAnd_9_11⟩,
  ⟨_, _, RND.cAnd_9_12⟩,
  ⟨_, _, RND.cAnd_9_13⟩,
  ⟨_, _, RND.cAnd_9_14⟩,
  ⟨_, _, RND.cAnd_10_11⟩,
  ⟨_, _, RND.cAnd_10_12⟩,
  ⟨_, _, RND.cAnd_10_13⟩,
  ⟨_, _, RND.cAnd_10_14⟩,
  ⟨_, _, RND.cAnd_11_12⟩,
  ⟨_, _, RND.cAnd_11_13⟩,
  ⟨_, _, RND.cAnd_11_14⟩,
  ⟨_, _, RND.cAnd_12_13⟩,
  ⟨_, _, RND.cAnd_12_14⟩,
  ⟨_, _, RND.cAnd_13_14⟩,
  ⟨_, _, RND.cOr_2_4⟩,
  ⟨_, _, RND.cOr_2_5⟩,
  ⟨_, _, RND.cOr_2_6⟩,
  ⟨_, _, RND.cOr_2_7⟩,
  ⟨_, _, RND.cOr_2_8⟩,
  ⟨_, _, RND.cOr_2_9⟩,
  ⟨_, _, RND.cOr_2_10⟩,
  ⟨_, _, RND.cOr_2_11⟩,
  ⟨_, _, RND.cOr_2_12⟩,
  ⟨_, _, RND.cOr_2_13⟩,
  ⟨_, _, RND.cOr_2_14⟩,
  ⟨_, _, RND.cOr_3_4⟩,
  ⟨_, _, RND.cOr_3_5⟩,
  ⟨_, _, RND.cOr_3_7⟩,
  ⟨_, _, RND.cOr_3_8⟩,
  ⟨_, _, RND.cOr_3_9⟩,
  ⟨_, _, RND.cOr_3_10⟩,
  ⟨_, _, RND.cOr_3_11⟩,
  ⟨_, _, RND.cOr_3_12⟩,
  ⟨_, _, RND.cOr_3_13⟩,
  ⟨_, _, RND.cOr_3_14⟩,
  ⟨_, _, RND.cOr_4_5⟩,
  ⟨_, _, RND.cOr_4_6⟩,
  ⟨_, _, RND.cOr_4_7⟩,
  ⟨_, _, RND.cOr_4_8⟩,
  ⟨_, _, RND.cOr_4_9⟩,
  ⟨_, _, RND.cOr_4_10⟩,
  ⟨_, _, RND.cOr_4_11⟩,
  ⟨_, _, RND.cOr_4_12⟩,
  ⟨_, _, RND.cOr_4_13⟩,
  ⟨_, _, RND.cOr_4_14⟩,
  ⟨_, _, RND.cOr_5_7⟩,
  ⟨_, _, RND.cOr_5_8⟩,
  ⟨_, _, RND.cOr_5_9⟩,
  ⟨_, _, RND.cOr_5_10⟩,
  ⟨_, _, RND.cOr_5_11⟩,
  ⟨_, _, RND.cOr_5_12⟩,
  ⟨_, _, RND.cOr_5_13⟩,
  ⟨_, _, RND.cOr_5_14⟩,
  ⟨_, _, RND.cOr_6_7⟩,
  ⟨_, _, RND.cOr_6_8⟩,
  ⟨_, _, RND.cOr_6_9⟩,
  ⟨_, _, RND.cOr_6_11⟩,
  ⟨_, _, RND.cOr_6_12⟩,
  ⟨_, _, RND.cOr_6_13⟩,
  ⟨_, _, RND.cOr_6_14⟩,
  ⟨_, _, RND.cOr_7_8⟩,
  ⟨_, _, RND.cOr_7_9⟩,
  ⟨_, _, RND.cOr_7_10⟩,
  ⟨_, _, RND.cOr_7_11⟩,
  ⟨_, _, RND.cOr_7_12⟩,
  ⟨_, _, RND.cOr_7_13⟩,
  ⟨_, _, RND.cOr_7_14⟩,
  ⟨_, _, RND.cOr_8_9⟩,
  ⟨_, _, RND.cOr_8_10⟩,
  ⟨_, _, RND.cOr_8_11⟩,
  ⟨_, _, RND.cOr_8_12⟩,
  ⟨_, _, RND.cOr_8_13⟩,
  ⟨_, _, RND.cOr_8_14⟩,
  ⟨_, _, RND.cOr_9_10⟩,
  ⟨_, _, RND.cOr_9_11⟩,
  ⟨_, _, RND.cOr_9_12⟩,
  ⟨_, _, RND.cOr_9_13⟩,
  ⟨_, _, RND.cOr_9_14⟩,
  ⟨_, _, RND.cOr_10_11⟩,
  ⟨_, _, RND.cOr_10_12⟩,
  ⟨_, _, RND.cOr_10_13⟩,
  ⟨_, _, RND.cOr_10_14⟩,
  ⟨_, _, RND.cOr_11_12⟩,
  ⟨_, _, RND.cOr_11_13⟩,
  ⟨_, _, RND.cOr_11_14⟩,
  ⟨_, _, RND.cOr_12_13⟩,
  ⟨_, _, RND.cOr_12_14⟩,
  ⟨_, _, RND.cOr_13_14⟩,
  ⟨_, _, RND.cImp_2_3⟩,
  ⟨_, _, RND.cImp_2_4⟩,
  ⟨_, _, RND.cImp_2_5⟩,
  ⟨_, _, RND.cImp_2_6⟩,
  ⟨_, _, RND.cImp_2_7⟩,
  ⟨_, _, RND.cImp_2_8⟩,
  ⟨_, _, RND.cImp_2_9⟩,
  ⟨_, _, RND.cImp_2_10⟩,
  ⟨_, _, RND.cImp_2_11⟩,
  ⟨_, _, RND.cImp_2_12⟩,
  ⟨_, _, RND.cImp_2_13⟩,
  ⟨_, _, RND.cImp_2_14⟩,
  ⟨_, _, RND.cImp_3_2⟩,
  ⟨_, _, RND.cImp_3_4⟩,
  ⟨_, _, RND.cImp_3_5⟩,
  ⟨_, _, RND.cImp_3_6⟩,
  ⟨_, _, RND.cImp_3_7⟩,
  ⟨_, _, RND.cImp_3_8⟩,
  ⟨_, _, RND.cImp_3_9⟩,
  ⟨_, _, RND.cImp_3_10⟩,
  ⟨_, _, RND.cImp_3_11⟩,
  ⟨_, _, RND.cImp_3_12⟩,
  ⟨_, _, RND.cImp_3_13⟩,
  ⟨_, _, RND.cImp_3_14⟩,
  ⟨_, _, RND.cImp_4_0⟩,
  ⟨_, _, RND.cImp_4_2⟩,
  ⟨_, _, RND.cImp_4_3⟩,
  ⟨_, _, RND.cImp_4_5⟩,
  ⟨_, _, RND.cImp_4_6⟩,
  ⟨_, _, RND.cImp_4_7⟩,
  ⟨_, _, RND.cImp_4_8⟩,
  ⟨_, _, RND.cImp_4_9⟩,
  ⟨_, _, RND.cImp_4_10⟩,
  ⟨_, _, RND.cImp_4_11⟩,
  ⟨_, _, RND.cImp_4_12⟩,
  ⟨_, _, RND.cImp_4_13⟩,
  ⟨_, _, RND.cImp_4_14⟩,
  ⟨_, _, RND.cImp_5_0⟩,
  ⟨_, _, RND.cImp_5_2⟩,
  ⟨_, _, RND.cImp_5_3⟩,
  ⟨_, _, RND.cImp_5_6⟩,
  ⟨_, _, RND.cImp_5_7⟩,
  ⟨_, _, RND.cImp_5_8⟩,
  ⟨_, _, RND.cImp_5_9⟩,
  ⟨_, _, RND.cImp_5_10⟩,
  ⟨_, _, RND.cImp_5_11⟩,
  ⟨_, _, RND.cImp_5_12⟩,
  ⟨_, _, RND.cImp_5_13⟩,
  ⟨_, _, RND.cImp_5_14⟩,
  ⟨_, _, RND.cImp_6_0⟩,
  ⟨_, _, RND.cImp_6_3⟩,
  ⟨_, _, RND.cImp_6_4⟩,
  ⟨_, _, RND.cImp_6_5⟩,
  ⟨_, _, RND.cImp_6_7⟩,
  ⟨_, _, RND.cImp_6_8⟩,
  ⟨_, _, RND.cImp_6_9⟩,
  ⟨_, _, RND.cImp_6_10⟩,
  ⟨_, _, RND.cImp_6_11⟩,
  ⟨_, _, RND.cImp_6_12⟩,
  ⟨_, _, RND.cImp_6_13⟩,
  ⟨_, _, RND.cImp_6_14⟩,
  ⟨_, _, RND.cImp_7_0⟩,
  ⟨_, _, RND.cImp_7_2⟩,
  ⟨_, _, RND.cImp_7_3⟩,
  ⟨_, _, RND.cImp_7_4⟩,
  ⟨_, _, RND.cImp_7_5⟩,
  ⟨_, _, RND.cImp_7_6⟩,
  ⟨_, _, RND.cImp_7_8⟩,
  ⟨_, _, RND.cImp_7_9⟩,
  ⟨_, _, RND.cImp_7_10⟩,
  ⟨_, _, RND.cImp_7_11⟩,
  ⟨_, _, RND.cImp_7_12⟩,
  ⟨_, _, RND.cImp_7_13⟩,
  ⟨_, _, RND.cImp_7_14⟩,
  ⟨_, _, RND.cImp_8_0⟩,
  ⟨_, _, RND.cImp_8_2⟩,
  ⟨_, _, RND.cImp_8_3⟩,
  ⟨_, _, RND.cImp_8_4⟩,
  ⟨_, _, RND.cImp_8_5⟩,
  ⟨_, _, RND.cImp_8_6⟩,
  ⟨_, _, RND.cImp_8_7⟩,
  ⟨_, _, RND.cImp_8_9⟩,
  ⟨_, _, RND.cImp_8_10⟩,
  ⟨_, _, RND.cImp_8_11⟩,
  ⟨_, _, RND.cImp_8_12⟩,
  ⟨_, _, RND.cImp_8_13⟩,
  ⟨_, _, RND.cImp_8_14⟩,
  ⟨_, _, RND.cImp_9_0⟩,
  ⟨_, _, RND.cImp_9_2⟩,
  ⟨_, _, RND.cImp_9_3⟩,
  ⟨_, _, RND.cImp_9_4⟩,
  ⟨_, _, RND.cImp_9_5⟩,
  ⟨_, _, RND.cImp_9_6⟩,
  ⟨_, _, RND.cImp_9_7⟩,
  ⟨_, _, RND.cImp_9_8⟩,
  ⟨_, _, RND.cImp_9_10⟩,
  ⟨_, _, RND.cImp_9_11⟩,
  ⟨_, _, RND.cImp_9_12⟩,
  ⟨_, _, RND.cImp_9_13⟩,
  ⟨_, _, RND.cImp_9_14⟩,
  ⟨_, _, RND.cImp_10_0⟩,
  ⟨_, _, RND.cImp_10_2⟩,
  ⟨_, _, RND.cImp_10_3⟩,
  ⟨_, _, RND.cImp_10_4⟩,
  ⟨_, _, RND.cImp_10_6⟩,
  ⟨_, _, RND.cImp_10_7⟩,
  ⟨_, _, RND.cImp_10_8⟩,
  ⟨_, _, RND.cImp_10_9⟩,
  ⟨_, _, RND.cImp_10_11⟩,
  ⟨_, _, RND.cImp_10_12⟩,
  ⟨_, _, RND.cImp_10_13⟩,
  ⟨_, _, RND.cImp_10_14⟩,
  ⟨_, _, RND.cImp_11_0⟩,
  ⟨_, _, RND.cImp_11_2⟩,
  ⟨_, _, RND.cImp_11_3⟩,
  ⟨_, _, RND.cImp_11_4⟩,
  ⟨_, _, RND.cImp_11_5⟩,
  ⟨_, _, RND.cImp_11_6⟩,
  ⟨_, _, RND.cImp_11_7⟩,
  ⟨_, _, RND.cImp_11_8⟩,
  ⟨_, _, RND.cImp_11_9⟩,
  ⟨_, _, RND.cImp_11_10⟩,
  ⟨_, _, RND.cImp_11_12⟩,
  ⟨_, _, RND.cImp_11_13⟩,
  ⟨_, _, RND.cImp_11_14⟩,
  ⟨_, _, RND.cImp_12_0⟩,
  ⟨_, _, RND.cImp_12_2⟩,
  ⟨_, _, RND.cImp_12_3⟩,
  ⟨_, _, RND.cImp_12_4⟩,
  ⟨_, _, RND.cImp_12_5⟩,
  ⟨_, _, RND.cImp_12_6⟩,
  ⟨_, _, RND.cImp_12_7⟩,
  ⟨_, _, RND.cImp_12_8⟩,
  ⟨_, _, RND.cImp_12_9⟩,
  ⟨_, _, RND.cImp_12_10⟩,
  ⟨_, _, RND.cImp_12_11⟩,
  ⟨_, _, RND.cImp_12_13⟩,
  ⟨_, _, RND.cImp_12_14⟩,
  ⟨_, _, RND.cImp_13_0⟩,
  ⟨_, _, RND.cImp_13_2⟩,
  ⟨_, _, RND.cImp_13_3⟩,
  ⟨_, _, RND.cImp_13_4⟩,
  ⟨_, _, RND.cImp_13_5⟩,
  ⟨_, _, RND.cImp_13_6⟩,
  ⟨_, _, RND.cImp_13_7⟩,
  ⟨_, _, RND.cImp_13_8⟩,
  ⟨_, _, RND.cImp_13_9⟩,
  ⟨_, _, RND.cImp_13_10⟩,
  ⟨_, _, RND.cImp_13_11⟩,
  ⟨_, _, RND.cImp_13_12⟩,
  ⟨_, _, RND.cImp_13_14⟩,
  ⟨_, _, RND.cImp_14_0⟩,
  ⟨_, _, RND.cImp_14_2⟩,
  ⟨_, _, RND.cImp_14_3⟩,
  ⟨_, _, RND.cImp_14_4⟩,
  ⟨_, _, RND.cImp_14_5⟩,
  ⟨_, _, RND.cImp_14_6⟩,
  ⟨_, _, RND.cImp_14_7⟩,
  ⟨_, _, RND.cImp_14_8⟩,
  ⟨_, _, RND.cImp_14_9⟩,
  ⟨_, _, RND.cImp_14_10⟩,
  ⟨_, _, RND.cImp_14_11⟩,
  ⟨_, _, RND.cImp_14_12⟩,
  ⟨_, _, RND.cImp_14_13⟩,
  ⟨_, _, RND.cBox_1⟩,
  ⟨_, _, RND.cBox_4⟩,
  ⟨_, _, RND.cBox_6⟩,
  ⟨_, _, RND.cBox_9⟩,
  ⟨_, _, RND.cBox_10⟩,
  ⟨_, _, RND.cBox_11⟩,
  ⟨_, _, RND.cBox_14⟩ ]

/-- The full round-1 PLL simpset: the modal laws plus the table. -/
def fullSet : List RwRule := pllSet ++ rndSet

end Rewrite
