#!/usr/bin/env python3
"""Rewrite the generated figures block in `README.md` from the ledger record.

    scripts/readme-figures.py [docs/status-ledger.jsonl] [README.md] [--check]

`--check` rewrites nothing and exits 1 if the block is out of date, so CI can
say "the README is lying" without touching the tree.

WHY THIS EXISTS.  The README quotes nine figures and a four-way breakdown of the
`sorryAx` declarations.  Hand-maintained, every one of them is a hostage: the
first draft of that section had the breakdown wrong (it said 20 in `wip/`; the
record said 16), and nothing would have caught it.  `scripts/ledger-report.py`
already regenerates `docs/status-ledger.md` from the same record; this does the
same job for the README's summary, and `scripts/check-ledger.sh --update` runs
both.

WHAT IT DOES NOT DO: interpret.  Every number is a count of rows in the record.
The one judgement in the file is `DELIBERATE` below, and it is deliberately
visible rather than derived.
"""
import json
import re
import subprocess
import sys
import textwrap
from collections import Counter

# Library modules whose `sorry` is there ON PURPOSE, each with the reason.  This
# is the only judgement in this script, and it mirrors the hold-out list in
# `Audit/Production.lean` — keep the two in step.  A library `sorry` in a module
# NOT named here is reported as unintended, which is the alarm you want: a new
# one means either a real open case or a missing line in both lists.
DELIBERATE = {
    "LaxLogic.Obligation.Examples":
        "§5 exists to show what one `sorry` does to everything downstream, and "
        "both carry pins asserting `[sorryAx]` on purpose",
}

# Module prefixes that are not libraries.  `wip/` permits a `sorry` by
# CLAUDE.md rule 1; `ToolkitTest/` files are deliberately holed fixtures the
# prover toolkit is measured against.
WIP_PREFIXES = ("wip.", "wipx.", "wipa.", "wipb.", "wipc.", "wipd.")
FIXTURE_PREFIX = "LaxLogic.ToolkitTest."

BEGIN = "<!-- BEGIN generated by scripts/readme-figures.py -->"
END = "<!-- END generated -->"


def kernel_axioms(row) -> tuple:
    """The row's axioms with any `native_decide`-minted axiom dropped, so the
    axiom-profile rows count what the kernel was asked to trust."""
    return tuple(a for a in row["axioms"] if "native_decide" not in a)


def render(rows, date: str) -> str:
    n_mod = len({r["module"] for r in rows})
    kinds = Counter(r["kind"] for r in rows)
    clean = [r for r in rows if not r["sorry"]]
    prof = Counter(kernel_axioms(r) for r in clean)
    choice = sum(v for k, v in prof.items() if "Classical.choice" in k)
    sorried = [r for r in rows if r["sorry"]]
    native = [r for r in rows if r["native"]]

    wip = [r for r in sorried if r["module"].startswith(WIP_PREFIXES)]
    fixture = [r for r in sorried if r["module"].startswith(FIXTURE_PREFIX)]
    lib = [r for r in sorried if r not in wip and r not in fixture]
    intended = [r for r in lib if r["module"] in DELIBERATE]
    unintended = [r for r in lib if r["module"] not in DELIBERATE]

    def n(x) -> str:
        return f"{x:,}"

    out = [BEGIN, "", f"As of {date}:", "", "| | |", "|---|--:|"]
    out += [
        f"| declarations recorded | {n(len(rows))} in {n(n_mod)} modules |",
        f"| theorems | {n(kinds['theorem'])} |",
        f"| axiom-free | {n(prof[()])} |",
        f"| `[propext, Quot.sound]` | {n(prof[('propext', 'Quot.sound')])} |",
        f"| `[propext]` | {n(prof[('propext',)])} |",
        f"| using `Classical.choice` | {n(choice)} |",
        f"| carrying `sorryAx` | **{n(len(sorried))}** |",
        f"| `native_decide`-tainted | **{n(len(native))}** |",
        "",
    ]

    # The breakdown, as a sentence, because the shape of it is the point.
    parts = [f"**{n(len(wip))} in `wip/`**, where a `sorry` is permitted and is "
             "the point of a blueprint file"]
    if fixture:
        parts.append(f"**{n(len(fixture))} in `LaxLogic/ToolkitTest/`**, which "
                     "are deliberately holed fixtures the prover toolkit is "
                     "measured against")
    for mod, why in sorted(DELIBERATE.items()):
        k = sum(1 for r in intended if r["module"] == mod)
        if k:
            parts.append(f"**{n(k)} deliberate** in `{mod.replace('.', '/')}.lean`, whose {why}")
    if unintended:
        names = ", ".join(f"`{r['decl']}`" for r in sorted(unintended, key=lambda r: r["decl"]))
        parts.append(f"and **{n(len(unintended))} unintended open "
                     f"case{'s' if len(unintended) != 1 else ''}** in a library — {names}")
    else:
        parts.append("and **no unintended open case in any library**")

    sentence = (f"The {n(len(sorried))} `sorryAx` declarations break down as: "
                + "; ".join(parts[:-1]) + "; " + parts[-1]
                + ". `docs/status-ledger.md` names them all.")
    # Wrapped at the width the rest of the file uses, so a changed figure gives a
    # one-line diff instead of rewrapping the paragraph.
    out += textwrap.wrap(sentence, width=80, break_long_words=False,
                         break_on_hyphens=False)
    out += ["", END]
    return "\n".join(out)


def main(argv) -> int:
    check = "--check" in argv
    argv = [a for a in argv if not a.startswith("--")]
    record = argv[0] if argv else "docs/status-ledger.jsonl"
    readme = argv[1] if len(argv) > 1 else "README.md"

    rows = [json.loads(l) for l in open(record, encoding="utf-8")]
    # The record's own commit date, not today's: the figures describe the record.
    try:
        date = subprocess.run(["git", "log", "-1", "--format=%ad", "--date=short",
                               "--", record], capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:
        date = ""
    if not date:
        date = subprocess.run(["date", "+%Y-%m-%d"], capture_output=True,
                              text=True).stdout.strip()

    text = open(readme, encoding="utf-8").read()
    if BEGIN not in text or END not in text:
        print(f"readme-figures: {readme} has no generated block; expected\n"
              f"  {BEGIN}\n  …\n  {END}", file=sys.stderr)
        return 3
    block = render(rows, date)
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block,
                 text, count=1, flags=re.S)

    if new == text:
        print(f"readme-figures: {readme} is up to date")
        return 0
    if check:
        print(f"readme-figures: {readme} is OUT OF DATE — run "
              f"scripts/readme-figures.py", file=sys.stderr)
        return 1
    open(readme, "w", encoding="utf-8").write(new)
    print(f"readme-figures: {readme} figures regenerated from {record}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
