#!/usr/bin/env python3
"""Check the prose's claims against the ledger.

    scripts/reconcile-claims.py [docs/claims.tsv] [docs/status-ledger.jsonl]
                                [docs/claim-reconciliation.md]

Every claim that cites a Lean declaration is one of:

  CONTRADICTED  the prose says proved; the ledger says `sorryAx`, or
                `native_decide`, i.e. not kernel-checked
  DANGLING      the cited declaration is not in the estate at all — renamed,
                deleted, or never existed under that name
  CONFIRMED     the cited declaration is in the estate and kernel-clean
  STALE-OPEN    the prose says OPEN/conjecture; the ledger says kernel-clean —
                the question may have been closed since the sentence was written
  UNCITED       no declaration named: not mechanically checkable

A DANGLING citation is not automatically an error: the prose may cite a module,
a file, a paper theorem number, or a declaration in `wip/` that the ledger does
not cover.  The report separates "not in the estate, but a module of it is
named" from "no such name anywhere", because only the second needs a human.
"""
import csv, json, os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROVED = {"PROVED", "proved", "machine-checked", "kernel-checked", "sorry-free",
          "provable", "disproved", "disproves", "theorem", "lemma",
          "proposition", "corollary"}
OPEN = {"OPEN", "open", "conjecture", "conjectured", "conjectures",
        "unverified", "unproved"}
KERNEL = {"propext", "Classical.choice", "Quot.sound"}


def load_ledger(path):  # noqa: D401
    """Index every declaration by its full name AND by every suffix of it that
    starts at a component boundary: the prose writes `soundness` or
    `PLLND.soundness` where the ledger has `PLLND.soundness`.  One name can
    therefore hit several rows (the `ToolkitTest/` copies share names with the
    modules they copy), so the index holds lists."""
    index, modules = {}, set()
    with open(path, encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            modules.add(r["module"])
            parts = r["decl"].split(".")
            for i in range(len(parts)):
                index.setdefault(".".join(parts[i:]), []).append(r)
    return index, modules


def ledger_size(path):
    with open(path, encoding="utf-8") as f:
        return sum(1 for _ in f)


def classify(verdict, rows):
    """`rows` are every ledger row the cited name can denote.  A claim of proof
    is CONTRADICTED only if EVERY candidate is unclean: if any declaration of
    that name is kernel-clean, the prose is citing that one."""
    if not rows:
        return "DANGLING"
    clean = [r for r in rows
             if set(r["axioms"]) <= KERNEL and not r["sorry"] and not r["native"]]
    v = verdict.strip()
    if v in PROVED:
        return "CONFIRMED" if clean else "CONTRADICTED"
    if v in OPEN:
        return "STALE-OPEN" if clean else "CONFIRMED"
    return "CONFIRMED" if clean else "CONTRADICTED"


def main(claims_path, ledger_path, out_path):
    decls, modules = load_ledger(ledger_path)
    known_prefixes = {m for m in modules}
    rows = list(csv.DictReader(open(claims_path, encoding="utf-8"), delimiter="\t"))

    buckets = {k: [] for k in
               ("CONTRADICTED", "DANGLING", "CONFIRMED", "STALE-OPEN", "UNCITED")}
    for r in rows:
        cited = [d for d in (r["decls"] or "").split(",") if d]
        if not cited:
            buckets["UNCITED"].append((r, None, None))
            continue
        for d in cited:
            hits = decls.get(d, [])
            worst = None
            if hits:
                # show the row that justifies the verdict: an unclean one if the
                # claim is contradicted, else the first hit
                unclean = [h for h in hits if h["sorry"] or h["native"]
                           or not set(h["axioms"]) <= KERNEL]
                worst = (unclean or hits)[0]
            buckets[classify(r["verdict"], hits)].append((r, d, worst))

    # a dangling citation that names a module of the estate is a path/name
    # reference, not a missing theorem
    dangling_named, dangling_unknown = [], []
    for r, d, _ in buckets["DANGLING"]:
        (dangling_named if d in known_prefixes or
         any(d.startswith(m + ".") or m.startswith(d + ".") for m in known_prefixes)
         else dangling_unknown).append((r, d))

    out = ["# Claims against the ledger", "",
           f"Generated by `scripts/reconcile-claims.py` from `{os.path.basename(claims_path)}` "
           f"({len(rows)} claims) and `{os.path.basename(ledger_path)}` "
           f"({ledger_size(ledger_path)} declarations).", "",
           "**Read the verdicts as prompts, not judgments.** The scan is "
           "line-local: it pairs a verdict word with the declaration names on "
           "the same line, so a sentence of the form *\"machine-checked modulo "
           "the holes `a` and `b`\"* is flagged CONTRADICTED although it is "
           "exactly right, and a verdict word that happens to share a line with "
           "an unrelated identifier produces a spurious STALE-OPEN. Every row "
           "below is a place to look, and the count that means something is the "
           "count of claims that cite nothing at all.", "",
           "A claim is checkable only if it names a Lean declaration. "
           f"**{len(rows) - len(buckets['UNCITED'])} of {len(rows)} do "
           f"({100 * (len(rows) - len(buckets['UNCITED'])) // max(len(rows), 1)}%)**; "
           "the rest are prose about results, not records of them.", "",
           "| verdict of the check | count |", "|---|--:|",
           f"| CONFIRMED — ledger agrees | {len(buckets['CONFIRMED'])} |",
           f"| CONTRADICTED — prose claims proof, ledger says otherwise | {len(buckets['CONTRADICTED'])} |",
           f"| DANGLING, name is a module of the estate | {len(dangling_named)} |",
           f"| DANGLING, no such name anywhere | {len(dangling_unknown)} |",
           f"| STALE-OPEN — prose says open, ledger is clean | {len(buckets['STALE-OPEN'])} |",
           f"| UNCITED — no declaration named | {len(buckets['UNCITED'])} |", ""]

    def table(title, items, note=None, limit=None):
        out.append(f"## {title}")
        out.append("")
        if note:
            out.append(note)
            out.append("")
        if not items:
            out.append("None.")
            out.append("")
            return
        out.append("| where | claim | declaration | ledger says |")
        out.append("|---|---|---|---|")
        for r, d, row in items[:limit] if limit else items:
            says = ("`sorryAx`" if row and row["sorry"] else
                    "`native_decide`" if row and row["native"] else
                    ", ".join(f"`{a}`" for a in row["axioms"]) if row else "not in the estate")
            quote = r["quote"].replace("|", "\\|")[:90]
            out.append(f"| `{r['file']}:{r['line']}` | {r['verdict']}: {quote} | `{d}` | {says} |")
        if limit and len(items) > limit:
            out.append(f"| … | *{len(items) - limit} more* | | |")
        out.append("")

    table("CONTRADICTED — these need a human",
          buckets["CONTRADICTED"],
          "The prose asserts a proof; the ledger says the declaration carries "
          "`sorryAx` or is compiler-checked. Either the sentence is stale or "
          "the proof regressed.")
    table("DANGLING — cited name is not in the estate",
          [(r, d, None) for r, d in dangling_unknown],
          "No declaration of that name is built. Renamed, deleted, in `wip/` "
          "(which the ledger covers only where it builds), or a paper-level "
          "name that never was a Lean declaration.", limit=60)
    table("STALE-OPEN — prose says open, the ledger is clean",
          buckets["STALE-OPEN"],
          "Worth a look: the cited declaration is kernel-clean today.",
          limit=40)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"{out_path}: {len(buckets['CONTRADICTED'])} contradicted, "
          f"{len(dangling_unknown)} dangling, {len(buckets['CONFIRMED'])} confirmed, "
          f"{len(buckets['STALE-OPEN'])} stale-open, {len(buckets['UNCITED'])} uncited")
    return 0


if __name__ == "__main__":
    a = sys.argv[1:]
    sys.exit(main(a[0] if a else os.path.join(REPO, "docs", "claims.tsv"),
                  a[1] if len(a) > 1 else os.path.join(REPO, "docs", "status-ledger.jsonl"),
                  a[2] if len(a) > 2 else os.path.join(REPO, "docs", "claim-reconciliation.md")))
