/-
# Bank the ρ-order refutations as kernel-checkable certificates

`lake exe rhobank > Certified/RhoRefutations.lean` sweeps ALL 462 ordered
ρ-order cells with the profile engine (cap-free arity, `lamCap`
effectively off) and emits one certificate block per refutation found, in
exactly the `wip/rnFRJCerts.lean` format: a finite `Search.Tab`, its
frame check and root check by `decide`, the forcing refutation by
`decide`, the bridge through `FRJ.not_entails_of_countermodel`, and a
non-degeneracy control (the model still forces `⊤`).

Discover-then-pin: the SEARCH is untrusted and appears nowhere in the
emitted file; every emitted theorem is re-checked by the kernel when the
file compiles.  The `#print axioms` lines at the foot are emitted
UNGUARDED and must be guarded by `tools/pin-backfill.py` from Lean's own
output before the file is committed — an unguarded pin checks nothing.
-/
import FRJ.Search.Profile
import FRJ.Search.Pin
import FRJ.Bridge
import wip.rho_order

open FRJ

namespace RhoBank

def block (i j : Nat) (M : Search.Tab) : String :=
  let nm := s!"rho_{i}_{j}"
  String.intercalate "\n" [
    s!"/-! ### ρ{i} ⊬ ρ{j}  ({M.n}-world countermodel) -/", "",
    Search.render M s!"cm_{nm}",
    s!"theorem cm_{nm}_ok : cm_{nm}.okB = true := by decide",
    s!"theorem cm_{nm}_root : cm_{nm}.root < cm_{nm}.n := by decide", "",
    s!"def K_{nm} : Kripke := cm_{nm}.toKripke cm_{nm}_ok cm_{nm}_root", "",
    "set_option maxRecDepth 1000000 in",
    s!"theorem cm_{nm}_force :",
    s!"    ¬ (K_{nm}).force (K_{nm}).root",
    s!"        (ofPLL (.ifThen (RhoOrder.rhoF {i}) (RhoOrder.rhoF {j}))) := by decide", "",
    s!"/-- One-directional on purpose: a countermodel establishes exactly",
    s!"this, and `¬ Interd` would lose WHICH direction failed.  `⊬` is",
    s!"`PLLND.Underivable`, a reducible abbrev for `¬ Nonempty (LaxND …)`,",
    s!"so the bridge lemma's conclusion unifies with it unchanged. -/",
    s!"theorem rho_{i}_nle_{j} :",
    s!"    [RhoOrder.rhoF {i}] ⊬ RhoOrder.rhoF {j} :=",
    s!"  not_entails_of_countermodel (K_{nm}) cm_{nm}_force", "",
    "set_option maxRecDepth 1000000 in",
    s!"/-- Control: the model still forces `ρ1 = ⊤` — it does not refute by",
    s!"making everything false. -/",
    s!"theorem cm_{nm}_control :",
    s!"    (K_{nm}).force (K_{nm}).root (ofPLL (RhoOrder.rhoF 1)) := by decide", ""
  ]

def main : IO Unit := do
  let cfg : Search.Config :=
    { rounds := 12, lamCap := 1000000, maxRS := 800, maxIS := 800 }
  let out ← IO.getStdout
  let err ← IO.getStderr
  out.putStrLn "/-"
  out.putStrLn "# The ρ-order refutation certificates"
  out.putStrLn ""
  out.putStrLn "GENERATED by `lake exe rhobank` (tools/BankRho.lean); do not hand-edit"
  out.putStrLn "except to re-run the generator or to guard the pins.  Every theorem is"
  out.putStrLn "kernel-checked on compilation; the search that FOUND the models appears"
  out.putStrLn "nowhere below.  Sweep config: rounds=12, arity uncapped (profile"
  out.putStrLn "engine, FRJ/Search/Profile.lean), lamCap effectively off."
  out.putStrLn "-/"
  out.putStrLn "import FRJ.Search.Pin"
  out.putStrLn "import FRJ.Bridge"
  out.putStrLn "import wip.rho_order"
  out.putStrLn ""
  out.putStrLn "open FRJ PLLND"
  out.putStrLn ""
  out.putStrLn "namespace RhoCerts"
  out.putStrLn ""
  let mut names : List String := []
  for i in List.range RhoOrder.n do
    for j in List.range RhoOrder.n do
      if i != j then
        let G := ofPLL (PLLFormula.ifThen (RhoOrder.rhoF i) (RhoOrder.rhoF j))
        let (db, _) := Search.saturateProf G cfg
        match db.rs.find? (fun r => decide (r.rhs = G)) with
        | none => pure ()
        | some r =>
            let T := Search.tabOf (modR r.der) (Search.atomsOf G)
            let M := T.minimise G
            if M.okB && M.refutes G then
              out.putStrLn (block i j M)
              names := names ++ [s!"rho_{i}_nle_{j}"]
            else
              -- never bank a model the checker rejects; report and skip
              err.putStrLn s!"-- SKIPPED ρ{i}⊃ρ{j}: minimised model failed its own check"
    err.putStrLn s!"-- row ρ{i} done ({names.length} banked so far)"
    err.flush
  out.putStrLn "/-! ## Pins — UNGUARDED as emitted; guard via tools/pin-backfill.py -/"
  out.putStrLn ""
  for nm in names do
    out.putStrLn s!"#print axioms {nm}"
  out.putStrLn ""
  out.putStrLn "end RhoCerts"
  out.flush
  err.putStrLn s!"-- TOTAL banked: {names.length}"

end RhoBank

def main : IO Unit := RhoBank.main
