import LaxLogic.PLL.G4.G4Term
import LaxLogic.RN.Reps
import LaxLogic.RN.Rho
import tools.RCells

/-!
# Generator for `wip/rcells.lean` — the R-increment simpset cells

The R-peg loop's promotion step (standing rule, 2026-08-26): every
classed R-table cell involving the nine post-dictionary classes
ρ13–ρ21 becomes a kernel-checked `Interd` theorem, G4c route — the
budgeted `G4cTm.findBounded` searcher runs COMPILED and untrusted, and
the found proof TERMS are printed as Lean source, so the kernel's only
job is type-checking the literals.  No fuel, no `decide` re-search.

Run: `lake build rcellsgen && .lake/build/bin/rcellsgen > wip/rcells.lean`
(progress and skips to stderr; skips also appear as comments in the file).
-/

open RCells (cells)

open PLLFormula PLLND RhoOrder

namespace RCGen

/-! ## Printer machinery, copied from `wip/rnDictGen.lean` (RNGen) —
that module exports a root-level `main`, so it cannot be imported by
another executable.  `ppFN` names the fifteen q-representatives (via
`RNReps`, the same formulas); unknown formulas print as raw
constructors, so naming is compression only, never correctness. -/

def reps : List PLLFormula :=
  [RNReps.q0, RNReps.q1, RNReps.q2, RNReps.q3, RNReps.q4, RNReps.q5,
   RNReps.q6, RNReps.q7, RNReps.q8, RNReps.q9, RNReps.q10, RNReps.q11,
   RNReps.q12, RNReps.q13, RNReps.q14]

def repIdx? (X : PLLFormula) : Option Nat := reps.findIdx? (· = X)

def budget : Nat := 400000

partial def ppFN (n : Nat) (X : PLLFormula) : String :=
  match (repIdx? X).filter (· < n) with
  | some i => s!"q{i}"
  | none =>
    match X with
    | .prop s => s!"(.prop \"{s}\")"
    | .falsePLL => ".falsePLL"
    | .and a b => s!"(.and {ppFN n a} {ppFN n b})"
    | .or a b => s!"(.or {ppFN n a} {ppFN n b})"
    | .ifThen a b => s!"(.ifThen {ppFN n a} {ppFN n b})"
    | .somehow a => s!"(.somehow {ppFN n a})"

def ppF (X : PLLFormula) : String := ppFN 15 X

def memIdx (X : PLLFormula) : List PLLFormula → Nat
  | [] => 0
  | Y :: R => if X = Y then 0 else memIdx X R + 1

def memStrN : Nat → String
  | 0 => "(.head _)"
  | n + 1 => s!"(.tail _ {memStrN n})"

def memS (X : PLLFormula) (Γ : List PLLFormula) : String :=
  memStrN (memIdx X Γ)

partial def emitTm : {Γ : List PLLFormula} → {C : PLLFormula} → G4cTm Γ C → String
  | _, _, @G4cTm.init Γ a _ => s!"(.init {memS (.prop a) Γ})"
  | _, _, @G4cTm.botL Γ _ _ => s!"(.botL {memS .falsePLL Γ})"
  | _, _, @G4cTm.andR _ _ _ t1 t2 => s!"(.andR {emitTm t1} {emitTm t2})"
  | _, _, @G4cTm.orR1 _ _ _ t => s!"(.orR1 {emitTm t})"
  | _, _, @G4cTm.orR2 _ _ _ t => s!"(.orR2 {emitTm t})"
  | _, _, @G4cTm.impR _ _ _ t => s!"(.impR {emitTm t})"
  | _, _, @G4cTm.laxR _ _ t => s!"(.laxR {emitTm t})"
  | _, _, @G4cTm.laxL Γ A _ _ t =>
      s!"(.laxL (A := {ppF A}) {memS A.somehow Γ} {emitTm t})"
  | _, _, @G4cTm.andL Γ A B _ _ t =>
      s!"(.andL (A := {ppF A}) (B := {ppF B}) {memS (A.and B) Γ} {emitTm t})"
  | _, _, @G4cTm.orL Γ A B _ _ t1 t2 =>
      s!"(.orL (A := {ppF A}) (B := {ppF B}) {memS (A.or B) Γ} {emitTm t1} {emitTm t2})"
  | _, _, @G4cTm.impLProp Γ a B _ _ _ t =>
      s!"(.impLProp (a := \"{a}\") (B := {ppF B}) {memS ((PLLFormula.prop a).ifThen B) Γ} {memS (.prop a) Γ} {emitTm t})"
  | _, _, @G4cTm.impLAnd Γ A B D _ _ t =>
      s!"(.impLAnd (A := {ppF A}) (B := {ppF B}) (D := {ppF D}) {memS ((A.and B).ifThen D) Γ} {emitTm t})"
  | _, _, @G4cTm.impLOr Γ A B D _ _ t =>
      s!"(.impLOr (A := {ppF A}) (B := {ppF B}) (D := {ppF D}) {memS ((A.or B).ifThen D) Γ} {emitTm t})"
  | _, _, @G4cTm.impLImp Γ A B D _ _ t1 t2 =>
      s!"(.impLImp (A := {ppF A}) (B := {ppF B}) (D := {ppF D}) {memS ((A.ifThen B).ifThen D) Γ} {emitTm t1} {emitTm t2})"
  | _, _, @G4cTm.impLLax Γ A B _ _ t1 t2 =>
      s!"(.impLLax (A := {ppF A}) (B := {ppF B}) {memS (A.somehow.ifThen B) Γ} {emitTm t1} {emitTm t2})"
  | _, _, @G4cTm.impLLaxLax Γ A B X _ _ _ t1 t2 =>
      s!"(.impLLaxLax (A := {ppF A}) (B := {ppF B}) (X := {ppF X}) {memS (A.somehow.ifThen B) Γ} {memS X.somehow Γ} {emitTm t1} {emitTm t2})"


def mkOp : String → PLLFormula → PLLFormula → PLLFormula
  | "and", a, b => a.and b
  | "or",  a, b => a.or b
  | "imp", a, b => a.ifThen b
  | _,     a, _ => a.somehow

def opSrc : String → Nat → Nat → String
  | "and", i, j => s!"((rhoF {i}).and (rhoF {j}))"
  | "or",  i, j => s!"((rhoF {i}).or (rhoF {j}))"
  | "imp", i, j => s!"((rhoF {i}).ifThen (rhoF {j}))"
  | _,     i, _ => s!"((rhoF {i}).somehow)"

def main : IO Unit := do
  let err ← IO.getStderr
  IO.println "import wip.rnDict"
  IO.println "import LaxLogic.RN.Rho"
  IO.println "import Rewrite.Core"
  IO.println ""
  IO.println "/-!"
  IO.println "# The R-increment simpset cells — GENERATED by `rcellsgen`"
  IO.println ""
  IO.println "Kernel-checked `Interd` theorems for the classed R-table cells"
  IO.println "involving ρ13–ρ21, each proved by a pair of emitted `G4cTm` proof"
  IO.println "terms through `ofG4` (`wip/rnDictBase.lean`).  The searcher that"
  IO.println "found the terms is untrusted; the kernel type-checks every literal"
  IO.println "at elaboration.  `rcSet` collects the cells as rewrite rules,"
  IO.println "oriented compound → representative.  DO NOT EDIT BY HAND — rerun"
  IO.println "the generator (see tools/RCellsGen.lean)."
  IO.println "-/"
  IO.println ""
  IO.println "open PLLFormula RhoOrder"
  IO.println ""
  IO.println "namespace PLLND"
  IO.println "namespace SemUI"
  IO.println "namespace RCX"
  IO.println ""
  IO.println "export RNReps (q0 q1 q2 q3 q4 q5 q6 q7 q8 q9 q10 q11 q12 q13 q14)"
  IO.println ""
  IO.println "open RND (ofG4)"
  IO.println ""
  let mut names : List String := []
  let mut nSkip := 0
  for (op, i, j, k) in cells do
    let lhs := mkOp op (rhoF i) (rhoF j)
    let rhs := rhoF k
    if lhs == rhs then
      IO.println s!"-- TRIV {op} {i} {j}: lhs is ρ{k} syntactically; no rule"
      continue
    match (G4cTm.findBounded budget [lhs] rhs).1 with
    | none =>
        nSkip := nSkip + 1
        IO.println s!"-- SKIP {op} {i} {j} ≡ ρ{k}: forward direction not settled at budget {budget}"
        err.putStrLn s!"SKIP fwd {op} {i} {j} {k}"
    | some t1 =>
      match (G4cTm.findBounded budget [rhs] lhs).1 with
      | none =>
          nSkip := nSkip + 1
          IO.println s!"-- SKIP {op} {i} {j} ≡ ρ{k}: backward direction not settled at budget {budget}"
          err.putStrLn s!"SKIP bwd {op} {i} {j} {k}"
      | some t2 =>
          let nm := s!"rc_{op}_{i}_{j}"
          names := nm :: names
          IO.println s!"theorem {nm} : Interd {opSrc op i j} (rhoF {k}) :="
          IO.println s!"  ⟨(ofG4 {emitTm t1}),"
          IO.println s!"   (ofG4 {emitTm t2})⟩"
          IO.println ""
          err.putStrLn s!"OK {op} {i} {j} {k}"
  IO.println "/-- The increment rules, oriented compound → representative. -/"
  IO.println "def rcSet : List Rewrite.RwRule :="
  IO.println "  ["
  for nm in names.reverse do
    IO.println s!"  ⟨_, _, {nm}⟩,"
  IO.println "  ]"
  IO.println ""
  IO.println "end RCX"
  IO.println "end SemUI"
  IO.println "end PLLND"
  err.putStrLn s!"RCELLSGEN-DONE ok={names.length} skip={nSkip}"

end RCGen

def main : IO Unit := RCGen.main
