import wip.envDesc
import LaxLogic.PLLSearchPin

/-!
# The boxed γ-branch at target budget `1`, CLOSED at one configuration

`wip/sealRefute.lean` shows this branch has no uniform route: each of the three
target disjuncts it could aim at is individually underivable from its
hypotheses.  `wip/envDesc.lean`'s `branch_of_cases` supplies the case analysis
that must replace one — `orAll_elim` on the branch's **second** hypothesis,
which is itself a disjunction.

This file runs the two together on a concrete configuration and closes the
branch there, kernel-checked:

    S = {◯r ⊃ s, ◯r, r, s, z}      (piece-closed, γ-head an ordinary atom)
    Γ = [◯r ⊃ s],   A = r,   B = s,   C = z

The γ-head is `r`, **not** the eliminated variable `p` — which is what makes
`wip/sealRefute.lean`'s refutations bite and the `◯⊥` collapse of §86
unavailable.  So this is the branch closing in the case that was supposed to be
hard.

## What the proof is

The second component's table has exactly one disjunct here, `z` itself, and the
case closes by **route (c)** — inject the target's own goal clause for `C = z`
and finish by `init`.  Two nodes.  Contrast:

* the *whole* obligation is not found by proof search at `findBudget` 40 000
  (`wip/sealprobe6.lean`), and
* each of routes (a), (b) and (b′) is *refuted* (`wip/sealRefute.lean`).

So the case split is not a formality.  It is what turns an obligation that
resists both search and every one-move argument into one the searcher closes in
two nodes — which is a fair diagnosis of why the July survey, which looked for a
uniform route, found none.

## What it does *not* show

One configuration is not the lemma.  The second component has a single disjunct
here because every environment clause of `s :: Γ` is guard-dead once `s` is in
the context.  A configuration whose grown context still has a live clause gives
several cases, and each needs its own route; `wip/sealprobe6.lean` runs that
larger configuration.  What this file establishes is that the *mechanism* is
sound and sufficient at least once, in the case the refutations single out.
-/

open PLLFormula

namespace PLLND
namespace BoxedBranchS1

/-- `◯a ⊃ b`. -/
def gam (a b : String) : PLLFormula := ((prop a).somehow).ifThen (prop b)

/-- The piece-closed space, γ-head an ordinary atom. -/
def S1 : Finset PLLFormula :=
  { gam "r" "s", (prop "r").somehow, prop "r", prop "s", prop "z" }

def G1 : List PLLFormula := [gam "r" "s"]

/-! ### The branch's data -/

/-- The ambient at budget `2`. -/
def amb : PLLFormula := itpE "p" S1 4 2 G1

/-- The source's boxed first component. -/
def box : PLLFormula :=
  ((itpE "p" S1 3 1 G1).ifThen (itpA "p" S1 3 1 G1 (prop "r").somehow)).somehow

/-- The source's second component, at the grown context. -/
def snd : PLLFormula := itpA "p" S1 4 1 (prop "s" :: G1) (prop "z")

/-- The target table. -/
def goal : PLLFormula := orAll (itpAoth "p" S1 3 1 G1 (prop "z"))

/-- The context of the branch. -/
def ctx : List PLLFormula := [amb, box, snd]

/-- The disjuncts of the second component — the cases of the analysis. -/
def cases1 : List PLLFormula := itpAfull "p" S1 3 1 (prop "s" :: G1) (prop "z")

/-- There is exactly one case here, and it is `z`. -/
theorem cases1_eq : cases1 = [prop "z"] := by decide

/-- The `i`-th case (with `z` as the out-of-range default, never used). -/
def caseAt (i : Nat) : PLLFormula := cases1.getD i (prop "z")

/-! ### The case, pinned

Generated by `#pinsrc` (`LaxLogic/PLLSearchPin.lean`) and re-elaborated here.
The derivation is route (c): `orR1` injects the target's goal clause for `z`,
and `init` closes it from the case hypothesis. -/

/-- Case 0 of the second component, pinned by `#pinsrc` (2 nodes). -/
theorem case0 : G4c (caseAt 0 :: ctx) goal :=
  (((.orR1 (.init (.head _)))) :
    G4cTm (caseAt 0 :: ctx) goal).toG4c

/-! ### The branch -/

/-- **The boxed γ-branch obligation at target budget `1`, closed at this
configuration.**  The ambient, the source's boxed first component and the
source's second component together reach the target table — by case analysis on
the second component (`EnvDesc.branch_of_cases`), with the single case
discharged by the pinned derivation. -/
theorem boxed_branch : G4c ctx goal := by
  refine @EnvDesc.branch_of_cases "p" S1 3 3 G1 ctx (prop "s") (prop "z")
    ?_ (G4c.identity_mem (.tail _ (.tail _ (.head _))))
  intro ψ hψ
  rw [show itpAfull "p" S1 3 1 (prop "s" :: G1) (prop "z") = cases1 from rfl,
    cases1_eq] at hψ
  rcases List.mem_singleton.mp hψ with rfl
  exact case0

end BoxedBranchS1
end PLLND

/-! ### Axiom audit -/

/--
info: 'PLLND.BoxedBranchS1.case0' depends on axioms: [propext, Quot.sound]
-/
#guard_msgs in
#print axioms PLLND.BoxedBranchS1.case0

/--
info: 'PLLND.BoxedBranchS1.boxed_branch' depends on axioms: [propext, Quot.sound]
-/
#guard_msgs in
#print axioms PLLND.BoxedBranchS1.boxed_branch
