import LaxLogic.PLLSearch
import LaxLogic.PLLConfluentComplete
import LaxLogic.PLLSearchConf
import LaxLogic.RN.Reps

/-!
# The closed (variable-free) fragment of PCLL, stratified by `crank`

PCLL = PLL + the distribution scheme `◯(A∨B) ⊃ (◯A∨◯B)`; derivability
is `ConfluentU.DerivU`.  This probe asks whether the closed fragment
collapses at a bounded Litak–Visser complexity: is there an `R₀ ≤ 7`
such that every `DerivU`-interderivability class with a representative
of `crank ≤ 7` already has a representative of `crank ≤ R₀`?

`crank` (restated locally as `crankL`, definitionally `SemUI.crank` of
`LaxLogic/PLLSemUILayered.lean`): atoms/⊥ cost 0, ∧/∨ take the max,
⊃ adds 1, ◯ adds 2.

## Method

The Lindenbaum algebra of the closed fragment is generated by ⊥ under
∧, ∨, ⊃, ◯, and `DerivU`-interderivability is a congruence for all
four connectives.  Since every connective is monotone in the `crank`s
of its arguments, a closed formula of `crank ≤ R` is interderivable
with a connective combination, of `crank ≤ R`, of MINIMAL-crank class
representatives.  So the stratified closure below — at each stratum
`R = 0 … 7`, close the discovered representative set under the four
connectives keeping results of `crank ≤ R`, to a fixpoint, before
moving to `R+1` — visits a representative of every class that has a
`crank ≤ 7` member, PROVIDED every classification cell it meets is
settled.  Unsettled cells are FLAGGED and reported; each flag punctures
the completeness argument above it (a flagged candidate is never used
as a generator).

## Verdicts (three-valued, certificate discipline)

* separated — the candidate's forcing vector differs from a
  representative's somewhere on the confluent battery (ALL well-formed
  mutually confluent frames on ≤ 4 worlds + the canonical rooted
  5-world orbits, exhaustive at 5 by the generated-submodel argument).
  A disagreement world is a mutually confluent countermodel to one
  entailment direction, exactly what `RNC.not_derivU_of_checkConf`
  consumes — kernel-escalatable cell by cell.
* ≡ (member) — both entailment directions found by the positive tier
  ladder of `wip/rnc_probe.lean` (`decidePosT`: plain PLL at 20000
  nodes, then one and two cut-style distribution applications at
  15000/12000).  Sound for `DerivU` by `RNC.derivU_of_proved`.
* FLAG — vector-identical on the whole battery but not certified
  interderivable within the tier budgets.  Escalated once at the end
  (the `phaseR` ladder, budgets 100000/60000/40000); survivors are
  reported as final flags, never dropped.

A candidate vector-separated from EVERY representative is a certified
NEW class (representatives are pairwise vector-distinct by
construction, so the shortlist of vector-identical representatives has
at most one element).

Cheap syntactic dedup (`nfc`): constant folding (⊥∧φ=⊥, ⊤∧φ=φ, ⊥∨φ=φ,
⊤∨φ=⊤, ⊥⊃φ=⊤, ⊤⊃φ=φ, φ⊃⊤=⊤, φ⊃φ=⊤), idempotence, a canonical
argument order for ∧/∨, and ◯◯φ=◯φ, ◯⊤=⊤ — each a plain-PLL
interderivability, so quotienting by them loses no class and never
raises `crank`.

Run compiled (`lake build closedfrag`), streaming one line per
classification cell:

    .lake/build/bin/closedfrag | tee -a wip/closed_frag_out.txt
-/

open PLLFormula

namespace PLLND
namespace RNC
namespace CF

/-! ## Toolkit, copied verbatim from `wip/rnc_probe.lean`

(That module carries its own `def main`, so it cannot be imported into
an exe root; the searcher/battery toolkit below is its §§ "confluent
battery" / "positive tiers" / "rooted 5-world battery", unchanged, in
namespace `PLLND.RNC.CF` instead of `PLLND.RNC`.  `confB` and the
certificate theorems come from the library, `LaxLogic/PLLSearchConf.lean`.) -/

/-! The fifteen RN(◯,{}) representatives, from the shared dictionary
`LaxLogic/RN/Reps.lean` (append-only: `qk` never changes meaning).  This
`export` re-exports the SAME constants under this namespace, so every
existing reference keeps working and there is no second copy. -/
export RNReps (q0 q1 q2 q3 q4 q5 q6 q7 q8 q9 q10 q11 q12 q13 q14)

/-- The four closure witnesses (wip/rnDictRefute.lean). -/
def w15 : PLLFormula := q8.and q10
def w16 : PLLFormula := q9.ifThen q4
def w17 : PLLFormula := q12.ifThen q4
def w18 : PLLFormula := q14.ifThen q4

def subsets {α : Type} : List α → List (List α)
  | [] => [[]]
  | a :: as => (subsets as) ++ (subsets as).map (a :: ·)

def pairsOf (n : Nat) : List (Nat × Nat) :=
  (List.range n).flatMap fun a =>
    (List.range n).filterMap fun b => if a = b then none else some (a, b)

def memP (r : List (Nat × Nat)) (p : Nat × Nat) : Bool := decide (p ∈ r)

def transL (r : List (Nat × Nat)) : Bool :=
  r.all fun p => r.all fun q =>
    !(decide (p.2 = q.1)) || memP r (p.1, q.2)

def antisymL (r : List (Nat × Nat)) : Bool :=
  r.all fun p => !(memP r (p.2, p.1))

def upClosedL (r : List (Nat × Nat)) (s : List Nat) : Bool :=
  s.all fun w => r.all fun p =>
    !(decide (p.1 = w)) || decide (p.2 ∈ s)

def framesN (n : Nat) : List FinCM :=
  ((subsets (pairsOf n)).filter fun ri => transL ri && antisymL ri).flatMap
    fun ri =>
      ((subsets ri).filter transL).flatMap fun rm =>
        ((subsets (List.range n)).filter (upClosedL ri)).filterMap fun fall =>
          let M : FinCM := ⟨n, ri, rm, fall, []⟩
          if M.wellB && confB M then some M else none

def battery : Array FinCM :=
  (framesN 1 ++ framesN 2 ++ framesN 3 ++ framesN 4).toArray

def subsF : PLLFormula → List PLLFormula
  | .and A B => .and A B :: (subsF A ++ subsF B)
  | .or A B => .or A B :: (subsF A ++ subsF B)
  | .ifThen A B => .ifThen A B :: (subsF A ++ subsF B)
  | .somehow A => .somehow A :: subsF A
  | F => [F]

def closureL (l : List PLLFormula) : List PLLFormula :=
  (l.flatMap subsF).eraseDups

def orPairs (l : List PLLFormula) : List (PLLFormula × PLLFormula) :=
  l.filterMap fun φ =>
    match φ with
    | .or A B => some (A, B)
    | _ => none

/-- The four disjunctions generating the fragment's ∨-structure. -/
def canon4 : List (PLLFormula × PLLFormula) :=
  [(q2, q3), (q3, q6), (q5, q6), (q6, q10)]

def tier1 (X Y : PLLFormula) : List (PLLFormula × PLLFormula) :=
  (orPairs (closureL [X, Y]) ++ canon4).eraseDups

def distsOf (ps : List (PLLFormula × PLLFormula)) : List PLLFormula :=
  ps.map fun p => ConfluentU.distF p.1 p.2

/-- Strip a chain of top-level implications. -/
def stripImp : PLLFormula → List PLLFormula × PLLFormula
  | .ifThen A B => let (as, h) := stripImp B; (A :: as, h)
  | C => ([], C)

/-- Cheap syntactic derivability guard (see rnc_probe). -/
def trivHead (Γ : List PLLFormula) (C : PLLFormula) : Bool :=
  let (as, h) := stripImp C
  decide (h ∈ Γ) || decide (h ∈ as) || decide (h = q1)

def andParts : PLLFormula → List PLLFormula
  | .and A B => andParts A ++ andParts B
  | F => [F]

/-- Sound sequent preprocessing: uncurry the goal's ⊃-chain, split
∧-premises. -/
def preprocess : List PLLFormula → PLLFormula → List PLLFormula × PLLFormula
  | Γ, .ifThen A B => preprocess (A :: Γ) B
  | Γ, C => (Γ.flatMap andParts, C)

def provedAt (b : Nat) (Γ : List PLLFormula) (C : PLLFormula) : Bool :=
  trivHead Γ C ||
  (let (Γ', C') := preprocess Γ C
   decide (C' ∈ Γ') ||
   match Search.decide { findBudget := some b, emitClosureCap := 0 } Γ' C' with
   | .proved _ => true
   | _ => false)

inductive Verd where
  | proved (tier : Nat)
  | refuted (fi : Nat) (w : Nat)
  | unknown
deriving Repr, DecidableEq

def Verd.tag : Verd → String
  | .proved t => s!"P{t}"
  | .refuted fi w => s!"R[{fi}.{w}]"
  | .unknown => "?"

/-- ONE application of distribution, cut-style. -/
def provedDist1 (b : Nat) (X Y : PLLFormula) : Bool :=
  (tier1 X Y).any fun p =>
    let mid := (somehow p.1).or (somehow p.2)
    provedAt b [X] (somehow (p.1.or p.2)) && provedAt b [mid, X] Y

/-- Two nested applications of distribution, cut-style. -/
def provedDist2 (b : Nat) (X Y : PLLFormula) : Bool :=
  (tier1 X Y).any fun p =>
    let mid := (somehow p.1).or (somehow p.2)
    provedAt b [X] (somehow (p.1.or p.2)) &&
      ((tier1 mid Y).any fun q =>
        let mid2 := (somehow q.1).or (somehow q.2)
        provedAt b [mid, X] (somehow (q.1.or q.2)) &&
          provedAt b [mid2, mid, X] Y)

/-- Tier ladder (rnc_probe's `decidePosT`). -/
def decidePosT (cap : Nat) (X Y : PLLFormula) : Verd :=
  if provedAt 20000 [X] Y then .proved 0
  else if cap ≥ 1 && provedDist1 15000 X Y then .proved 1
  else if cap ≥ 2 && provedDist2 12000 X Y then .proved 2
  else if cap ≥ 3 &&
      (tier1 X Y).any (fun p => provedAt 8000 [X, ConfluentU.distF p.1 p.2] Y) then
    .proved 3
  else if cap ≥ 4 && provedAt 40000 (X :: distsOf (tier1 X Y)) Y then .proved 4
  else .unknown

/-! Rooted 5-world confluent battery (canonical orbits). -/

def ltKey : List Nat → List Nat → Bool
  | [], [] => false
  | [], _ :: _ => true
  | _ :: _, [] => false
  | a :: as, b :: bs =>
    if a < b then true else if b < a then false else ltKey as bs

def keyOf (r : List (Nat × Nat)) : List Nat :=
  (r.map fun q => q.1 * 16 + q.2).mergeSort (fun a b => a ≤ b)

def pairKey (ri rm : List (Nat × Nat)) : List Nat :=
  keyOf ri ++ [999] ++ keyOf rm

def applyPerm (p : List Nat) (k : Nat) : Nat :=
  if k = 0 then 0 else p.getD (k - 1) k

def isCanon (ri4 rm : List (Nat × Nat)) : Bool :=
  let k0 := pairKey ri4 rm
  ([1, 2, 3, 4].permutations).all fun p =>
    let ri' := ri4.map fun q => (applyPerm p q.1, applyPerm p q.2)
    let rm' := rm.map fun q => (applyPerm p q.1, applyPerm p q.2)
    !(ltKey (pairKey ri' rm') k0)

def framesRooted5 : List FinCM :=
  let inner := (pairsOf 4).map fun q => (q.1 + 1, q.2 + 1)
  ((subsets inner).filter fun ri4 => transL ri4 && antisymL ri4).flatMap
    fun ri4 =>
      let ri := ((List.range 4).map fun k => (0, k + 1)) ++ ri4
      (((subsets ri).filter transL).filter (isCanon ri4)).flatMap fun rm =>
        if confB ⟨5, ri, rm, [], []⟩ then
          ((subsets (List.range 5)).filter (upClosedL ri)).filterMap
            fun fall =>
              let M : FinCM := ⟨5, ri, rm, fall, []⟩
              if M.wellB && confB M then some M else none
        else []

def vecOf (M : FinCM) (φ : PLLFormula) : Array Bool :=
  (Array.range M.n).map fun w => M.forceB w φ

/-! ## End of the copied toolkit -/

/-- `SemUI.crank`, restated locally (avoids the `PLLSemUILayered`
import): atoms/⊥ 0, ∧/∨ max, ⊃ +1, ◯ +2. -/
def crankL : PLLFormula → Nat
  | .prop _ => 0
  | .falsePLL => 0
  | .and a b => max (crankL a) (crankL b)
  | .or a b => max (crankL a) (crankL b)
  | .ifThen a b => max (crankL a) (crankL b) + 1
  | .somehow a => crankL a + 2

def sizeF : PLLFormula → Nat
  | .and a b => sizeF a + sizeF b + 1
  | .or a b => sizeF a + sizeF b + 1
  | .ifThen a b => sizeF a + sizeF b + 1
  | .somehow a => sizeF a + 1
  | _ => 1

/-- Injective string key (prefix code) — the canonical order for the
∧/∨ argument sort and the seen-set. -/
def keyF : PLLFormula → String
  | .falsePLL => "F"
  | .prop s => "P" ++ s ++ ";"
  | .and a b => "A" ++ keyF a ++ "," ++ keyF b ++ ";"
  | .or a b => "O" ++ keyF a ++ "," ++ keyF b ++ ";"
  | .ifThen a b => "I" ++ keyF a ++ "," ++ keyF b ++ ";"
  | .somehow a => "S" ++ keyF a ++ ";"

/-! ## The normalizer (all rewrites are plain-PLL interderivabilities) -/

def mkAnd (a b : PLLFormula) : PLLFormula :=
  if a = falsePLL ∨ b = falsePLL then falsePLL
  else if a = truePLL then b
  else if b = truePLL then a
  else if a = b then a
  else if keyF a ≤ keyF b then .and a b else .and b a

def mkOr (a b : PLLFormula) : PLLFormula :=
  if a = falsePLL then b
  else if b = falsePLL then a
  else if a = truePLL ∨ b = truePLL then truePLL
  else if a = b then a
  else if keyF a ≤ keyF b then .or a b else .or b a

def mkImp (a b : PLLFormula) : PLLFormula :=
  if a = falsePLL then truePLL
  else if b = truePLL then truePLL
  else if a = truePLL then b
  else if a = b then truePLL
  else .ifThen a b

/-- `◯⊤ = ⊤` (`⊤ ⊢ ◯⊤` by `laxIntro`; `◯⊤ ⊃ ⊤` trivially) and
`◯◯φ = ◯φ` (unit and join of the lax modality). -/
def mkBox (a : PLLFormula) : PLLFormula :=
  if a = truePLL then truePLL
  else match a with
    | .somehow _ => a
    | _ => .somehow a

def nfc : PLLFormula → PLLFormula
  | .and a b => mkAnd (nfc a) (nfc b)
  | .or a b => mkOr (nfc a) (nfc b)
  | .ifThen a b => mkImp (nfc a) (nfc b)
  | .somehow a => mkBox (nfc a)
  | F => F

/-! ## Display -/

mutual
partial def ppA (F : PLLFormula) : String :=
  match F with
  | .falsePLL => "⊥"
  | .prop s => s
  | .ifThen _ _ => if F = truePLL then "⊤" else s!"({pp F})"
  | .somehow a => s!"◯{ppA a}"
  | _ => s!"({pp F})"

partial def pp (F : PLLFormula) : String :=
  match F with
  | .falsePLL => "⊥"
  | .prop s => s
  | .and a b => s!"{ppA a} ∧ {ppA b}"
  | .or a b => s!"{ppA a} ∨ {ppA b}"
  | .ifThen a b =>
    if F = truePLL then "⊤"
    else if b = falsePLL then s!"¬{ppA a}"
    else s!"{ppA a} ⊃ {ppA b}"
  | .somehow a => s!"◯{ppA a}"
end

/-! ## Classification -/

structure RepC where
  name : String
  F : PLLFormula
  rk : Nat                       -- crank at discovery (minimal, see header)
  vec : Array (Array Bool)       -- forcing vectors over the battery

instance : Inhabited RepC := ⟨⟨"", falsePLL, 0, #[]⟩⟩

inductive Cls where
  | newClass
  | member (idx t1 t2 : Nat)
  | flagged (idx : Nat) (d1 d2 : String)

/-- Vector shortlist, then the positive tier ladder.  Representatives
are pairwise vector-distinct, so at most one can agree with `F`. -/
def classifyF (bat : Array FinCM) (reps : Array RepC) (F : PLLFormula) :
    Cls × Array (Array Bool) :=
  let vF := bat.map fun M => vecOf M F
  match (List.range reps.size).filter
      (fun c => decide ((reps.getD c default).vec = vF)) with
  | [] => (.newClass, vF)
  | c :: _ =>
    let r := reps.getD c default
    match decidePosT 2 F r.F, decidePosT 2 r.F F with
    | .proved t1, .proved t2 => (.member c t1 t2, vF)
    | d1, d2 => (.flagged c d1.tag d2.tag, vF)

/-- One-step connective closure over the representatives, capped at
`crank ≤ rcap`, normalized. -/
def genFrom (reps : Array RepC) (rcap : Nat) : List PLLFormula :=
  let rl := reps.toList.map (·.F)
  let uns :=
    (rl.map fun a => nfc (.somehow a)) ++
    (rl.flatMap fun a => rl.flatMap fun b =>
      [nfc (.and a b), nfc (.or a b), nfc (.ifThen a b)])
  (uns.filter fun F => crankL F ≤ rcap).eraseDups

def sortCands (l : List PLLFormula) : List PLLFormula :=
  l.mergeSort fun a b =>
    let (ca, cb) := (crankL a, crankL b)
    if ca ≠ cb then decide (ca < cb)
    else
      let (sa, sb) := (sizeF a, sizeF b)
      if sa ≠ sb then decide (sa < sb) else decide (keyF a ≤ keyF b)

/-- The escalation ladder of `phaseR` (one positive push per unproved
direction of a flagged cell). -/
def escalate (X Y : PLLFormula) : Option String :=
  if provedAt 100000 [X] Y then some "plain PLL, budget 100000"
  else if provedDist1 60000 X Y then some "one dist application, budget 60000"
  else if provedDist2 40000 X Y then some "two dist applications, budget 40000"
  else if (tier1 X Y).any
      (fun p => provedAt 60000 [X, ConfluentU.distF p.1 p.2] Y) then
    some "single instance premise, budget 60000"
  else if provedAt 100000 (X :: distsOf (tier1 X Y)) Y then
    some "full tier-1 premise list, budget 100000"
  else none

/-- First battery cell separating `F` from `G` (a world forcing `F` but
not `G`): a mutually confluent countermodel to `[F] ⊢ G`. -/
def firstSep (bat : Array FinCM) (vF vG : Array (Array Bool)) :
    Option (Nat × Nat) := Id.run do
  for fi in [0:bat.size] do
    let a := vF.getD fi #[]
    let b := vG.getD fi #[]
    for w in [0:a.size] do
      if a.getD w false && !(b.getD w false) then
        return some (fi, w)
  return none

def pinLine (bat : Array FinCM) (fi w : Nat) (X Y : PLLFormula) : String :=
  let M := bat.getD fi ⟨0, [], [], [], []⟩
  s!"    pin: ¬ ConfluentU.DerivU [{pp X}] ({pp Y}) := not_derivU_of_checkConf (M := {Search.srcOfCM M}) (w := {w}) (by decide) (by decide)"

/-! ## The sweep -/

def dictSeeds : List (String × PLLFormula) :=
  [("q0", q0), ("q1", q1), ("q2", q2), ("q3", q3), ("q4", q4),
   ("q5", q5), ("q6", q6), ("q7", q7), ("q8", q8), ("q9", q9),
   ("q10", q10), ("q11", q11), ("q12", q12), ("q13", q13), ("q14", q14),
   ("w15", w15), ("w16", w16), ("w17", w17), ("w18", w18)]

def mainSweep : IO Unit := do
  let out ← IO.getStdout
  let t0 ← IO.monoMsNow
  IO.println "=== closed fragment of PCLL: crank-stratified DerivU classes (cap crank ≤ 7) ==="
  let b4 := battery
  let b5 := framesRooted5.toArray
  let bat := b4 ++ b5
  IO.println s!"confluent battery: {b4.size} frames (ALL well-formed confluent ≤4 worlds) + {b5.size} rooted 5-world canonical orbits"
  -- dictionary seeds outside the cap: reported, not silently dropped
  for (nm, F) in dictSeeds do
    let F' := nfc F
    if crankL F' > 7 then
      IO.println s!"SKIP seed {nm} = {pp F'} (crank {crankL F'} > cap 7)"
  out.flush
  let mut reps : Array RepC := #[]
  let mut seen : List String := []
  let mut flags : Array (PLLFormula × Nat × String × String) := #[]
  let mut newAt : Array (Nat × String) := #[]   -- (stratum, rep name)
  for R in [0:8] do
    let mut fresh := true
    let mut rounds := 0
    for _ in [0:6] do
      if fresh then
        fresh := false
        rounds := rounds + 1
        let base : List PLLFormula := if reps.isEmpty then [falsePLL] else []
        let seeds := (dictSeeds.map fun s => nfc s.2).filter fun F => crankL F = R
        let cands0 := (base ++ seeds ++ genFrom reps R).eraseDups
        let cands := sortCands (cands0.filter fun F => !(seen.contains (keyF F)))
        for F in cands do
          seen := keyF F :: seen
          let ts ← IO.monoMsNow
          let (cl, vF) := classifyF bat reps F
          let te ← IO.monoMsNow
          let slow := if te - ts > 3000 then s!"  [{te - ts} ms]" else ""
          match cl with
          | .newClass =>
            let nm := s!"r{reps.size}"
            IO.println s!"NEW  {nm} := {pp F}   crank={crankL F}{slow}"
            reps := reps.push ⟨nm, F, crankL F, vF⟩
            newAt := newAt.push (R, nm)
            fresh := true
          | .member c t1 t2 =>
            IO.println s!"MEM  {pp F} ≡ {(reps.getD c default).name} (tiers {t1}/{t2})   crank={crankL F}{slow}"
          | .flagged c d1 d2 =>
            IO.println s!"FLAG {pp F} ?≡ {(reps.getD c default).name} ({d1}/{d2})   crank={crankL F}{slow}"
            flags := flags.push (F, c, d1, d2)
          out.flush
    if fresh then
      IO.println s!"CAP  stratum {R}: round cap 6 hit with new classes still appearing"
    let newHere := (newAt.toList.filter (·.1 = R)).map (·.2)
    IO.println s!"STRATUM {R}: rounds={rounds} classes-so-far={reps.size} new-at-this-crank={newHere} flags-so-far={flags.size}"
    out.flush
  let t1 ← IO.monoMsNow
  IO.println s!"sweep done in {t1 - t0} ms"
  -- representative table
  IO.println ""
  IO.println "=== representatives (name, min-crank, formula) ==="
  for r in reps do
    let dict := (dictSeeds.filter fun s => nfc s.2 = r.F).map (·.1)
    let al := if dict.isEmpty then "" else s!"   [= {dict}]"
    IO.println s!"  {r.name}  crank={r.rk}  {pp r.F}{al}"
  -- escalation
  IO.println ""
  IO.println s!"=== escalation: {flags.size} flagged cells (positive ladder; the battery side is already exhaustive ≤ 5 worlds) ==="
  let mut finalFlags : Nat := 0
  for (F, c, d1, d2) in flags do
    let r := reps.getD c default
    let e1 := if d1 = "?" then escalate F r.F else some s!"already {d1}"
    let e2 := if d2 = "?" then escalate r.F F else some s!"already {d2}"
    match e1, e2 with
    | some s1, some s2 =>
      IO.println s!"  RESOLVED {pp F} ≡ {r.name}  ({s1} / {s2})"
    | _, _ =>
      finalFlags := finalFlags + 1
      let m1 := match e1 with | some s => s | none => "UNPROVED"
      let m2 := match e2 with | some s => s | none => "UNPROVED"
      IO.println s!"  FLAG {pp F} ?≡ {r.name}  (fwd: {m1} / bwd: {m2})  — vector-identical on the whole ≤5-world confluent battery"
    out.flush
  IO.println s!"final flags: {finalFlags}"
  -- pivots
  IO.println ""
  IO.println "=== pivots ==="
  -- ◯⊤ vs ⊤
  let bt := PLLFormula.somehow truePLL
  match decidePosT 0 bt truePLL, decidePosT 0 truePLL bt with
  | .proved _, .proved _ =>
    IO.println s!"  ◯⊤ ≡ ⊤ (both directions plain PLL: ◯⊤ ⊃ ⊤ trivial, ⊤ ⊢ ◯⊤ by laxIntro): crank 3 collapses to crank 1"
  | a, b =>
    IO.println s!"  ◯⊤ vs ⊤: {a.tag}/{b.tag} — NOT settled at tier 0"
  -- ¬¬◯⊥ (q6, crank 4) and ◯¬◯⊥ (q5, crank 5) vs all smaller-crank reps
  for (nm, F, ck) in [("¬¬◯⊥ (q6)", nfc q6, crankL (nfc q6)),
                      ("◯¬◯⊥ (q5)", nfc q5, crankL (nfc q5))] do
    IO.println s!"  {nm}, crank {ck}, vs every representative of smaller crank:"
    let vF := bat.map fun M => vecOf M F
    for r in reps do
      if r.rk < ck then
        if decide (r.vec = vF) then
          IO.println s!"    vs {r.name}: vector-identical (see class table)"
        else
          let s1 := firstSep bat vF r.vec
          let s2 := firstSep bat r.vec vF
          match s1, s2 with
          | some (fi, w), _ =>
            IO.println s!"    vs {r.name} ({pp r.F}): separated, [{pp F}] ⊬ {pp r.F} at frame {fi} world {w}"
            IO.println (pinLine bat fi w F r.F)
          | none, some (fi, w) =>
            IO.println s!"    vs {r.name} ({pp r.F}): separated, [{pp r.F}] ⊬ {pp F} at frame {fi} world {w}"
            IO.println (pinLine bat fi w r.F F)
          | none, none => pure ()
    out.flush
  -- frames cited
  IO.println ""
  IO.println "=== battery frames cited (index: n, ri, rm, fall) ==="
  IO.println "  (indices into b4 ++ b5; render any index i with: bat.getD i)"
  let tz ← IO.monoMsNow
  IO.println s!"=== done in {tz - t0} ms ==="

/-! ## Pin emission (`closedfrag pin`)

The 22 representatives are deterministic outputs of the sweep;
reconstructed here as `nfc`-images of dictionary combinations (checked
against the sweep's printed table).  For each crank-7 class and each
crank-≤6 class, emit the paste-ready kernel certificate
(`not_derivU_of_checkConf`, both side conditions `by decide`) for the
first battery cell separating them — the separations that carry the
no-collapse verdict at the crank-7 boundary. -/

def repsList : List PLLFormula :=
  [q0, q1, q2, q3, q4, q6, q7, q5, q10, q9, q11,
   q8, q14, q10.ifThen q4, w16, q8.or q5, w16.or q5, q6.or w16, w16.or q9,
   q8.ifThen q5, q8.ifThen q7, w16.ifThen q5].map nfc

def pinBoundary : IO Unit := do
  let out ← IO.getStdout
  let bat := battery ++ framesRooted5.toArray
  let rl := repsList.toArray
  let vecs := rl.map fun F => bat.map fun M => vecOf M F
  IO.println "-- generated by `closedfrag pin`: crank-7 classes vs all crank-≤6 classes"
  for i in [0:rl.size] do
    IO.println s!"-- r{i} crank={crankL (rl.getD i falsePLL)} {pp (rl.getD i falsePLL)}"
  IO.println ""
  for i in [19:22] do
    for j in [0:19] do
      let X := rl.getD i falsePLL
      let Y := rl.getD j falsePLL
      let vX := vecs.getD i #[]
      let vY := vecs.getD j #[]
      match firstSep bat vX vY with
      | some (fi, w) =>
        let M := bat.getD fi ⟨0, [], [], [], []⟩
        IO.println s!"/-- `r{i} ⊬ r{j}`: [{pp X}] ⊬ {pp Y}. -/"
        IO.println s!"theorem cf_sep_{i}_{j} :"
        IO.println s!"    ¬ ConfluentU.DerivU [{Search.srcOf X}] ({Search.srcOf Y}) :="
        IO.println s!"  not_derivU_of_checkConf (M := {Search.srcOfCM M}) (w := {w}) (by decide) (by decide)"
        IO.println ""
      | none =>
        match firstSep bat vY vX with
        | some (fi, w) =>
          let M := bat.getD fi ⟨0, [], [], [], []⟩
          IO.println s!"/-- `r{j} ⊬ r{i}`: [{pp Y}] ⊬ {pp X}. -/"
          IO.println s!"theorem cf_sep_{j}_{i} :"
          IO.println s!"    ¬ ConfluentU.DerivU [{Search.srcOf Y}] ({Search.srcOf X}) :="
          IO.println s!"  not_derivU_of_checkConf (M := {Search.srcOfCM M}) (w := {w}) (by decide) (by decide)"
          IO.println ""
        | none =>
          IO.println s!"-- NOSEP r{i} vs r{j} (UNEXPECTED: reps must be vector-distinct)"
      out.flush

end CF
end RNC
end PLLND

def main (args : List String) : IO Unit :=
  match args with
  | "pin" :: _ => PLLND.RNC.CF.pinBoundary
  | _ => PLLND.RNC.CF.mainSweep
