import LaxLogic.PLLSearchConf

/-!
# Kernel-checked PCLL separations at the crank-7 boundary

GENERATED by `closedfrag pin` (wip/closed_frag.lean) — for each of the
three closed-fragment PCLL classes discovered at crank 7 (`r19`, `r20`,
`r21` of wip/closed_frag_out.txt) and each of the 19 classes of
crank ≤ 6, one separating cell: a MUTUALLY CONFLUENT finite
countermodel to one entailment direction, so the two formulas are not
`ConfluentU.DerivU`-interderivable.  Confluent models validate every
distribution instance, hence these refute PLL + the distribution
scheme (PCLL), not merely PLL (`RNC.not_derivU_of_checkConf`; both
side conditions are closed Boolean computations, `by decide` is kernel
evaluation).

Together with the sweep's flag-free strata 0–5 these pin the
no-collapse verdict: the closed fragment of PCLL has classes of
minimal crank 7 (relative to the certified ≤5-world-battery
partition; see wip/closed_frag_report.md).
-/

open PLLFormula

namespace PLLND
namespace RNC
namespace CF


/-- `r19 ⊬ r0`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ⊥. -/
theorem cf_sep_19_0 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (PLLFormula.falsePLL) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r1 ⊬ r19`: [⊤] ⊬ (◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥). -/
theorem cf_sep_1_19 :
    ¬ ConfluentU.DerivU [(PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r19 ⊬ r2`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ◯⊥. -/
theorem cf_sep_19_2 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((PLLFormula.falsePLL.somehow)) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r19 ⊬ r3`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ¬◯⊥. -/
theorem cf_sep_19_3 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)) :=
  not_derivU_of_checkConf (M := ⟨2, [(1, 0)], [(1, 0)], [0], []⟩) (w := 1) (by decide) (by decide)

/-- `r19 ⊬ r4`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬◯⊥) ∨ ◯⊥. -/
theorem cf_sep_19_4 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r19 ⊬ r5`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ¬(¬◯⊥). -/
theorem cf_sep_19_5 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL)) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r19 ⊬ r6`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬(¬◯⊥)) ∨ (¬◯⊥). -/
theorem cf_sep_19_6 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r19 ⊬ r7`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ◯(¬◯⊥). -/
theorem cf_sep_19_7 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r8 ⊬ r19`: [(¬(¬◯⊥)) ⊃ ◯⊥] ⊬ (◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥). -/
theorem cf_sep_8_19 :
    ¬ ConfluentU.DerivU [((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

/-- `r19 ⊬ r9`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬(¬◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_19_9 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r10 ⊬ r19`: [((¬(¬◯⊥)) ⊃ ◯⊥) ∨ (¬(¬◯⊥))] ⊬ (◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥). -/
theorem cf_sep_10_19 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r19 ⊬ r11`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_19_11 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r19 ⊬ r12`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ((¬(¬◯⊥)) ⊃ ◯⊥) ⊃ ◯(¬◯⊥). -/
theorem cf_sep_19_12 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r19 ⊬ r13`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ((¬(¬◯⊥)) ⊃ ◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_19_13 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r19 ⊬ r14`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_19_14 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r19 ⊬ r15`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_19_15 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r19 ⊬ r16`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_19_16 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r19 ⊬ r17`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬(¬◯⊥)) ∨ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)). -/
theorem cf_sep_19_17 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r19 ⊬ r18`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ((¬(¬◯⊥)) ∨ ◯(¬◯⊥)). -/
theorem cf_sep_19_18 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r20 ⊬ r0`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ⊥. -/
theorem cf_sep_20_0 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (PLLFormula.falsePLL) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r1 ⊬ r20`: [⊤] ⊬ (◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥)). -/
theorem cf_sep_1_20 :
    ¬ ConfluentU.DerivU [(PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

/-- `r20 ⊬ r2`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ◯⊥. -/
theorem cf_sep_20_2 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] ((PLLFormula.falsePLL.somehow)) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r20 ⊬ r3`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ¬◯⊥. -/
theorem cf_sep_20_3 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)) :=
  not_derivU_of_checkConf (M := ⟨2, [(1, 0)], [(1, 0)], [0], []⟩) (w := 1) (by decide) (by decide)

/-- `r20 ⊬ r4`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ (¬◯⊥) ∨ ◯⊥. -/
theorem cf_sep_20_4 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r20 ⊬ r5`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ¬(¬◯⊥). -/
theorem cf_sep_20_5 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL)) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r20 ⊬ r6`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ (¬(¬◯⊥)) ∨ (¬◯⊥). -/
theorem cf_sep_20_6 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r20 ⊬ r7`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ◯(¬◯⊥). -/
theorem cf_sep_20_7 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r20 ⊬ r8`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ (¬(¬◯⊥)) ⊃ ◯⊥. -/
theorem cf_sep_20_8 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r20 ⊬ r9`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ (¬(¬◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_20_9 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r10 ⊬ r20`: [((¬(¬◯⊥)) ⊃ ◯⊥) ∨ (¬(¬◯⊥))] ⊬ (◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥)). -/
theorem cf_sep_10_20 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

/-- `r20 ⊬ r11`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_20_11 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r20 ⊬ r12`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ((¬(¬◯⊥)) ⊃ ◯⊥) ⊃ ◯(¬◯⊥). -/
theorem cf_sep_20_12 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r20 ⊬ r13`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ((¬(¬◯⊥)) ⊃ ◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_20_13 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r20 ⊬ r14`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ ((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_20_14 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r20 ⊬ r15`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ (◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_20_15 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r20 ⊬ r16`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_20_16 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r20 ⊬ r17`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ (¬(¬◯⊥)) ∨ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)). -/
theorem cf_sep_20_17 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r20 ⊬ r18`: [(◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ((¬(¬◯⊥)) ∨ (¬◯⊥))] ⊬ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ((¬(¬◯⊥)) ∨ ◯(¬◯⊥)). -/
theorem cf_sep_20_18 :
    ¬ ConfluentU.DerivU [(((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)))] (((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r21 ⊬ r0`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ⊥. -/
theorem cf_sep_21_0 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (PLLFormula.falsePLL) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r1 ⊬ r21`: [⊤] ⊬ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥). -/
theorem cf_sep_1_21 :
    ¬ ConfluentU.DerivU [(PLLFormula.falsePLL.ifThen PLLFormula.falsePLL)] (((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨4, [(2, 1), (3, 0), (3, 1), (3, 2)], [(2, 1)], [1], []⟩) (w := 3) (by decide) (by decide)

/-- `r21 ⊬ r2`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ◯⊥. -/
theorem cf_sep_21_2 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((PLLFormula.falsePLL.somehow)) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r21 ⊬ r3`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ¬◯⊥. -/
theorem cf_sep_21_3 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL)) :=
  not_derivU_of_checkConf (M := ⟨2, [(1, 0)], [(1, 0)], [0], []⟩) (w := 1) (by decide) (by decide)

/-- `r21 ⊬ r4`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬◯⊥) ∨ ◯⊥. -/
theorem cf_sep_21_4 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r21 ⊬ r5`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ¬(¬◯⊥). -/
theorem cf_sep_21_5 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL)) :=
  not_derivU_of_checkConf (M := ⟨1, [], [], [], []⟩) (w := 0) (by decide) (by decide)

/-- `r21 ⊬ r6`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬(¬◯⊥)) ∨ (¬◯⊥). -/
theorem cf_sep_21_6 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or ((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r21 ⊬ r7`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ◯(¬◯⊥). -/
theorem cf_sep_21_7 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r21 ⊬ r8`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬(¬◯⊥)) ⊃ ◯⊥. -/
theorem cf_sep_21_8 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r21 ⊬ r9`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬(¬◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_21_9 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r21 ⊬ r10`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ((¬(¬◯⊥)) ⊃ ◯⊥) ∨ (¬(¬◯⊥)). -/
theorem cf_sep_21_10 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r21 ⊬ r11`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_21_11 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r21 ⊬ r12`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ((¬(¬◯⊥)) ⊃ ◯⊥) ⊃ ◯(¬◯⊥). -/
theorem cf_sep_21_12 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r21 ⊬ r13`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ((¬(¬◯⊥)) ⊃ ◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_21_13 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).ifThen (PLLFormula.falsePLL.somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r21 ⊬ r14`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ ((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥). -/
theorem cf_sep_21_14 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow)))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r21 ⊬ r15`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (◯(¬◯⊥) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_21_15 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] ((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], [(1, 2), (4, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- `r21 ⊬ r16`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ◯(¬◯⊥). -/
theorem cf_sep_21_16 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))) :=
  not_derivU_of_checkConf (M := ⟨3, [(1, 0), (2, 0), (2, 1)], [(1, 0)], [0], []⟩) (w := 2) (by decide) (by decide)

/-- `r21 ⊬ r17`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (¬(¬◯⊥)) ∨ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)). -/
theorem cf_sep_21_17 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))))) :=
  not_derivU_of_checkConf (M := ⟨4, [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2)], [(2, 0), (3, 1)], [0], []⟩) (w := 3) (by decide) (by decide)

/-- `r21 ⊬ r18`: [(((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ⊃ ◯(¬◯⊥)] ⊬ (((¬(¬◯⊥)) ∨ ◯(¬◯⊥)) ⊃ ((¬◯⊥) ∨ ◯⊥)) ∨ ((¬(¬◯⊥)) ∨ ◯(¬◯⊥)). -/
theorem cf_sep_21_18 :
    ¬ ConfluentU.DerivU [((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow))] (((((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)).ifThen (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).or (PLLFormula.falsePLL.somehow))).or ((((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).ifThen PLLFormula.falsePLL).or (((PLLFormula.falsePLL.somehow).ifThen PLLFormula.falsePLL).somehow)))) :=
  not_derivU_of_checkConf (M := ⟨5, [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], [(2, 3)], [3], []⟩) (w := 0) (by decide) (by decide)

/-- info: 'PLLND.RNC.CF.cf_sep_19_0' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms cf_sep_19_0

/-- info: 'PLLND.RNC.CF.cf_sep_21_18' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms cf_sep_21_18

end CF
end RNC
end PLLND
