import wip.postui

/-!
# REFUTED: `CoverConj`.  The substitution-cover method fails on the `∃`-side too

`wip/postui.lean` reduces last-variable `∃p` for PLL to the substitution
cover conjecture

    CoverConj :  ∀ φ with atoms ⊆ {p}, ∃ a finite list S of variable-free θ,
                 φ ⊢ ⋁_{θ ∈ S} φ[p := θ]

and REFUTES the `∀`-side analogue `MeetCoverConj` at `p ∨ ¬p`.  This file
refutes `CoverConj` itself, at

    φ★ = ((◯⊥ ⊃ p) ⊃ (◯⊥ ∧ p)) ∧ ¬¬p .

So the cover method is incomplete on BOTH sides.  As with `MeetCoverConj`,
this refutes the METHOD, not uniform interpolation: whether `∃p.φ★`
exists is left OPEN (`phiStar_nnbox` shows the only candidate below
`¬¬◯⊥`, and `phiStar_not_oBot` shows it is not `◯⊥`).

## The countermodel

    M4 :  0 ⊑ 1 ⊑ 2 ⊑ 3,   Rₘ = id ∪ {(x,3) : x ≠ 0},   F = {3},
          V(a) = {2,3}

`◯⊥` holds exactly on `{1,2,3}` (world `0`'s only `Rₘ`-successor is `0`,
which is not fallible; every other world sees the fallible top `3`), and
`p` holds exactly on `{2,3}`.  So *the valuation of `p` is squeezed
strictly between `‖⊥‖ = {3}` and `‖◯⊥‖ = {1,2,3}`*, and — the crux —

    `M4_swap` : worlds `1` and `2` satisfy exactly the same VARIABLE-FREE
    formulas,

so no variable-free `θ` has truth set `{2,3}`: the valuation of `p` is
undefinable.  `φ★` detects this:

* `¬¬p` fails at `0` whenever `θ` is `⊥`-like above `0` (only the
  fallible world forces it);
* `(◯⊥ ⊃ θ) ⊃ (◯⊥ ∧ θ)` fails at `0` whenever `θ` holds at `1` — for then
  `◯⊥ ⊃ θ` holds at `0` (the only `◯⊥`-worlds are `1, 2, 3`), and the
  implication would force `◯⊥` at `0`, which is false.

The two cases are exhaustive by `M4_swap` plus heredity, so EVERY
variable-free instance `φ★[p := θ]` fails at `0` while `φ★` itself holds
there.  Soundness turns that into `¬ HasCover φ★`.

## The place of the counterexample in the method

The two cases the method DOES handle in general are isolated here as
`force_inst_top` (`w ⊩ p` ⟹ `w ⊩ φ[p := ⊤]`) and `force_inst_bot`
(`p` only fallibly true above `w` ⟹ `w ⊩ φ[p := ⊥]`); together they are
the whole content of the `◯`-free proof `hasCover_of_boxFree`, whose
extra ingredient was two-valuedness.  `φ★` lives in the remaining
INTERMEDIATE case, and `M4_intermediate` pins that: at the root of `M4`
the atom `p` is false, yet true at the non-fallible world `2`.

Contrast `phiMix = (p ⊃ ◯⊥) ∧ ¬¬p` of `postui.lean`, which HAS the
one-element cover `[◯⊥]`.  `phiStar_to_phiMix` shows `φ★ ⊢ phiMix`: the
extra clause `(◯⊥ ⊃ p) ⊃ ◯⊥` is exactly what kills the substitution
`θ = ◯⊥`, and every substitution above it, while `¬¬p` kills everything
below.

## Where `φ★` came from, and what is open

`wip/coverprobe.lean` searched, for every rooted constraint model with
at most five worlds and every valuation `U` of `p` that is NOT a
variable-free truth set, the subalgebra of the product
`A_U × ∏_{d ∈ D} A_d` generated by `p ↦ (U, d₁, …, d_k)` — that is, all
one-variable formulas up to semantic equivalence — for one that is true
at the root under `U` and false at the root under every variable-free
`d`.  No hit at three worlds; four at four worlds (this `φ★` and one
variant); 2548 at five worlds, closure never capped.  The phenomenon is
generic.

§6′ and §6″ record the follow-up.  `∃p.φ★`, if it exists, is `¬¬◯⊥`
unless something strictly between shows up, and
`postInterpPhiStarIsNNBox_iff` reduces the claim to MINIMALITY alone.
`M3v_phiStar_fails` shows the cheap route to that is dead: the
three-world `M3` frame forces `¬¬◯⊥` at its root yet admits no valuation
of `p` making `φ★` true there, so a proof must STRETCH a model (`M4` is
`M3` with the `◯⊥`-floor split in two), on the pattern of `postui`'s
doubling `dbl`.  `wip/interpprobe.lean` supplies the evidence FOR the
candidate: over all rooted models with at most five worlds the
variable-free root TYPES realised at `¬¬◯⊥`-roots and at `φ★`-roots
coincide exactly.

Everything here is proved; there are no sorries.
-/

open PLLFormula

namespace PLLND
namespace RNEmbed

open SemUI PLLND.SemUI.RND
open PLLND.LaxInfinite (atomFree)

/-! ## 0.  The semantic form of a cover

`HasCover` is a derivability statement; soundness and the finite model
property turn it into a statement about the VALUATION of `p`. -/

/-- Forcing of a finite disjunction: some disjunct is forced, or the
world is fallible (`bigOr [] = ⊥`). -/
theorem force_bigOr {C : ConstraintModel} {w : C.W} :
    ∀ {L : List PLLFormula}, C.force w (bigOr L) →
      (∃ A ∈ L, C.force w A) ∨ C.force w PLLFormula.falsePLL
  | [], h => Or.inr h
  | A :: L, h => by
      rcases (h : C.force w A ∨ C.force w (bigOr L)) with h1 | h2
      · exact Or.inl ⟨A, .head _, h1⟩
      · rcases force_bigOr h2 with ⟨B, hB, hf⟩ | hf
        · exact Or.inl ⟨B, .tail _ hB, hf⟩
        · exact Or.inr hf

/-- A forced disjunct forces the disjunction. -/
theorem force_bigOr_of_mem {C : ConstraintModel} {w : C.W} {A : PLLFormula} :
    ∀ {L : List PLLFormula}, A ∈ L → C.force w A → C.force w (bigOr L)
  | [], h, _ => absurd h (by simp)
  | B :: L, h, hf => by
      rcases List.mem_cons.mp h with rfl | h'
      · exact Or.inl hf
      · exact Or.inr (force_bigOr_of_mem h' hf)

/-- **The semantic form of the cover `S`**: at every world forcing `φ`,
some instance `φ[p := θ]`, `θ ∈ S`, is forced (or the world is
fallible, where everything is forced anyway). -/
def SemCover (φ : PLLFormula) (S : List PLLFormula) : Prop :=
  ∀ (C : ConstraintModel) (w : C.W), C.force w φ →
    (∃ θ ∈ S, C.force w (inst θ φ)) ∨ C.force w PLLFormula.falsePLL

theorem semCover_of_deriv {φ : PLLFormula} {S : List PLLFormula}
    (h : Deriv [φ] (bigOr (instList S φ))) : SemCover φ S := by
  rintro C w hw
  obtain ⟨d⟩ := h
  have hforce : C.force w (bigOr (instList S φ)) :=
    soundness d C w (fun ψ hψ => by
      have e : ψ = φ := by
        cases hψ with
        | head => rfl
        | tail _ h => cases h
      subst e; exact hw)
  rcases force_bigOr hforce with ⟨A, hA, hfA⟩ | hf
  · obtain ⟨θ, hθ, rfl⟩ := mem_instList hA
    exact Or.inl ⟨θ, hθ, hfA⟩
  · exact Or.inr hf

theorem deriv_of_semCover {φ : PLLFormula} {S : List PLLFormula}
    (h : SemCover φ S) : Deriv [φ] (bigOr (instList S φ)) := by
  classical
  by_contra hcon
  obtain ⟨C, -, v, hv, hnv⟩ := countermodel_of_not_deriv hcon
  rcases h C v hv with ⟨θ, hθ, hf⟩ | hbot
  · exact hnv (force_bigOr_of_mem (List.mem_map.mpr ⟨θ, hθ, rfl⟩) hf)
  · exact hnv (C.force_of_fallible hbot)

/-- **The cover conjecture is a statement about valuations.** -/
theorem hasCover_iff_semCover {φ : PLLFormula} :
    HasCover φ ↔ ∃ S : List PLLFormula, (∀ θ ∈ S, atomFree θ = true) ∧ SemCover φ S :=
  ⟨fun ⟨S, hS, hd⟩ => ⟨S, hS, semCover_of_deriv hd⟩,
   fun ⟨S, hS, hs⟩ => ⟨S, hS, deriv_of_semCover hs⟩⟩

/-- **The refutation tool.**  One world forcing `φ` at which NO
variable-free instance is forced refutes every cover at once. -/
theorem not_hasCover_of_model {φ : PLLFormula} (C : ConstraintModel) (w : C.W)
    (hw : C.force w φ) (hwF : ¬ C.force w PLLFormula.falsePLL)
    (hno : ∀ θ : PLLFormula, atomFree θ = true → ¬ C.force w (inst θ φ)) :
    ¬ HasCover φ := by
  rintro ⟨S, hS, hd⟩
  rcases semCover_of_deriv hd C w hw with ⟨θ, hθ, hf⟩ | hbot
  · exact hno θ (hS θ hθ) hf
  · exact hwF hbot

/-! ## 1.  The two cases the method does handle

These are the general (not `◯`-free) content of `hasCover_of_boxFree`:
where the valuation of `p` is definable by `⊤` or by `⊥` above `w`, the
corresponding instance is forced.  A counterexample must therefore live
in the INTERMEDIATE case. -/

/-- **Top case.**  If `p` holds at `w` it holds throughout the cone, so
`⊤` may be substituted. -/
theorem force_inst_top {C : ConstraintModel} {w : C.W} {φ : PLLFormula}
    (hp : C.force w (PLLFormula.prop pv)) (hφ : C.force w φ) :
    C.force w (inst truePLL φ) :=
  (force_inst_congr (θ := truePLL)
    (fun v hv => ⟨fun _ _ _ hbot => hbot, fun _ => C.force_hered hv hp⟩)
    φ w (C.refl_i w)).mp hφ

/-- **Bottom case.**  If `p` holds only at fallible worlds of the cone,
`⊥` may be substituted. -/
theorem force_inst_bot {C : ConstraintModel} {w : C.W} {φ : PLLFormula}
    (hp : ∀ v : C.W, C.Ri w v → C.force v (PLLFormula.prop pv) →
      C.force v PLLFormula.falsePLL)
    (hφ : C.force w φ) : C.force w (inst PLLFormula.falsePLL φ) :=
  (force_inst_congr (θ := PLLFormula.falsePLL)
    (fun v hv => ⟨hp v hv, fun hbot => C.force_of_fallible hbot⟩)
    φ w (C.refl_i w)).mp hφ

/-! ## 2.  The model `M4` -/

/-- `Rₘ` of `M4`: the identity, plus an edge from every non-root world to
the fallible top. -/
def Rm4 (x y : Fin 4) : Prop := x = y ∨ (x ≠ 0 ∧ y = 3)

instance (x y : Fin 4) : Decidable (Rm4 x y) := by unfold Rm4; infer_instance

theorem Rm4_refl : ∀ x : Fin 4, Rm4 x x := by decide
theorem Rm4_trans : ∀ x y z : Fin 4, Rm4 x y → Rm4 y z → Rm4 x z := by decide
theorem Rm4_sub : ∀ x y : Fin 4, Rm4 x y → x ≤ y := by decide
theorem Rm4_top : ∀ x : Fin 4, x ≠ 0 → Rm4 x 3 := by decide
theorem Rm4_from_three : ∀ u : Fin 4, Rm4 3 u → u = 3 := by decide
theorem Rm4_from_zero : ∀ u : Fin 4, Rm4 0 u → u = 0 := by decide

theorem Fin4_hered_F : ∀ x y : Fin 4, x ≤ y → x = 3 → y = 3 := by decide
theorem Fin4_hered_V : ∀ x y : Fin 4, x ≤ y → 2 ≤ x → 2 ≤ y := by decide
theorem Fin4_full : ∀ x : Fin 4, x = 3 → 2 ≤ x := by decide
theorem Fin4_le_three : ∀ x : Fin 4, x ≤ 3 := by decide
theorem Fin4_ne_zero : ∀ x v : Fin 4, 1 ≤ x → x ≤ v → v ≠ 0 := by decide
theorem Fin4_not_two : ∀ v : Fin 4, ¬ (2 ≤ v) → v ≤ 1 := by decide
theorem Fin4_ne_three : ∀ v : Fin 4, ¬ (v = 3) → v ≤ 2 := by decide
theorem Fin4_one_cases : ∀ u : Fin 4, 1 ≤ u → u = 1 ∨ 2 ≤ u := by decide
theorem Fin4_cases : ∀ u : Fin 4, u = 0 ∨ u = 1 ∨ u = 2 ∨ u = 3 := by decide

/-- The four-world countermodel: a chain, fallible at the top, with the
modal relation skipping world `2` from world `1`. -/
@[reducible] def M4 : ConstraintModel where
  W := Fin 4
  Ri x y := x ≤ y
  Rm := Rm4
  F := {x | x = 3}
  V _ := {x | 2 ≤ x}
  refl_i x := le_refl x
  trans_i {x y z} h1 h2 := le_trans h1 h2
  refl_m := Rm4_refl
  trans_m {x y z} h1 h2 := Rm4_trans x y z h1 h2
  sub_mi {x y} h := Rm4_sub x y h
  hered_F {x y} h hx := Fin4_hered_F x y h hx
  hered_V {_ x y} h hx := Fin4_hered_V x y h hx
  full_F {_ x} hx := Fin4_full x hx

/-- `◯⊥` holds from world `1` upwards. -/
theorem M4_oBot_of_one : ∀ x : Fin 4, 1 ≤ x → M4.force x oBot := by
  intro x hx v hv
  exact ⟨3, Rm4_top v (Fin4_ne_zero x v hx hv), rfl⟩

/-- `◯⊥` fails at the root: `0`'s only `Rₘ`-successor is `0`. -/
theorem M4_not_oBot_zero : ¬ M4.force (0 : Fin 4) oBot := by
  intro h
  obtain ⟨u, hu, hf⟩ := h 0 (le_refl _)
  have hu0 : u = 0 := Rm4_from_zero u hu
  subst hu0
  have hf' : (0 : Fin 4) = 3 := hf
  exact absurd hf' (by decide)

/-- Above world `1` the `◯`-clause collapses to truth at the top. -/
theorem M4_box_iff {A : PLLFormula} {x : Fin 4} (hx : 1 ≤ x) :
    M4.force x A.somehow ↔ M4.force (3 : Fin 4) A := by
  constructor
  · intro h
    obtain ⟨u, hu, hA⟩ := h 3 (Fin4_le_three x)
    have hu3 : u = 3 := Rm4_from_three u hu
    subst hu3
    exact hA
  · intro h v hv
    exact ⟨3, Rm4_top v (Fin4_ne_zero x v hx hv), h⟩

/-- **The crux: worlds `1` and `2` are indistinguishable to the
variable-free fragment.**  (World `1` sees world `2` intuitionistically,
but not modally, and the `◯`-clause above `1` only reports the top.) -/
theorem M4_swap : ∀ {A : PLLFormula}, atomFree A = true →
    (M4.force (1 : Fin 4) A ↔ M4.force (2 : Fin 4) A) := by
  intro A
  induction A with
  | prop a => intro h; exact absurd h (by simp [atomFree])
  | falsePLL =>
      intro _
      constructor
      · intro h
        have h' : (1 : Fin 4) = 3 := h
        exact absurd h' (by decide)
      · intro h
        have h' : (2 : Fin 4) = 3 := h
        exact absurd h' (by decide)
  | and A B ihA ihB =>
      intro h
      have h' : atomFree A = true ∧ atomFree B = true := by
        simpa [atomFree, Bool.and_eq_true] using h
      exact and_congr (ihA h'.1) (ihB h'.2)
  | or A B ihA ihB =>
      intro h
      have h' : atomFree A = true ∧ atomFree B = true := by
        simpa [atomFree, Bool.and_eq_true] using h
      exact or_congr (ihA h'.1) (ihB h'.2)
  | ifThen A B ihA ihB =>
      intro h
      have h' : atomFree A = true ∧ atomFree B = true := by
        simpa [atomFree, Bool.and_eq_true] using h
      constructor
      · intro hh u hu hA
        exact hh u (le_trans (by decide : (1 : Fin 4) ≤ 2) hu) hA
      · intro hh u hu hA
        rcases Fin4_one_cases u hu with rfl | hu2
        · exact (ihB h'.2).mpr (hh 2 (le_refl (2 : Fin 4)) ((ihA h'.1).mp hA))
        · exact hh u hu2 hA
  | somehow A _ =>
      intro _
      rw [M4_box_iff (by decide : (1 : Fin 4) ≤ 1),
          M4_box_iff (by decide : (1 : Fin 4) ≤ 2)]

/-- The counterexample is in the INTERMEDIATE case: `p` fails at the
root, but holds at the non-fallible world `2`. -/
theorem M4_intermediate :
    ¬ M4.force (0 : Fin 4) (PLLFormula.prop pv) ∧
      M4.force (2 : Fin 4) (PLLFormula.prop pv) ∧
      ¬ M4.force (2 : Fin 4) PLLFormula.falsePLL :=
  ⟨by
     intro h
     have h' : (2 : Fin 4) ≤ 0 := h
     exact absurd h' (by decide),
   (by decide : (2 : Fin 4) ≤ 2),
   by
     intro h
     have h' : (2 : Fin 4) = 3 := h
     exact absurd h' (by decide)⟩

/-! ## 3.  The formula `φ★`, and its truth at the root -/

/-- **`φ★ = ((◯⊥ ⊃ p) ⊃ (◯⊥ ∧ p)) ∧ ¬¬p`.** -/
def phiStar : PLLFormula :=
  ((oBot.ifThen (PLLFormula.prop pv)).ifThen (oBot.and (PLLFormula.prop pv))).and
    (nt (nt (PLLFormula.prop pv)))

theorem phiStar_onlyPv : onlyPv phiStar = true := by decide

/-- `φ★` holds at the root of `M4`. -/
theorem M4_force_phiStar : M4.force (0 : Fin 4) phiStar := by
  constructor
  · -- `(◯⊥ ⊃ p) ⊃ (◯⊥ ∧ p)`: a world forcing `◯⊥ ⊃ p` is `≥ 2`
    intro v _ hvimp
    have hv2 : (2 : Fin 4) ≤ v := by
      by_contra hcon
      have hv1 : v ≤ 1 := Fin4_not_two v hcon
      have h1p : M4.force (1 : Fin 4) (PLLFormula.prop pv) :=
        hvimp 1 hv1 (M4_oBot_of_one 1 (le_refl (1 : Fin 4)))
      have h1p' : (2 : Fin 4) ≤ 1 := h1p
      exact absurd h1p' (by decide)
    exact ⟨M4_oBot_of_one v (le_trans (by decide : (1 : Fin 4) ≤ 2) hv2), hv2⟩
  · -- `¬¬p`: only the fallible world forces `¬p`
    intro v _ hvn
    by_contra hcon
    have hv2 : v ≤ 2 := Fin4_ne_three v hcon
    have hcon' : (2 : Fin 4) = 3 := hvn 2 hv2 (by decide : (2 : Fin 4) ≤ 2)
    exact absurd hcon' (by decide)

/-! ## 4.  Every variable-free instance fails at the root -/

theorem inst_phiStar (θ : PLLFormula) :
    inst θ phiStar
      = ((oBot.ifThen θ).ifThen (oBot.and θ)).and ((θ.ifThen .falsePLL).ifThen .falsePLL) := by
  show (((inst θ oBot).ifThen (inst θ (PLLFormula.prop pv))).ifThen
      ((inst θ oBot).and (inst θ (PLLFormula.prop pv)))).and
      (((inst θ (PLLFormula.prop pv)).ifThen (inst θ PLLFormula.falsePLL)).ifThen
        (inst θ PLLFormula.falsePLL)) = _
  rw [inst_var_eq, inst_atomFree_eq θ (show atomFree oBot = true from rfl)]
  rfl

/-- **No variable-free instance of `φ★` is forced at the root of `M4`.**
Either `θ` holds at world `1` — and then `◯⊥ ⊃ θ` holds at `0`, so the
first conjunct would force `◯⊥` at `0` — or it does not, and then `θ`
holds only at the fallible world, so `¬θ` holds at `0` and `¬¬θ` fails
there.  `M4_swap` is what makes the two cases exhaustive. -/
theorem M4_inst_fails {θ : PLLFormula} (hθ : atomFree θ = true) :
    ¬ M4.force (0 : Fin 4) (inst θ phiStar) := by
  classical
  rw [inst_phiStar θ]
  rintro ⟨h1, h2⟩
  by_cases hone : M4.force (1 : Fin 4) θ
  · have htwo : M4.force (2 : Fin 4) θ := (M4_swap hθ).mp hone
    have hthree : M4.force (3 : Fin 4) θ :=
      M4.force_of_fallible (show (3 : Fin 4) ∈ M4.F from rfl)
    have himp : M4.force (0 : Fin 4) (oBot.ifThen θ) := by
      intro u _ hu
      rcases Fin4_cases u with rfl | rfl | rfl | rfl
      · exact absurd hu M4_not_oBot_zero
      · exact hone
      · exact htwo
      · exact hthree
    exact M4_not_oBot_zero (h1 0 (le_refl (0 : Fin 4)) himp).1
  · have h0 : ¬ M4.force (0 : Fin 4) θ := fun h =>
      hone (M4.force_hered (show M4.Ri 0 1 by decide) h)
    have htwo : ¬ M4.force (2 : Fin 4) θ := fun h => hone ((M4_swap hθ).mpr h)
    have hneg : M4.force (0 : Fin 4) (θ.ifThen .falsePLL) := by
      intro u _ hu
      rcases Fin4_cases u with rfl | rfl | rfl | rfl
      · exact absurd hu h0
      · exact absurd hu hone
      · exact absurd hu htwo
      · rfl
    have hcon' : (0 : Fin 4) = 3 := h2 0 (le_refl (0 : Fin 4)) hneg
    exact absurd hcon' (by decide)

/-! ## 5.  The refutation -/

/-- **`φ★` has NO finite variable-free substitution cover.** -/
theorem phiStar_no_cover : ¬ HasCover phiStar :=
  not_hasCover_of_model M4 0 M4_force_phiStar
    (by
      intro h
      have h' : (0 : Fin 4) = 3 := h
      exact absurd h' (by decide))
    (fun _ hθ => M4_inst_fails hθ)

/-- **REFUTED: `CoverConj`.**  Not every one-variable formula has a
variable-free substitution cover; the `∃`-side of the substitution
method is incomplete, exactly as `meetCoverConj_false` shows for the
`∀`-side.  Uniform interpolation itself is untouched. -/
theorem coverConj_false : ¬ CoverConj :=
  fun h => phiStar_no_cover (h phiStar phiStar_onlyPv)

/-! ## 6.  What survives: the interpolant of `φ★` is squeezed

`φ★ ⊢ ¬¬◯⊥` but `φ★ ⊬ ◯⊥`, and `φ★ ⊢ phiMix`, whose interpolant is
`¬¬◯⊥` (`exists_phiMix`).  So if `∃p.φ★` exists it lies between the join
of the instances and `¬¬◯⊥`; the cover method cannot produce it. -/

/-- `φ★ ⊢ ¬¬◯⊥`: assume `¬◯⊥`; then `◯⊥ ⊃ p` holds vacuously, so the
first conjunct yields `◯⊥ ∧ p`, contradiction. -/
theorem phiStar_nnbox : Deriv [phiStar] (nt (nt oBot)) := by
  refine Deriv.impIntro ?_
  have hp : Deriv [nt oBot, phiStar] (oBot.ifThen (PLLFormula.prop pv)) :=
    Deriv.impIntro (Deriv.falsoElim _
      (Deriv.impElim (Deriv.iden (.tail _ (.head _))) (Deriv.iden (.head _))))
  have hbox : Deriv [nt oBot, phiStar] (oBot.and (PLLFormula.prop pv)) :=
    Deriv.impElim (Deriv.andElim1 (Deriv.iden (.tail _ (.head _)))) hp
  exact Deriv.impElim (Deriv.iden (.head _)) (Deriv.andElim1 hbox)

/-- `φ★ ⊢ phiMix`: the counterexample strengthens `postui`'s `phiMix`,
which has the one-element cover `[◯⊥]`.  The added clause
`(◯⊥ ⊃ p) ⊃ ◯⊥` is what destroys that cover. -/
theorem phiStar_to_phiMix : Deriv [phiStar] phiMix := by
  refine Deriv.andIntro ?_ (Deriv.andElim2 (Deriv.iden (.head _)))
  refine Deriv.impIntro ?_
  have hp : Deriv [PLLFormula.prop pv, phiStar] (oBot.ifThen (PLLFormula.prop pv)) :=
    Deriv.impIntro (Deriv.iden (.tail _ (.head _)))
  exact Deriv.andElim1 (Deriv.impElim
    (Deriv.andElim1 (Deriv.iden (.tail _ (.head _)))) hp)

/-- `φ★ ⊬ ◯⊥` — the root of `M4` forces `φ★` and not `◯⊥`. -/
theorem phiStar_not_oBot : ¬ Deriv [phiStar] oBot := by
  rintro ⟨d⟩
  refine M4_not_oBot_zero (soundness d M4 0 ?_)
  intro ψ hψ
  have e : ψ = phiStar := by
    cases hψ with
    | head => rfl
    | tail _ h => cases h
  subst e
  exact M4_force_phiStar

/-- `φ★` is consistent. -/
theorem phiStar_consistent : ¬ Deriv [phiStar] PLLFormula.falsePLL := by
  rintro ⟨d⟩
  have hs := soundness d M4 0 (fun ψ hψ => by
    have e : ψ = phiStar := by
      cases hψ with
      | head => rfl
      | tail _ h => cases h
    subst e
    exact M4_force_phiStar)
  have hs' : (0 : Fin 4) = 3 := hs
  exact absurd hs' (by decide)

/-! ## 6′.  The revaluation route to `∃p.φ★ = ¬¬◯⊥` is dead

`¬¬◯⊥` is the natural candidate for `∃p.φ★`, and by
`postInterpPhiStarIsNNBox_iff` below only MINIMALITY is left to prove:
every variable-free `χ` with `φ★ ⊢ χ` should follow from `¬¬◯⊥`.  By the
finite model property that asks, for each finite `¬¬◯⊥`-world refuting
`χ`, for SOME model with a `φ★`-world refuting `χ`.  The cheapest
possible construction — keep the model, re-value `p` — does NOT work:
the three-world frame `M3` of `postui.lean` forces `¬¬◯⊥` at its root
(`M3v_root_nnbox`) and yet `φ★` fails there under EVERY valuation of `p`
(`M3v_phiStar_fails`).  `M4` is exactly `M3` with the `◯⊥`-floor split
in two, which is what makes room for an undefinable `p`; so a proof must
STRETCH the model, not re-value it. -/

theorem Fin3_all_cases : ∀ u : Fin 3, u = 0 ∨ u = 1 ∨ u = 2 := by decide

/-- The `M3` frame (`0 ⊑ 1 ⊑ 2`, `Rₘ = id ∪ {(1,2)}`, `F = {2}`) with the
valuation of `p` an ARBITRARY up-set containing the fallible world. -/
@[reducible] def M3v (U : Set (Fin 3))
    (hU : ∀ x y : Fin 3, x ≤ y → x ∈ U → y ∈ U)
    (hUF : ∀ x : Fin 3, x = 2 → x ∈ U) : ConstraintModel where
  W := Fin 3
  Ri x y := x ≤ y
  Rm := Rm3
  F := {x | x = 2}
  V _ := U
  refl_i x := le_refl x
  trans_i {x y z} h1 h2 := le_trans h1 h2
  refl_m := Rm3_refl
  trans_m {x y z} h1 h2 := Rm3_trans x y z h1 h2
  sub_mi {x y} h := Rm3_sub x y h
  hered_F {x y} h hx := Fin3_hered_F x y h hx
  hered_V {_ x y} h hx := hU x y h hx
  full_F {_ x} hx := hUF x hx

theorem M3v_oBot_of_one (U : Set (Fin 3)) (hU : ∀ x y : Fin 3, x ≤ y → x ∈ U → y ∈ U)
    (hUF : ∀ x : Fin 3, x = 2 → x ∈ U) {x : Fin 3} (h : 1 ≤ x) :
    (M3v U hU hUF).force x oBot := by
  intro v hv
  exact ⟨2, Rm3_to_two v (le_trans h hv), rfl⟩

theorem M3v_not_oBot_zero (U : Set (Fin 3))
    (hU : ∀ x y : Fin 3, x ≤ y → x ∈ U → y ∈ U)
    (hUF : ∀ x : Fin 3, x = 2 → x ∈ U) :
    ¬ (M3v U hU hUF).force (0 : Fin 3) oBot := by
  intro h
  obtain ⟨u, hu, hf⟩ := h 0 (le_refl _)
  have hu2 : u = 2 := hf
  subst hu2
  have hu' : Rm3 0 2 := hu
  exact absurd hu' (by decide)

/-- The root of the `M3` frame forces `¬¬◯⊥`, whatever `p` means. -/
theorem M3v_root_nnbox (U : Set (Fin 3))
    (hU : ∀ x y : Fin 3, x ≤ y → x ∈ U → y ∈ U)
    (hUF : ∀ x : Fin 3, x = 2 → x ∈ U) :
    (M3v U hU hUF).force (0 : Fin 3) (nt (nt oBot)) := by
  intro v _ hvn
  by_contra hcon
  have hv1 : v ≤ 1 := Fin3_ne_two v hcon
  have hbad : (1 : Fin 3) = 2 :=
    hvn 1 hv1 (M3v_oBot_of_one U hU hUF (le_refl (1 : Fin 3)))
  exact absurd hbad (by decide)

/-- **`φ★` fails at the root of the `M3` frame under EVERY valuation of
`p`.**  (If `p` reaches world `1` it covers all of `‖◯⊥‖ = {1,2}`, so
`◯⊥ ⊃ p` holds at the root and the first conjunct would force `◯⊥`
there; if it does not, `p` lives only on the fallible world and `¬¬p`
fails.)  There is no room in three worlds for a `p` strictly between
`⊥` and `◯⊥`. -/
theorem M3v_phiStar_fails (U : Set (Fin 3))
    (hU : ∀ x y : Fin 3, x ≤ y → x ∈ U → y ∈ U)
    (hUF : ∀ x : Fin 3, x = 2 → x ∈ U) :
    ¬ (M3v U hU hUF).force (0 : Fin 3) phiStar := by
  classical
  rintro ⟨h1, h2⟩
  by_cases hone : (1 : Fin 3) ∈ U
  · have htwo : (2 : Fin 3) ∈ U := hU 1 2 (by decide) hone
    have himp : (M3v U hU hUF).force (0 : Fin 3)
        (oBot.ifThen (PLLFormula.prop pv)) := by
      intro u _ hu
      rcases Fin3_all_cases u with rfl | rfl | rfl
      · exact absurd hu (M3v_not_oBot_zero U hU hUF)
      · exact hone
      · exact htwo
    exact M3v_not_oBot_zero U hU hUF (h1 0 (le_refl (0 : Fin 3)) himp).1
  · have hzero : (0 : Fin 3) ∉ U := fun h => hone (hU 0 1 (by decide) h)
    have hneg : (M3v U hU hUF).force (0 : Fin 3) (nt (PLLFormula.prop pv)) := by
      intro u _ hu
      rcases Fin3_all_cases u with rfl | rfl | rfl
      · exact absurd hu hzero
      · exact absurd hu hone
      · rfl
    have hcon' : (0 : Fin 3) = 2 := h2 0 (le_refl (0 : Fin 3)) hneg
    exact absurd hcon' (by decide)

/-! ## 6″.  The open follow-up, statement-only -/

/-- **OPEN.**  Does `φ★` have a uniform post-interpolant over the
variable-free fragment at all?  `coverConj_false` says the substitution
method cannot answer this. -/
def PostInterpPhiStarExists : Prop := ∃ ψ, IsPostInterp phiStar ψ

/-- **OPEN.**  Is it `¬¬◯⊥`? -/
def PostInterpPhiStarIsNNBox : Prop := IsPostInterp phiStar (nt (nt oBot))

/-- The open question with its settled half removed: variable-freeness
and `φ★ ⊢ ¬¬◯⊥` are proved, so only MINIMALITY is at issue. -/
theorem postInterpPhiStarIsNNBox_iff :
    PostInterpPhiStarIsNNBox ↔
      ∀ χ, atomFree χ = true → Deriv [phiStar] χ → Deriv [nt (nt oBot)] χ :=
  ⟨fun h χ hχ hd => h.2.2 χ hχ hd, fun h => ⟨rfl, phiStar_nnbox, h⟩⟩

/-! ## 7.  Axiom audit -/

/-- info: 'PLLND.RNEmbed.force_bigOr' does not depend on any axioms -/
#guard_msgs in
#print axioms force_bigOr

/-- info: 'PLLND.RNEmbed.semCover_of_deriv' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms semCover_of_deriv

/-- info: 'PLLND.RNEmbed.deriv_of_semCover' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms deriv_of_semCover

/-- info: 'PLLND.RNEmbed.hasCover_iff_semCover' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms hasCover_iff_semCover

/-- info: 'PLLND.RNEmbed.not_hasCover_of_model' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms not_hasCover_of_model

/-- info: 'PLLND.RNEmbed.force_inst_top' does not depend on any axioms -/
#guard_msgs in
#print axioms force_inst_top

/-- info: 'PLLND.RNEmbed.force_inst_bot' does not depend on any axioms -/
#guard_msgs in
#print axioms force_inst_bot

/-- info: 'PLLND.RNEmbed.M4_swap' depends on axioms: [propext] -/
#guard_msgs in
#print axioms M4_swap

/-- info: 'PLLND.RNEmbed.M4_force_phiStar' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms M4_force_phiStar

/-- info: 'PLLND.RNEmbed.M4_inst_fails' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms M4_inst_fails

/-- info: 'PLLND.RNEmbed.phiStar_no_cover' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms phiStar_no_cover

/-- info: 'PLLND.RNEmbed.coverConj_false' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms coverConj_false

/-- info: 'PLLND.RNEmbed.phiStar_nnbox' does not depend on any axioms -/
#guard_msgs in
#print axioms phiStar_nnbox

/-- info: 'PLLND.RNEmbed.phiStar_to_phiMix' does not depend on any axioms -/
#guard_msgs in
#print axioms phiStar_to_phiMix

/-- info: 'PLLND.RNEmbed.phiStar_not_oBot' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms phiStar_not_oBot

/-- info: 'PLLND.RNEmbed.M3v_root_nnbox' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms M3v_root_nnbox

/-- info: 'PLLND.RNEmbed.M3v_phiStar_fails' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms M3v_phiStar_fails

/-- info: 'PLLND.RNEmbed.postInterpPhiStarIsNNBox_iff' does not depend on any axioms -/
#guard_msgs in
#print axioms postInterpPhiStarIsNNBox_iff

end RNEmbed
end PLLND
