import LaxLogic.PLLFormula

/-!
# CoverConj probe: is the `p`-valuation replaceable by a variable-free one?

`wip/postui.lean` reduces last-variable `∃p` for PLL to

    CoverConj :  ∀ φ with atoms ⊆ {p}, ∃ finite S of variable-free θ,
                 φ ⊢ ⋁_{θ ∈ S} φ[p := θ].

By soundness the SEMANTIC form of a single cover step is: in every
constraint model `C` and world `w` with `w ⊩ φ`, some `θ ∈ S` has
`w ⊩ φ[p := θ]`.  Two standard facts turn this into a pure
model-theoretic question about the *valuation of `p`*:

* generated submodels — restrict to the `Rᵢ`-cone `↑w`, so `w` is the
  ROOT and truth sets are up-sets, "true at the root" = "the whole cone";
* the substitution lemma — `w ⊩ φ[p := θ]` in `C` is exactly
  `w ⊩ φ` in `C[p := ‖θ‖]`, the same model with the valuation of `p`
  replaced by the (variable-free, hence `V(p)`-independent) truth set of
  `θ`.

So write `D(C)` for the family of truth sets of variable-free formulas:
the closure of `{‖⊥‖ = F}` under `∧, ∨, ⊃, ◯`, computed inside the finite
algebra of up-sets.  The question becomes

    (★)  given a finite rooted model `C`, a valuation `U` of `p`, and a
         one-variable `φ` true at the root under `U`, is there `d ∈ D(C)`
         with `φ` true at the root under `d`?

A model + valuation + `φ` where (★) FAILS refutes the cover method on the
`∃`-side (the analogue of `wemP_no_meetCover` for `∀`).  This probe
searches for one exhaustively.

## The search is exact, not a sample of formulas

For a fixed model and `U` we do not enumerate formulas: we enumerate the
subalgebra of the PRODUCT

    A_U × A_{d₁} × … × A_{d_k}        (A_X = up-sets of `C`, `p ↦ X`)

generated by the single element `p ↦ (U, d₁, …, d_k)` together with `⊥`.
Every one-variable `φ` has its tuple of truth sets in this subalgebra and
conversely, so the closure is the set of ALL formulas up to semantic
equivalence in that product.  A separating `φ` exists iff some tuple has
coordinate 0 equal to the whole model (true at the root under `U`) and
every other coordinate a proper up-set (false at the root under each
variable-free valuation).  The closure carries a witness term, so a hit
is a concrete formula.

Run: `scripts/probe <sec> coverprobe <maxN> <cap> <mode>`
  mode = "sweep" (default) | "models" (enumeration census) | "detail".
-/

namespace CoverProbe

open PLLFormula

abbrev Mask := Nat

/-- A finite rooted constraint model: worlds `0 … n-1`, world `0` the
root, `ri[v]`/`rm[v]` the `Rᵢ`/`Rₘ`-successor masks, `f` the fallible
mask. -/
structure FM where
  n : Nat
  ri : Array Mask
  rm : Array Mask
  f : Mask
  deriving Inhabited

def bit (i : Nat) : Mask := 1 <<< i

def hasBit (m : Mask) (i : Nat) : Bool := (m >>> i) % 2 == 1

def FM.full (M : FM) : Mask := (1 <<< M.n) - 1

def popcount (n : Nat) (m : Mask) : Nat := Id.run do
  let mut c := 0
  for i in [0:n] do
    if hasBit m i then c := c + 1
  return c

def maskStr (n : Nat) (m : Mask) : String := Id.run do
  let mut s := "{"
  let mut first := true
  for i in [0:n] do
    if hasBit m i then
      s := s ++ (if first then "" else ",") ++ toString i
      first := false
  return s ++ "}"

/-! ## The four operations on truth sets -/

def mAnd (a b : Mask) : Mask := a &&& b
def mOr (a b : Mask) : Mask := a ||| b

/-- `‖A ⊃ B‖ = {v : ∀ u ≥ᵢ v, u ∈ A → u ∈ B}`. -/
def mImp (M : FM) (a b : Mask) : Mask := Id.run do
  let mut r := 0
  for v in [0:M.n] do
    if (M.ri[v]! &&& a &&& (M.full ^^^ b)) == 0 then r := r ||| bit v
  return r

/-- `‖◯A‖ = {v : ∀ u ≥ᵢ v, ∃ y, u Rₘ y ∧ y ∈ A}`. -/
def mBox (M : FM) (a : Mask) : Mask := Id.run do
  let mut r := 0
  for v in [0:M.n] do
    let mut ok := true
    for u in [0:M.n] do
      if hasBit M.ri[v]! u && (M.rm[u]! &&& a) == 0 then ok := false
    if ok then r := r ||| bit v
  return r

/-! ## The variable-free truth sets -/

/-- `D(C)`: closure of `{‖⊥‖}` under `∧, ∨, ⊃, ◯`.  Every variable-free
formula has its truth set here, and every element of it is the truth set
of a variable-free formula. -/
def defClosure (M : FM) : Array Mask := Id.run do
  let mut S : Array Mask := #[M.f]
  let mut changed := true
  while changed do
    changed := false
    let cur := S
    for a in cur do
      for b in cur do
        for c in [mAnd a b, mOr a b, mImp M a b] do
          if !S.contains c then
            S := S.push c
            changed := true
      let c := mBox M a
      if !S.contains c then
        S := S.push c
        changed := true
  return S

/-! ## Up-sets, and the model enumeration -/

def isUp (M : FM) (m : Mask) : Bool := Id.run do
  for v in [0:M.n] do
    if hasBit m v && (M.ri[v]! &&& (M.full ^^^ m)) != 0 then return false
  return true

def upsets (M : FM) : Array Mask := Id.run do
  let mut acc : Array Mask := #[]
  for m in [0:(1 <<< M.n)] do
    if isUp M m then acc := acc.push m
  return acc

/-- All rooted partial orders on `0 … n-1` whose numbering is a linear
extension (root `0`, and `v ≤ u → v ≤ᴺ u`).  Complete up to isomorphism. -/
def posets (n : Nat) : Array (Array Mask) := Id.run do
  let mut acc : Array (Array Mask) := #[]
  -- world v (1 ≤ v < n) chooses a subset of {v+1, …, n-1}
  let mut opts : Array (Array Mask) := #[]
  for v in [0:n] do
    if v == 0 then
      opts := opts.push #[((1 <<< n) - 1)]
    else
      let hi := n - v - 1                 -- number of worlds above v
      let mut o : Array Mask := #[]
      for s in [0:(1 <<< hi)] do
        -- bits of s, shifted to start at v+1, plus v itself
        o := o.push (bit v ||| (s <<< (v + 1)))
      opts := opts.push o
  -- mixed-radix walk
  let mut idx : Array Nat := Array.replicate n 0
  let mut go := true
  while go do
    let mut ri : Array Mask := #[]
    for v in [0:n] do
      ri := ri.push ((opts[v]!)[idx[v]!]!)
    -- transitivity check
    let mut ok := true
    for v in [0:n] do
      for u in [0:n] do
        if hasBit ri[v]! u && (ri[u]! &&& (((1 <<< n) - 1) ^^^ ri[v]!)) != 0 then
          ok := false
    if ok then acc := acc.push ri
    -- increment
    let mut i := 0
    let mut carry := true
    while carry && i < n do
      if idx[i]! + 1 < opts[i]!.size then
        idx := idx.set! i (idx[i]! + 1)
        carry := false
      else
        idx := idx.set! i 0
        i := i + 1
    if carry then go := false
  return acc

/-- All reflexive transitive `Rₘ ⊆ Rᵢ`. -/
def modals (n : Nat) (ri : Array Mask) : Array (Array Mask) := Id.run do
  let full := (1 <<< n) - 1
  let mut opts : Array (Array Mask) := #[]
  for v in [0:n] do
    -- subsets of ri[v] containing v
    let mut o : Array Mask := #[]
    for m in [0:(1 <<< n)] do
      if hasBit m v && (m &&& (full ^^^ ri[v]!)) == 0 then o := o.push m
    opts := opts.push o
  let mut acc : Array (Array Mask) := #[]
  let mut idx : Array Nat := Array.replicate n 0
  let mut go := true
  while go do
    let mut rm : Array Mask := #[]
    for v in [0:n] do
      rm := rm.push ((opts[v]!)[idx[v]!]!)
    let mut ok := true
    for v in [0:n] do
      for u in [0:n] do
        if hasBit rm[v]! u && (rm[u]! &&& (full ^^^ rm[v]!)) != 0 then ok := false
    if ok then acc := acc.push rm
    let mut i := 0
    let mut carry := true
    while carry && i < n do
      if idx[i]! + 1 < opts[i]!.size then
        idx := idx.set! i (idx[i]! + 1)
        carry := false
      else
        idx := idx.set! i 0
        i := i + 1
    if carry then go := false
  return acc

/-! ## The product-subalgebra search -/

/-- A tuple of truth sets, one coordinate per valuation. -/
abbrev Tup := Array Mask

def encode (n : Nat) (t : Tup) : Nat :=
  t.foldl (fun acc m => acc * (1 <<< n) + m) 0

def tAnd (a b : Tup) : Tup := a.zipWith (fun x y => mAnd x y) b
def tOr (a b : Tup) : Tup := a.zipWith (fun x y => mOr x y) b
def tImp (M : FM) (a b : Tup) : Tup := a.zipWith (fun x y => mImp M x y) b
def tBox (M : FM) (a : Tup) : Tup := a.map (mBox M)

/-- Coordinate 0 is the whole model (φ true at the root under `U`) and
every other coordinate is proper (φ false at the root under every
variable-free valuation). -/
def isSep (M : FM) (t : Tup) : Bool := Id.run do
  if t[0]! != M.full then return false
  for i in [1:t.size] do
    if t[i]! == M.full then return false
  return true

structure SearchOut where
  hit : Option (PLLFormula × Tup) := none
  size : Nat := 0
  capped : Bool := false

def fsize : PLLFormula → Nat
  | .prop _ => 1
  | .falsePLL => 1
  | .and a b => 1 + fsize a + fsize b
  | .or a b => 1 + fsize a + fsize b
  | .ifThen a b => 1 + fsize a + fsize b
  | .somehow a => 1 + fsize a

/-- Generate the subalgebra of `∏ A_{vals i}` generated by `p` and `⊥`,
looking for a separating element.  The closure is generated in order of
increasing term size, so the FIRST separating element found is of minimal
size among separating elements (up to the term chosen for each semantic
value).  `capped` says the closure was cut off (verdict inconclusive). -/
def search (M : FM) (vals : Array Mask) (cap : Nat) : SearchOut := Id.run do
  let P : PLLFormula := .prop "p"
  let botT : Tup := vals.map (fun _ => M.f)
  let genT : Tup := vals
  let mut seen : Std.HashMap Nat Unit := {}
  let mut all : Array (Tup × PLLFormula) := #[]
  let mut frontier : Array (Tup × PLLFormula) := #[]
  for (t, e) in [(botT, (PLLFormula.falsePLL : PLLFormula)), (genT, P)] do
    let k := encode M.n t
    if !seen.contains k then
      seen := seen.insert k ()
      all := all.push (t, e)
      frontier := frontier.push (t, e)
      if isSep M t then return { hit := some (e, t), size := all.size }
  while frontier.size > 0 do
    if all.size > cap then
      return { size := all.size, capped := true }
    let mut next : Array (Tup × PLLFormula) := #[]
    let cur := all
    let mut best : Option (PLLFormula × Tup) := none
    for (ta, ea) in frontier do
      -- unary
      let mut cands : Array (Tup × PLLFormula) := #[(tBox M ta, ea.somehow)]
      for (tb, eb) in cur do
        cands := cands.push (tAnd ta tb, ea.and eb)
        cands := cands.push (tOr ta tb, ea.or eb)
        cands := cands.push (tImp M ta tb, ea.ifThen eb)
        cands := cands.push (tImp M tb ta, eb.ifThen ea)
      for (t, e) in cands do
        let k := encode M.n t
        if !seen.contains k then
          seen := seen.insert k ()
          all := all.push (t, e)
          next := next.push (t, e)
          if isSep M t then
            match best with
            | none => best := some (e, t)
            | some (e', _) => if fsize e < fsize e' then best := some (e, t)
    match best with
    | some h => return { hit := some h, size := all.size }
    | none => pure ()
    frontier := next
  return { size := all.size }

/-! ## Driver -/

structure Stats where
  models : Nat := 0
  pairs : Nat := 0          -- (model, U) with U ∉ D
  capped : Nat := 0
  hits : Nat := 0
  maxClosure : Nat := 0
  deriving Repr

def describe (M : FM) : String := Id.run do
  let mut s := s!"n={M.n} F={maskStr M.n M.f}"
  s := s ++ " Ri:"
  for v in [0:M.n] do
    s := s ++ s!" {v}↑{maskStr M.n M.ri[v]!}"
  s := s ++ " Rm:"
  for v in [0:M.n] do
    s := s ++ s!" {v}⇝{maskStr M.n M.rm[v]!}"
  return s

def runModel (pl : String → IO Unit) (M : FM) (cap : Nat) (verbose : Bool)
    (st : Stats) : IO Stats := do
  let mut st := st
  let D := defClosure M
  let ups := upsets M
  -- valuations: up-sets containing F that are NOT variable-free definable
  let cands := ups.filter (fun u => (M.f &&& (M.full ^^^ u)) == 0 && !D.contains u)
  if verbose && cands.size > 0 then
    pl s!"  model {describe M}"
    pl s!"    definable truth sets ({D.size}): {D.toList.map (maskStr M.n)}"
    pl s!"    undefinable valuations ({cands.size}): {cands.toList.map (maskStr M.n)}"
  for u in cands do
    st := { st with pairs := st.pairs + 1 }
    let vals : Array Mask := #[u] ++ D
    let out := search M vals cap
    st := { st with maxClosure := max st.maxClosure out.size }
    if out.capped then
      st := { st with capped := st.capped + 1 }
      pl s!"  CAPPED at {out.size}: {describe M} U={maskStr M.n u}"
    match out.hit with
    | some (φ, t) =>
        st := { st with hits := st.hits + 1 }
        pl "  *** SEPARATING FORMULA FOUND ***"
        pl s!"      model  : {describe M}"
        pl s!"      V(p)   : {maskStr M.n u}"
        pl s!"      D      : {D.toList.map (maskStr M.n)}"
        pl s!"      φ      : {φ.toString}"
        pl s!"      tuple  : {t.toList.map (maskStr M.n)}"
    | none => pure ()
  return st

def enumerate (n : Nat) : Array FM := Id.run do
  let mut acc : Array FM := #[]
  for ri in posets n do
    let M0 : FM := { n := n, ri := ri, rm := ri, f := 0 }
    for rm in modals n ri do
      let M1 : FM := { M0 with rm := rm }
      for f in upsets M1 do
        if !hasBit f 0 then
          acc := acc.push { M1 with f := f }
  return acc

def main (args : List String) : IO Unit := do
  let out ← IO.getStdout
  let pl (x : String) : IO Unit := do out.putStrLn x; out.flush
  let maxN := (args[0]?.getD "4").toNat!
  let cap := (args[1]?.getD "4000").toNat!
  let mode := args[2]?.getD "sweep"
  pl s!"== CoverConj probe: maxN={maxN} closureCap={cap} mode={mode} =="
  for n in [2:maxN+1] do
    let ms := enumerate n
    pl s!"-- n={n}: {ms.size} rooted models (poset × Rₘ × F) --"
    if mode == "models" then continue
    let t0 ← IO.monoMsNow
    let mut st : Stats := {}
    for M in ms do
      st := { st with models := st.models + 1 }
      st ← runModel pl M cap (mode == "detail") st
    let t1 ← IO.monoMsNow
    pl s!"   models {st.models}, (model,U) pairs with U undefinable {st.pairs}, \
capped {st.capped}, SEPARATING HITS {st.hits}, max closure {st.maxClosure} \
[{t1 - t0} ms]"
  pl "done"

end CoverProbe

def main (args : List String) : IO Unit := CoverProbe.main args
