import wip.families
import wip.uiObstruct

/-!
# The `◯`-depth stratification of RN(◯,{}) — syntax, the depth-reducing
# laws, and the class-depth upper bounds

For closed (variable-free) formulas the stratification is

    D₀ = {⊥, ⊤}
    D₁ = the Heyting subalgebra generated by ◯⊥            (the ladder, im h)
    D_{n+1} = the Heyting subalgebra generated by D_n ∪ ◯D_n

and RN(◯,{}) = ⋃ₙ D_n, since every closed formula has finite `◯`-nesting.

**Syntactic depth versus class depth.**  `boxDepth A` counts the `◯`-nesting
of the given formula `A`.  It is NOT an invariant of the Lindenbaum class:
`gap 0 = ◯t1 ⊃ t1 = ◯◯⊥ ⊃ ◯⊥` has `boxDepth = 2` but is interderivable with
`⊤` (`Visibility.interd_gap_zero_top`), so its CLASS depth is `0`.  Only the
class depth

    DepthLe n A  :=  ∃ B, Interd A B ∧ boxDepth B ≤ n

is meaningful, and every statement below is about `DepthLe`.

## The depth-reducing laws (this file, all PROVED)

    ◯⊤        ⊣⊢ ⊤                                    `box_top`
    ◯◯A       ⊣⊢ ◯A                                   `box_idem`
    ◯(A ∧ B)  ⊣⊢ ◯A ∧ ◯B                              `box_and`
    ◯(A ⊃ ◯B) ⊣⊢ A ⊃ ◯B                               `box_imp_box`
    ◯(◯A ∨ ◯B) ⊣⊢ ◯(A ∨ B)                            `box_or_box`

The last two are the ones that make the collapse question sharp.
`box_imp_box` is the syntactic form of the standard fact that the fixed
points of a nucleus are closed under `a ⊃ (-)`; `box_or_box` says that
boxing the disjuncts before boxing the disjunction is free.  Together with
`box_and` and `box_idem` they show that **the only depth-raising
constructions are `◯` over a disjunction and `◯` over an implication whose
consequent is not already boxed** (`depth_raising_only_or_imp`, the
`boxDepth`-level corollaries `depth_and`, `depth_boxbox`, `depth_imp_box`).

`◯` over `∨` genuinely escapes: `RNEmbed.distr_4_3_not_derivable`
(`wip/ladderdistr.lean`) refutes `◯(t3 ∨ t4) ⊢ ◯t3 ∨ ◯t4`.

## Upper bounds for the named families (this file, all PROVED)

    t n      = rnSub n                    DepthLe 1
    c k      = ◯t(2k+1)   (`chainF`)      DepthLe 2
    g k      = c k ⊃ t(2k+1) (`gap`)      DepthLe 2
    s k      = c k ∨ t(2k+2) (`sC`)       DepthLe 2
    r k      = t(2k+4) ⊃ c k (`rC`)       DepthLe 2   and ◯-FIXED
    ◯g k     (`bg`)                       DepthLe 3
    w k      = g k ∧ t(2k+4)              DepthLe 2
    Gmeet n  = g 1 ∧ … ∧ g (n+1)          DepthLe 2

`r k` is `◯`-fixed by `box_imp_box` (`box_rC`): `◯r k ⊣⊢ r k`, so the whole
`r`-family stays at depth 2 under boxing.  The `◯g k` bound is only an upper
bound; `wip/depth2.lean` proves it EXACT at `k = 1`.

The matching lower bounds are semantic and live in `wip/depth2.lean`.
-/

open PLLFormula

namespace PLLND
namespace Depth

open SemUI RNEmbed

/-! ## `Deriv` helpers for the two lax rules -/

theorem Deriv.laxIntro {Γ : List PLLFormula} {φ : PLLFormula} :
    Deriv Γ φ → Deriv Γ (.somehow φ)
  | ⟨p⟩ => ⟨.laxIntro p⟩

theorem Deriv.laxElim {Γ : List PLLFormula} {φ ψ : PLLFormula} :
    Deriv Γ (.somehow φ) → Deriv (φ :: Γ) (.somehow ψ) → Deriv Γ (.somehow ψ)
  | ⟨p⟩, ⟨q⟩ => ⟨.laxElim p q⟩

/-! ## Syntactic `◯`-depth and class depth -/

/-- The `◯`-nesting depth of a formula. -/
def boxDepth : PLLFormula → Nat
  | .prop _ => 0
  | .falsePLL => 0
  | .and A B => max (boxDepth A) (boxDepth B)
  | .or A B => max (boxDepth A) (boxDepth B)
  | .ifThen A B => max (boxDepth A) (boxDepth B)
  | .somehow A => boxDepth A + 1

@[simp] theorem boxDepth_prop (a : String) : boxDepth (.prop a) = 0 := rfl
@[simp] theorem boxDepth_false : boxDepth .falsePLL = 0 := rfl
@[simp] theorem boxDepth_and (A B : PLLFormula) :
    boxDepth (A.and B) = max (boxDepth A) (boxDepth B) := rfl
@[simp] theorem boxDepth_or (A B : PLLFormula) :
    boxDepth (A.or B) = max (boxDepth A) (boxDepth B) := rfl
@[simp] theorem boxDepth_imp (A B : PLLFormula) :
    boxDepth (A.ifThen B) = max (boxDepth A) (boxDepth B) := rfl
@[simp] theorem boxDepth_box (A : PLLFormula) :
    boxDepth A.somehow = boxDepth A + 1 := rfl

/-- **Class depth ≤ n**: some formula of syntactic `◯`-depth ≤ `n` is
interderivable with `A`. -/
def DepthLe (n : Nat) (A : PLLFormula) : Prop :=
  ∃ B, Interd A B ∧ boxDepth B ≤ n

theorem DepthLe.of_boxDepth {n : Nat} {A : PLLFormula} (h : boxDepth A ≤ n) :
    DepthLe n A :=
  ⟨A, Interd.refl A, h⟩

theorem DepthLe.mono {m n : Nat} {A : PLLFormula} (h : m ≤ n) :
    DepthLe m A → DepthLe n A
  | ⟨B, hB, hd⟩ => ⟨B, hB, le_trans hd h⟩

theorem DepthLe.of_interd {n : Nat} {A A' : PLLFormula} (h : Interd A A') :
    DepthLe n A' → DepthLe n A
  | ⟨B, hB, hd⟩ => ⟨B, Interd.trans h hB, hd⟩

theorem DepthLe.and {n : Nat} {A B : PLLFormula} :
    DepthLe n A → DepthLe n B → DepthLe n (A.and B)
  | ⟨A', hA, hdA⟩, ⟨B', hB, hdB⟩ =>
      ⟨A'.and B', Interd.and_congr hA hB, by simp only [boxDepth_and]; omega⟩

theorem DepthLe.or {n : Nat} {A B : PLLFormula} :
    DepthLe n A → DepthLe n B → DepthLe n (A.or B)
  | ⟨A', hA, hdA⟩, ⟨B', hB, hdB⟩ =>
      ⟨A'.or B', Interd.or_congr hA hB, by simp only [boxDepth_or]; omega⟩

theorem DepthLe.imp {n : Nat} {A B : PLLFormula} :
    DepthLe n A → DepthLe n B → DepthLe n (A.ifThen B)
  | ⟨A', hA, hdA⟩, ⟨B', hB, hdB⟩ =>
      ⟨A'.ifThen B', Interd.imp_congr hA hB, by simp only [boxDepth_imp]; omega⟩

theorem DepthLe.box {n : Nat} {A : PLLFormula} :
    DepthLe n A → DepthLe (n + 1) A.somehow
  | ⟨A', hA, hdA⟩ => ⟨A'.somehow, Interd.box_congr hA, by simp only [boxDepth_box]; omega⟩

/-! ## The depth-reducing laws

Displayed:

    ◯⊤        ⊣⊢ ⊤
    ◯◯A       ⊣⊢ ◯A
    ◯(A ∧ B)  ⊣⊢ ◯A ∧ ◯B
    ◯(A ⊃ ◯B) ⊣⊢ A ⊃ ◯B
    ◯(◯A ∨ ◯B) ⊣⊢ ◯(A ∨ B)
-/

/-- `◯⊤ ⊣⊢ ⊤`. -/
theorem box_top : Interd (PLLFormula.somehow truePLL) truePLL :=
  ⟨Deriv.impIntro (Deriv.iden (.head _)),
   Deriv.laxIntro (Deriv.impIntro (Deriv.iden (.head _)))⟩

/-- **Idempotency**: `◯◯A ⊣⊢ ◯A`.  `R` gives one direction, `J` the other. -/
theorem box_idem (A : PLLFormula) :
    Interd (PLLFormula.somehow (PLLFormula.somehow A)) (PLLFormula.somehow A) :=
  ⟨Deriv.laxElim (Deriv.iden (.head _)) (Deriv.iden (.head _)),
   Deriv.laxIntro (Deriv.iden (.head _))⟩

/-- **`◯` over `∧`**: `◯(A ∧ B) ⊣⊢ ◯A ∧ ◯B`. -/
theorem box_and (A B : PLLFormula) :
    Interd (PLLFormula.somehow (A.and B))
      ((PLLFormula.somehow A).and (PLLFormula.somehow B)) := by
  refine ⟨Deriv.andIntro ?_ ?_, ?_⟩
  · exact Deriv.somehowMono (Deriv.andElim1 (Deriv.iden (.head _)))
  · exact Deriv.somehowMono (Deriv.andElim2 (Deriv.iden (.head _)))
  · refine Deriv.laxElim (Deriv.andElim1 (Deriv.iden (.head _))) ?_
    refine Deriv.laxElim (Deriv.andElim2 (Deriv.iden (.tail _ (.head _)))) ?_
    exact Deriv.laxIntro
      (Deriv.andIntro (Deriv.iden (.tail _ (.head _))) (Deriv.iden (.head _)))

/-- **`◯` absorbs into an implication with boxed consequent**:

    ◯(A ⊃ ◯B) ⊣⊢ A ⊃ ◯B

the syntactic form of "the fixed points of a nucleus are closed under
`a ⊃ (-)`".  This is the law that keeps the `r`-family at depth 2. -/
theorem box_imp_box (A B : PLLFormula) :
    Interd (PLLFormula.somehow (A.ifThen (PLLFormula.somehow B)))
      (A.ifThen (PLLFormula.somehow B)) := by
  refine ⟨Deriv.impIntro ?_, Deriv.laxIntro (Deriv.iden (.head _))⟩
  refine Deriv.laxElim (Deriv.iden (.tail _ (.head _))) ?_
  exact Deriv.impElim (Deriv.iden (.head _)) (Deriv.iden (.tail _ (.head _)))

/-- **Boxing the disjuncts is free**: `◯(◯A ∨ ◯B) ⊣⊢ ◯(A ∨ B)`. -/
theorem box_or_box (A B : PLLFormula) :
    Interd (PLLFormula.somehow ((PLLFormula.somehow A).or (PLLFormula.somehow B)))
      (PLLFormula.somehow (A.or B)) := by
  constructor
  · refine Deriv.laxElim (Deriv.iden (.head _)) ?_
    refine Deriv.orElim (Deriv.iden (.head _)) ?_ ?_
    · exact Deriv.somehowMono (Deriv.orIntro1 (Deriv.iden (.head _)))
    · exact Deriv.somehowMono (Deriv.orIntro2 (Deriv.iden (.head _)))
  · refine Deriv.somehowMono (Deriv.orElim (Deriv.iden (.head _)) ?_ ?_)
    · exact Deriv.orIntro1 (Deriv.laxIntro (Deriv.iden (.head _)))
    · exact Deriv.orIntro2 (Deriv.laxIntro (Deriv.iden (.head _)))

/-! ### The depth corollaries: `◯` over `∧`, over `◯`, and into a boxed
consequent never raises the class depth. -/

/-- `◯(A ∧ B)` never needs more depth than `◯A ∧ ◯B`. -/
theorem depth_and {n : Nat} {A B : PLLFormula}
    (hA : DepthLe n (PLLFormula.somehow A)) (hB : DepthLe n (PLLFormula.somehow B)) :
    DepthLe n (PLLFormula.somehow (A.and B)) :=
  DepthLe.of_interd (box_and A B) (hA.and hB)

/-- `◯◯A` never needs more depth than `◯A`. -/
theorem depth_boxbox {n : Nat} {A : PLLFormula} (h : DepthLe n (PLLFormula.somehow A)) :
    DepthLe n (PLLFormula.somehow (PLLFormula.somehow A)) :=
  DepthLe.of_interd (box_idem A) h

/-- `◯(A ⊃ ◯B)` never needs more depth than `A ⊃ ◯B`. -/
theorem depth_imp_box {n : Nat} {A B : PLLFormula}
    (h : DepthLe n (A.ifThen (PLLFormula.somehow B))) :
    DepthLe n (PLLFormula.somehow (A.ifThen (PLLFormula.somehow B))) :=
  DepthLe.of_interd (box_imp_box A B) h

/-- `◯(◯A ∨ ◯B)` never needs more depth than `◯(A ∨ B)`. -/
theorem depth_or_box {n : Nat} {A B : PLLFormula}
    (h : DepthLe n (PLLFormula.somehow (A.or B))) :
    DepthLe n (PLLFormula.somehow ((PLLFormula.somehow A).or (PLLFormula.somehow B))) :=
  DepthLe.of_interd (box_or_box A B) h

/-- **The depth-raising constructions are exactly `◯∨` and `◯⊃`.**  Stated as
the closure property that survives them: if every `◯`-subformula of the
argument is already accounted for at depth `n`, then boxing a conjunction, a
box, or an implication with boxed consequent stays at depth `n`. -/
theorem depth_raising_only_or_imp {n : Nat} {A B : PLLFormula}
    (hA : DepthLe n (PLLFormula.somehow A)) (hB : DepthLe n (PLLFormula.somehow B))
    (hI : DepthLe n (A.ifThen (PLLFormula.somehow B))) :
    DepthLe n (PLLFormula.somehow (A.and B)) ∧
    DepthLe n (PLLFormula.somehow (PLLFormula.somehow A)) ∧
    DepthLe n (PLLFormula.somehow (A.ifThen (PLLFormula.somehow B))) :=
  ⟨depth_and hA hB, depth_boxbox hA, depth_imp_box hI⟩

/-! ## The `◯`-free part: `boxDepth = 0` closed formulas are `⊥` or `⊤`

`boxDepth A = 0` says `A` carries no `◯` at all; if in addition `A` is
atom-free it is an IPC formula with no variables, hence interderivable with
`⊥` or with `⊤`.  We do not need the classification here — the semantic
lower bounds of `wip/depth2.lean` work directly with `DepthLe`. -/

/-! ## Upper bounds for the named families

`substP` of a `◯`-free formula puts every `◯` of the result inside the
substituted `◯⊥`, so the substituted rungs have `boxDepth ≤ 1`. -/

theorem boxDepth_substP_of_boxFree {p : String} {χ : PLLFormula} :
    ∀ {A : PLLFormula}, boxFree A = true → boxDepth (substP p χ A) ≤ boxDepth χ := by
  intro A
  induction A with
  | prop a =>
      intro _
      by_cases h : a = p
      · simp [substP, h]
      · simp [substP, h]
  | falsePLL => intro _; simp [substP]
  | and A B ihA ihB =>
      intro h
      have h' := Bool.and_eq_true .. |>.mp h
      have := ihA h'.1; have := ihB h'.2
      simp only [substP, boxDepth_and]; omega
  | or A B ihA ihB =>
      intro h
      have h' := Bool.and_eq_true .. |>.mp h
      have := ihA h'.1; have := ihB h'.2
      simp only [substP, boxDepth_or]; omega
  | ifThen A B ihA ihB =>
      intro h
      have h' := Bool.and_eq_true .. |>.mp h
      have := ihA h'.1; have := ihB h'.2
      simp only [substP, boxDepth_imp]; omega
  | somehow A _ => intro h; simp [boxFree] at h

/-- Every ladder rung `t n = rnSub n` has syntactic `◯`-depth ≤ 1. -/
theorem boxDepth_rnSub (n : Nat) : boxDepth (rnSub n) ≤ 1 :=
  boxDepth_substP_of_boxFree (rn_boxFree n)

theorem depth_rnSub (n : Nat) : DepthLe 1 (rnSub n) :=
  DepthLe.of_boxDepth (boxDepth_rnSub n)

/-- `c k = ◯t(2k+1)` has syntactic depth ≤ 2. -/
theorem boxDepth_chainF (k : Nat) : boxDepth (RNEmbed.chainF k) ≤ 2 := by
  have := boxDepth_rnSub (2 * k + 1)
  show boxDepth (PLLFormula.somehow (rnSub (2 * k + 1))) ≤ 2
  simp only [boxDepth_box]; omega

theorem depth_chainF (k : Nat) : DepthLe 2 (RNEmbed.chainF k) :=
  DepthLe.of_boxDepth (boxDepth_chainF k)

/-- `g k = c k ⊃ t(2k+1)` has syntactic depth ≤ 2. -/
theorem boxDepth_gap (k : Nat) : boxDepth (gap k) ≤ 2 := by
  have h₁ := boxDepth_chainF k
  have h₂ := boxDepth_rnSub (2 * k + 1)
  show boxDepth ((RNEmbed.chainF k).ifThen (rnSub (2 * k + 1))) ≤ 2
  simp only [boxDepth_imp]; omega

theorem depth_gap (k : Nat) : DepthLe 2 (gap k) :=
  DepthLe.of_boxDepth (boxDepth_gap k)

/-- `s k = c k ∨ t(2k+2)` has syntactic depth ≤ 2. -/
theorem boxDepth_sC (k : Nat) : boxDepth (sC k) ≤ 2 := by
  have h₁ := boxDepth_chainF k
  have h₂ := boxDepth_rnSub (2 * k + 2)
  show boxDepth ((RNEmbed.chainF k).or (rnSub (2 * k + 2))) ≤ 2
  simp only [boxDepth_or]; omega

theorem depth_sC (k : Nat) : DepthLe 2 (sC k) :=
  DepthLe.of_boxDepth (boxDepth_sC k)

/-- `r k = t(2k+4) ⊃ c k` has syntactic depth ≤ 2. -/
theorem boxDepth_rC (k : Nat) : boxDepth (rC k) ≤ 2 := by
  have h₁ := boxDepth_chainF k
  have h₂ := boxDepth_rnSub (2 * k + 4)
  show boxDepth ((rnSub (2 * k + 4)).ifThen (RNEmbed.chainF k)) ≤ 2
  simp only [boxDepth_imp]; omega

theorem depth_rC (k : Nat) : DepthLe 2 (rC k) :=
  DepthLe.of_boxDepth (boxDepth_rC k)

/-- **The `r`-family is `◯`-fixed**: `◯r k ⊣⊢ r k`, by `box_imp_box` — its
consequent `c k` is already a box.  So boxing never lifts it off depth 2. -/
theorem box_rC (k : Nat) : Interd (PLLFormula.somehow (rC k)) (rC k) :=
  box_imp_box (rnSub (2 * k + 4)) (rnSub (2 * k + 1))

theorem depth_box_rC (k : Nat) : DepthLe 2 (PLLFormula.somehow (rC k)) :=
  DepthLe.of_interd (box_rC k) (depth_rC k)

/-- `w k = g k ∧ t(2k+4)` has syntactic depth ≤ 2. -/
theorem boxDepth_wC (k : Nat) : boxDepth ((gap k).and (rnSub (2 * k + 4))) ≤ 2 := by
  have h₁ := boxDepth_gap k
  have h₂ := boxDepth_rnSub (2 * k + 4)
  simp only [boxDepth_and]; omega

theorem depth_wC (k : Nat) : DepthLe 2 ((gap k).and (rnSub (2 * k + 4))) :=
  DepthLe.of_boxDepth (boxDepth_wC k)

/-- `Gmeet n = g 1 ∧ … ∧ g (n+1)` has syntactic depth ≤ 2. -/
theorem boxDepth_Gmeet : ∀ n : Nat, boxDepth (Gmeet n) ≤ 2
  | 0 => boxDepth_gap 1
  | n + 1 => by
      have h₁ := boxDepth_Gmeet n
      have h₂ := boxDepth_gap (n + 2)
      simp only [Gmeet, boxDepth_and]; omega

theorem depth_Gmeet (n : Nat) : DepthLe 2 (Gmeet n) :=
  DepthLe.of_boxDepth (boxDepth_Gmeet n)

/-- `◯g k` has syntactic depth ≤ 3 — an UPPER bound only.  `wip/depth2.lean`
shows it is exact at `k = 1`. -/
theorem boxDepth_bg (k : Nat) : boxDepth (PLLFormula.somehow (gap k)) ≤ 3 := by
  have := boxDepth_gap k
  simp only [boxDepth_box]; omega

theorem depth_bg (k : Nat) : DepthLe 3 (PLLFormula.somehow (gap k)) :=
  DepthLe.of_boxDepth (boxDepth_bg k)

/-- `g 0 = ◯t1 ⊃ t1 = ◯◯⊥ ⊃ ◯⊥ ⊣⊢ ⊤`: idempotency of `◯` collapses the
zeroth gap.  (The same statement is `Visibility.interd_gap_zero_top` in
`wip/visible.lean`, which is not in the `wipshared` import closure; this is a
self-contained re-proof.) -/
theorem interd_gap_zero_top : Interd (gap 0) truePLL :=
  ⟨Deriv.impIntro (Deriv.iden (.head _)),
   Deriv.impIntro (Deriv.laxElim (Deriv.iden (.head _)) (Deriv.iden (.head _)))⟩

/-- `g 0` is the standing warning: syntactic depth 2, class depth 0. -/
theorem depth_gap_zero : DepthLe 0 (gap 0) :=
  ⟨truePLL, interd_gap_zero_top, by simp [boxDepth]⟩

/-! ## Axiom pins -/

/-- info: 'PLLND.Depth.box_top' does not depend on any axioms -/
#guard_msgs in
#print axioms box_top

/-- info: 'PLLND.Depth.box_idem' does not depend on any axioms -/
#guard_msgs in
#print axioms box_idem

/-- info: 'PLLND.Depth.box_and' depends on axioms: [propext] -/
#guard_msgs in
#print axioms box_and

/-- info: 'PLLND.Depth.box_imp_box' does not depend on any axioms -/
#guard_msgs in
#print axioms box_imp_box

/-- info: 'PLLND.Depth.box_or_box' depends on axioms: [propext] -/
#guard_msgs in
#print axioms box_or_box

/-- info: 'PLLND.Depth.depth_raising_only_or_imp' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms depth_raising_only_or_imp

/-- info: 'PLLND.Depth.box_rC' does not depend on any axioms -/
#guard_msgs in
#print axioms box_rC

/-- info: 'PLLND.Depth.depth_rnSub' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms depth_rnSub

/-- info: 'PLLND.Depth.depth_Gmeet' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms depth_Gmeet

/-- info: 'PLLND.Depth.depth_gap_zero' depends on axioms: [propext] -/
#guard_msgs in
#print axioms depth_gap_zero

end Depth
end PLLND
