import LaxLogic.PLLSearchCmd

/-!
# Is the booleanization 𝔟⊥ of RN(◯,{}) finite?

`𝔟⊥ = {y | y = ¬¬y}` is the set of regular elements of the closed fragment —
equivalently the image of `¬`, since `¬¬¬x ⊣⊢ ¬x` always.  By Glivenko–Frink
it is a boolean lattice (Erné §5).

It contains at least `⊥, ¬◯⊥, ¬¬◯⊥, ⊤`, pairwise distinct.  Two guesses point
opposite ways:

* **exactly four.**  `◯⊥` freely generates a copy of the Rieger–Nishimura
  lattice inside RN(◯,{}) (`closed_lax_infinite`), and by Glivenko the
  booleanization of the free Heyting algebra on one generator is the free
  boolean algebra on one generator — four elements.  If `¬¬` also respects
  `◯`, the booleanization of the whole of RN(◯,{}) would be exactly our
  four-element classical rung `{⊥, ◯⊥, ¬◯⊥, ⊤}` (`varfree_exactly_four`),
  with `◯⊥ ↦ ¬¬◯⊥`.
* **infinite.**  RN(◯,{}) is much larger than the subalgebra generated by
  `◯⊥` — the boxed rungs, the gap antichain, the descending chain with no
  floor.  If any of those has a negation outside the four, the count grows.

This probe negates a spread of closed formulas and classifies each result
against the four candidates.  Anything matching NONE of them is a fifth
regular element and settles the question the second way.

PROBE, not a theorem.  Not registered in `lakefile.toml`; run with
`lake env lean wip/erneBool.lean`.
-/

open PLLFormula PLLND PLLND.Search

namespace ErneBool

def g : PLLFormula := falsePLL.somehow          -- ◯⊥, the free generator
def neg (x : PLLFormula) : PLLFormula := x.ifThen falsePLL
def imp (x a : PLLFormula) : PLLFormula := x.ifThen a

/-- The four known regular elements. -/
def reps : List (String × PLLFormula) :=
  [ ("⊥", falsePLL), ("¬◯⊥", neg g), ("¬¬◯⊥", neg (neg g)), ("⊤", truePLL) ]

/-- A spread of closed formulas whose negations we classify.  Rieger–Nishimura
ladder terms over the generator `◯⊥`, their boxes, the Figure 6 elements, and
some joins — the places a new regular element could plausibly hide. -/
def sample : List (String × PLLFormula) :=
  let ng := neg g
  let nng := neg ng
  let wlem := ng.or nng                       -- weak excluded middle at ◯⊥
  let r6 := imp nng g                         -- ¬¬◯⊥ ⊃ ◯⊥
  let r7 := r6.or ng
  let bg := g.somehow                         -- ◯◯⊥
  let bng := ng.somehow                       -- ◯¬◯⊥
  [ ("◯⊥",            g)
  , ("¬◯⊥",           ng)
  , ("¬¬◯⊥",          nng)
  , ("◯⊥ ∨ ¬◯⊥",      g.or ng)
  , ("¬◯⊥ ∨ ¬¬◯⊥",    wlem)
  , ("¬¬◯⊥ ⊃ ◯⊥",     r6)
  , ("(¬¬◯⊥⊃◯⊥) ∨ ¬◯⊥", r7)
  , ("◯◯⊥",           bg)
  , ("◯¬◯⊥",          bng)
  , ("◯¬¬◯⊥",         nng.somehow)
  , ("◯(¬◯⊥∨¬¬◯⊥)",   wlem.somehow)
  , ("◯(¬¬◯⊥⊃◯⊥)",    r6.somehow)
  , ("◯((¬¬◯⊥⊃◯⊥)∨¬◯⊥)", r7.somehow)
  , ("(¬¬◯⊥⊃◯⊥)⊃◯¬◯⊥", imp r6 bng)
  , ("◯⊥ ∧ ¬◯⊥",      g.and ng)
  , ("◯¬◯⊥ ⊃ ◯⊥",     imp bng g)
  , ("◯⊥ ⊃ ¬◯⊥",      imp g ng)
  , ("¬◯⊥ ⊃ ◯⊥",      imp ng g)
  , ("◯(◯⊥⊃¬◯⊥)",     (imp g ng).somehow)
  , ("¬(◯⊥∨¬◯⊥)",     neg (g.or ng)) ]

def derives (P Q : PLLFormula) : Bool :=
  match settle budgetedConfig [P] Q with
  | .proved _ => true
  | _         => false

def interdB (A B : PLLFormula) : Bool := derives A B && derives B A

/-- Classify `¬x` against the four known regular elements. -/
def classify (x : PLLFormula) : String :=
  match reps.find? (fun (_, r) => interdB (neg x) r) with
  | some (nm, _) => nm
  | none         => "*** NONE OF THE FOUR ***"

def report : String :=
  String.intercalate "\n"
    (sample.map (fun (nm, e) =>
      let pad := String.ofList (List.replicate (max 1 (22 - nm.length)) ' ')
      "  ¬(" ++ nm ++ ")" ++ pad ++ "⊣⊢ " ++ classify e))

/-- Sanity: the four candidates really are pairwise distinct. -/
def repsDistinct : String :=
  String.intercalate "  "
    (reps.flatMap (fun (n1, r1) =>
      reps.filterMap (fun (n2, r2) =>
        if n1 == n2 then none
        else if interdB r1 r2 then some (n1 ++ "=" ++ n2) else none)))

end ErneBool

#eval IO.println ("collapses among the four (expect none): " ++ ErneBool.repsDistinct)
#eval IO.println ErneBool.report
