import wip.rnDict
import wip.rungPinned
import LaxLogic.PLLSearchConf

/-!
# The open cells against the FIVE-world battery

`sep_9_12` needed a five-world countermodel, and the searcher's default battery
is every frame up to FOUR worlds.  That gap explains a large part of the `?`
column.  `wip/rnc_probe.lean` already builds `framesRooted5`: the rooted
five-world mutually-confluent models, canonical up to permutation of the
non-root worlds, exhaustive at five by the generated-submodel argument.

These are fully decorated `FinCM`s and our formulas are variable-free, so no
search is involved at all: `FinCM.checkB M w Γ C` is a kernel-level computation,
and a hit is directly pinnable by `FinCM.not_provable_of_check`.

Run: `scripts/probe 900 five > wip/five_out.txt`.
-/

open PLLFormula PLLND PLLND.SemUI.RND

namespace Five

open PLLND.RNEmbed
open PLLND.RNC (confB)

/-! ## The rooted five-world battery, copied from `wip/rnc_probe.lean`
(that module declares its own top-level `main`, so it cannot be imported). -/

def subsets {α : Type} : List α → List (List α)
  | [] => [[]]
  | a :: as => (subsets as) ++ (subsets as).map (a :: ·)

def pairsOf (n : Nat) : List (Nat × Nat) :=
  (List.range n).flatMap fun a =>
    (List.range n).filterMap fun b => if a = b then none else some (a, b)

def memP (r : List (Nat × Nat)) (p : Nat × Nat) : Bool := decide (p ∈ r)

def transL (r : List (Nat × Nat)) : Bool :=
  r.all fun p => r.all fun q =>
    !(decide (p.2 = q.1)) || memP r (p.1, q.2)

def antisymL (r : List (Nat × Nat)) : Bool :=
  r.all fun p => !(memP r (p.2, p.1))

def upClosedL (r : List (Nat × Nat)) (s : List Nat) : Bool :=
  s.all fun w => r.all fun p =>
    !(decide (p.1 = w)) || decide (p.2 ∈ s)

def ltKey : List Nat → List Nat → Bool
  | [], [] => false
  | [], _ :: _ => true
  | _ :: _, [] => false
  | a :: as, b :: bs =>
    if a < b then true else if b < a then false else ltKey as bs

def keyOf (r : List (Nat × Nat)) : List Nat :=
  (r.map fun q => q.1 * 16 + q.2).mergeSort (fun a b => a ≤ b)

def pairKey (ri rm : List (Nat × Nat)) : List Nat :=
  keyOf ri ++ [999] ++ keyOf rm

def applyPerm (p : List Nat) (k : Nat) : Nat :=
  if k = 0 then 0 else p.getD (k - 1) k

def isCanon (ri4 rm : List (Nat × Nat)) : Bool :=
  let k0 := pairKey ri4 rm
  ([1, 2, 3, 4].permutations).all fun p =>
    let ri' := ri4.map fun q => (applyPerm p q.1, applyPerm p q.2)
    let rm' := rm.map fun q => (applyPerm p q.1, applyPerm p q.2)
    !(ltKey (pairKey ri' rm') k0)

def framesRooted5 : List FinCM :=
  let inner := (pairsOf 4).map fun q => (q.1 + 1, q.2 + 1)
  ((subsets inner).filter fun ri4 => transL ri4 && antisymL ri4).flatMap
    fun ri4 =>
      let ri := ((List.range 4).map fun k => (0, k + 1)) ++ ri4
      (((subsets ri).filter transL).filter (isCanon ri4)).flatMap fun rm =>
        if confB ⟨5, ri, rm, [], []⟩ then
          ((subsets (List.range 5)).filter (upClosedL ri)).filterMap
            fun fall =>
              let M : FinCM := ⟨5, ri, rm, fall, []⟩
              if M.wellB && confB M then some M else none
        else []

open PLLND.RNC (confB)

/-- Scan the five-world battery for a countermodel to `[A] ⊢ B`. -/
def scan (A B : PLLFormula) : Option (FinCM × Nat) := Id.run do
  for M in framesRooted5 do
    for w in List.range 5 do
      if FinCM.checkB M w [A] B then return some (M, w)
  return none

/-- The cells left open by the four-world battery. -/
def openCells : List (String × PLLFormula × String × PLLFormula) :=
  [("q5", q5, "q7", q7), ("q5", q5, "q8", q8), ("q8", q8, "q11", q11),
   ("q9", q9, "q8", q8), ("q10", q10, "q8", q8), ("q10", q10, "q13", q13),
   ("q11", q11, "q8", q8), ("q11", q11, "q13", q13), ("q12", q12, "q8", q8),
   ("q12", q12, "q11", q11), ("q13", q13, "q11", q11), ("q14", q14, "q8", q8),
   ("q14", q14, "q11", q11), ("q14", q14, "q13", q13),
   -- rung cells left open by wip/rungPinned.lean
   ("q5", q5, "t8", t8), ("t8", t8, "q9", q9), ("q9", q9, "t8", t8),
   ("t8", t8, "q12", q12), ("q12", q12, "t8", t8),
   ("t9", t9, "q8", q8), ("q8", q8, "t9", t9),
   ("t9", t9, "q13", q13), ("q13", q13, "t9", t9),
   ("t9", t9, "q14", q14), ("q14", q14, "t9", t9)]

def main : IO Unit := do
  let out ← IO.getStdout
  let pl (x : String) : IO Unit := do out.putStrLn x; out.flush
  pl "-- GENERATED by wip/five.lean -- do not edit by hand."
  pl "import wip.rnDict"
  pl "import wip.rungPinned"
  pl "import LaxLogic.PLLCountermodelEmit"
  pl "import LaxLogic.PLLSearchConf"
  pl ""
  pl "/-!"
  pl "# Cells closed by the FIVE-world battery"
  pl ""
  pl "`sep_9_12` needed a five-world countermodel and the searcher's default battery"
  pl "stops at four, which is why these cells read `?` however long the search ran."
  pl "Every model below is rooted, mutually confluent, and found by exhaustive scan of"
  pl "the 1459 canonical rooted five-world frames -- no proof search is involved."
  pl "-/"
  pl ""
  pl "open PLLFormula"
  pl "namespace PLLND"
  pl "namespace RNEmbed"
  pl "open SemUI PLLND.SemUI.RND"
  pl ""
  let mut hit := 0
  let mut miss : List String := []
  for (na, A, nb, B) in openCells do
    let r ← IO.lazyPure (fun _ => scan A B)
    let _ ← IO.lazyPure (fun _ => (r.map fun p => p.2).getD 0)
    match r with
    | some (M, w) =>
        hit := hit + 1
        pl s!"/-- Refuted at world {w} of a rooted five-world model \
(mutually confluent: {RNC.confB M}). -/"
        pl s!"theorem five_{na}_nle_{nb} : ¬ Deriv [{na}] {nb} :="
        pl s!"  FinCM.not_provable_of_check (M := {repr M}) (w := {w}) (by decide)"
        pl ""
    | none => miss := miss ++ [s!"{na} |- {nb}"]
  pl "end RNEmbed"
  pl "end PLLND"
  pl ""
  pl s!"-- {hit} cells closed at five worlds; {miss.length} still open:"
  for m in miss do pl s!"--   {m}"

end Five

def main : IO Unit := Five.main
