-- GENERATED by wip/five.lean -- do not edit by hand.
import wip.rnDict
import wip.rungPinned
import LaxLogic.PLLCountermodelEmit
import LaxLogic.PLLSearchConf

/-!
# Cells closed by the FIVE-world battery

`sep_9_12` needed a five-world countermodel and the searcher's default battery
stops at four, which is why these cells read `?` however long the search ran.
Every model below is rooted, mutually confluent, and found by exhaustive scan of
the 1459 canonical rooted five-world frames -- no proof search is involved.
-/

open PLLFormula
namespace PLLND
namespace RNEmbed
open SemUI PLLND.SemUI.RND

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q5_nle_q7 : [q5] ⊬ q7 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q5_nle_q8 : [q5] ⊬ q8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q8_nle_q11 : [q8] ⊬ q11 :=
  FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], rm := [(2, 3)], fall := [3], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q9_nle_q8 : [q9] ⊬ q8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q10_nle_q8 : [q10] ⊬ q8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q10_nle_q13 : [q10] ⊬ q13 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], rm := [(1, 2), (4, 3)], fall := [3], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q11_nle_q8 : [q11] ⊬ q8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q11_nle_q13 : [q11] ⊬ q13 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], rm := [(1, 2), (4, 3)], fall := [3], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q12_nle_q8 : [q12] ⊬ q8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q13_nle_q11 : [q13] ⊬ q11 :=
  FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], rm := [(2, 3)], fall := [3], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q14_nle_q8 : [q14] ⊬ q8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q14_nle_q11 : [q14] ⊬ q11 :=
  FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], rm := [(2, 3)], fall := [3], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q5_nle_t8 : [q5] ⊬ t8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_t8_nle_q9 : [t8] ⊬ q9 :=
  FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], rm := [(2, 3)], fall := [3], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q9_nle_t8 : [q9] ⊬ t8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_t8_nle_q12 : [t8] ⊬ q12 :=
  FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (2, 3)], rm := [(2, 3)], fall := [3], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_q12_nle_t8 : [q12] ⊬ t8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_t9_nle_q8 : [t9] ⊬ q8 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (3, 2), (4, 2)], rm := [(0, 1), (3, 2), (4, 2)], fall := [2], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_t9_nle_q13 : [t9] ⊬ q13 :=
 FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (4, 3)], rm := [(1, 2), (4, 3)], fall := [3], val := [] }) (w := 0) (by decide)

/-- Refuted at world 0 of a rooted five-world model (mutually confluent: true). -/
theorem five_t9_nle_q14 : [t9] ⊬ q14 :=
  FinCM.not_provable_of_check (M := { n := 5, ri := [(0, 1), (0, 2), (0, 3), (0, 4), (1, 2)], rm := [(1, 2)], fall := [2], val := [] }) (w := 0) (by decide)

end RNEmbed
end PLLND

-- 20 cells closed at five worlds; 5 still open:
--   q12 |- q11
--   q14 |- q13
--   q8 |- t9
--   q13 |- t9
--   q14 |- t9
