import wip.atomForce
import LaxLogic.PLLSearchPin

/-!
# The floor branch at a `⊃`-shaped goal, and where the residue finally sits

`wip/atomForce.lean` closes the floor branches at an **atom** goal uniformly in
the configuration.  `wip/sealprobe7.lean` then asks the oracle, for each of the
other two jump-goal shapes and for each case of the analysis, which disjunct of
the target table that case can reach.  The answer is sharp:

| goal shape | whole obligation | route taken by the cases |
|---|---|---|
| atom | proved in general (`AtomForce.floor_branch_atom`) | the goal clause |
| `A ⊃ B` | **PROVED**, 9 nodes, at both configurations | the goal clause (disjunct 0) |
| `◯A` | `~` | **no case reaches any target disjunct** |

So the `⊃`-shaped case behaves exactly like the atom case — every case of the
analysis reaches the target's own goal clause — while the **boxed** case reaches
nothing.  That is where the residue of the whole development now sits, and it is
a single goal shape.

This file pins the two `⊃`-shaped instances, so the middle row of that table is
a theorem rather than probe output.  Generated by `#pinsrc` and re-elaborated
here.
-/

open PLLFormula PLLND

namespace PLLND
namespace FloorImp

def gam (a b : String) : PLLFormula := ((prop a).somehow).ifThen (prop b)

/-- One live γ-clause. -/
def S1 : Finset PLLFormula :=
  { gam "r" "s", (prop "r").somehow, prop "r", prop "s", prop "z" }

def G1 : List PLLFormula := [gam "r" "s"]

/-- Two live γ-clauses, so the grown context still has one. -/
def S2 : Finset PLLFormula :=
  { gam "r" "s", (prop "r").somehow, prop "r", prop "s",
    gam "u" "v", (prop "u").somehow, prop "u", prop "v", prop "z" }

def G2 : List PLLFormula := [gam "r" "s", gam "u" "v"]

/-- The floor branch at the `⊃`-shaped goal `r ⊃ s`, pinned by `#pinsrc` (9 nodes). -/
theorem floor_branch_imp_S1 :
    G4c [itpE "p" S1 4 2 G1, (((itpE "p" S1 3 1 G1).ifThen (itpA "p" S1 3 1 G1 (prop "r").somehow)).somehow), itpA "p" S1 4 1 (prop "s" :: G1) ((prop "r").ifThen (prop "s"))]
      (orAll (itpAoth "p" S1 3 1 G1 ((prop "r").ifThen (prop "s")))) :=
  (((.orR1 (.impR (.orR1 (.andL (.head _) (.andL (.tail _ (.head _)) (.impLOr (.head _) (.impLProp (.head _) (.tail _ (.tail _ (.tail _ (.tail _ (.head _))))) (.andL (.head _) (.init (.head _))))))))))) :
    G4cTm [itpE "p" S1 4 2 G1, (((itpE "p" S1 3 1 G1).ifThen (itpA "p" S1 3 1 G1 (prop "r").somehow)).somehow), itpA "p" S1 4 1 (prop "s" :: G1) ((prop "r").ifThen (prop "s"))]
      (orAll (itpAoth "p" S1 3 1 G1 ((prop "r").ifThen (prop "s"))))).toG4c

/-- The floor branch at the `⊃`-shaped goal `r ⊃ s`, pinned by `#pinsrc` (9 nodes). -/
theorem floor_branch_imp_S2 :
    G4c [itpE "p" S2 4 2 G2, (((itpE "p" S2 3 1 G2).ifThen (itpA "p" S2 3 1 G2 (prop "r").somehow)).somehow), itpA "p" S2 4 1 (prop "s" :: G2) ((prop "r").ifThen (prop "s"))]
      (orAll (itpAoth "p" S2 3 1 G2 ((prop "r").ifThen (prop "s")))) :=
  (((.orR1 (.impR (.orR1 (.andL (.head _) (.andL (.tail _ (.head _)) (.impLOr (.head _) (.impLProp (.head _) (.tail _ (.tail _ (.tail _ (.tail _ (.head _))))) (.andL (.head _) (.init (.head _))))))))))) :
    G4cTm [itpE "p" S2 4 2 G2, (((itpE "p" S2 3 1 G2).ifThen (itpA "p" S2 3 1 G2 (prop "r").somehow)).somehow), itpA "p" S2 4 1 (prop "s" :: G2) ((prop "r").ifThen (prop "s"))]
      (orAll (itpAoth "p" S2 3 1 G2 ((prop "r").ifThen (prop "s"))))).toG4c


end FloorImp
end PLLND

/-! ### Axiom audit -/

/--
info: 'PLLND.FloorImp.floor_branch_imp_S1' depends on axioms: [propext, Quot.sound]
-/
#guard_msgs in
#print axioms PLLND.FloorImp.floor_branch_imp_S1

/--
info: 'PLLND.FloorImp.floor_branch_imp_S2' depends on axioms: [propext, Quot.sound]
-/
#guard_msgs in
#print axioms PLLND.FloorImp.floor_branch_imp_S2
