import wip.schemeext

/-!
# The booleanization of RN(◯,{}) has exactly four elements

`𝔟⊥ = {y | y = ¬¬y}`, the regular elements of the closed fragment, is the
**image of `¬`** — because `¬¬¬x ⊣⊢ ¬x` always, every regular element is `¬` of
something and every `¬x` is regular.  So the question "how big is the
booleanization?" is the question "how many values does `¬` take on closed
formulas?", and the theorem below answers it:

> For every variable-free `A`, `¬A` is interderivable with one of
> `⊥`, `¬◯⊥`, `¬¬◯⊥`, `⊤`.

By Glivenko–Frink `𝔟⊥` is a boolean lattice; with four elements it is the free
boolean algebra on one generator, generated by `¬¬◯⊥`.  So `¬¬` maps RN(◯,{})
onto the four-element **classical** rung of `wip/classical.lean`
(`varfree_exactly_four`, representatives `⊥, ◯⊥, ¬◯⊥, ⊤`) with `◯⊥ ↦ ¬¬◯⊥` —
the four-element rung of the ladder is the boolean part of the closed
fragment, not merely one rung among others.

## The proof

Two dichotomies from `wip/schemeext.lean`, and a four-way case split.  Write
`nb = ¬◯⊥` and `nnb = ¬¬◯⊥`.

* `dich_nobot`: under `nb`, every variable-free `A` is `⊣⊢ ⊥` or `⊣⊢ ⊤`;
* `dich_bot`:   under `◯⊥`, the same.

Let `a` abbreviate "`nb ⊢ A`" and `b` abbreviate "`◯⊥ ⊢ A`".  Then

| a | b | `¬A` | why |
|---|---|---|---|
| yes | yes | `⊥`   | `¬A ⊢ nb` from b and `¬A ⊢ nnb` from a; `nnb = ¬nb` |
| yes | no  | `nnb` | `¬A ⊢ nnb` from a; conversely b's failure gives `A ⊢ nb` |
| no  | yes | `nb`  | `¬A ⊢ nb` from b; conversely a's failure is exactly `nb, A ⊢ ⊥` |
| no  | no  | `⊤`   | `A ⊢ nnb` and `A ⊢ nb`, whose meet is `⊥`, so `⊢ ¬A` |

The last case is the one that looks as though it needs `◯⊥ ∨ ¬◯⊥` — which is
underivable — and does not: it goes through the meet `nb ∧ nnb = ⊥` instead.

Everything is proved for an arbitrary axiom set `X`, so it holds for plain PLL
and for every scheme extension; only the *distinctness* of the four is
special to PLL.
-/

namespace PLLND
namespace NegFour

open PLLFormula SchemeExt
open NoFall (VarFree)

variable {X : PLLFormula → Prop}

/-- `¬◯⊥`. -/
abbrev nb : PLLFormula := NoFall.nobot
/-- `¬¬◯⊥`. -/
abbrev nnb : PLLFormula := nnbot

/-- The four values of `¬` on the closed fragment: `⊥`, `¬◯⊥`, `¬¬◯⊥`, `⊤`. -/
def nrep (i : Fin 4) : PLLFormula :=
  if i.val = 0 then falsePLL
  else if i.val = 1 then nb
  else if i.val = 2 then nnb
  else truePLL

/-! ## Two small facts about `nb` and `nnb` -/

/-- `nnb` is literally `¬nb`, so together they are absurd. -/
theorem nb_nnb_absurd (Δ : List PLLFormula) (hnb : nb ∈ Δ) (hnnb : nnb ∈ Δ) :
    DerivX X Δ falsePLL :=
  DerivX.mp (φ := nb) (ψ := falsePLL) (DerivX.hyp hnnb) (DerivX.hyp hnb)

/-- From `P, A ⊢ ⊥` conclude `A ⊢ ¬P` — the shape both dichotomy branches
deliver, with the hypothesis order the classification needs. -/
theorem neg_of_absurd {P A : PLLFormula} (h : DerivX X [P, A] falsePLL) :
    DerivX X [A] (notPLL P) :=
  DerivX.deduction (h.rename (by intro θ hθ; simp at hθ ⊢; tauto))

/-! ## The classification -/

/-- **The booleanization of the closed fragment is four-element.**  For every
variable-free `A`, `¬A` is interderivable with one of `⊥`, `¬◯⊥`, `¬¬◯⊥`, `⊤`.

Since `𝔟⊥` is exactly the image of `¬` (as `¬¬¬x ⊣⊢ ¬x`), this says the
regular elements of RN(◯,{}) are just those four. -/
theorem neg_exactly_four (A : PLLFormula) (hA : VarFree A) :
    ∃ i : Fin 4, Interd X [] (notPLL A) (nrep i) := by
  obtain ⟨x, hx⟩ := dich_nobot (X := X) (Δ := [nb]) (by simp) A hA
  obtain ⟨y, hy⟩ := dich_bot (X := X) (Δ := [boxBot]) (by simp) A hA
  -- `¬P ⊢ ¬Q` whenever `Q ⊢ P`, the move used in three of the four cases
  have contra : ∀ {P Q : PLLFormula}, DerivX X [Q] P → DerivX X [notPLL P] (notPLL Q) :=
    fun {P Q} h => DerivX.deduction (DerivX.mp (φ := P) (ψ := falsePLL)
      (DerivX.hyp (by simp)) (h.rename (by intro θ hθ; simp at hθ ⊢; tauto)))
  have swap : ∀ {P Q : PLLFormula}, DerivX X [P, Q] falsePLL → DerivX X [Q, P] falsePLL :=
    fun {P Q} h => h.rename (by intro θ hθ; simp at hθ ⊢; tauto)
  fin_cases x <;> fin_cases y
  · -- `nb, A ⊢ ⊥` and `◯⊥, A ⊢ ⊥`: then `A ⊢ nnb` and `A ⊢ nb`, whose meet is
    -- `⊥`, so `⊢ ¬A` outright — class `⊤`
    refine ⟨3, DerivX.top, ?_⟩
    show DerivX X [truePLL] (notPLL A)
    have h1 : DerivX X [A] nnb := neg_of_absurd (P := nb) (swap hx.1)
    have h2 : DerivX X [A] nb := neg_of_absurd (P := boxBot) (swap hy.1)
    exact (DerivX.deduction (DerivX.mp (φ := nb) (ψ := falsePLL) h1 h2)).rename
      (by intro θ hθ; simp at hθ ⊢)
  · -- `nb, A ⊢ ⊥` and `◯⊥ ⊢ A` — class `¬◯⊥`
    refine ⟨1, ?_, ?_⟩
    · show DerivX X [notPLL A] nb
      exact contra (DerivX.cut DerivX.top hy.2)
    · show DerivX X [nb] (notPLL A)
      exact DerivX.deduction hx.1
  · -- `nb ⊢ A` and `◯⊥, A ⊢ ⊥` — class `¬¬◯⊥`
    refine ⟨2, ?_, ?_⟩
    · show DerivX X [notPLL A] nnb
      exact contra (DerivX.cut DerivX.top hx.2)
    · show DerivX X [nnb] (notPLL A)
      exact contra (neg_of_absurd (P := boxBot) (swap hy.1))
  · -- `nb ⊢ A` and `◯⊥ ⊢ A`: `¬A` entails both `nb` and `nnb` — class `⊥`
    refine ⟨0, ?_, bot_imp _⟩
    show DerivX X [notPLL A] falsePLL
    exact DerivX.mp (φ := nb) (ψ := falsePLL)
      (contra (DerivX.cut DerivX.top hx.2)) (contra (DerivX.cut DerivX.top hy.2))

/-- The `∨`-free corollary: `¬A` never needs a disjunction.  All four
representatives are `∨`-free, so the image of `¬` on the closed fragment lies
inside the eight-element `∨`-free algebra of Bezhanishvili et al.'s Figure 6
(`wip/nisFig6.lean`) — in fact inside four of its eight elements. -/
theorem neg_image_orFree (A : PLLFormula) (hA : VarFree A) :
    ∃ i : Fin 4, Interd X [] (notPLL A) (nrep i) ∧
      (nrep i = falsePLL ∨ nrep i = nb ∨ nrep i = nnb ∨ nrep i = truePLL) := by
  obtain ⟨i, hi⟩ := neg_exactly_four (X := X) A hA
  refine ⟨i, hi, ?_⟩
  fin_cases i <;> simp [nrep]

end NegFour
end PLLND

/-! ### Axiom audit — measured and pinned on creation (2026-08-07); every entry
transcribed from actual `#print axioms` output. -/

/-- info: 'PLLND.NegFour.neg_of_absurd' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms PLLND.NegFour.neg_of_absurd

/--
info: 'PLLND.NegFour.neg_exactly_four' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms PLLND.NegFour.neg_exactly_four

/--
info: 'PLLND.NegFour.neg_image_orFree' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms PLLND.NegFour.neg_image_orFree
