import LaxLogic.PLLG4UITrunc
import absorb_base
import adequacy

/-!
# WIP: packaging — the uniform-interpolation tower assembled

The packaging layer over the truncated quantifiers: the piece-closure
space `pieceClosure`/`pieceClosureList` (the canonical `PieceClosed`
space generated by a formula/context), the packaged quantifier
wrappers `existsP`/`forallP` with the p-free short circuit, and the
four Pitts UI conditions:

* (i) p-freeness — `existsP_atoms`, `forallP_atoms` — **outright**;
* (ii) `φ ⊢ ∃p φ` — `existsP_sound` — **outright**;
* (iii) `∀p C ⊢ C` — `forallP_sound` — **outright**;
* (iv) ∃-universality `existsP_adequate` and ∀-couniversality
  `forallP_adequate` — **modulo two named indifference hypotheses**,
  taken as explicit arguments (not sorries):
  - `FuelIndiffE`/`FuelIndiffA`: above the `uiFuel` threshold the
    truncated quantifiers are fuel-independent (in-flight:
    `wip/indiff.lean` will discharge);
  - `SpaceIndiffE`/`SpaceIndiffA`: two piece-closed spaces containing
    the closure of the data give *equal* quantifiers (separate
    discharge lemma).

On the ∀ side the formula-level condition **is** obtained cleanly:
`forallP` packages with `Γ = []`, and the ambient `E`-component
`itpE p S f B []` of the adequacy pair is outright provable
(`itp_sound` at the empty context), so it cuts away — no `E ⇢ A`
sequent residue survives at the packaged interface.  The honest
sequent-level statement remains `itp_adequate` itself.

Also included (§5): the Pitts factorization corollaries
`∃p (θ ∧ φ) ⊣⊢ θ ∧ ∃p φ` for p-free `θ`, derived from (i)–(iv) alone.

Build (absorb_base and adequacy are consumed as precompiled oleans):

    lake env lean wip/absorb_base.lean -o <depdir>/absorb_base.olean
    lake env sh -c 'LEAN_PATH="$LEAN_PATH:<depdir>" lean wip/adequacy.lean -o <depdir>/adequacy.olean'
    lake env sh -c 'LEAN_PATH="$LEAN_PATH:<depdir>" lean wip/packaging.lean'
-/

open PLLFormula

set_option maxHeartbeats 1600000

namespace PLLND

/-! ### §1 The piece-closure space

`pieceClosure φ` is the least set containing `φ` and closed under the
seven `PieceClosed` piece-formations; well-founded on Dyckhoff weight
(the `∧`-counts-2 convention is exactly what makes the curried
`impAnd` piece strictly smaller). -/

/-- Piece closure of a single formula. -/
def pieceClosure : PLLFormula → Finset PLLFormula
  | .prop a => {PLLFormula.prop a}
  | .falsePLL => {falsePLL}
  | .and A B => insert (A.and B) (pieceClosure A ∪ pieceClosure B)
  | .or A B => insert (A.or B) (pieceClosure A ∪ pieceClosure B)
  | .ifThen (.prop a) D =>
      insert ((PLLFormula.prop a).ifThen D)
        (pieceClosure (PLLFormula.prop a) ∪ pieceClosure D)
  | .ifThen .falsePLL D =>
      insert (falsePLL.ifThen D) (pieceClosure falsePLL ∪ pieceClosure D)
  | .ifThen (.and A B) D =>
      insert ((A.and B).ifThen D)
        (pieceClosure (A.and B) ∪ pieceClosure D
          ∪ pieceClosure (A.ifThen (B.ifThen D)))
  | .ifThen (.or A B) D =>
      insert ((A.or B).ifThen D)
        (pieceClosure (A.or B) ∪ pieceClosure D
          ∪ pieceClosure (A.ifThen D) ∪ pieceClosure (B.ifThen D))
  | .ifThen (.ifThen A B) D =>
      insert ((A.ifThen B).ifThen D)
        (pieceClosure (A.ifThen B) ∪ pieceClosure D
          ∪ pieceClosure (B.ifThen D))
  | .ifThen (.somehow X) D =>
      insert ((somehow X).ifThen D)
        (pieceClosure (somehow X) ∪ pieceClosure D)
  | .somehow χ => insert χ.somehow (pieceClosure χ)
termination_by φ => φ.weight
decreasing_by all_goals (simp only [PLLFormula.weight]; omega)

/-! Named unfolding equations (the WF equations, fixed under stable names). -/

theorem pieceClosure_prop (a : String) :
    pieceClosure (prop a) = {PLLFormula.prop a} := by simp [pieceClosure]

theorem pieceClosure_false :
    pieceClosure falsePLL = {falsePLL} := by simp [pieceClosure]

theorem pieceClosure_and (A B : PLLFormula) :
    pieceClosure (A.and B)
      = insert (A.and B) (pieceClosure A ∪ pieceClosure B) := by
  simp [pieceClosure]

theorem pieceClosure_or (A B : PLLFormula) :
    pieceClosure (A.or B)
      = insert (A.or B) (pieceClosure A ∪ pieceClosure B) := by
  simp [pieceClosure]

theorem pieceClosure_impProp (a : String) (D : PLLFormula) :
    pieceClosure ((prop a).ifThen D)
      = insert ((PLLFormula.prop a).ifThen D)
          (pieceClosure (prop a) ∪ pieceClosure D) := by
  simp [pieceClosure]

theorem pieceClosure_impFalse (D : PLLFormula) :
    pieceClosure (falsePLL.ifThen D)
      = insert (falsePLL.ifThen D)
          (pieceClosure falsePLL ∪ pieceClosure D) := by
  simp [pieceClosure]

theorem pieceClosure_impAnd (A B D : PLLFormula) :
    pieceClosure ((A.and B).ifThen D)
      = insert ((A.and B).ifThen D)
          (pieceClosure (A.and B) ∪ pieceClosure D
            ∪ pieceClosure (A.ifThen (B.ifThen D))) := by
  simp [pieceClosure]

theorem pieceClosure_impOr (A B D : PLLFormula) :
    pieceClosure ((A.or B).ifThen D)
      = insert ((A.or B).ifThen D)
          (pieceClosure (A.or B) ∪ pieceClosure D
            ∪ pieceClosure (A.ifThen D) ∪ pieceClosure (B.ifThen D)) := by
  simp [pieceClosure]

theorem pieceClosure_impImp (A B D : PLLFormula) :
    pieceClosure ((A.ifThen B).ifThen D)
      = insert ((A.ifThen B).ifThen D)
          (pieceClosure (A.ifThen B) ∪ pieceClosure D
            ∪ pieceClosure (B.ifThen D)) := by
  simp [pieceClosure]

theorem pieceClosure_impBox (X D : PLLFormula) :
    pieceClosure ((somehow X).ifThen D)
      = insert ((somehow X).ifThen D)
          (pieceClosure (somehow X) ∪ pieceClosure D) := by
  simp [pieceClosure]

theorem pieceClosure_box (χ : PLLFormula) :
    pieceClosure χ.somehow = insert χ.somehow (pieceClosure χ) := by
  simp [pieceClosure]

@[simp] theorem self_mem_pieceClosure (φ : PLLFormula) :
    φ ∈ pieceClosure φ := by
  cases φ with
  | prop a => simp [pieceClosure_prop]
  | falsePLL => simp [pieceClosure_false]
  | and A B => simp [pieceClosure_and]
  | or A B => simp [pieceClosure_or]
  | ifThen X D =>
      cases X with
      | prop a => simp [pieceClosure_impProp]
      | falsePLL => simp [pieceClosure_impFalse]
      | and A B => simp [pieceClosure_impAnd]
      | or A B => simp [pieceClosure_impOr]
      | ifThen A B => simp [pieceClosure_impImp]
      | somehow X => simp [pieceClosure_impBox]
  | somehow χ => simp [pieceClosure_box]

/-- Transitive containment: a member's closure is contained in the
closure.  This is what turns the seven per-shape membership facts
into `PieceClosed` for arbitrary unions of closures. -/
theorem pieceClosure_trans :
    ∀ (φ : PLLFormula), ∀ ψ ∈ pieceClosure φ,
      pieceClosure ψ ⊆ pieceClosure φ := by
  intro φ
  induction φ using pieceClosure.induct with
  | case1 a =>
      intro ψ hψ
      rw [pieceClosure_prop] at hψ ⊢
      rw [Finset.mem_singleton.mp hψ, pieceClosure_prop]
  | case2 =>
      intro ψ hψ
      rw [pieceClosure_false] at hψ ⊢
      rw [Finset.mem_singleton.mp hψ, pieceClosure_false]
  | case3 A B ihA ihB =>
      intro ψ hψ
      rw [pieceClosure_and] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · rcases Finset.mem_union.mp h with h | h
        · refine (ihA ψ h).trans fun x hx => ?_
          rw [pieceClosure_and]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
        · refine (ihB ψ h).trans fun x hx => ?_
          rw [pieceClosure_and]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
  | case4 A B ihA ihB =>
      intro ψ hψ
      rw [pieceClosure_or] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · rcases Finset.mem_union.mp h with h | h
        · refine (ihA ψ h).trans fun x hx => ?_
          rw [pieceClosure_or]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
        · refine (ihB ψ h).trans fun x hx => ?_
          rw [pieceClosure_or]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
  | case5 a D ihX ihD =>
      intro ψ hψ
      rw [pieceClosure_impProp] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · rcases Finset.mem_union.mp h with h | h
        · refine (ihX ψ h).trans fun x hx => ?_
          rw [pieceClosure_impProp]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
        · refine (ihD ψ h).trans fun x hx => ?_
          rw [pieceClosure_impProp]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
  | case6 D ihX ihD =>
      intro ψ hψ
      rw [pieceClosure_impFalse] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · rcases Finset.mem_union.mp h with h | h
        · refine (ihX ψ h).trans fun x hx => ?_
          rw [pieceClosure_impFalse]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
        · refine (ihD ψ h).trans fun x hx => ?_
          rw [pieceClosure_impFalse]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
  | case7 A B D ihX ihD ihC =>
      intro ψ hψ
      rw [pieceClosure_impAnd] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · rcases Finset.mem_union.mp h with h | h
        · rcases Finset.mem_union.mp h with h | h
          · refine (ihX ψ h).trans fun x hx => ?_
            rw [pieceClosure_impAnd]
            simp only [Finset.mem_insert, Finset.mem_union]; tauto
          · refine (ihD ψ h).trans fun x hx => ?_
            rw [pieceClosure_impAnd]
            simp only [Finset.mem_insert, Finset.mem_union]; tauto
        · refine (ihC ψ h).trans fun x hx => ?_
          rw [pieceClosure_impAnd]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
  | case8 A B D ihX ihD ihL ihR =>
      intro ψ hψ
      rw [pieceClosure_impOr] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · rcases Finset.mem_union.mp h with h | h
        · rcases Finset.mem_union.mp h with h | h
          · rcases Finset.mem_union.mp h with h | h
            · refine (ihX ψ h).trans fun x hx => ?_
              rw [pieceClosure_impOr]
              simp only [Finset.mem_insert, Finset.mem_union]; tauto
            · refine (ihD ψ h).trans fun x hx => ?_
              rw [pieceClosure_impOr]
              simp only [Finset.mem_insert, Finset.mem_union]; tauto
          · refine (ihL ψ h).trans fun x hx => ?_
            rw [pieceClosure_impOr]
            simp only [Finset.mem_insert, Finset.mem_union]; tauto
        · refine (ihR ψ h).trans fun x hx => ?_
          rw [pieceClosure_impOr]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
  | case9 A B D ihX ihD ihC =>
      intro ψ hψ
      rw [pieceClosure_impImp] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · rcases Finset.mem_union.mp h with h | h
        · rcases Finset.mem_union.mp h with h | h
          · refine (ihX ψ h).trans fun x hx => ?_
            rw [pieceClosure_impImp]
            simp only [Finset.mem_insert, Finset.mem_union]; tauto
          · refine (ihD ψ h).trans fun x hx => ?_
            rw [pieceClosure_impImp]
            simp only [Finset.mem_insert, Finset.mem_union]; tauto
        · refine (ihC ψ h).trans fun x hx => ?_
          rw [pieceClosure_impImp]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
  | case10 X D ihX ihD =>
      intro ψ hψ
      rw [pieceClosure_impBox] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · rcases Finset.mem_union.mp h with h | h
        · refine (ihX ψ h).trans fun x hx => ?_
          rw [pieceClosure_impBox]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
        · refine (ihD ψ h).trans fun x hx => ?_
          rw [pieceClosure_impBox]
          simp only [Finset.mem_insert, Finset.mem_union]; tauto
  | case11 χ ihχ =>
      intro ψ hψ
      rw [pieceClosure_box] at hψ
      rcases Finset.mem_insert.mp hψ with rfl | h
      · exact Finset.Subset.refl _
      · refine (ihχ ψ h).trans fun x hx => ?_
        rw [pieceClosure_box]
        simp only [Finset.mem_insert]; tauto

/-- Piece closure of a context. -/
def pieceClosureList (Γ : List PLLFormula) : Finset PLLFormula :=
  Γ.toFinset.biUnion pieceClosure

/-- Γ-members are in the context closure. -/
theorem pieceClosureList_mem {Γ : List PLLFormula} {φ : PLLFormula}
    (h : φ ∈ Γ) : φ ∈ pieceClosureList Γ :=
  Finset.mem_biUnion.mpr ⟨φ, List.mem_toFinset.mpr h, self_mem_pieceClosure φ⟩

theorem pieceClosure_subset_pieceClosureList {Γ : List PLLFormula}
    {φ : PLLFormula} (h : φ ∈ Γ) : pieceClosure φ ⊆ pieceClosureList Γ :=
  fun _ hx => Finset.mem_biUnion.mpr ⟨φ, List.mem_toFinset.mpr h, hx⟩

@[simp] theorem pieceClosureList_singleton (φ : PLLFormula) :
    pieceClosureList [φ] = pieceClosure φ := by
  simp [pieceClosureList]

@[simp] theorem pieceClosureList_nil : pieceClosureList [] = ∅ := by
  simp [pieceClosureList]

/-- **The keystone**: context closures are piece-closed, so every
`itp_adequate` space side-condition is dischargeable at
`S := pieceClosureList Γ`. -/
theorem pieceClosed_pieceClosureList (Γ : List PLLFormula) :
    PieceClosed (pieceClosureList Γ) := by
  have step : ∀ {χ ψ : PLLFormula}, χ ∈ pieceClosureList Γ →
      ψ ∈ pieceClosure χ → ψ ∈ pieceClosureList Γ := by
    intro χ ψ hχ hψ
    obtain ⟨φ, hφ, hχφ⟩ := Finset.mem_biUnion.mp hχ
    exact Finset.mem_biUnion.mpr ⟨φ, hφ, pieceClosure_trans φ χ hχφ hψ⟩
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro A B h
    exact ⟨step h (by rw [pieceClosure_and]; simp),
      step h (by rw [pieceClosure_and]; simp)⟩
  · intro A B h
    exact ⟨step h (by rw [pieceClosure_or]; simp),
      step h (by rw [pieceClosure_or]; simp)⟩
  · intro X D h
    cases X with
    | prop a =>
        exact ⟨step h (by rw [pieceClosure_impProp]; simp),
          step h (by rw [pieceClosure_impProp]; simp)⟩
    | falsePLL =>
        exact ⟨step h (by rw [pieceClosure_impFalse]; simp),
          step h (by rw [pieceClosure_impFalse]; simp)⟩
    | and A B =>
        exact ⟨step h (by rw [pieceClosure_impAnd]; simp),
          step h (by rw [pieceClosure_impAnd]; simp)⟩
    | or A B =>
        exact ⟨step h (by rw [pieceClosure_impOr]; simp),
          step h (by rw [pieceClosure_impOr]; simp)⟩
    | ifThen A B =>
        exact ⟨step h (by rw [pieceClosure_impImp]; simp),
          step h (by rw [pieceClosure_impImp]; simp)⟩
    | somehow X =>
        exact ⟨step h (by rw [pieceClosure_impBox]; simp),
          step h (by rw [pieceClosure_impBox]; simp)⟩
  · intro A B D h
    exact step h (by rw [pieceClosure_impAnd]; simp)
  · intro A B D h
    exact ⟨step h (by rw [pieceClosure_impOr]; simp),
      step h (by rw [pieceClosure_impOr]; simp)⟩
  · intro A B D h
    exact step h (by rw [pieceClosure_impImp]; simp)
  · intro χ h
    exact step h (by rw [pieceClosure_box]; simp)

/-- Single-formula corollary of the keystone. -/
theorem pieceClosed_pieceClosure (φ : PLLFormula) :
    PieceClosed (pieceClosure φ) := by
  rw [← pieceClosureList_singleton]
  exact pieceClosed_pieceClosureList _

/-! ### §2 Packaged quantifiers -/

/-- Uniform fuel allotment: one past the recursion measure `mu` at
weight cap `S.sup weight + slot`; `slot` is `0` on the E-side and the
goal weight on the A-side (mirroring `mu`'s slot convention).  Kept a
`def` so the indifference threshold can be retuned in one place. -/
def uiFuel (S : Finset PLLFormula) (B slot : Nat) (Γ : List PLLFormula) : Nat :=
  mu S ((S.sup PLLFormula.weight) + slot) B slot Γ + 1

/-- Packaged ∃-quantifier: `itpE` over the piece closure of `φ`, at
the uniform fuel and one past the jump-state budget threshold, with
the p-free short circuit. -/
def existsP (p : String) (φ : PLLFormula) : PLLFormula :=
  if p ∈ φ.atoms then
    itpE p (pieceClosure φ)
      (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ])
      (kcap (pieceClosure φ) + 1) [φ]
  else φ

/-- Packaged ∀-quantifier: `itpA` over the piece closure of `C`, empty
antecedent context, uniform fuel, one past the budget threshold, with
the p-free short circuit. -/
def forallP (p : String) (C : PLLFormula) : PLLFormula :=
  if p ∈ C.atoms then
    itpA p (pieceClosure C)
      (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight [])
      (kcap (pieceClosure C) + 1) [] C
  else C

/-- p-free short circuit, definitional. -/
@[simp] theorem existsP_pfree {p : String} {φ : PLLFormula}
    (h : p ∉ φ.atoms) : existsP p φ = φ := by
  unfold existsP; exact if_neg h

/-- p-free short circuit, definitional. -/
@[simp] theorem forallP_pfree {p : String} {C : PLLFormula}
    (h : p ∉ C.atoms) : forallP p C = C := by
  unfold forallP; exact if_neg h

/-! ### §3 Pitts conditions (i)–(iii): outright -/

/-- (i∃) The packaged ∃ is p-free. -/
theorem existsP_atoms (p : String) (φ : PLLFormula) :
    p ∉ (existsP p φ).atoms := by
  unfold existsP
  split
  · exact (itp_pfree p _ _).1 _ _
  · assumption

/-- (i∀) The packaged ∀ is p-free. -/
theorem forallP_atoms (p : String) (C : PLLFormula) :
    p ∉ (forallP p C).atoms := by
  unfold forallP
  split
  · exact (itp_pfree p _ _).2 _ _ _
  · assumption

/-- (ii) `φ ⊢ ∃p φ`. -/
theorem existsP_sound (p : String) (φ : PLLFormula) :
    G4c [φ] (existsP p φ) := by
  unfold existsP
  split
  · exact G4c.iff_set.mpr ((itp_sound p (pieceClosure φ) _).1 _ [φ])
  · exact G4c.iden (.head _)

/-- (iii) `∀p C ⊢ C`. -/
theorem forallP_sound (p : String) (C : PLLFormula) :
    G4c [forallP p C] C := by
  unfold forallP
  split
  · refine G4c.iff_set.mpr ?_
    have h := (itp_sound p (pieceClosure C)
        (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight [])).2
      (kcap (pieceClosure C) + 1) [] C
    simpa using h
  · exact G4c.iden (.head _)

/-! ### §4 Pitts condition (iv): adequacy, modulo named hypotheses

The two indifference hypotheses.  These are the exact specs the
in-flight discharge lemmas must provide; both are stated relative to
piece-closed spaces containing the closure of the data (the only
instances this file uses), which is the weakest form the packaged
route needs. -/

/-- **Named hypothesis hFI (E side)**: above the `uiFuel` threshold,
`itpE` is fuel-indifferent (equal, not just interderivable). -/
def FuelIndiffE (p : String) : Prop :=
  ∀ (S : Finset PLLFormula) (b : Nat) (Γ : List PLLFormula) (f f' : Nat),
    PieceClosed S → pieceClosureList Γ ⊆ S →
    uiFuel S b 0 Γ ≤ f → uiFuel S b 0 Γ ≤ f' →
    itpE p S f b Γ = itpE p S f' b Γ

/-- **Named hypothesis hFI (A side)**: above the `uiFuel` threshold at
slot `C.weight`, `itpA` is fuel-indifferent. -/
def FuelIndiffA (p : String) : Prop :=
  ∀ (S : Finset PLLFormula) (b : Nat) (Γ : List PLLFormula) (C : PLLFormula)
    (f f' : Nat),
    PieceClosed S → pieceClosureList Γ ⊆ S → pieceClosure C ⊆ S →
    uiFuel S b C.weight Γ ≤ f → uiFuel S b C.weight Γ ≤ f' →
    itpA p S f b Γ C = itpA p S f' b Γ C

/-- **Named hypothesis hSI (E side)**: two piece-closed spaces both
containing the context closure give equal `itpE`. -/
def SpaceIndiffE (p : String) : Prop :=
  ∀ (S S' : Finset PLLFormula) (f b : Nat) (Γ : List PLLFormula),
    PieceClosed S → PieceClosed S' →
    pieceClosureList Γ ⊆ S → pieceClosureList Γ ⊆ S' →
    itpE p S f b Γ = itpE p S' f b Γ

/-- **Named hypothesis hSI (A side)**: two piece-closed spaces both
containing the context and goal closures give equal `itpA`. -/
def SpaceIndiffA (p : String) : Prop :=
  ∀ (S S' : Finset PLLFormula) (f b : Nat) (Γ : List PLLFormula)
    (C : PLLFormula),
    PieceClosed S → PieceClosed S' →
    pieceClosureList Γ ⊆ S → pieceClosureList Γ ⊆ S' →
    pieceClosure C ⊆ S → pieceClosure C ⊆ S' →
    itpA p S f b Γ C = itpA p S' f b Γ C

/-! Budget bookkeeping and G4c-to-G4s consumption helpers. -/

/-- `kcap` is monotone in the space. -/
theorem kcap_mono {S S' : Finset PLLFormula} (h : S ⊆ S') :
    kcap S ≤ kcap S' := by
  have hc := Finset.card_le_card h
  simp only [kcap]
  exact Nat.mul_le_mul (by omega) (by omega)

/-- Feed a one-hypothesis `G4c` fact from a context member. -/
private theorem of_G4c1 {X Y : PLLFormula} (h : G4c [X] Y)
    {Δ : Finset PLLFormula} (hX : X ∈ Δ) : G4s Δ Y := by
  refine (G4c.iff_set.mp h).weaken_subset ?_
  intro y hy
  simp only [List.toFinset_cons, List.toFinset_nil,
    LawfulSingleton.insert_empty_eq, Finset.mem_singleton] at hy
  exact hy ▸ hX

/-- Feed a two-hypothesis `G4c` fact from two context members. -/
private theorem of_G4c2 {X₁ X₂ Y : PLLFormula} (h : G4c [X₁, X₂] Y)
    {Δ : Finset PLLFormula} (h₁ : X₁ ∈ Δ) (h₂ : X₂ ∈ Δ) : G4s Δ Y := by
  refine (G4c.iff_set.mp h).weaken_subset ?_
  intro y hy
  simp only [List.toFinset_cons, List.toFinset_nil,
    LawfulSingleton.insert_empty_eq, Finset.mem_insert,
    Finset.mem_singleton] at hy
  rcases hy with rfl | rfl
  · exact h₁
  · exact h₂

/-- List-level weakening for `G4c`, through the set calculus. -/
private theorem g4c_wk {Γ Γ' : List PLLFormula} {C : PLLFormula}
    (h : G4c Γ C) (hsub : Γ.toFinset ⊆ Γ'.toFinset) : G4c Γ' C :=
  G4c.iff_set.mpr ((G4c.iff_set.mp h).weaken_subset hsub)

/-- **(iv∃) ∃-universality, with p-free side context**: if
`φ, Δ ⊢ ψ` with `Δ, ψ` p-free, then `∃p φ, Δ ⊢ ψ` — modulo the two
E-side indifference hypotheses. -/
theorem existsP_adequate (p : String)
    (hFI : FuelIndiffE p) (hSI : SpaceIndiffE p)
    {φ ψ : PLLFormula} {Δ : List PLLFormula}
    (hΔp : ∀ χ ∈ Δ, p ∉ χ.atoms) (hψp : p ∉ ψ.atoms)
    (h : G4c (φ :: Δ) ψ) : G4c (existsP p φ :: Δ) ψ := by
  by_cases hp : p ∈ φ.atoms
  · obtain ⟨n, d⟩ := G4c.iff_set.mp h
    have hPCd : PieceClosed (pieceClosureList (φ :: ψ :: Δ)) :=
      pieceClosed_pieceClosureList _
    have hPCφ : PieceClosed (pieceClosure φ) := pieceClosed_pieceClosure φ
    have hsub : pieceClosure φ ⊆ pieceClosureList (φ :: ψ :: Δ) :=
      pieceClosure_subset_pieceClosureList (by simp)
    have d' : G4sh n ([φ].toFinset ∪ Δ.toFinset) ψ := by simpa using d
    have key := itp_adequate p (pieceClosureList (φ :: ψ :: Δ)) hPCd
      (show kcap (pieceClosureList (φ :: ψ :: Δ))
          < kcap (pieceClosureList (φ :: ψ :: Δ)) + 1 from Nat.lt_succ_self _)
      n
      (max (n + 1) (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ]))
      [φ] Δ.toFinset ψ
      (lt_of_lt_of_le (Nat.lt_succ_self n) (le_max_left _ _))
      d'
      (fun χ hχ => hΔp χ (List.mem_toFinset.mp hχ))
      (by
        intro F hF
        rw [List.mem_singleton.mp hF]
        exact pieceClosureList_mem (by simp))
      (fun χ hχ =>
        pieceClosureList_mem (by simp [List.mem_toFinset.mp hχ]))
      (pieceClosureList_mem (by simp))
    have hE : G4s
        (insert (itpE p (pieceClosureList (φ :: ψ :: Δ))
          (max (n + 1)
            (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ]))
          (kcap (pieceClosureList (φ :: ψ :: Δ)) + 1) [φ]) Δ.toFinset) ψ :=
      key.1 hψp
    -- space step: land on the packaged space
    rw [hSI (pieceClosureList (φ :: ψ :: Δ)) (pieceClosure φ)
      (max (n + 1)
        (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ]))
      (kcap (pieceClosureList (φ :: ψ :: Δ)) + 1) [φ] hPCd hPCφ
      (by simpa using hsub) (by simp)] at hE
    -- budget step: stabilize down to the packaged budget
    have hstab : G4c
        [itpE p (pieceClosure φ)
          (max (n + 1)
            (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ]))
          (kcap (pieceClosure φ) + 1) [φ]]
        (itpE p (pieceClosure φ)
          (max (n + 1)
            (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ]))
          (kcap (pieceClosureList (φ :: ψ :: Δ)) + 1) [φ]) :=
      (itp_stab_le p (pieceClosure φ)
        (show kcap (pieceClosure φ) < kcap (pieceClosure φ) + 1 from
          Nat.lt_succ_self _)
        (Nat.succ_le_succ (kcap_mono hsub))).1 [φ]
    have hcut : G4s
        (insert (itpE p (pieceClosure φ)
          (max (n + 1)
            (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ]))
          (kcap (pieceClosure φ) + 1) [φ]) Δ.toFinset) ψ :=
      G4s.cut_adm (of_G4c1 hstab (Finset.mem_insert_self _ _))
        (hE.weaken_subset
          (Finset.insert_subset_insert _ (Finset.subset_insert _ _)))
    -- fuel step: land on the packaged fuel
    rw [hFI (pieceClosure φ) (kcap (pieceClosure φ) + 1) [φ]
      (max (n + 1)
        (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ]))
      (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ])
      hPCφ (by simp) (le_max_right _ _) (le_refl _)] at hcut
    have hfin : G4c
        (itpE p (pieceClosure φ)
          (uiFuel (pieceClosure φ) (kcap (pieceClosure φ) + 1) 0 [φ])
          (kcap (pieceClosure φ) + 1) [φ] :: Δ) ψ :=
      G4c.iff_set.mpr (by simpa using hcut)
    unfold existsP
    rw [if_pos hp]
    exact hfin
  · rw [existsP_pfree hp]
    exact h

/-- **(iv∀) ∀-couniversality, with p-free context**: if `Δ ⊢ C` with
`Δ` p-free, then `Δ ⊢ ∀p C` — modulo the two A-side indifference
hypotheses.  The formula-level form is clean here because `forallP`
packages at `Γ = []`, where the ambient `E` of the adequacy pair is
provable outright and cuts away. -/
theorem forallP_adequate (p : String)
    (hFI : FuelIndiffA p) (hSI : SpaceIndiffA p)
    {C : PLLFormula} {Δ : List PLLFormula}
    (hΔp : ∀ χ ∈ Δ, p ∉ χ.atoms)
    (h : G4c Δ C) : G4c Δ (forallP p C) := by
  by_cases hp : p ∈ C.atoms
  · obtain ⟨n, d⟩ := G4c.iff_set.mp h
    have hPCd : PieceClosed (pieceClosureList (C :: Δ)) :=
      pieceClosed_pieceClosureList _
    have hPCC : PieceClosed (pieceClosure C) := pieceClosed_pieceClosure C
    have hsub : pieceClosure C ⊆ pieceClosureList (C :: Δ) :=
      pieceClosure_subset_pieceClosureList (by simp)
    have d' : G4sh n (([] : List PLLFormula).toFinset ∪ Δ.toFinset) C := by
      simpa using d
    have key := itp_adequate p (pieceClosureList (C :: Δ)) hPCd
      (show kcap (pieceClosureList (C :: Δ))
          < kcap (pieceClosureList (C :: Δ)) + 1 from Nat.lt_succ_self _)
      n
      (max (n + 1)
        (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
      [] Δ.toFinset C
      (lt_of_lt_of_le (Nat.lt_succ_self n) (le_max_left _ _))
      d'
      (fun χ hχ => hΔp χ (List.mem_toFinset.mp hχ))
      (by simp)
      (fun χ hχ =>
        pieceClosureList_mem (by simp [List.mem_toFinset.mp hχ]))
      (pieceClosureList_mem (by simp))
    have hA : G4s
        (insert (itpE p (pieceClosureList (C :: Δ))
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosureList (C :: Δ)) + 1) []) Δ.toFinset)
        (itpA p (pieceClosureList (C :: Δ))
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosureList (C :: Δ)) + 1) [] C) :=
      key.2
    -- the ambient E at the empty context is free: cut it away
    have hEd : G4s (Δ.toFinset : Finset PLLFormula)
        (itpE p (pieceClosureList (C :: Δ))
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosureList (C :: Δ)) + 1) []) :=
      ((itp_sound p (pieceClosureList (C :: Δ)) _).1 _ []).weaken_subset
        (by simp)
    have hA0 : G4s (Δ.toFinset : Finset PLLFormula)
        (itpA p (pieceClosureList (C :: Δ))
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosureList (C :: Δ)) + 1) [] C) :=
      G4s.cut_adm hEd hA
    -- space step
    rw [hSI (pieceClosureList (C :: Δ)) (pieceClosure C)
      (max (n + 1)
        (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
      (kcap (pieceClosureList (C :: Δ)) + 1) [] C hPCd hPCC
      (by simp) (by simp) hsub (Finset.Subset.refl _)] at hA0
    -- budget step: two-premise stabilization consumed under Δ
    have hstab : G4c
        [itpE p (pieceClosure C)
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosureList (C :: Δ)) + 1) [],
         itpA p (pieceClosure C)
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosureList (C :: Δ)) + 1) [] C]
        (itpA p (pieceClosure C)
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosure C) + 1) [] C) :=
      (itp_stab_le p (pieceClosure C)
        (show kcap (pieceClosure C) < kcap (pieceClosure C) + 1 from
          Nat.lt_succ_self _)
        (Nat.succ_le_succ (kcap_mono hsub))).2 [] C
    have hE2 : G4s
        (insert (itpA p (pieceClosure C)
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosureList (C :: Δ)) + 1) [] C) Δ.toFinset)
        (itpE p (pieceClosure C)
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosureList (C :: Δ)) + 1) []) :=
      ((itp_sound p (pieceClosure C) _).1 _ []).weaken_subset (by simp)
    have hA1 : G4s (Δ.toFinset : Finset PLLFormula)
        (itpA p (pieceClosure C)
          (max (n + 1)
            (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
          (kcap (pieceClosure C) + 1) [] C) :=
      G4s.cut_adm hA0
        (G4s.cut_adm hE2
          (of_G4c2 hstab (Finset.mem_insert_self _ _)
            (Finset.mem_insert_of_mem (Finset.mem_insert_self _ _))))
    -- fuel step
    rw [hFI (pieceClosure C) (kcap (pieceClosure C) + 1) [] C
      (max (n + 1)
        (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight []))
      (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight [])
      hPCC (by simp) (Finset.Subset.refl _)
      (le_max_right _ _) (le_refl _)] at hA1
    have hfin : G4c Δ
        (itpA p (pieceClosure C)
          (uiFuel (pieceClosure C) (kcap (pieceClosure C) + 1) C.weight [])
          (kcap (pieceClosure C) + 1) [] C) :=
      G4c.iff_set.mpr hA1
    unfold forallP
    rw [if_pos hp]
    exact hfin
  · rw [forallP_pfree hp]
    exact h

/-- (iv∃), single-antecedent corollary: `φ ⊢ ψ`, `ψ` p-free ⟹
`∃p φ ⊢ ψ`. -/
theorem existsP_adequate₀ (p : String)
    (hFI : FuelIndiffE p) (hSI : SpaceIndiffE p)
    {φ ψ : PLLFormula} (hψp : p ∉ ψ.atoms)
    (h : G4c [φ] ψ) : G4c [existsP p φ] ψ :=
  existsP_adequate p hFI hSI (by simp) hψp h

/-- (iv∀), single-antecedent corollary: `ψ ⊢ C`, `ψ` p-free ⟹
`ψ ⊢ ∀p C`. -/
theorem forallP_adequate₀ (p : String)
    (hFI : FuelIndiffA p) (hSI : SpaceIndiffA p)
    {ψ C : PLLFormula} (hψp : p ∉ ψ.atoms)
    (h : G4c [ψ] C) : G4c [ψ] (forallP p C) :=
  forallP_adequate p hFI hSI
    (by intro χ hχ; rw [List.mem_singleton.mp hχ]; exact hψp) h

/-! ### §5 Factorization corollaries (from (i)–(iv) alone) -/

/-- `∃p (θ ∧ φ) ⊢ θ ∧ ∃p φ` for p-free `θ`. -/
theorem existsP_and_factor_l (p : String)
    (hFI : FuelIndiffE p) (hSI : SpaceIndiffE p)
    {θ φ : PLLFormula} (hθ : p ∉ θ.atoms) :
    G4c [existsP p (θ.and φ)] (θ.and (existsP p φ)) := by
  have hcons : G4c [θ.and φ] (θ.and (existsP p φ)) := by
    refine G4c.andR ?_ ?_
    · exact G4c.andL (List.Perm.refl _)
        (G4c.identity_mem (.head _))
    · exact G4c.andL (List.Perm.refl _)
        (g4c_wk (existsP_sound p φ) (by intro x hx; simp at hx ⊢; tauto))
  have hgoal : p ∉ (θ.and (existsP p φ)).atoms := by
    simp only [atoms_and, Finset.mem_union]
    rintro (h | h)
    · exact hθ h
    · exact existsP_atoms p φ h
  exact existsP_adequate p hFI hSI (Δ := []) (by simp) hgoal hcons

/-- `θ ∧ ∃p φ ⊢ ∃p (θ ∧ φ)` for p-free `θ`. -/
theorem existsP_and_factor_r (p : String)
    (hFI : FuelIndiffE p) (hSI : SpaceIndiffE p)
    {θ φ : PLLFormula} (hθ : p ∉ θ.atoms) :
    G4c [θ.and (existsP p φ)] (existsP p (θ.and φ)) := by
  have hand : G4c [φ, θ] (θ.and φ) :=
    G4c.andR (G4c.identity_mem (.tail _ (.head _)))
      (G4c.identity_mem (.head _))
  have hcons : G4c (φ :: [θ]) (existsP p (θ.and φ)) :=
    G4c.cut hand
      (g4c_wk (existsP_sound p (θ.and φ))
        (by intro x hx; simp at hx ⊢; tauto))
  have h2 : G4c (existsP p φ :: [θ]) (existsP p (θ.and φ)) :=
    existsP_adequate p hFI hSI
      (by intro χ hχ; rw [List.mem_singleton.mp hχ]; exact hθ)
      (existsP_atoms p (θ.and φ)) hcons
  exact G4c.andL (List.Perm.refl _)
    (g4c_wk h2 (by intro x hx; simp at hx ⊢; tauto))

end PLLND
