import LaxLogic.PLLSearch
import LaxLogic.PLLSearchPin
import LaxLogic.PLLSearchConf
import wip.rnEmbed
import wip.rnDict

/-!
# Generator: pin the ladder/dictionary cross-relations

Emits ONE Lean file holding every rung-vs-class fact that closes, as a
kernel-checked theorem: proof terms for the positives, checked finite
countermodels for the negatives.

Rungs are taken in their MINIMAL form `t n`, found by enumerating
◯-free formulas by ladder truth set.  The recursion is shorter than the
textbook one —

    t (2k+4) = t (2k+2) ⊃ t (2k-1),   t (2k+3) = t (2k) ∨ t (2k+2)

— which is what brings rungs 10–13 within reach of the searcher at all
(weights 23, 37, 37, 61 against 62, 108, 154, 263).

Run: `lake build rungPin && .lake/build/bin/rungPin > wip/rungCross.lean`.
-/

open PLLFormula PLLND PLLND.Search

namespace RungPin

open PLLND.RNEmbed PLLND.SemUI.RND

def cfg : Config := { findBudget := some 60000, emitClosureCap := 28 }

/-- Minimal representatives of the rungs. -/
def t : Nat → PLLFormula
  | 0 => q0 | 1 => q2 | 2 => q3
  | 3 => (t 1).or (t 2)      | 4 => (t 2).ifThen (t 1)
  | 5 => (t 2).or (t 4)      | 6 => (t 4).ifThen (t 1)
  | 7 => (t 4).or (t 6)      | 8 => (t 6).ifThen (t 3)
  | 9 => (t 6).or (t 8)      | 10 => (t 8).ifThen (t 5)
  | 11 => (t 8).or (t 10)    | 12 => (t 10).ifThen (t 7)
  | 13 => (t 10).or (t 12)   | _ => q0

def tSrc : Nat → String
  | 0 => "q0" | 1 => "q2" | 2 => "q3"
  | 3 => "((t 1).or (t 2))" | 4 => "((t 2).ifThen (t 1))"
  | 5 => "((t 2).or (t 4))" | 6 => "((t 4).ifThen (t 1))"
  | 7 => "((t 4).or (t 6))" | 8 => "((t 6).ifThen (t 3))"
  | 9 => "((t 6).or (t 8))" | 10 => "((t 8).ifThen (t 5))"
  | 11 => "((t 8).or (t 10))" | 12 => "((t 10).ifThen (t 7))"
  | 13 => "((t 10).or (t 12))" | _ => "q0"

def offLadder : List (String × PLLFormula) :=
  [("q1", q1), ("q5", q5), ("q8", q8), ("q9", q9),
   ("q12", q12), ("q13", q13), ("q14", q14)]

/-- Emit a pinned theorem body for `Γ ⊢ C`, or `none`. -/
def pinPos (A B : PLLFormula) : Option String :=
  match settleWhy cfg [A] B with
  | .proved p => some s!"ofG4 {p.toLeanSrc}"
  | _ => none

def pinNeg (A B : PLLFormula) : Option String :=
  match settleWhy cfg [A] B with
  | .refuted M w _ =>
      some s!"FinCM.not_provable_of_check (M := {repr M}) (w := {w}) (by decide)"
  | _ => none

def main : IO Unit := do
  let out ← IO.getStdout
  let pl (x : String) : IO Unit := do out.putStrLn x; out.flush
  let mut pos := 0
  let mut neg := 0
  let mut opn := 0
  pl "-- GENERATED by wip/rungPin.lean -- do not edit by hand."
  pl "import wip.rnEmbed"
  pl "import wip.rnDict"
  pl "import wip.rnDictBase"
  pl "import LaxLogic.PLLCountermodelEmit"
  pl ""
  pl "/-!"
  pl "# The ladder/dictionary cross-relations, pinned"
  pl ""
  pl "Rungs 8-13 against the seven dictionary classes that are not rungs."
  pl "Positives are proof terms; negatives are checked finite countermodels."
  pl "Rungs are in minimal form (`t n`), found by ladder truth set."
  pl "-/"
  pl ""
  pl "open PLLFormula"
  pl "namespace PLLND"
  pl "namespace RNEmbed"
  pl "open SemUI PLLND.SemUI.RND"
  pl ""
  pl "/-- Minimal representatives of the Rieger-Nishimura rungs under `p ↦ ◯⊥`."
  pl "The recursion `t (2k+4) = t (2k+2) ⊃ t (2k-1)`, `t (2k+3) = t (2k) ∨ t (2k+2)`"
  pl "is shorter than the textbook one and gives forms 2-4x smaller. -/"
  pl "def t : Nat → PLLFormula"
  pl "  | 0 => q0 | 1 => q2 | 2 => q3"
  pl "  | 3 => (t 1).or (t 2)      | 4 => (t 2).ifThen (t 1)"
  pl "  | 5 => (t 2).or (t 4)      | 6 => (t 4).ifThen (t 1)"
  pl "  | 7 => (t 4).or (t 6)      | 8 => (t 6).ifThen (t 3)"
  pl "  | 9 => (t 6).or (t 8)      | 10 => (t 8).ifThen (t 5)"
  pl "  | 11 => (t 8).or (t 10)    | 12 => (t 10).ifThen (t 7)"
  pl "  | 13 => (t 10).or (t 12)   | _ => q0"
  pl ""
  for n in [8, 9, 10, 11, 12, 13] do
    pl s!"/-! ## rung {n} -/"
    pl ""
    for (nm, B) in offLadder do
      let A := t n
      let up ← IO.lazyPure (fun _ => pinPos A B)
      let _ ← IO.lazyPure (fun _ => (up.getD "").length)
      match up with
      | some body =>
          pos := pos + 1
          pl s!"theorem rung{n}_le_{nm} : Deriv [t {n}] {nm} :="
          pl s!"  {body}"
      | none =>
          let r ← IO.lazyPure (fun _ => pinNeg A B)
          let _ ← IO.lazyPure (fun _ => (r.getD "").length)
          match r with
          | some body => neg := neg + 1
                         pl s!"theorem rung{n}_nle_{nm} : ¬ Deriv [t {n}] {nm} :="
                         pl s!"  {body}"
          | none => opn := opn + 1
                    pl s!"-- OPEN: t {n} ⊢ {nm}  (search cut off; asserts nothing)"
      let dn ← IO.lazyPure (fun _ => pinPos B A)
      let _ ← IO.lazyPure (fun _ => (dn.getD "").length)
      match dn with
      | some body =>
          pos := pos + 1
          pl s!"theorem {nm}_le_rung{n} : Deriv [{nm}] (t {n}) :="
          pl s!"  {body}"
      | none =>
          let r ← IO.lazyPure (fun _ => pinNeg B A)
          let _ ← IO.lazyPure (fun _ => (r.getD "").length)
          match r with
          | some body => neg := neg + 1
                         pl s!"theorem {nm}_nle_rung{n} : ¬ Deriv [{nm}] (t {n}) :="
                         pl s!"  {body}"
          | none => opn := opn + 1
                    pl s!"-- OPEN: {nm} ⊢ t {n}  (search cut off; asserts nothing)"
      pl ""
  pl "end RNEmbed"
  pl "end PLLND"
  pl ""
  pl s!"-- {pos} positives pinned, {neg} negatives pinned, {opn} cells left open."

end RungPin

def main : IO Unit := RungPin.main
