import wip.witTripleC
import wip.residueGrowth

/-!
# The witness-form OUTPUT — `ABisimWit`, rank preservation, and the
re-typed projection

Branch `ui-confluence`.  The candidates-lens conclusion (2026-07-26)
made Lean: the adversarial M-side ◯-clause is the wrong OBJECT, not
just a hard one.  The specification consumes exactly one property of
the output p-variant link — preservation of protected formulas — and
over a confluent base model that property survives when BOTH
◯-directions of the output are weakened to witness form.  Three
results:

1. `ABisimWit` + `force_iff_of_witOut` (PROVED): the unbounded
   witness-form p-variant link, and its rank-preservation theorem.
   ONLY THE LEFT (base) MODEL NEED BE CONFLUENT; the variant is
   arbitrary.  The ◯-forward direction extracts the base-side witness
   directly from the `∀∃` clause and pushes it through `mwit`; the
   ◯-backward direction pulls the reflexive-successor witness through
   `mback` and rebuilds the `∀∃` clause by bare possibility — the one
   use of confluence.

2. `witTriple_mwit` + `MwitResidue` (PROVED modulo the displayed
   residue): the ◯-maintenance of the amalgam in witness form.  The
   input's M-side clause is the WITNESS clause `MWitM` (strictly
   weaker than the old `MBack`: the adversary chooses only the
   formula, not the world), and the obligation's conclusion allows
   answering ANY row-witness of the formula.  `MwitResidue` is the
   surviving configuration — the same two-degenerate-partners shape as
   `MforthResidue`, but with strictly more hypotheses (the partners
   come from the witness clause, and a forcing fact rides along) and a
   strictly weaker conclusion (any witness may be answered).  Bridges:
   `mwitResidue_of_mforthResidue` (the new pipeline is never harder
   than the old) and `mwitResidue_of_stabilised` (constant families
   pay it, as before).

3. `wit_pbisimW` + `amalgamation_assembledW` (PROVED modulo
   `MwitResidue`): the projection is a lawful `PBisimWit`, and the
   assembly delivers the p-variant with BOTH the closure agreement and
   — over a confluent base — the transfer of every p-free formula, via
   `force_iff_of_witOut`.

The cascade (wip/bandW.lean): under the band collapse both witness
clauses are paid by the maximal-type ascent (K-side proved earlier,
M-side by symmetry), the residue is paid by stabilisation, and
`BandMback` LEAVES THE LEDGER — the banded one-variable amalgamation
holds from the band collapse alone.
-/

open PLLFormula

namespace PLLND
namespace SemUI

open FinComp
open ConfluentU
open SetDeriv

variable {p : String} {K M : ConstraintModel}

/-! ## 1. The witness-form output link and its rank preservation -/

/-- **The witness-form p-variant link** (unbounded output format): the
i-zigzags carry fallibility escapes (the E-form), and BOTH ◯-clauses
are witness-form — `mwit` answers a chosen base-row witness, `mback`
answers every variant-row move but may pair fallible worlds.  This is
the output notion the semantic quantifier ranges over on confluent
bases; `force_iff_of_witOut` is the property the specification
consumes. -/
structure ABisimWit (A : String → Prop) (M N : ConstraintModel) where
  Z : M.W → N.W → Prop
  atoms : ∀ {w w'}, Z w w' → ∀ a, A a → (w ∈ M.V a ↔ w' ∈ N.V a)
  fall : ∀ {w w'}, Z w w' → (w ∈ M.F ↔ w' ∈ N.F)
  iforth : ∀ {w w'}, Z w w' → ∀ {v}, M.Ri w v →
    (∃ v', N.Ri w' v' ∧ Z v v') ∨ v ∈ M.F
  iback : ∀ {w w'}, Z w w' → ∀ {v'}, N.Ri w' v' →
    (∃ v, M.Ri w v ∧ Z v v') ∨ v' ∈ N.F
  mwit : ∀ {w w'}, Z w w' → ∀ {ψ : PLLFormula},
    (∃ u, M.Rm w u ∧ M.force u ψ) →
      ∃ u u', M.Rm w u ∧ M.force u ψ ∧ N.Rm w' u' ∧
        (Z u u' ∨ (u ∈ M.F ∧ u' ∈ N.F))
  mback : ∀ {w w'}, Z w w' → ∀ {u'}, N.Rm w' u' →
    ∃ u, M.Rm w u ∧ (Z u u' ∨ (u ∈ M.F ∧ u' ∈ N.F))

/-- The witness-form p-variant relation. -/
abbrev PBisimWit (p : String) := ABisimWit (fun a => a ≠ p)

/-- Every full bisimulation is a witness-form one: the new output
format strictly widens the class of p-variants. -/
def _root_.PLLND.SemUI.ABisim.toWitOut {A : String → Prop}
    {M N : ConstraintModel} (B : ABisim A M N) : ABisimWit A M N where
  Z := B.Z
  atoms := B.atoms
  fall := B.fall
  iforth := by
    intro w w' hZ v hv
    exact .inl (B.iforth hZ hv)
  iback := by
    intro w w' hZ v' hv'
    exact .inl (B.iback hZ hv')
  mwit := by
    intro w w' hZ ψ hex
    obtain ⟨u, hu, hψ⟩ := hex
    obtain ⟨u', hu', hZu⟩ := B.mforth hZ hu
    exact ⟨u, u', hu, hψ, hu', .inl hZu⟩
  mback := by
    intro w w' hZ u' hu'
    obtain ⟨u, hu, hZu⟩ := B.mback hZ hu'
    exact ⟨u, hu, .inl hZu⟩

/-- **Rank preservation for the witness-form output** — the linchpin:
a witness-form link between a MUTUALLY CONFLUENT base `M` and an
ARBITRARY variant `N` transfers every formula over the protected
alphabet, at every rank.  ◯-forward: an M-successor pair is
regenerated by `iback` (fallible variant successors witness
themselves), the base-side `∀∃` clause hands a row-witness directly,
and `mwit` pushes a chosen witness across (fallible pairs
self-absorb).  ◯-backward: the variant's reflexive successor yields a
row-witness, `mback` pulls it to the base row, and BARE POSSIBILITY —
the single use of confluence — rebuilds the `∀∃` clause.  ⊃ exactly as
in `force_iff_of_layeredE`. -/
theorem force_iff_of_witOut {A : String → Prop} {M N : ConstraintModel}
    (hM : MutuallyConfluent M) (C : ABisimWit A M N) :
    ∀ {φ : PLLFormula}, (∀ a ∈ φ.atoms, A a) →
    ∀ {w : M.W} {w' : N.W}, C.Z w w' → (M.force w φ ↔ N.force w' φ) := by
  intro φ
  induction φ with
  | prop a =>
      intro hA w w' hZ
      simpa [ConstraintModel.force] using C.atoms hZ a (hA a (by simp))
  | falsePLL =>
      intro _ w w' hZ
      simpa [ConstraintModel.force] using C.fall hZ
  | and φ ψ ihφ ihψ =>
      intro hA w w' hZ
      have h1 : ∀ a ∈ φ.atoms, A a := fun a ha => hA a (by simp [ha])
      have h2 : ∀ a ∈ ψ.atoms, A a := fun a ha => hA a (by simp [ha])
      simp only [ConstraintModel.force]
      exact and_congr (ihφ h1 hZ) (ihψ h2 hZ)
  | or φ ψ ihφ ihψ =>
      intro hA w w' hZ
      have h1 : ∀ a ∈ φ.atoms, A a := fun a ha => hA a (by simp [ha])
      have h2 : ∀ a ∈ ψ.atoms, A a := fun a ha => hA a (by simp [ha])
      simp only [ConstraintModel.force]
      exact or_congr (ihφ h1 hZ) (ihψ h2 hZ)
  | ifThen φ ψ ihφ ihψ =>
      intro hA w w' hZ
      have h1 : ∀ a ∈ φ.atoms, A a := fun a ha => hA a (by simp [ha])
      have h2 : ∀ a ∈ ψ.atoms, A a := fun a ha => hA a (by simp [ha])
      simp only [ConstraintModel.force]
      constructor
      · intro hf v' hv' hφ'
        rcases C.iback hZ hv' with ⟨v, hv, hZv⟩ | hF
        · exact (ihψ h2 hZv).mp (hf v hv ((ihφ h1 hZv).mpr hφ'))
        · exact N.force_of_fallible hF
      · intro hf v hv hφv
        rcases C.iforth hZ hv with ⟨v', hv', hZv⟩ | hF
        · exact (ihψ h2 hZv).mpr (hf v' hv' ((ihφ h1 hZv).mp hφv))
        · exact M.force_of_fallible hF
  | somehow φ ihφ =>
      intro hA w w' hZ
      simp only [ConstraintModel.force]
      constructor
      · -- forward: regenerate the pair, extract the base witness, push it
        intro hf v' hv'
        rcases C.iback hZ hv' with ⟨v, hv, hZv⟩ | hF
        · obtain ⟨u, hu, hφu⟩ := hf v hv
          obtain ⟨u₁, u', hu₁, hφu₁, hu', hres⟩ := C.mwit hZv ⟨u, hu, hφu⟩
          rcases hres with hZu | ⟨-, hu'F⟩
          · exact ⟨u', hu', (ihφ hA hZu).mp hφu₁⟩
          · exact ⟨u', hu', N.force_of_fallible hu'F⟩
        · exact ⟨v', N.refl_m v', N.force_of_fallible hF⟩
      · -- backward: pull the reflexive-successor witness, rebuild by
        -- bare possibility (the one use of confluence)
        intro hf v hv
        obtain ⟨u', hu', hφu'⟩ := hf w' (N.refl_i w')
        obtain ⟨u, hu, hres⟩ := C.mback hZ hu'
        have hforce : M.force w (PLLFormula.somehow φ) := by
          rw [force_somehow_iff_of_confluent hM]
          rcases hres with hZu | ⟨huF, -⟩
          · exact ⟨u, hu, (ihφ hA hZu).mpr hφu'⟩
          · exact ⟨u, hu, M.force_of_fallible huF⟩
        exact hforce v hv

/-! ## 2. The witness-form ◯-maintenance and its residue -/

variable (cl : Finset PLLFormula) (B : LayeredBisimWit (fun a => a ≠ p) K M)

/-- **The witness residue (OPEN)** — the surviving configuration of the
witness-form ◯-maintenance, strictly weaker than `MforthResidue` on
both sides.  Configuration: a proper triple at `(Δ, m)` (with
`⊥ ∉ val Δ`, so `d ≥ 1`), a chooseable M-row witness `u'` for `ψ`
(delivered by the M-side witness clause, so it comes with the K-side
partner `κ`), and the two spends both degenerate FOR THAT WITNESS:

* the reservoir's `iback`-partner `kv` (`Rᵢ k′ kv`, level `2d`)
  STRICTLY GROWS the trace, while
* the witness clause's K-partner `κ` (`Rₘ k κ`, level `2d−1`) KEEPS it.

Wanted: SOME M-row witness for `ψ` carried by SOME canonical
`RmC`-successor.  Extra hypotheses relative to `MforthResidue`:
`M.force u' ψ` rides along, and the `κ`-partner arises from a witness
clause rather than an adversarial spend; weaker conclusion: any
row-witness may be answered, not the given world. -/
def MwitResidue : Prop :=
  ∀ (_hK : MutuallyConfluent K)
    {Δ : (canonFinC cl).W} {k' k kv κ : K.W} {m' m u' : M.W}
    {ψ : PLLFormula},
    SubClosed cl →
    PLLFormula.falsePLL ∉ Δ.1.val →
    (traceT K cl k).val = Δ.1.val →
    (traceT K cl k').val = Δ.1.val →
    K.Ri k' k →
    M.Ri m' m → M.Rm m u' → M.force u' ψ → u' ∉ M.F →
    B.Z (2 * canonDepthC cl Δ + 1) k' m' →
    B.Z (2 * canonDepthC cl Δ) k m →
    K.Ri k' kv → B.Z (2 * canonDepthC cl Δ) kv u' →
    (traceT K cl kv).val ≠ Δ.1.val →
    K.Rm k κ → B.Z (2 * canonDepthC cl Δ - 1) κ u' →
    (traceT K cl κ).val = Δ.1.val →
    ∃ (u'' : M.W) (Δ' : (canonFinC cl).W), M.Rm m u'' ∧ M.force u'' ψ ∧
      (canonFinC cl).Rm Δ Δ' ∧ WitTripleC cl B Δ' u''

/-- The old residue pays the new one: answer the clause's own witness
adversarially.  The witness-form pipeline is never harder. -/
theorem mwitResidue_of_mforthResidue (h : MforthResidue cl B) :
    MwitResidue cl B := by
  intro hK Δ k' k kv κ m' m u' ψ hcl hbot hΔk hΔk' hik him hmu' hψ hu'F hZ' hZ
    hk'kv hZkv hsame hkκ hZκ hκsame
  obtain ⟨Δ', hRm, htrip⟩ := h hK hcl hbot hΔk hΔk' hik him hmu' hu'F hZ' hZ
    hk'kv hZkv hsame hkκ hZκ hκsame
  exact ⟨u', Δ', hmu', hψ, hRm, htrip⟩

/-- Stabilised links pay the new residue exactly as the old: the
witness clause's same-trace partner is promoted to a full-level base
and answers reflexively. -/
theorem mwitResidue_of_stabilised
    (h : ∀ {Δ : (canonFinC cl).W} {κ : K.W} {u : M.W},
      B.Z (2 * canonDepthC cl Δ - 1) κ u →
      B.Z (2 * canonDepthC cl Δ) κ u) :
    MwitResidue cl B := by
  intro hK Δ k' k kv κ m' m u' ψ _hcl hbot hΔk hΔk' hik him hmu' hψ hu'F hZ' hZ
    hk'kv hZkv hsame hkκ hZκ hκsame
  exact ⟨u', Δ, hmu', hψ, (canonFinC cl).refl_m Δ,
    .proper k' κ m' hκsame hΔk' (M.trans_i him (M.sub_mi hmu')) hZ' (h hZκ)
      (K.trans_i hik (K.sub_mi hkκ))⟩

/-- **The witness-form ◯-maintenance**: an M-row witness for `ψ` is
answered by SOME M-row witness for `ψ` carried by a canonical
`RmC`-successor.  Consumes the M-side WITNESS clause `MWitM` — never
the adversarial `MBack`.  Case analysis: the clause's K-partner either
grows the trace (the depth drop finances a fresh reflexive triple),
keeps it with a fallible witness (fall + the canonical top at the
partner's trace), or keeps it infallibly — where the reservoir
regenerates a full-level base (same trace: reflexive answer; grown:
`MwitResidue`). -/
theorem witTriple_mwit (hcl : SubClosed cl) (hK : MutuallyConfluent K)
    (hmw : B.MWitM) (hres : MwitResidue cl B)
    {Δ : (canonFinC cl).W} {m : M.W} (ht : WitTripleC cl B Δ m)
    {ψ : PLLFormula} (hex : ∃ u, M.Rm m u ∧ M.force u ψ) :
    ∃ (u' : M.W) (Δ' : (canonFinC cl).W), M.Rm m u' ∧ M.force u' ψ ∧
      (canonFinC cl).Rm Δ Δ' ∧ WitTripleC cl B Δ' u' := by
  obtain ⟨u, hmu, huψ⟩ := hex
  cases ht with
  | top hbot hmF =>
      exact ⟨u, Δ, hmu, huψ, (canonFinC cl).refl_m Δ,
        .top hbot (M.hered_F (M.sub_mi hmu) hmF)⟩
  | proper k' k m' hΔk hΔk' him hZ' hZ hik =>
      by_cases hbot : PLLFormula.falsePLL ∈ Δ.1.val
      · -- the top-val proper triple is secretly fallible on both sides
        have hkF : k ∈ K.F := by
          have hm : PLLFormula.falsePLL ∈ (traceT K cl k).val := by
            rw [hΔk]; exact hbot
          exact (mem_traceT_val.mp hm).2
        have hmF : m ∈ M.F := (B.fall hZ).mp hkF
        exact ⟨u, Δ, hmu, huψ, (canonFinC cl).refl_m Δ,
          .top hbot (M.hered_F (M.sub_mi hmu) hmF)⟩
      · have hd : 1 ≤ canonDepthC cl Δ := canonDepthC_pos hcl hbot
        have hRmκ : ∀ κ : K.W, K.Rm k κ →
            (canonFinC cl).Rm Δ (traceC hK cl κ) := by
          intro κ hkκ
          have h := traceC_mforth (cl := cl) hK hkκ
          refine ⟨?_, ?_⟩
          · intro χ hχ
            rw [← hΔk] at hχ
            exact h.1 hχ
          · intro χ hbcl hχ
            rw [← hΔk]
            exact h.2 χ hbcl hχ
        have hZbase : B.Z (2 * canonDepthC cl Δ - 1 + 1) k m := by
          have : 2 * canonDepthC cl Δ - 1 + 1 = 2 * canonDepthC cl Δ := by
            omega
          rw [this]; exact hZ
        -- the M-side witness clause: a chooseable witness with a K-partner
        obtain ⟨u₁, κ, hmu₁, hu₁ψ, hkκ, hresκ⟩ := hmw hZbase ⟨u, hmu, huψ⟩
        rcases hresκ with hZκ | ⟨hκF, hu₁F⟩
        · by_cases hκsame : (traceT K cl κ).val = Δ.1.val
          · -- the K-partner keeps the trace
            by_cases hu₁F : u₁ ∈ M.F
            · -- fallible witness: its K-partner is fallible too
              have hκF : κ ∈ K.F := (B.fall hZκ).mpr hu₁F
              exact ⟨u₁, traceC hK cl κ, hmu₁, hu₁ψ, hRmκ κ hkκ,
                .top (mem_traceT_val.mpr
                  ⟨hcl.bot, K.force_of_fallible hκF⟩) hu₁F⟩
            · -- regenerate a full-level base from the reservoir
              have hm'u₁ : M.Ri m' u₁ := M.trans_i him (M.sub_mi hmu₁)
              rcases B.iback hZ' hm'u₁ with ⟨kv, hk'kv, hZkv⟩ | hu₁F'
              · by_cases hsame : (traceT K cl kv).val = Δ.1.val
                · -- CASE A: same-trace regeneration answers reflexively
                  exact ⟨u₁, Δ, hmu₁, hu₁ψ, (canonFinC cl).refl_m Δ,
                    .proper k' kv m' hsame hΔk' hm'u₁ hZ' hZkv hk'kv⟩
                · -- THE WITNESS RESIDUE
                  exact hres hK hcl hbot hΔk hΔk' hik him hmu₁ hu₁ψ hu₁F hZ' hZ
                    hk'kv hZkv hsame hkκ hZκ hκsame
              · exact absurd hu₁F' hu₁F
          · -- the K-partner grows: the depth drop finances a fresh triple
            have hsub : Δ.1.val ⊆ (traceC hK cl κ).1.val := by
              intro φ hφ
              rw [← hΔk] at hφ
              obtain ⟨hφcl, hf⟩ := mem_traceT_val.mp hφ
              exact mem_traceT_val.mpr
                ⟨hφcl, K.force_hered (K.sub_mi hkκ) hf⟩
            have hlt : canonDepthC cl (traceC hK cl κ) < canonDepthC cl Δ :=
              canonDepthC_lt hsub (fun h => hκsame h.symm)
            exact ⟨u₁, traceC hK cl κ, hmu₁, hu₁ψ, hRmκ κ hkκ,
              .proper κ κ u₁ rfl rfl (M.refl_i u₁)
                (B.mono_le (by omega) hZκ) (B.mono_le (by omega) hZκ)
                (K.refl_i κ)⟩
        · -- the clause escaped: fallible pair, top at the partner's trace
          exact ⟨u₁, traceC hK cl κ, hmu₁, hu₁ψ, hRmκ κ hkκ,
            .top (mem_traceT_val.mpr
              ⟨hcl.bot, K.force_of_fallible hκF⟩) hu₁F⟩

/-! ## 3. The re-typed projection and assembly -/

/-- **The projection is a lawful witness-form p-variant link** — the
re-typed `wit_pbisimC`: no adversarial clause is consumed anywhere.
The M-to-amalgam ◯-direction is `witTriple_mwit`; every projection
direction is free. -/
theorem wit_pbisimW (hcl : SubClosed cl) (hK : MutuallyConfluent K)
    (hmw : B.MWitM) (hres : MwitResidue cl B) :
    ∃ C : PBisimWit p M (witAmalgamC cl B),
      ∀ (q : (witAmalgamC cl B).W), C.Z q.1.2 q := by
  refine ⟨⟨fun m q => q.1.2 = m, ?_, ?_, ?_, ?_, ?_, ?_⟩, fun _ => rfl⟩
  · -- atoms off p
    rintro m q rfl a ha
    show q.1.2 ∈ M.V a ↔ (if a = p then q.1.1 ∈ (canonFinC cl).V a ∨ q.1.2 ∈ M.F
        else q.1.2 ∈ M.V a)
    rw [if_neg ha]
  · -- fall
    rintro m q rfl
    exact Iff.rfl
  · -- iforth: an M-move, matched through the triple
    rintro m q rfl v hmv
    obtain ⟨Δ', hRi, htrip⟩ := witTriple_iforth cl B hcl hK q.2 hmv
    exact .inl ⟨⟨(Δ', v), htrip⟩, ⟨hRi, hmv⟩, rfl⟩
  · -- iback: projection
    rintro m q rfl q' hq'
    exact .inl ⟨q'.1.2, hq'.2, rfl⟩
  · -- mwit: the witness-form ◯-maintenance
    rintro m q rfl ψ hex
    obtain ⟨u', Δ', hmu', hψ, hRm, htrip⟩ :=
      witTriple_mwit cl B hcl hK hmw hres q.2 hex
    exact ⟨u', ⟨(Δ', u'), htrip⟩, hmu', hψ, ⟨hRm, hmu'⟩, .inl rfl⟩
  · -- mback: projection
    rintro m q rfl q' hq'
    exact ⟨q'.1.2, hq'.2, .inl rfl⟩

/-- **The amalgamation, assembled in witness form**: from a layered
witness link of budget `2·cl.card + 1` (M-side clause in WITNESS form
— no adversarial hypothesis anywhere), a witness-form p-variant of `M`
whose distinguished world agrees with `k₀` on the whole closure; and
over a confluent base, every p-free formula transfers at the root. -/
theorem amalgamation_assembledW (hcl : SubClosed cl) (hadeq : OBoxAdeq cl)
    (hK : MutuallyConfluent K)
    (hmw : B.MWitM) (hres : MwitResidue cl B)
    (k₀ : K.W) (m₀ : M.W)
    (hB : B.Z (2 * cl.card + 1) k₀ m₀) :
    ∃ (N : ConstraintModel) (C : PBisimWit p M N) (n₀ : N.W),
      C.Z m₀ n₀ ∧ (∀ φ ∈ cl, (N.force n₀ φ ↔ K.force k₀ φ)) ∧
      (MutuallyConfluent M → ∀ χ : PLLFormula, (∀ a ∈ χ.atoms, a ≠ p) →
        (M.force m₀ χ ↔ N.force n₀ χ)) := by
  classical
  set Δ₀ : (canonFinC cl).W := traceC hK cl k₀ with hΔ₀
  have hd₀ := canonDepthC_le cl Δ₀
  have htrip : WitTripleC cl B Δ₀ m₀ :=
    .proper k₀ k₀ m₀ rfl rfl (M.refl_i m₀)
      (B.mono_le (by omega) hB) (B.mono_le (by omega) hB) (K.refl_i k₀)
  obtain ⟨C, hC⟩ := wit_pbisimW cl B hcl hK hmw hres
  refine ⟨witAmalgamC cl B, C, ⟨(Δ₀, m₀), htrip⟩,
    hC ⟨(Δ₀, m₀), htrip⟩, ?_, ?_⟩
  · intro φ hφ
    rw [wit_forceC cl B hcl hadeq hK φ hφ ⟨(Δ₀, m₀), htrip⟩]
    constructor
    · intro h
      exact (mem_traceT_val.mp h).2
    · intro h
      exact mem_traceT_val.mpr ⟨hφ, h⟩
  · intro hM χ hχ
    exact force_iff_of_witOut hM C hχ (hC ⟨(Δ₀, m₀), htrip⟩)

/-! ## Axiom audit -/

/--
info: 'PLLND.SemUI.force_iff_of_witOut' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms force_iff_of_witOut

/--
info: 'PLLND.SemUI.mwitResidue_of_mforthResidue' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms mwitResidue_of_mforthResidue

/--
info: 'PLLND.SemUI.mwitResidue_of_stabilised' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms mwitResidue_of_stabilised

/--
info: 'PLLND.SemUI.witTriple_mwit' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms witTriple_mwit

/--
info: 'PLLND.SemUI.wit_pbisimW' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms wit_pbisimW

/--
info: 'PLLND.SemUI.amalgamation_assembledW' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms amalgamation_assembledW

end SemUI
end PLLND
