/- GENERATED by `lake exe frjcert`.  Do not edit. -/
import FRJ.Search.Pin
import LaxLogic.PLLNDCore
import wip.rnBank

open FRJ PLLND

/-- The sequent: `(¬¬◯⊥ ⊃ ◯⊥) ⊢ ((¬¬◯⊥ ⊃ ◯⊥) ∧ ◯(◯¬◯⊥ ⊃ (◯⊥ ∨ ¬◯⊥)))`,
    searched as the goal `((¬¬◯⊥ ⊃ ◯⊥) ⊃ ((¬¬◯⊥ ⊃ ◯⊥) ∧ ◯(◯¬◯⊥ ⊃ (◯⊥ ∨ ¬◯⊥))))`. -/
def cm_frjcert_cAnd_10_13 : FRJ.Search.Tab where
  n := 5
  root := 0
  leT := [[true, true, true, true, true], [false, true, true, true, true], [false, false, true, true, false], [false, false, false, true, false], [false, false, false, false, true]]
  rmT := [[true, false, false, false, false], [false, true, false, false, true], [false, false, true, true, false], [false, false, false, true, false], [false, false, false, false, true]]
  falT := [false, false, false, true, false]
  atomsT := [[], [], [], [], []]

theorem cm_frjcert_cAnd_10_13_ok : (cm_frjcert_cAnd_10_13).okB = true := by decide
theorem cm_frjcert_cAnd_10_13_root : (cm_frjcert_cAnd_10_13).root < (cm_frjcert_cAnd_10_13).n := by decide

def K_frjcert_cAnd_10_13 : Kripke := (cm_frjcert_cAnd_10_13).toKripke cm_frjcert_cAnd_10_13_ok cm_frjcert_cAnd_10_13_root

set_option maxRecDepth 1000000 in
theorem frjcert_cAnd_10_13_force :
    ¬ (K_frjcert_cAnd_10_13).force (K_frjcert_cAnd_10_13).root (ofPLL ((PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.somehow PLLFormula.falsePLL) PLLFormula.falsePLL) PLLFormula.falsePLL) (PLLFormula.somehow PLLFormula.falsePLL)) (PLLFormula.and (PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.somehow PLLFormula.falsePLL) PLLFormula.falsePLL) PLLFormula.falsePLL) (PLLFormula.somehow PLLFormula.falsePLL)) (PLLFormula.somehow (PLLFormula.ifThen (PLLFormula.somehow (PLLFormula.ifThen (PLLFormula.somehow PLLFormula.falsePLL) PLLFormula.falsePLL)) (PLLFormula.or (PLLFormula.somehow PLLFormula.falsePLL) (PLLFormula.ifThen (PLLFormula.somehow PLLFormula.falsePLL) PLLFormula.falsePLL)))))) : PLLFormula)) := by decide

/-- **(¬¬◯⊥ ⊃ ◯⊥) ⊬ ((¬¬◯⊥ ⊃ ◯⊥) ∧ ◯(◯¬◯⊥ ⊃ (◯⊥ ∨ ¬◯⊥)))** — stated with the
    RN(◯) dictionary names.  `frjcert_cAnd_10_13_expanded` below says the same thing
    with every name written out. -/
theorem frjcert_cAnd_10_13 : [RNBank.q10] ⊬ (RNBank.q10.and RNBank.q13) :=
  not_entails_of_countermodel K_frjcert_cAnd_10_13 frjcert_cAnd_10_13_force

/-- The SAME statement, every abbreviation expanded — nothing to look up.
    Definitionally equal to `frjcert_cAnd_10_13`, so the proof is `frjcert_cAnd_10_13` itself. -/
theorem frjcert_cAnd_10_13_expanded : [(PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.somehow PLLFormula.falsePLL) PLLFormula.falsePLL) PLLFormula.falsePLL) (PLLFormula.somehow PLLFormula.falsePLL))] ⊬ (PLLFormula.and (PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.ifThen (PLLFormula.somehow PLLFormula.falsePLL) PLLFormula.falsePLL) PLLFormula.falsePLL) (PLLFormula.somehow PLLFormula.falsePLL)) (PLLFormula.somehow (PLLFormula.ifThen (PLLFormula.somehow (PLLFormula.ifThen (PLLFormula.somehow PLLFormula.falsePLL) PLLFormula.falsePLL)) (PLLFormula.or (PLLFormula.somehow PLLFormula.falsePLL) (PLLFormula.ifThen (PLLFormula.somehow PLLFormula.falsePLL) PLLFormula.falsePLL))))) :=
  frjcert_cAnd_10_13

/-- Control: the model is not degenerate — it still forces `⊤`. -/
theorem cm_frjcert_cAnd_10_13_control :
    (K_frjcert_cAnd_10_13).force (K_frjcert_cAnd_10_13).root (ofPLL (PLLFormula.ifThen PLLFormula.falsePLL PLLFormula.falsePLL)) := by decide

#print axioms frjcert_cAnd_10_13
#print axioms frjcert_cAnd_10_13_expanded
